### ISSUE TITLE
12.2.10 Upgrade Error - Payables Report - PBS Account Analysis - XML Output not displaying

### ISSUE THREAD

**Issue by vinaytalasila** [Fujitsu-America/Fujitsu-Repository#10]
**Describe the bug**
Mark has reported this issue. ***Update the content of the issue***

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vinaytalasila** [comment]
Mark,

Ashok has fixed this issue (he reattached the template) in STG 12.2.10 and tested this successfully. Request ID related to his testing is 35388112
**PBS Account Analysis Report**.

Attached output file of his test:
[PBS_Account_Analysis_Report_010621.pdf](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6587393/PBS_Account_Analysis_Report_010621.pdf)

Could you please retest 'PBS Account Analysis Report' from your end in STG 12.2.10 and confirm the results from your end as well so that we can 'Close' this issue.

Thanks
Vinay Talasila

**Comment by hamiltonmark** [comment]
Thank You Ashok
Yes - I re-ran the PBS Account Analysis Report in STG.
I was able to view the pdf output.
Screenshot with timestamp...


![image](https://user-images.githubusercontent.com/85197361/120552869-c8d04c80-c3c5-11eb-9587-2f938450bc2c.png)

**Comment by vinaytalasila** [comment]
Thank you for your update Mark!!! I am 'Closing' this issue now.

Thanks
Vinay Talasila
