### ISSUE TITLE
STG 12.2.10 - ssh sbsintf@oci-ssh-dev.snaponbusinesssolutions.com requiring password

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#100]
**Describe the bug**

**Instance Name**
Instance:  tpqs2i

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
Sorry - we may have missed the ssh key for STG.
Can you please create public ssh key for this new server?

login as: mhamil
mhamil@ssbsashebsap3.oci.snapbs.com's password:
Last login: Wed Sep  8 10:33:42 2021 from 172.22.216.7
[mhamil@ssbsashebsap3 ~]$ sudo su aptpqs2i
[sudo] password for mhamil:

  E-Business Suite Environment Information
  ----------------------------------------
  RUN File System           : /tpqs2i/12.2/STG/fs2/EBSapps/appl
  PATCH File System         : /tpqs2i/12.2/STG/fs1/EBSapps/appl
  Non-Editioned File System : /tpqs2i/12.2/STG/fs_ne


  DB Host: ssbsashebsdb3.oci.snapbs.com  Service/SID: TPQS2I


  Sourcing the RUN File System ...

[aptpqs2i@ssbsashebsap3 mhamil]$ hostname
ssbsashebsap3
[aptpqs2i@ssbsashebsap3 mhamil]$ whoami
aptpqs2i
[aptpqs2i@ssbsashebsap3 mhamil]$ ssh sbsintf@oci-ssh-dev.snaponbusinesssolutions.com
sbsintf@oci-ssh-dev.snaponbusinesssolutions.com's password:

**Comment by vinaytalasila** [comment]
@arsidhan : Could you please look into this?

Thanks
Vinay

**Comment by SomuSundaramM** [comment]
[ssbsashebsap3_public_key.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7133052/ssbsashebsap3_public_key.zip)

**Comment by SomuSundaramM** [comment]
Hi Mark,

Attached the public key from new STG server.

Thanks,
Somu

**Comment by hamiltonmark** [comment]
Thanks Somu

Public ssh key installed successfully on SBS Server - rich-oodi-10-rv.

Tested by running CPQ Inventory Items Interface Job - successful.

Jobs are scheduled as follows:
5:30am               CPQ Inventory Items Interface from STG
6:30am               CPQ BOMS Interface from STG
7:30am               CPQ Price Lists (US) Interface from STG
8:30am               CPQ Price Lists (CA) Interface from STG

US Price List will be updated in STG approx. 7:45am.
CA Price List will be updated in STG approx. 8:45am.

Price Lists needed updated for end user testing and should be working now.

Thanks!

**Comment by hamiltonmark** [comment]
Ok to close this ticket.

**Comment by SomuSundaramM** [comment]
Hi Mark,

Thank you for the confirmation.

Regards,
Som
