### ISSUE TITLE
Customer Search page not opening

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#101]
**Describe the bug**
When clicking the link to do a customer search...page not found error.

**Instance Name**
Instance: PPQS1I

**Responsibility Name**
Responsibility: SBS OM Customer Search

**Navigation**
Navigation: Customer Search
[Production Issue Customer Search Post Go Live.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7195724/Production.Issue.Customer.Search.Post.Go.Live.docx)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vinaytalasila** [comment]
Tina,

We are looking this and will keep you posted.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Tina,

Could you please approve DBA team to bounce **apache and oacore** in the INT and STG 12.2.10 instances.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Just an update...We retested the issue in INT 12.2.10 and getting the same error as before. We will continue to work on this and keep you posted.

[Customer OM Search error.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7198442/Customer.OM.Search.error.txt)

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Just an update...Applied the fix in the INT and STG instances. Linda has tested and confirmed. 

Below is the latest communication regarding this issue...

Amit -> **In Production instance, we need to bounce only apache and oacore services all other services – database, concurrent managers, scheduled jobs will run without any impact. The only impact is current logged in users will be disconnected and new user will not be able to login during bounce period which is 15 mins.**

Tina -> **Tonight, off hours, this can be performed.  If you want to send Linda the exact time you plan, she can approve it.**

@amitjori: Could you please reply to Tina's last comment?

Thanks
Vinay

**Comment by vinaytalasila** [comment]
From: Amit.Jori@fujitsu.com <Amit.Jori@fujitsu.com> 
Sent: Tuesday, September 21, 2021 12:23 PM
To: Griffin, Tina <Tina.Griffin@snapon.com>; Rigo, Linda M <Linda.M.Rigo@snapon.com>
Cc: Akshay.Kumar@fujitsu.com; Somasundaram.Muthunarayanan@fujitsu.com; Vinay.Talasila@fujitsu.com; Hanmant.Arsid@fujitsu.com
Subject: RE: Customer Search page not opening #101

Hello Linda,

We will **bounce apache/oacore services on 09/22/2021 @1:00 AM EDT in PPQS1I instance, ETA is 20 minutes**.

Can you please approve ?

Regards,
Amit

From: Rigo, Linda M <Linda.M.Rigo@snapon.com> 
Sent: Tuesday, September 21, 2021 12:04 PM
To: Jori, Amit <Amit.Jori@fujitsu.com>; Griffin, Tina <Tina.Griffin@snapon.com>
Cc: Kumar, Akshay <Akshay.Kumar@fujitsu.com>; Muthunarayanan, Somasundaram <Somasundaram.Muthunarayanan@fujitsu.com>; Talasila, Vinay <Vinay.Talasila@fujitsu.com>; Arsid, Hanmant <Hanmant.Arsid@fujitsu.com>
Subject: RE: Customer Search page not opening #101

**This is approved**

**Comment by vinaytalasila** [comment]
Hello Linda/Team,

Apache/Oacore services have been bounced in PROD instance, can you please re-test issue #101 and confirm?

Regards,
Amit

**Comment by lindamrigo** [comment]
This is working as expected
