### ISSUE TITLE
PROD Authoring Report is not outputting Move to Monthly items or Hardware. It is only showing Software.

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#102]
**Describe the bug**
Run the Authoring Report, see missing data.

**Instance Name**
Instance: PPQS1I

**Responsibility Name**
Responsibility: PBS US Contracts Administrator

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vinaytalasila** [comment]
Tina,

We will look into this and keep you posted.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Tina,

Could you please let us know the exact name of the report so that we will look into this and also check in 12.2.10 non-production instances as well.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Tina,

We just ran (did not change anything) the '**PBS Authoring Report for Service Contracts**' report in INT 12.2.10 instance. Please find the attached file for the details. Could you please check whether Move to Monthly items or Hardware is showing there in that? 

[PBS Authoring Report for Service Contracts.pdf](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7196523/PBS.Authoring.Report.for.Service.Contracts.pdf)

If it is not showing in that report in INT 12.2.10 instance either then this will be an enhancement request related to the **PBS_QOT_AUTHRSC** rdf. This is not a retrofitted object.

Thanks
Vinay

**Comment by TinaGriffin** [comment]
So on your pdf...these are the the types of lines that will not show in production now.
HWMonthly 49.76 49.76 49.76 49.76 49.76
SITA 22.08 22.74 23.42 24.12 24.84
0.00 1,406.40
 262-0026-01NS 4992407 0.00 0.00 0.00 0.00 0.00
0.00 0.00

 810-0372- 4992403 0.00 0.00 0.00 0.00 0.00
0.00 0.00

 810-0419-BLK 4992402 0.00 0.00 0.00 0.00 0.00
0.00 0.00
 PC-DESKTOP 4992406 0.00 0.00 0.00 0.00 0.00
0.00 0.00
 PM-DESKTOPPC- 4992405 22.08 22.74 23.42 24.12 24.84

**Comment by TinaGriffin** [comment]
So yes they are there in INT 12.2.10

**Comment by vinaytalasila** [comment]
Status update....Mark, Tina, Ashok, Akshay and I had a Teams meeting and verified the queries in the report. Queries looks good and it is something with the data. Tina will look into this further and update us.

Thanks
Vinay

**Comment by TinaGriffin** [comment]
I found the issue and the fix.  Give me about 10 or 15 minutes and I'll join the bridge call.

**Comment by TinaGriffin** [comment]
The issue was that an nvl was needed for the Service Items that are not in the IB at all.
currently: WHERE CII.instance_status_id  <> 1
changed to:  WHERE nvl(CII.instance_status_id,3)

**Comment by TinaGriffin** [comment]
Sorry, I didn't capture it all above.
changed to: WHERE nvl(CII.instance_status_id,3) <> 1

**Comment by vinaytalasila** [comment]
Tina,

Thank you for your updates.  That change should be done in the **PBS_OKS_CONT_AUTHOR_REP_PKG package body** right and we don't need to touch the **PBS_QOT_AUTHRSC** rdf.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Just an update....Tina has applied the fix to let the process running. So I downgraded the ticket status from 'Critical' to 'Minor'.

Tina will create a ticket in TFSNow. Then, we will make the changes and store that xbol_top in 12.2.10 non-production and Production instances.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Tina,

Could you please create a TFSNow ticket so that DBA team can perform the action plan in INT and Pre-Prod instances and 'Close' this issue.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Just an update...Tina will create TFSNow ticket and provide that ticket details in this issue. Then, we can close this ticket.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Tina,

A gentle remainder....Could you please create a TFSNow ticket today and provide that ticket details in this issue. Then, we can close this ticket.

Thanks
Vinya

**Comment by TinaGriffin** [comment]
Number
RITM0050773
Request
REQ0050323

**Comment by vinaytalasila** [comment]
Tina,

Thank you for your update. I am 'Closing' this ticket now.

Thanks
Vinay
