### ISSUE TITLE
PROD Unable to submit CPQ Orders***	SR 3-27079763371***

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#104]
**Describe the bug**
A clear and concise description of what the bug is.  Receiving error.  See attached.

**Instance Name**
Instance: PPQS1I

**Responsibility Name**
Responsibility: CPQ

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TinaGriffin** [comment]
[Production Issue Cannot Submit CPQ Quote.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7196729/Production.Issue.Cannot.Submit.CPQ.Quote.docx)

**Comment by vinaytalasila** [comment]
Hi Tina,

We will look into this and keep you posted.

Thanks
Vinay

**Comment by TinaGriffin** [comment]
Per the question on the SR...they did do an International order in EBS Quoting using the configurator today and it worked fine.

**Comment by vinaytalasila** [comment]
Tina,

Thank you for your update. We will update that info in the SR.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Just an update....Communication between Oracle support engineer and DBA Team is still going on. If there are any major updates then DBA Team will update the info here.

Thanks
Vinay

**Comment by amitjori** [comment]
Hi Team,

We have bounced PPQS1I instance and Tina confirmed CPQ orders are now working.

Regards,
Amit

**Comment by TinaGriffin** [comment]
Garnett has confirmed it's working as well:
Tina,

I was able to submit Jan’s two quotes, Ellen’s one and mine all without issue this morning.

Thanks,
Garnett
