### ISSUE TITLE
Forms personalization option needs have correct Apex Sales Snapshot button URL address.  

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#105]
Responsibility: 
sales user
Navigation:
sales dashboard
click on Customers (second option on Shortcuts)
enter 87847 in Account Number
click Go
Click on 'Ganley Ford'
The page that loads is the page with Apex Sales Snapshot button. The button's properties need to change. The button is a forms personalization 
and needs to be corrected to the correct URL  in each instance
   URLS are as follows:
     Production: https://psbsashebsap1.oci.snapbs.com:8443/ords/f?p=100:1:10626152849081:::::
     INT: https://isbsashebsap4.oci.snapbs.com:8443/ords/f?p=100:1:4071629433044:::::
     Stage: http://ssbsashebsap3.oci.snapbs.com:8181/ords/f?p=100:1:14856527524034:::::

**Comment by vinaytalasila** [comment]
DBA Team,

Could you please look into this?

Thanks
Vinay

**Comment by amitjori** [comment]
Hi Vinay,

The url's are correct , as per below statement from Linda looks like we need to change the button properties.

The page that loads is the page with Apex Sales Snapshot button. The button's properties need to change. The button is a forms personalization.

Regards,
Amit

**Comment by vinaytalasila** [comment]
@ashoksnapfj 

I looked into this issue and getting the below error. I added the most of the Sales related roles to my user and still getting the same error in INT 12.2.10 instance. Could you please investigate this from your end and update. 
![image](https://user-images.githubusercontent.com/84878630/134079767-9ca91e9b-e669-4b63-9215-bf866fe59d25.png)

If you are unable to duplicate the issue in the non-production instances then we can have a Teams meeting with Linda tomorrow at 10:30 AM EDT.

Thanks
Vinay

**Comment by AkshayK247** [comment]
Hi @lindamrigo 

I have update the Apex Sales Snapshot button URL on INT 12.2.10, STG 12.2.10 and PROD 12.2.10(with help of AMIT).
Please verify the same and let us know if any changes required.

Regards,
Akshay

**Comment by lindamrigo** [comment]
I have verified that this is now working in INT. I will ask a sales user to test in production.

**Comment by lindamrigo** [comment]
This has been corrected.
