### ISSUE TITLE
Universal Work Queue Not saving changed screen

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#107]
Responsibility: PBS US Depot Repair
Navigation:
Universal Work Queue
Changed my screens (hid some columns and moved some)  Hit save as I usually do (2nd screenshot).  When I go back in, it defaults back to the original view.
[Universal Work Queue 2.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7197320/Universal.Work.Queue.2.docx)

**Comment by vinaytalasila** [comment]
Linda,

We will look into this and keep you posted.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
**@AkshayK247 and @ashoksnapfj:** Could you please look into this. If you are unable to duplicate or need more info then please setup a meeting with Linda tomorrow at 10:30 AM EDT. 

Thanks
Vinay

**Comment by lindamrigo** [comment]
The bounce corrected the problem
