### ISSUE TITLE
PRD Local Event ERROR on Event - Oracle apps cs sr ServiceRequest updated **SR 3-27090385569 : Local Event ERROR : Oracle.apps.cs.sr.ServiceRequest.updated

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#108]
**Describe the bug**

**Instance Name**
Instance:  ppqs1i

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
See word doc with screenshots and explanation.
Possible solution given in word doc.

[Local Event ERROR Oracle apps cs sr ServiceRequest updated.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7197768/Local.Event.ERROR.Oracle.apps.cs.sr.ServiceRequest.updated.docx)

**Comment by vinaytalasila** [comment]
Mark,

We will look into this and keep you posted.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
FYI
The main issues are:
1.  Received 200+ emails on Day one.
2.  Event is erroring and probably needs turned off
THanks


![image](https://user-images.githubusercontent.com/85197361/134052857-7a18e6e1-74ed-447e-8647-fbf574c0c121.png)

**Comment by vinaytalasila** [comment]
**@ashoksnapfj:** Could you please look into this and work with DBA team during your shift.

Thanks
Vinay

**Comment by SomuSundaramM** [comment]
Hi Mark,

Its done in PROD.

![image](https://user-images.githubusercontent.com/85238833/134121672-ac3262c0-bc4a-4ab0-b93e-6c2d7972d64c.png)

Thanks,
Somu

**Comment by hamiltonmark** [comment]
Thanks Som
I will need to enter an SR for this.
We are still receiving Event emails ....

![image](https://user-images.githubusercontent.com/85197361/134169941-3d9ed980-77fb-4c74-8f25-7596c63192fb.png)

**Comment by SomuSundaramM** [comment]
Hi Mark,

Thank you for the update.

Regards,
Som

**Comment by vinaytalasila** [comment]
Just an update....Mark has uploaded 'Diagnostics: Apps Check' report output to Oracle support.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Latest update from SR references this note...

Hi Mark,
Thanks for the update.
Could you refer the note below & disable the subscription listed there?
Notifications Being Send: Local Event ERROR : Oracle.apps.cs.sr.ServiceRequest.statuschanged ( Doc ID 2318402.1 )
Regards,
- Clinton
Global Customer Support 

[Notifications Being Send Local Event ERROR Oracle apps cs sr ServiceRequest statuschanged Doc ID 2318402_1.pdf](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7219693/Notifications.Being.Send.Local.Event.ERROR.Oracle.apps.cs.sr.ServiceRequest.statuschanged.Doc.ID.2318402_1.pdf)

**Comment by SomuSundaramM** [comment]
Hi Mark,

i have disabled the below one as per doc id,

![image](https://user-images.githubusercontent.com/85238833/134626125-3b2fa844-f41c-4f72-a6e6-85e1efdb20b7.png)

Thanks,
Somu

**Comment by hamiltonmark** [comment]
Thanks Som
I checked this morning.
We are still receiving event emails for this.

Below shows latest list.
In addition - included one of the emails.

![image](https://user-images.githubusercontent.com/85197361/134668860-7c465337-5f33-42c5-8a47-e507c0fef591.png

[Action Required Local Event ERROR  oracle.apps.cs.sr.ServiceRequest.updated  2376972-3121682-EVT.msg.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7225365/Action.Required.Local.Event.ERROR.oracle.apps.cs.sr.ServiceRequest.updated.2376972-3121682-EVT.msg.zip)
)

**Comment by TinaGriffin** [comment]
Was the bounce done.  According to "FYI Notification To SYSADMIN User: Error ORA-01403 EAM_SRAPPROVAL_PVT After Creating Or Updating Service Request (Doc ID 2495125.1)"

Solution

To implement the solution, please execute the following steps:

1. Go into the responsibility: Workflow Administrator Web Applications

2. Navigate to Business Events

3. ENABLE the Business Events: oracle.apps.cs.sr.ServiceRequest.created and
oracle.apps.cs.sr.ServiceRequest.updated

4.Click on the Subscription link for each of these events.

5.For Business Event: oracle.apps.cs.sr.ServiceRequest.updated , DISABLE the subscription EAM_SRAPPROVAL_PVT.service_request_updated and also isc_fs_event_log_etl_pkg.log_sr

6.Bounce mid tier and database

7. Retest the issue.

8. Migrate the solution as appropriate to other environments.

**Comment by vinaytalasila** [comment]
Update...

- Mark has setup the email in the workflow in the INT 12.2.10 instance.
- Existing service request needs to be updated in INT instance to test the steps that are mentioned by Tina in the above comment.
- If it works then we will apply the same solution in the Production instance.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Mark,

After Tina or you update the existing service request then let us know. Then, Hanmant will perform the steps that are mentioned by Tina in todays comments in INT 12.2.10 instance.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
SR Analyst asked for below 2 SQLs run in Prod....

[SQL Script Results.xlsx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7228837/SQL.Script.Results.xlsx)

In addition - Tina and I attempted to test in INT today without any results.
No email was sent to our email box.

We verified events were enabled.
Need to verify WF Background engine is running.  SERVEREQ  JTFTASK
Once verified - Tina will need to update a Service Request.
Then check for business event sending email notif.

**Comment by vinaytalasila** [comment]
Update...

- Tina will look into this and update a service request in INT 12.2.10 instance. Then Mark will check whether it works as expected or not.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
SR Analyst response....
Hi Mark,

Thank you for your update.

Seems like you have disabled the Events and Subscriptions however they are not reflected in the tables. Just to confirm that these Events/Subscription are disabled using:

(R) Workflow Administrator -> Business Events
(R) Workflow Administrator -> Subscriptions

They also show as disabled here.

Regards,
- Clinton
Global Customer Support

**Comment by hamiltonmark** [comment]
Mark's response....
Used - Workflow Administrator Web (New) - responsibility.
See uploaded doc for screenshots.

[Screenshots showing events.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7240046/Screenshots.showing.events.docx)

**Comment by hamiltonmark** [comment]
I updated the SR with the attached and following to finally verify what needs disabled....

Clinton
I uploaded Screenshots asking what to disable...
Can you please review and let me know?
I will disable them and test.
If needed - we can sched a bounce.

Appreciate it.
Mark
[Screenshots asking what to Disable.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7251809/Screenshots.asking.what.to.Disable.docx)

**Comment by hamiltonmark** [comment]
I have been using this responsibility for years to perform workflow administration:

Workflow Administrator Web (New)

Navigation:  Administrator Workflow > Business Events

I’ve attempted numerous times to disable these 2 business events using this responsibility – without success.  I’ve made the change and clicked apply but after re-querying the event it still is enabled.

Decided to try a different responsibility:

Workflow Administrator Web Applications

Same Navigation:  Administrator Workflow > Business Events

It worked in STG… but still cannot disable in PROD using either responsibility.

In STG - it returns a green message saying it was successful.
In PRD - it returns nothing after hit apply.

**Comment by hamiltonmark** [comment]
Used an old Vinay trick and tried a different browser... success!

Was able to disable these events in Prod using Edge....

![image](https://user-images.githubusercontent.com/85197361/135508354-f168a82e-992f-4c2d-8519-2c3d92ecd9df.png)

![image](https://user-images.githubusercontent.com/85197361/135508864-89473bec-0fbb-425a-b4e8-6e08bf044eaa.png)

**Comment by vinaytalasila** [comment]
Thank you for your update Mark.

**Comment by hamiltonmark** [comment]
Even though the events have been disabled... we are still receiving email alerts.
Probably need the Mid Tier and DB Bounced.... but I am not going to schedule it.
We will wait until the next time we need a bounce for something else...
or possibly in a few weeks when the upgrade dust settles.

![image](https://user-images.githubusercontent.com/85197361/135515384-df66edfc-cc0c-4c8a-9d30-b45a0e8e42f8.png)

**Comment by hamiltonmark** [comment]
We have a Plan to bounce the next time there is a need to bounce Mid Tier and DB.
This ticket can be closed.
In addition the SR can be closed as well.

**Comment by vinaytalasila** [comment]
Mark - Thank you for your update.

Thanks
Vinay
