### ISSUE TITLE
PRD PO Approval Error '3103: Attribute 'FEDERAL_FLAG' does not exist for item' occurs on Requisition Approval (Doc ID 1987601.1)***SR 3-27081841321***

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#109]
**Describe the bug**

**Instance Name**
Instance:  ppqs1i

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
PO Requisition Approver received ERROR after approving PO Req.
See screenshots doc for explanation and data fix according to doc id.

[Screenshots Attribute 'FEDERAL_FLAG' does not exist for item.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7197910/Screenshots.Attribute.FEDERAL_FLAG.does.not.exist.for.item.docx)

**Comment by vinaytalasila** [comment]
Mark,

I will look into this and keep you posted.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Thanks Vinay
Looks like we need an SR opened to obtain a datafix.

**Comment by vinaytalasila** [comment]
Mark,

I looked into your document. I will create the SR shortly.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Just an FYI...
According to the document - datafix is only needed for "pre-12.2.10 upgrade" PO Requisitions.
There exists 3.  Any newly created PO Reqs should be ok.

![image](https://user-images.githubusercontent.com/85197361/134061485-b49f4501-f2fe-467c-b6af-5969ce22d230.png)

**Comment by vinaytalasila** [comment]
Hi Mark,

Thank you for your update. I am in the process of creating the SR now. I will let them know that we have the issue for three PO Req's.

Could you please check how many PO Reqs are there in INT 12.2.10 instance. When Oracle provides any fix to us then we can try that datafix first in that instance by tweaking the queries.

Thanks
Vinay Talasila

**Comment by hamiltonmark** [comment]
6 open PO Reqs exists in INT 12.2.10.
Datafix should fix these 6.

![image](https://user-images.githubusercontent.com/85197361/134063022-defc272e-7319-454c-8630-55b588001187.png)

**Comment by vinaytalasila** [comment]
Mark,

Thank you for your last update. I have created an SR 3-27081841321 for this issue.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Mark,

Could you please let us know the **Org_ID** for all the PO Requisitions that are having the issue in Production and INT 12.2.10 instances?

Thanks
Vinay

**Comment by hamiltonmark** [comment]
All PO's are in Org Id 83

**Comment by vinaytalasila** [comment]
Thank you Mark.

**Comment by vinaytalasila** [comment]
Mark,

Could you please run the below from any Purchasing responsibility in the Production instance and upload the file to this ticket.

Diag Apps Check PO + ICX + AME: Upload the output from "Diagnostics: Apps Check" Report using a Purchasing responsibility:

a. Navigate to Reports > Run
b. Choose Submit a Single Request
c. At Name choose Diagnostics: Apps Check
d. At Parameters enter:
Application 1: Purchasing
Application 2: Oracle iProcurement
Application 3: Approvals Management
e. Submit the request
f. Navigate to View > Requests
g. Select the Report Output (not the Log) to upload

This information is also available in SRDC Doc ID 1665009.1

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Mark,

Got the solution from Oracle support. Could you please try this 1st in INT 12.2.10 instance from your end. If that works there for couple of the requisitions then you can do the same in Production instance.

Steps:

1) To insert the attribute values

First create backup tables:

create table WF_ITEM_ATT_VAL_BAK as
select * from WF_ITEM_ATTRIBUTE_VALUES
where item_type = 'REQAPPRV';

create table fed_temp as
select distinct por.wf_item_type, por.wf_item_key
from WF_ITEM_ATTRIBUTE_VALUES wiav,
po_requisition_headers_all por
where por.wf_item_type = wiav.item_type
and por.wf_item_key = wiav.item_key
and por.wf_item_type = 'REQAPPRV'
and not exists (select 'existing FEDERAL_FLAG' from WF_ITEM_ATTRIBUTE_VALUES wiav1
where wiav1.item_type = wiav.item_type
and wiav1.item_key = wiav.item_key
and wiav1.name = 'FEDERAL_FLAG');

INSERT INTO WF_ITEM_ATTRIBUTE_VALUES (ITEM_TYPE, ITEM_KEY, NAME, TEXT_VALUE)
select wf_item_type, wf_item_key, 'FEDERAL_FLAG', ''
from fed_temp;

commit;

2) For already errored workflows, do a Retry after step1)

Reference Note 458216.1 that has a few different ways to retry failed workflows. Choose the option to Retry failed Requisition Approval for "LAUNCH_CREATEPO_WF"[This section is not visible to customers.]

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Uploaded Diag Apps Check to SR....

[Diagnostics__Apps_Check_200921.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7198762/Diagnostics__Apps_Check_200921.txt)

**Comment by hamiltonmark** [comment]
Vinay
Shouldn't I create a tfsnow ticket to do this in a non-prod?
Even if it works - I won't be able to run it in Prod.

select distinct por.wf_item_type, por.wf_item_key
from WF_ITEM_ATTRIBUTE_VALUES wiav,
po_requisition_headers_all por
where por.wf_item_type = wiav.item_type
and por.wf_item_key = wiav.item_key
and por.wf_item_type = 'REQAPPRV'
and not exists (select 'existing FEDERAL_FLAG' from WF_ITEM_ATTRIBUTE_VALUES wiav1
where wiav1.item_type = wiav.item_type
and wiav1.item_key = wiav.item_key
and wiav1.name = 'FEDERAL_FLAG');
order by 2

This select returned 43 rows in INT and 48 in Prod.

**Comment by vinaytalasila** [comment]
Mark,

I am not sure how TFSNow ticket works. I don't have access to that ticketing system either. Do I need to work with DBA team regarding that from here on?

Thanks
Vinay

**Comment by amitjori** [comment]
Hello Mark,

Yes, please create a TFSNow ticket and we will work on it.

Regards,
Amit

**Comment by SomuSundaramM** [comment]
Hi Mark,

We have performed the action plan in INT 12.2.10, please check and confirm if that works will do the same in Prod.
Note : TFS ticket needed for PROD 

SQL> create table WF_ITEM_ATT_VAL_BAK as
select * from WF_ITEM_ATTRIBUTE_VALUES
where item_type = 'REQAPPRV';  2    3

Table created.

SQL> select count(*) from WF_ITEM_ATTRIBUTE_VALUES
where item_type = 'REQAPPRV';  2

  COUNT(*)
----------
      7233

SQL> select count(*) from WF_ITEM_ATT_VAL_BAK;

  COUNT(*)
----------
      7233

SQL> create table fed_temp as
  2  select distinct por.wf_item_type, por.wf_item_key
from WF_ITEM_ATTRIBUTE_VALUES wiav,
  3    4  po_requisition_headers_all por
  5  where por.wf_item_type = wiav.item_type
  6  and por.wf_item_key = wiav.item_key
  7  and por.wf_item_type = 'REQAPPRV'
  8  and not exists (select 'existing FEDERAL_FLAG' from WF_ITEM_ATTRIBUTE_VALUES wiav1
  9  where wiav1.item_type = wiav.item_type
 10  and wiav1.item_key = wiav.item_key
 11  and wiav1.name = 'FEDERAL_FLAG');

Table created.


SQL> INSERT INTO WF_ITEM_ATTRIBUTE_VALUES (ITEM_TYPE, ITEM_KEY, NAME, TEXT_VALUE)
select wf_item_type, wf_item_key, 'FEDERAL_FLAG', ''
from fed_temp;  2    3

43 rows created.

SQL> commit;

Commit complete.

SQL> select name from v$database;

NAME
---------
DPQS2I

Thanks,
Som

**Comment by hamiltonmark** [comment]
Thanks Som.  I sent this email this morning to end user.
Waiting for response....

![image](https://user-images.githubusercontent.com/85197361/134166565-4ad89036-19f0-473c-8fd8-ced6ea72f46d.png)

![image](https://user-images.githubusercontent.com/85197361/134166632-91f5e6f9-56f9-4ffc-84ac-7a5d839ee4fa.png)

**Comment by hamiltonmark** [comment]
tfsnow ticket with Action Plan created and submitted to Fujitsu for DataFix.

![image](https://user-images.githubusercontent.com/85197361/134209584-49195527-2e20-4983-8e5e-b07105757dc6.png)

**Comment by amitjori** [comment]
Hello Mark,

Action plan has been performed in PROD and TFSNow ticket has been updated. Attached is the output for reference.

[RITM0050592_output.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7204790/RITM0050592_output.txt)


Regards,
Amit

**Comment by hamiltonmark** [comment]
Thanks Amit / Vinay
End User was able to successfully Approve PO Req after Datafix.


![image](https://user-images.githubusercontent.com/85197361/134233287-d0cc348d-d794-4867-9b26-b93284434fbb.png)

**Comment by hamiltonmark** [comment]
Ok to close ticket.

**Comment by vinaytalasila** [comment]
Mark,

Thank you for update. I will close this ticket and the corresponding SR now.

Thanks
Vinay
