### ISSUE TITLE
PRD - Workflow Item Type AZWM023P - What does it do?

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#111]
**Describe the bug**

**Instance Name**
Instance:  ppqs1i

**Responsibility Name**
Responsibility: 

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
We have a Workflow Background Job on Hold.
I am unsure what it does.
I Opened Workflow Builder and searched for the Item Type AZWM023P - but not found.
Searched MOS and Google without successful hits.

I do not want to remove the hold until I know if is needed and what it does.
Any help is appreciated.
Mark

![image](https://user-images.githubusercontent.com/85197361/134225076-1a189e63-4f4c-47cf-82ea-2a95a507d594.png)

**Comment by vinaytalasila** [comment]
Mark,

We will look into this and keep you posted.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Mark,

Item Type AZWM023P is related to the 'Purchasing' Workflow Type. Please see below screenshot for the reference.

![image](https://user-images.githubusercontent.com/84878630/134241816-d40c0096-f48d-4c57-9085-622c6675ba00.png)

You may need to remove the hold now.

If you are not having any further queries then can I 'Close' this issue?

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Ok - thanks
Hold has been removed.
Scheduled to run every 5 mins.

Ok to close ticket.

**Comment by vinaytalasila** [comment]
Mark,

Just an additional info (for future reference purpose)....**WF_ITEM_TYPES_TL** table shows the display and internal names of the workflow item types.

Thanks
Vinay
