### ISSUE TITLE
PRD Conc Job IEX Scoring Engine Harness has Value Set erroring on where mo_global.check_access(organization_id)='Y'

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#112]
**Describe the bug**

**Instance Name**
Instance:  PPQS1I

**Responsibility Name**
Responsibility:  SBS Collections Administrator

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
See Screenshots Doc for explanation of problem...

Possible Problem:   mo_global.check_access seems to have issues returning data.

[Screenshots IEX Scoring Engine Harness.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7210618/Screenshots.IEX.Scoring.Engine.Harness.docx)

**Comment by hamiltonmark** [comment]
Google Search found...

https://www.oracleappsdna.com/2012/02/moac-oracle-apps-org_id-multi-org-concept/

Can you please check if API/Package - mo_global.check_access -  is ok?

**Comment by hamiltonmark** [comment]
This Scheduled job has been running successfully everyday in INT since Test Cycle 1.
Below is the latest LOG FIle from INT.


![image](https://user-images.githubusercontent.com/85197361/134360473-bf83a7f4-201e-4a83-a42f-61e878950c42.png)



+---------------------------------------------------------------------------+
Collections: Version : 12.2

Copyright (c) 1998, 2013, Oracle and/or its affiliates. All rights reserved.

IEX_SCORE_OBJECTS: IEX: Scoring Engine Harness
+---------------------------------------------------------------------------+

Current system time is 22-SEP-2021 06:06:10

+---------------------------------------------------------------------------+

[22-SEP-2021 06:06:10]: **Starts**
[22-SEP-2021 06:07:18]: **Ends**
+---------------------------------------------------------------------------+
Start of log messages from FND_FILE
+---------------------------------------------------------------------------+
Profile Value MO: Default Operating Unit : OU-PROQUEST USD
Profile Value MO: Operating Unit: OU-PROQUEST USD
Profile Value MO: Security Profile: BG-PROQUEST BUSINESS SOLUTIONS
                                      
***start of xml hdr***
Constructing the XML Header is success
Batch Size: 100000
Running Scoring Engine: 2
Operating Unit: OU-PROQUEST USD
Using bridge 37312 one for each scoring engine
Scoring engine object filter SQL: SELECT PAYMENT_SCHEDULE_ID  FROM (select PAYMENT_SCHEDULE_ID ,ROWNUM rn from IEX_F_SCORE_INVOICES_V) WHERE PAYMENT_SCHEDULE_ID IS NOT NULL  and PAYMENT_SCHEDULE_ID > 0 
Number of worker(1) - Scoring engine object filter SQL: SELECT PAYMENT_SCHEDULE_ID  FROM (select PAYMENT_SCHEDULE_ID ,ROWNUM rn from IEX_F_SCORE_INVOICES_V) WHERE PAYMENT_SCHEDULE_ID IS NOT NULL  and PAYMENT_SCHEDULE_ID > 0 
Scoring objects in batch 1 is 11725 at 06:06:2121
universe size 11725
Using bridge id 37312
Profile:Store Score Histories for Transactions: Y
Scoring objects in batch 2 is 0 at 06:06:3030
 Completed Scoring  objects of type Collections Transaction
IEX_SCORE: scoreObjects: Spawning IEXDLMGB
Start Time of the spawned Process IEXDLMGB =>22/sep/2021 :06:06:30
End Time of the spawned Process IEXDLMGB =>22/sep/2021 :06:07:01
IEX_SCORE: scoreObjects: Launched cp 35513049 successfully
Operating Unit: OU-PROQUEST USD
Score Engine: 2 Status: S
Running Scoring Engine: 1
Operating Unit: OU-PROQUEST USD
Using bridge 37314 one for each scoring engine
Scoring engine object filter SQL: SELECT PARTY_ID  FROM IEX_F_PARTIES WHERE PARTY_ID IS NOT NULL  and PARTY_ID > 0  ORDER BY PARTY_ID
Number of worker(1) - Scoring engine object filter SQL: SELECT PARTY_ID  FROM IEX_F_PARTIES WHERE PARTY_ID IS NOT NULL  and PARTY_ID > 0  ORDER BY PARTY_ID
Scoring objects in batch 1 is 6448 at 06:07:0606
universe size 6448
Using bridge id 37314
Profile:Store Score Histories for Transactions: Y
Scoring objects in batch 2 is 0 at 06:07:1212
 Completed Scoring  objects of type Party
Score Engine: 1 Status: S
Running Scoring Engine: 6
Operating Unit: OU-PROQUEST USD
Using bridge 37317 one for each scoring engine
Scoring engine object filter SQL: SELECT CUST_ACCOUNT_ID  FROM IEX_F_ACCOUNTS_V WHERE CUST_ACCOUNT_ID IS NOT NULL  and CUST_ACCOUNT_ID > 0  ORDER BY CUST_ACCOUNT_ID
Number of worker(1) - Scoring engine object filter SQL: SELECT CUST_ACCOUNT_ID  FROM IEX_F_ACCOUNTS_V WHERE CUST_ACCOUNT_ID IS NOT NULL  and CUST_ACCOUNT_ID > 0  ORDER BY CUST_ACCOUNT_ID
Scoring objects in batch 1 is 6448 at 06:07:1212
universe size 6448
Using bridge id 37317
Profile:Store Score Histories for Transactions: Y
Scoring objects in batch 2 is 0 at 06:07:1818
 Completed Scoring  objects of type Account
Score Engine: 6 Status: S
Running Scoring Engine: 
Operating Unit: OU-PROQUEST USD
Running Scoring Engine: 
Operating Unit: OU-PROQUEST USD
1
2
len_tempRes-->490
inside print_clob
3
+---------------------------------------------------------------------------+
End of log messages from FND_FILE
+---------------------------------------------------------------------------+


+---------------------------------------------------------------------------+
Executing request completion options...

Output file size: 
490

+--------- 1) POST-PROCESSING  ---------+
Beginning post-processing of request 35513047 on node ISBSASHEBSAP4 at 22-SEP-2021 06:07:18.
-- Publishing output

 
Post-processing of request 35513047 completed at 22-SEP-2021 06:07:19.
 
CONC-POST-PROCESSING RESULTS

-- PUBLISH: 
CONC-OPP-XMLPUB SUCCESS
+---------------------------------------+

**Comment by hamiltonmark** [comment]
If I attempt to view the details on the Scheduled Job... Get the following...

![image](https://user-images.githubusercontent.com/85197361/134364900-0394fc14-3b58-401b-9a01-4802c44f5d25.png)

**Comment by vinaytalasila** [comment]
Mark,

Can we have a Teams meeting now regarding this issue?

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Vinay
Sorry - We can have it on Thu.
I am leaving at 11:30 for a Dr's Appt.

**Comment by vinaytalasila** [comment]
Mark,

Got it. Let me schedule a meeting tomorrow at 10:00 AM EDT.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Got back early from Dr's Appt.

For tonight's scheduled run...  PBS Advanced Collections Assign Collector Populate UWQ Process (Report Set)
I've put the Request Set On Hold for the 9:30pm and 6am runs....
then resubmitted the request set - saving all new parameters for just the 9:30pm sched run.

I believe I may have done the same in INT during Test Cycle 1 - instead of just Removing the Hold.

Will check it in the morning...

![image](https://user-images.githubusercontent.com/85197361/134401727-adfad4f2-9fe3-4dae-9b68-73287ff82f43.png)

**Comment by vinaytalasila** [comment]
Mark,

Noted your last comments.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Success!
The resubmitted job -  PBS Advanced Collections Assign Collector Populate UWQ Process (Report Set)
with all new parameter values worked without erroring.  I did enter the wrong date of 17-Sep-2021
but it ran successfully.  The date parameter has been changed for the next run.

Will keep an eye on the job.
Should be able to close this ticket in a day.

![image](https://user-images.githubusercontent.com/85197361/134452169-bb214c55-a705-49f1-a815-069dfcc33bc9.png)

**Comment by hamiltonmark** [comment]
Last night 9:30 Request Set was successful.
This morning's 6am Request Set was successful too.
This ticket can be closed.

![image](https://user-images.githubusercontent.com/85197361/134502242-d4057c39-3967-4fa1-8519-2a742d86819b.png)

**Comment by vinaytalasila** [comment]
Mark,

Thank you for your update. Closing this ticket now.

Thanks
Vinay
