### ISSUE TITLE
PROD Create Service Request status:E Error msg count:1API Programming Error (CS_ServiceRequest_PVT.Create_ServiceRequest): The value "" for parameter business_process_id is invalid.

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#113]
**Describe the bug**
We have a custom workflow that runs within the order process flow and uses a seeded API to create a service request if an install item is on the order.  These are all erroring.  I originally thought it was because shipping was down and they had to manually ship (because the workflow triggers its action when the last shippable item on the order ships)...however after researching...I'm seeing orders today erroring even though shipping is no longer down.  Here is the error
"Create Service Request status:E Error msg count:1API Programming Error (CS_ServiceRequest_PVT.Create_ServiceRequest): The value "" for parameter business_process_id is invalid."

**Instance Name**
Instance:  PPQS1I

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**
Service Request should automatically create from the API.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
the package name is "PBS_CSX_FITS_UAI_WKF_PKG".  There was a code change for retrofit made to this package and any time a code change is made to a workflow package, the workflow mailer must be bounced.  However, I would think that the upgrade itself would have taken care of that.  The quickest thing to try to fix is to bounce the workflow mailer.  FYI.  I did find a direct hit on this error in MOS which shows a patch...but we probably already are beyond that because it was for 12.2.4.  TeleService: Error Creating or Updating Service Requests (business_process_id) (Doc ID 2098269.1)

**Comment by TinaGriffin** [comment]
This doc looks closer as we are using an API and the first doc I gave you was for manually creating a service request
Invalid Business Process ID Error While Creating Service Request Using Create Service Request API (Doc ID 2094890.1)

**Comment by TinaGriffin** [comment]
TFSNow ticket has been opened.
 Number
RITM0050670
Request
REQ0050220

**Comment by vinaytalasila** [comment]
Hanmant,

I am not having access to TFSNow. So, could you please accept that and proceed with the next step.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Updates...

- Tina has updated the **PBS_CSX_FITS_UAI_WKF_PKG** package body with a one line new code of 'lr_service_request_rec.business_process_id  := 1;' in the INT 12.2.10 instance.
- Tina has provided us the action plan and the code in the email to migrate that to the Production instance.
- Hanmant has followed the action plan successfully
- At around 4:00 PM EDT (9/22/2021), Tina has already seen two orders that created service requests and confirmed that it looks good.

**Tina - Can I close this issue now?**

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Update...In today's status meeting Tina has confirmed to 'Close' this issue.

Thanks
Vinay
