### ISSUE TITLE
PRD Using AR Transaction Workbench to create a Debit Memo for Canadian Customer - Errors with Cannot Derive Tax Jurisdiction***SR 3-27130748011***

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#114]
**Describe the bug**

**Instance Name**
Instance:  PPQS1I

**Responsibility Name**
Responsibility:  PBS CAN Receivables Invoice User

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
Millice is saying....
Mark,
I am unable to enter a Debit Memo in the CAD operating unit due to the error message below.  Error message appears when I choose the Lines items button.  Yes, this is stopping me/I cannot work around.   I do not receive this error message in the USD operating unit.


![image](https://user-images.githubusercontent.com/85197361/134404791-66dc8015-a61b-4c9a-996c-514d32a3f038.png)

**Comment by hamiltonmark** [comment]
MOS Hit below.

[Transaction Workbench Error System cannot determine geographical information for this location and cannot derive a tax jurisdiction Doc ID 438718_1.pdf](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7213141/Transaction.Workbench.Error.System.cannot.determine.geographical.information.for.this.location.and.cannot.derive.a.tax.jurisdiction.Doc.ID.438718_1.pdf)

**Comment by hamiltonmark** [comment]
System Administrator > Profile > System
Query Profile Option Name: HZ: Generate Party Number

**In PPQS1I - This Profile Value is NULL

Query shows there is no location_id for this customer in the
table - hz_geo_name_reference_log

select map_status, location_id
from hz_geo_name_reference_log
where location_id = &location_id;  --266362

** Returns no rows


![image](https://user-images.githubusercontent.com/85197361/134405748-dcc763b8-9405-48b9-b282-f7cc21519efa.png)

**Comment by vinaytalasila** [comment]
Mark,

We will look into this and keep you posted.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Mark,

If you are still at work then can we have a quick Teams meeting now?

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Yes - please send me a Teams Mtg.

**Comment by vinaytalasila** [comment]
I just sent the Teams meeting invite now.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
![image](https://user-images.githubusercontent.com/85197361/134525135-32c69f66-65cb-411d-8955-f534d26425a9.png)


![image](https://user-images.githubusercontent.com/85197361/134525643-af5a6cee-cc93-4323-8326-ac7532196314.png)

**Comment by vinaytalasila** [comment]
Just an update...Mark, Akshay and I had a Teams meeting today and performed the steps by referring to the Doc ID 438718.1. Still this issue did not fix. I will create an SR for this issue today.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Created **SR 3-27130748011** for this issue.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Vinay - Just received an email from end user saying...

Brenda is getting the same error message when creating manual invoices in Canada.

**Comment by vinaytalasila** [comment]
Mark,

Thank you for the update. When I created the SR I mentioned that this issue is happening to Canadian customers and did not limit this issue to Debit memos. 

Could you please run the below program in the Production instance and attach the output to this ticket? If you are not having the responsibility then I will request **Hanmant** to run that from his end in that instance.

RDA/ACT or Apps Check (AR): Upload Apps Check Output

Responsibility: **Order Management**
Navigation: Report, Request > Run Requests
Submit a Single Request for Name = Diagnostics: Apps Check
Parameters:
Parameter 1: Receivables 

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Mark,

Hanmant ran the report and sent the output to me. So you don't need to run from your end in the Production instance.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Sorry - already done...
[Diagnostics__Apps_Check_230921.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7220160/Diagnostics__Apps_Check_230921.txt)

**Comment by vinaytalasila** [comment]
Thank you Mark.

**Comment by hamiltonmark** [comment]
Vinay
In INT - I asked Nichole to create another DM using a different Province... her response...
"Success!  I was able to complete DM 20785 for account #74600 (in Quebec) without receive the tax error."

Then I asked Nichole to create another DM using a different customer with Province=AB...   her response...
"Success - DM 20786 on #103657 in AB – completed as expected"

**Comment by vinaytalasila** [comment]
Mark,

Thank you for your update. It looks like the issue with the city 'ENOCH'. That city does not exist in the list of cities under Alberta province. That is the core issue. Let us get a fix from Oracle support regarding this.

![image](https://user-images.githubusercontent.com/84878630/134936352-d275dec4-50bf-4058-bc13-8615e0c2a2c5.png)

![image](https://user-images.githubusercontent.com/84878630/134936499-113262af-fd4a-4feb-9772-af7fa7a24ce3.png)

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Vinay
Here is another issue with a different customer...
Can we discuss?

[Tax Jurisdiction error for Canadian Customer in WOODBRIDGE ON.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7245071/Tax.Jurisdiction.error.for.Canadian.Customer.in.WOODBRIDGE.ON.docx)

**Comment by vinaytalasila** [comment]
Mark,

Sure. I have sent Teams meeting invite to you in the email to meet now. 

Thanks
Vinay

**Comment by TinaGriffin** [comment]
Hey I just came across this doc
"Run Geography Name Referencing Program and all Locations have map_status = E (Doc ID 1401903.1)"

It references Canada ‘cities’ and has two programs to run.  Just thought it may be an option to try for issue # 114.  Give it a look and see what you think.

**Comment by hamiltonmark** [comment]
Receivables Transaction Analyzer - from PPQS1I for copied Invoice 235314


[Receivables_Transaction_Analyz_280921.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7246829/Receivables_Transaction_Analyz_280921.zip)

**Comment by vinaytalasila** [comment]
Mark,

- I have updated the SR regarding today's issue and attached the Receivables Transaction Analyzer zip file in that.
- I have talked to the Manager who is taking care of that SR and the support engineer has responded us. They are working on that now.

Thanks
Vinay

**Comment by SomuSundaramM** [comment]
Hi Team,

We have scheduled to run the program at 3 AM tomorrow in PPQSi1 

![image](https://user-images.githubusercontent.com/85238833/135293767-40657dd1-0c46-4ade-b8af-4950d935d383.png)


Thanks,
somu

**Comment by SomuSundaramM** [comment]
HI Mark,

Program completed within 2 mins in PROD.

Thanks,
Somu

**Comment by hamiltonmark** [comment]
Thanks Somu

**Comment by hamiltonmark** [comment]
Results from Production...

From: Dotson, Nichole 
Sent: Thursday, September 30, 2021 8:46 AM

The address has been added in PROD.  
Millice -  it will likely default to the PO Box since that is the bill to address, but you can click on the address line to change it to 180 Macdonald Crescent, Fort McMurray AB.


From: Kreighbaum, Millice M <Millice.M.Kreighbaum@snapon.com> 
Sent: Thursday, September 30, 2021 9:09 AM

Success!  Debit memo has been created and applied. (Physical address defaulted down for Ship to and Bill to)

**Comment by vinaytalasila** [comment]
Mark,

Thank you for your update. Before, I close this issue, I will summarize the steps for your future reference purpose.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Results from Production (Copying Intercompany Manual Invoice ...

From: Maynard, Brenda S <Brenda.S.Maynard@snapon.com> 
Sent: Thursday, September 30, 2021 9:57 AM

The invoices for Snap-on Canada in US Org and Mobis Canada in Canadian Org completed successfully. 

Invoice 235302 I was able to incomplete. Let me know if it’s okay to delete it. 

However, Invoice 235314 cannot be incomplete. Will need to credit it. The GL date is in the current period so that should not present an issue. 

C# 36441 (US)

![image](https://user-images.githubusercontent.com/85197361/135473308-09a96e3a-ea29-4bc8-a3b8-b79e1f72a04a.png)

C# 234379 (CAD)
Neither of the erroneous invoices can be incomplete. Will need to credit both. 

![image](https://user-images.githubusercontent.com/85197361/135473363-94c8de06-77d3-49ee-a44f-f0434c738c57.png)

Thanks,
Brenda

**Comment by vinaytalasila** [comment]
Summary: 

**Issue 1:** Unable to create an AR Invoice related to Canadian customer.

**Analysis:** 

- Wrong city name was setup in the customer. That city name does not exist under in that province. 
- As shown in the below screenshot, currently we have a geography validation related to the 'City'. This is the key reason it has failed to create an Invoice for that location.

![image](https://user-images.githubusercontent.com/84878630/135493684-87ed7020-d0c5-4231-857c-45fa05fc94a4.png)

**Solution:** 

- Corrected the city name in the customer setup. 

- Ran the '**Geography Name Referencing Program**' with the parameters shown in the below screenshot.

![image](https://user-images.githubusercontent.com/84878630/135494308-516217ed-475b-4e0a-9b4c-d66f08c2eb26.png)

**Issue 2:** Most of the Canadian AR invoices has failed after upgrading to 12.2.10

**Analysis:** In the Oracle docs and also from previous upgrades we remembered that we need to run **'Geography Name Referencing Program'** atleast once after the upgrade.

**Solution:** 

- Updated the **HZ: Number of workers for a given Geography Name Referencing request** profile value at the site level from 1 to 10. 

- Ran 'Geography Name Referencing Program' with the parameters shown in the below screenshot.
![image](https://user-images.githubusercontent.com/84878630/135494308-516217ed-475b-4e0a-9b4c-d66f08c2eb26.png)

- Users are able to create / copy invoices related to the Canadian customers.

**Future considerations:** 

- After a month or after your month end activities are done, please take a decision to uncheck 'Geography Validation' and 'Tax Validation' corresponding to the 'City'. Save and Apply. This setup change will not validate the city name in the future under the Canadian provinces.

- Navigation for that setup: **Trading Community Manager (Responsibility) -> Trading Community -> Administration -> Geography Hierarchy -> Search 'Code' as 'CA' -> Go -> Click on 'Manage Validations'**

- Run 'Geography Name Referencing Program' with the parameters shown in the below screenshot.
![image](https://user-images.githubusercontent.com/84878630/135494308-516217ed-475b-4e0a-9b4c-d66f08c2eb26.png)

- Also consider scheduling the 'Geography Name Referencing Program' with the parameters as shown above during the weekend.

**Mark** - If the above looks good then you may close this issue now and I will close the corresponding SR too.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
**Mark** - Could you please find sometime today before you leave and review my previous comments in this issue so that we can close this?

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Yes - thanks Vinay
This ticket can be closed.
In addition - the SR can be closed as well.

**Comment by vinaytalasila** [comment]
Thank you Mark!!!
