### ISSUE TITLE
PRD PBS_XML_GATE_SHIP_CONFIRM - Inbound files Not being processed

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#115]
**Describe the bug**

**Instance Name**
Instance:  PPQS1I

**Responsibility Name**
Responsibility:  

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vinaytalasila** [comment]
Mark,

To investigate this issue, could you please provide additional details to us.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
LOG seems to show that files are sent to /ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp
but
PBS_XML_GATE_SHIP_CONFIRM
is looking for them in $APPLCSF/tmp

The PBS_XML_GATE_SHIP_CONFIRM is not finding the files
when trying to do an
utl_file.fopen
using this Directory Object - SBS_UTL_FILE_DIR


[apppqs1i@psbsashebsap1 inbound]$ cd $APPLCSF
[apppqs1i@psbsashebsap1 applcsf]$ pwd
/ppqs1i/applcsf
[apppqs1i@psbsashebsap1 applcsf]$ cd tmp
[apppqs1i@psbsashebsap1 tmp]$ pwd
/ppqs1i/applcsf/tmp

[apppqs1i@psbsashebsap1 tmp]$ cd $APPLTMP
[apppqs1i@psbsashebsap1 appltmp]$ pwd
/ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp
[apppqs1i@psbsashebsap1 appltmp]$






+---------------------------------------------------------------------------+
Business Online: Version : 12.2

Copyright (c) 1998, 2013, Oracle and/or its affiliates. All rights reserved.

PBS_AVNET_IN_FILE: PBS Avnet FTP External Data Load
+---------------------------------------------------------------------------+

Current system time is 21-SEP-2021 07:56:59

+---------------------------------------------------------------------------+

--------------------------------------------------------------------
Application Object Library Default Parameter Values
--------------------------------------------------------------------

Applications Login User Id     : 1554
Applications Login User Name   : ROBERTS
Concurrent Request Id          : 36071050
--------------------------------------------------------------------
User Parameter values
--------------------------------------------------------------------
Avnet Host Address             : ftp.snaponbusinesssolutions.com
Avnet FTP User Name            : Avnet
Data File Path                 : /inbound/shipNotifications
Source File Path               : ShipNotification
Application SID                : APPS/s1mpl3t3st
--------------------------------------------------------------------

1. OOD: PINGING PBS DB SERVER  to check if host is alive. 
1. RESULT: PBS DB SERVER is alive.
*****************************************************************************
Prepare Evironment
*****************************************************************************
Performing PPQS1I
At Destdir /oodxfer/wsh_avnet/inbound
At Srcdir ShipNotification
*******************************************************************************************
1. REMOTE:  PERFORMING FTP FROM ftp.snaponbusinesssolutions.com to  /oodxfer/wsh_avnet/inbound
1. REMOTE:  And save the files to CompletedShiptNotification
drwxr-sr-x  avnet/nobody      176 2021-09-21 07:53 .
drwxr-sr-x  avnet/nobody      132 2021-08-11 19:27 ..
-rw-r--r--  avnet/nobody     2605 2021-09-20 23:30 373054_09202021_083032.txt
-rw-r--r--  avnet/nobody     2541 2021-09-21 00:17 373056_09202021_091720.txt
-rw-r--r--  avnet/nobody     2681 2021-09-21 00:49 373058_09202021_094936.txt
-rw-r--r--  avnet/nobody     3112 2021-09-21 00:05 373060_09202021_090512.txt
-rw-r--r--  avnet/nobody     1399 2021-09-20 23:58 373062_09202021_085824.txt
status SFTP files from Srchost to rich-oodi
0
Here is the Results in Destdir:
373054_09202021_083032.txt
373056_09202021_091720.txt
373058_09202021_094936.txt
373060_09202021_090512.txt
373062_09202021_085824.txt
archive
bad
*******************************************************************************************
3. REMOTE: Delete files from Srcdir after FTP to rich-oodi.
3. REMOTE: Removing file 373054_09202021_083032.txt from ShipNotification
wsh_avnet/PBS_AVNET_LOAD_SH2.prog[118]: prompt: not found [No such file or directory]
3. REMOTE: Removing file 373056_09202021_091720.txt from ShipNotification
wsh_avnet/PBS_AVNET_LOAD_SH2.prog[118]: prompt: not found [No such file or directory]
3. REMOTE: Removing file 373058_09202021_094936.txt from ShipNotification
wsh_avnet/PBS_AVNET_LOAD_SH2.prog[118]: prompt: not found [No such file or directory]
3. REMOTE: Removing file 373060_09202021_090512.txt from ShipNotification
wsh_avnet/PBS_AVNET_LOAD_SH2.prog[118]: prompt: not found [No such file or directory]
3. REMOTE: Removing file 373062_09202021_085824.txt from ShipNotification
wsh_avnet/PBS_AVNET_LOAD_SH2.prog[118]: prompt: not found [No such file or directory]
*******************************************************************************************
4. REMOTE: This routine renames all the files to have the PBS_AVNET_ appended to the beginning.
*******************************************************************************************
5. REMOTE: Here is a list of files to be transferred:
archive
bad
PBS_AVNET_373054_09202021_083032.txt
PBS_AVNET_373056_09202021_091720.txt
PBS_AVNET_373058_09202021_094936.txt
PBS_AVNET_373060_09202021_090512.txt
PBS_AVNET_373062_09202021_085824.txt
*******************************************************************************************
6. REMOTE: Avnet File(s) ready to be transferred to OOD FTP Server: (ftp01.oracle.com) 
Interactive mode off.
Passive mode off.
257 "/interface/infpqsti/PPQS1I/incoming"
Local directory now /oodxfer/wsh_avnet/inbound
-rw-r--r--    1 510      510          2668 Sep 21 11:57 PBS_AVNET_373054_09202021_083032.txt
-rw-r--r--    1 510      510          2603 Sep 21 11:57 PBS_AVNET_373056_09202021_091720.txt
-rw-r--r--    1 510      510          2745 Sep 21 11:57 PBS_AVNET_373058_09202021_094936.txt
-rw-r--r--    1 510      510          3188 Sep 21 11:57 PBS_AVNET_373060_09202021_090512.txt
-rw-r--r--    1 510      510          1434 Sep 21 11:57 PBS_AVNET_373062_09202021_085824.txt
0
Status on transfer file to ftp01.oracle.com
6. RESULT: Avnet File(s) transferred to OOD FTP Server using simple FTP -- SUCCESSFUL.
*******************************************************************************************
7. REMOTE: Archiving /oodxfer/wsh_avnet/inbound/PBS_AVNET* TO
7. REMOTE: /oodxfer/wsh_avnet/inbound/archive 
*******************************************************************************************
8. REMOTE: Housecleaning - remove archive files GT 14 days old.
9. RESULT: Relinquishing control to OOD Server(dual step).
8. RESULT: Remote Script Complete. Returned to Calling Script on OOD Server. 
9. RESULT: COPY SUCCESSFUL -- Ready for Import Step -- Please proceed.
10. OOD: Transforming XML file for PBS_AVNET_373054_09202021_083032.txt ...
11. OOD: Copy to /ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp Successful.

Submitting the PBS XML Ship Confirmation for PBS_AVNET_373054_09202021_083032.txt ...

Calling PBS_XML_GATE_SHIP_CONFIRM.sql.../ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp PBS_AVNET_373054_09202021_083032.txt 373054 36071050 1554

SQL*Plus: Release 10.1.0.5.0 - Production on Tue Sep 21 07:57:22 2021

Copyright (c) 1982, 2005, Oracle.  All rights reserved.


Connected to:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Advanced Analytics
and Real Application Testing options

/ppqs1i/applcsf/tmp/
PBS_AVNET_373054_09202021_083032.txt
Testing Seeded Inbound Map for Oracle XML Gateway
Errors for Sample Inbound
Error Code
Error Messg
Error MessgORA-29283: invalid file operation
ORA-06512: at "SYS.UTL_FILE", line
536
ORA-29283: invalid file operation
PBS_XML_GATE_SHIP_CONFIRM.sql  done

PL/SQL procedure successfully completed.

No errors.
Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Advanced Analytics
and Real Application Testing options

Completed processing XML, Shell Script PBS_AVNET_LOAD_SH execution...
File PBS_AVNET_373054_09202021_083032.txt Deleted from /ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp

10. OOD: Transforming XML file for PBS_AVNET_373056_09202021_091720.txt ...
11. OOD: Copy to /ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp Successful.

Submitting the PBS XML Ship Confirmation for PBS_AVNET_373056_09202021_091720.txt ...

Calling PBS_XML_GATE_SHIP_CONFIRM.sql.../ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp PBS_AVNET_373056_09202021_091720.txt 373056 36071050 1554

SQL*Plus: Release 10.1.0.5.0 - Production on Tue Sep 21 07:57:22 2021

Copyright (c) 1982, 2005, Oracle.  All rights reserved.


Connected to:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Advanced Analytics
and Real Application Testing options

/ppqs1i/applcsf/tmp/
PBS_AVNET_373056_09202021_091720.txt
Testing Seeded Inbound Map for Oracle XML Gateway
Errors for Sample Inbound
Error Code
Error Messg
Error MessgORA-29283: invalid file operation
ORA-06512: at "SYS.UTL_FILE", line
536
ORA-29283: invalid file operation
PBS_XML_GATE_SHIP_CONFIRM.sql  done

PL/SQL procedure successfully completed.

No errors.
Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Advanced Analytics
and Real Application Testing options

Completed processing XML, Shell Script PBS_AVNET_LOAD_SH execution...
File PBS_AVNET_373056_09202021_091720.txt Deleted from /ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp

10. OOD: Transforming XML file for PBS_AVNET_373058_09202021_094936.txt ...
11. OOD: Copy to /ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp Successful.

Submitting the PBS XML Ship Confirmation for PBS_AVNET_373058_09202021_094936.txt ...

Calling PBS_XML_GATE_SHIP_CONFIRM.sql.../ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp PBS_AVNET_373058_09202021_094936.txt 373058 36071050 1554

SQL*Plus: Release 10.1.0.5.0 - Production on Tue Sep 21 07:57:23 2021

Copyright (c) 1982, 2005, Oracle.  All rights reserved.


Connected to:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Advanced Analytics
and Real Application Testing options

/ppqs1i/applcsf/tmp/
PBS_AVNET_373058_09202021_094936.txt
Testing Seeded Inbound Map for Oracle XML Gateway
Errors for Sample Inbound
Error Code
Error Messg
Error MessgORA-29283: invalid file operation
ORA-06512: at "SYS.UTL_FILE", line
536
ORA-29283: invalid file operation
PBS_XML_GATE_SHIP_CONFIRM.sql  done

PL/SQL procedure successfully completed.

No errors.
Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Advanced Analytics
and Real Application Testing options

Completed processing XML, Shell Script PBS_AVNET_LOAD_SH execution...
File PBS_AVNET_373058_09202021_094936.txt Deleted from /ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp

10. OOD: Transforming XML file for PBS_AVNET_373060_09202021_090512.txt ...
11. OOD: Copy to /ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp Successful.

Submitting the PBS XML Ship Confirmation for PBS_AVNET_373060_09202021_090512.txt ...

Calling PBS_XML_GATE_SHIP_CONFIRM.sql.../ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp PBS_AVNET_373060_09202021_090512.txt 373060 36071050 1554

SQL*Plus: Release 10.1.0.5.0 - Production on Tue Sep 21 07:57:23 2021

Copyright (c) 1982, 2005, Oracle.  All rights reserved.


Connected to:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Advanced Analytics
and Real Application Testing options

/ppqs1i/applcsf/tmp/
PBS_AVNET_373060_09202021_090512.txt
Testing Seeded Inbound Map for Oracle XML Gateway
Errors for Sample Inbound
Error Code
Error Messg
Error MessgORA-29283: invalid file operation
ORA-06512: at "SYS.UTL_FILE", line
536
ORA-29283: invalid file operation
PBS_XML_GATE_SHIP_CONFIRM.sql  done

PL/SQL procedure successfully completed.

No errors.
Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Advanced Analytics
and Real Application Testing options

Completed processing XML, Shell Script PBS_AVNET_LOAD_SH execution...
File PBS_AVNET_373060_09202021_090512.txt Deleted from /ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp

10. OOD: Transforming XML file for PBS_AVNET_373062_09202021_085824.txt ...
11. OOD: Copy to /ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp Successful.

Submitting the PBS XML Ship Confirmation for PBS_AVNET_373062_09202021_085824.txt ...

Calling PBS_XML_GATE_SHIP_CONFIRM.sql.../ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp PBS_AVNET_373062_09202021_085824.txt 373062 36071050 1554

SQL*Plus: Release 10.1.0.5.0 - Production on Tue Sep 21 07:57:24 2021

Copyright (c) 1982, 2005, Oracle.  All rights reserved.


Connected to:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Advanced Analytics
and Real Application Testing options

/ppqs1i/applcsf/tmp/
PBS_AVNET_373062_09202021_085824.txt
Testing Seeded Inbound Map for Oracle XML Gateway
Errors for Sample Inbound
Error Code
Error Messg
Error MessgORA-29283: invalid file operation
ORA-06512: at "SYS.UTL_FILE", line
536
ORA-29283: invalid file operation
PBS_XML_GATE_SHIP_CONFIRM.sql  done

PL/SQL procedure successfully completed.

No errors.
Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Advanced Analytics
and Real Application Testing options

Completed processing XML, Shell Script PBS_AVNET_LOAD_SH execution...
File PBS_AVNET_373062_09202021_085824.txt Deleted from /ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp




+---------------------------------------------------------------------------+
Executing request completion options...

Output file size: 



Output is not being printed because:
The print option has been disabled for this report.

+------------- 1) PRINT    -------------+
+---------------------------------------+


Finished executing request completion options.

+---------------------------------------------------------------------------+
Concurrent request completed successfully
Current system time is 21-SEP-2021 07:57:24

+---------------------------------------------------------------------------+

**Comment by vinaytalasila** [comment]
Mark,

To verify the directories and paths, I tried to check the 'View Log' of the previous runs of the 'PBS Avnet FTP External Data Load' program in INT 12.2.10 instance but unable to open that.

![image](https://user-images.githubusercontent.com/84878630/134424741-7fa19fe8-0f36-432a-b50d-968e81a01ae5.png)

Could you please run 'PBS Avnet FTP External Data Load' program in INT 12.2.10 instance so that we can see whether it creates the Inbound files in the correct location? If it works good there then we can compare that with the Production instance.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Vinay
I had the same issue checking view log in INT for the Job.
Unfortunately - I do no know how to test this right now.
This is Sherry's area and she is on vacation.
Tina just sent it to me today.
I will find find out tomorrow.

**Comment by vinaytalasila** [comment]
Noted Mark. We can discuss more regarding this in our 10:00 AM EDT meeting. I will include DBA team as well in that meeting.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
**@amitjori and @SomuSundaramM:** I had a Teams meeting with Mark. Could you please review the log file that was attached by Mark in this ticket and check whether you find anything before our meeting tomorrow. 

**@ashoksnapfj:** Please help / work with DBA team regarding this.

Thanks
Vinay

**Comment by SomuSundaramM** [comment]
Hi Mark,

I've mapped the appltmp path to $APPLCSF/tmp in our env file. Can you please retest now and update  the result.

Thanks,
Somu

**Comment by hamiltonmark** [comment]
Deb ran the job this morning - PBS Avnet FTP External Data Load
but it still errored.  See Log below...

Can you please check on the Directory Object - SBS_UTL_FILE_DIR ?



+---------------------------------------------------------------------------+
Business Online: Version : 12.2

Copyright (c) 1998, 2013, Oracle and/or its affiliates. All rights reserved.

PBS_AVNET_IN_FILE: PBS Avnet FTP External Data Load
+---------------------------------------------------------------------------+

Current system time is 23-SEP-2021 08:30:05

+---------------------------------------------------------------------------+

--------------------------------------------------------------------
Application Object Library Default Parameter Values
--------------------------------------------------------------------

Applications Login User Id     : 1554
Applications Login User Name   : ROBERTS
Concurrent Request Id          : 36078318
--------------------------------------------------------------------
User Parameter values
--------------------------------------------------------------------
Avnet Host Address             : ftp.snaponbusinesssolutions.com
Avnet FTP User Name            : Avnet
Data File Path                 : /inbound/shipNotifications
Source File Path               : ShipNotification
Application SID                : APPS/s1mpl3t3st
--------------------------------------------------------------------

1. OOD: PINGING PBS DB SERVER  to check if host is alive. 
1. RESULT: PBS DB SERVER is alive.
*****************************************************************************
Prepare Evironment
*****************************************************************************
Performing PPQS1I
At Destdir /oodxfer/wsh_avnet/inbound
At Srcdir ShipNotification
*******************************************************************************************
1. REMOTE:  PERFORMING FTP FROM ftp.snaponbusinesssolutions.com to  /oodxfer/wsh_avnet/inbound
1. REMOTE:  And save the files to CompletedShiptNotification
drwxr-sr-x  avnet/nobody       74 2021-09-23 08:28 .
drwxr-sr-x  avnet/nobody      132 2021-08-11 19:27 ..
-rw-r--r--  avnet/nobody     1975 2021-09-22 17:42 373152_09222021_024249.txt
-rw-r--r--  avnet/nobody     1602 2021-09-22 15:29 373159_09222021_122957.txt
 status SFTP files from Srchost to rich-oodi
0
Here is the Results in Destdir:
373152_09222021_024249.txt
373159_09222021_122957.txt
archive
bad
*******************************************************************************************
3. REMOTE: Delete files from Srcdir after FTP to rich-oodi.
3. REMOTE: Removing file 373152_09222021_024249.txt from ShipNotification
wsh_avnet/PBS_AVNET_LOAD_SH2.prog[118]: prompt: not found [No such file or directory]
3. REMOTE: Removing file 373159_09222021_122957.txt from ShipNotification
wsh_avnet/PBS_AVNET_LOAD_SH2.prog[118]: prompt: not found [No such file or directory]
*******************************************************************************************
4. REMOTE: This routine renames all the files to have the PBS_AVNET_ appended to the beginning.
*******************************************************************************************
5. REMOTE: Here is a list of files to be transferred:
archive
bad
PBS_AVNET_373152_09222021_024249.txt
PBS_AVNET_373159_09222021_122957.txt
*******************************************************************************************
6. REMOTE: Avnet File(s) ready to be transferred to OOD FTP Server: (ftp01.oracle.com) 
Interactive mode off.
Passive mode off.
257 "/interface/infpqsti/PPQS1I/incoming"
Local directory now /oodxfer/wsh_avnet/inbound
-rw-r--r--    1 510      510          2023 Sep 23 12:30 PBS_AVNET_373152_09222021_024249.txt
-rw-r--r--    1 510      510          1640 Sep 23 12:30 PBS_AVNET_373159_09222021_122957.txt
0
Status on transfer file to ftp01.oracle.com
6. RESULT: Avnet File(s) transferred to OOD FTP Server using simple FTP -- SUCCESSFUL.
*******************************************************************************************
7. REMOTE: Archiving /oodxfer/wsh_avnet/inbound/PBS_AVNET* TO
7. REMOTE: /oodxfer/wsh_avnet/inbound/archive 
*******************************************************************************************
8. REMOTE: Housecleaning - remove archive files GT 14 days old.
9. RESULT: Relinquishing control to OOD Server(dual step).
8. RESULT: Remote Script Complete. Returned to Calling Script on OOD Server. 
9. RESULT: COPY SUCCESSFUL -- Ready for Import Step -- Please proceed.
10. OOD: Transforming XML file for PBS_AVNET_373152_09222021_024249.txt ...
11. OOD: Copy to /ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp Successful.

Submitting the PBS XML Ship Confirmation for PBS_AVNET_373152_09222021_024249.txt ...

Calling PBS_XML_GATE_SHIP_CONFIRM.sql.../ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp PBS_AVNET_373152_09222021_024249.txt 373152 36078318 1554

SQL*Plus: Release 10.1.0.5.0 - Production on Thu Sep 23 08:30:19 2021

Copyright (c) 1982, 2005, Oracle.  All rights reserved.


Connected to:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Advanced Analytics
and Real Application Testing options

/ppqs1i/applcsf/tmp/
PBS_AVNET_373152_09222021_024249.txt
Testing Seeded Inbound Map for Oracle XML Gateway
Errors for Sample Inbound
Error Code
Error Messg
Error MessgORA-29283: invalid file operation
ORA-06512: at "SYS.UTL_FILE", line
536
ORA-29283: invalid file operation
PBS_XML_GATE_SHIP_CONFIRM.sql  done

PL/SQL procedure successfully completed.

No errors.
Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Advanced Analytics
and Real Application Testing options

Completed processing XML, Shell Script PBS_AVNET_LOAD_SH execution...
File PBS_AVNET_373152_09222021_024249.txt Deleted from /ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp

10. OOD: Transforming XML file for PBS_AVNET_373159_09222021_122957.txt ...
11. OOD: Copy to /ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp Successful.

Submitting the PBS XML Ship Confirmation for PBS_AVNET_373159_09222021_122957.txt ...

Calling PBS_XML_GATE_SHIP_CONFIRM.sql.../ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp PBS_AVNET_373159_09222021_122957.txt 373159 36078318 1554

SQL*Plus: Release 10.1.0.5.0 - Production on Thu Sep 23 08:30:19 2021

Copyright (c) 1982, 2005, Oracle.  All rights reserved.


Connected to:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Advanced Analytics
and Real Application Testing options

/ppqs1i/applcsf/tmp/
PBS_AVNET_373159_09222021_122957.txt
Testing Seeded Inbound Map for Oracle XML Gateway
Errors for Sample Inbound
Error Code
Error Messg
Error MessgORA-29283: invalid file operation
ORA-06512: at "SYS.UTL_FILE", line
536
ORA-29283: invalid file operation
PBS_XML_GATE_SHIP_CONFIRM.sql  done

PL/SQL procedure successfully completed.

No errors.
Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Advanced Analytics
and Real Application Testing options

Completed processing XML, Shell Script PBS_AVNET_LOAD_SH execution...
File PBS_AVNET_373159_09222021_122957.txt Deleted from /ppqs1i/12.2/PROD/fs2/inst/apps/PPQS1I_psbsashebsap1/appltmp




+---------------------------------------------------------------------------+
Executing request completion options...

Output file size: 



Output is not being printed because:
The print option has been disabled for this report.

+------------- 1) PRINT    -------------+
+---------------------------------------+


Finished executing request completion options.

+---------------------------------------------------------------------------+
Concurrent request completed successfully
Current system time is 23-SEP-2021 08:30:19

+---------------------------------------------------------------------------+

**Comment by vinaytalasila** [comment]
Just an update...Somu will publish the next action steps regarding this issue and request for approval for the downtime of Production instance tonight.

Thanks
Vinay

**Comment by SomuSundaramM** [comment]
Hi Linda,

Please approve the below downtime to bounce the application services for resetting the env variable of $APPLTMP.

Instance : PPQS1I
Downtime : 24-Sep-21 @1.00 AM EST to 1.30 EST

Thanks,
Somu

**Comment by lindamrigo** [comment]
Below downtime is approved

**Comment by SomuSundaramM** [comment]
Hi Mark,

We have bounced the services by resetting the env to right path, Please retest now 

![image](https://user-images.githubusercontent.com/85238833/134624483-140f0223-cd07-4fa9-9a74-f3735218060d.png)


Thanks,
Somu

**Comment by vinaytalasila** [comment]
Update....

As per today's status meeting, end user will create a new order on 09/27/2021 then we can check whether this issue resolved or not.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Response from Deb Roberts...

![image](https://user-images.githubusercontent.com/85197361/134913468-2e2a3c8a-89eb-44b8-a5cf-dc6a0a2cb361.png)

**Comment by hamiltonmark** [comment]
Thanks Som/Vinay
This ticket can be closed.
Thanks
Mark

**Comment by vinaytalasila** [comment]
Thank you for your update Mark.

**Comment by hamiltonmark** [comment]
[PBS_Avnet_FTP_External_Data_Lo_270921_SUCCESSFUL_LOG_AFTER_FIX.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7236439/PBS_Avnet_FTP_External_Data_Lo_270921_SUCCESSFUL_LOG_AFTER_FIX.txt)
