### ISSUE TITLE
Production timing within 10 minutes when using HTML forms

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#116]
Production timing within 10 minutes when using HTML forms

**Comment by vinaytalasila** [comment]
Linda,

Is this happening to all the users or only to some of them? 

**@amitjori:** Could you please look into this?

Thanks
Vinay

**Comment by lindamrigo** [comment]
This is happening to all users

**Comment by SomuSundaramM** [comment]
Hi Linda,

Checking on this.

Thanks,
Somu

**Comment by lindamrigo** [comment]
It is happening on HTML forms - timing out after 15 minutes.
These two were noted by Nichole Dotson ->PBS US Finance Approval (and CA) Workflow Notifications and PBS US Quote and Install Base View ( and CA) Quotes, Quotes, Dashboard.
I had it happen on SOA Integration

**Comment by vinaytalasila** [comment]
Linda,

Thank you for the details. Somu will check this from from his user.

Thanks
Vinay

**Comment by lindamrigo** [comment]
This is happening on all HTML forms. Nichole's were just an example. Use Integrated SOA Responsibility, click Search and let the form sit for 15 minutes also causes a timeout.  Nichole was using PBS US Finance Approval responsibility

**Comment by vinaytalasila** [comment]
Update...

When Somu and Hanmant tested this in the Production instance in the jump server and it did not time out for them.

So the steps are...

- Amit or Somu needs to login to Production instance thru Snap-On's VPN and do the test.

- Linda needs to check whether the same issue is happening in INT 12.2.10 instance as well or not. 

- Linda needs to check whether this is a Firefox browser issue. She can try the same test in Chrome browser and let us know the results.

Thanks
Vinay

**Comment by lindamrigo** [comment]
Got confirmation from Nichole and Mark P that they are no longer timing out
