### ISSUE TITLE
PRD iPay Process - Create Auto Receipts duplicating Receipts **SR 3-27129228041 : Manually added Credit Cards on Invoices having Duplicate Receipts

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#117]
**Describe the bug**

**Instance Name**
Instance:  ppqs1i

**Responsibility Name**
Responsibility:  

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
Now that we are able to get thru the iPayment Process.

Create Auto Receipts is creating duplicate Receipts - one in open and one is closed.
Not sure if this is new functionality or an issue.
Went back to INT and the same happened there but end user did not notice it.

![image](https://user-images.githubusercontent.com/85197361/134515588-8790416c-f2d6-4789-9e1c-95c05f5be277.png)

**Comment by hamiltonmark** [comment]
Had a discussion with Millice in AR.
Normally a Service Contract could have a credit card.
It would be invoiced and then
during the iPay Process - Auto Receipts would be created.

She is saying - for these tests (both INT and PRD) - since 
Service Contracts Main Billing had not run yet - 
she "manually" added the credit card to the invoice.

Millice is saying - the duplicate receipts are only being replicated for invoices
where they were manually entered.  In INT the receipts auto created from Service Contracts
into invoices were NOT duplicated.

I think we are good to go for processing iPays but
will still enter an SR to verify.

**Comment by vinaytalasila** [comment]
Mark,

Thank you for the update.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
SR Created

SR 3-27129228041 : Manually added Credit Cards on Invoices having Duplicate Receipts

[Duplicate Receipts for Manually adding CC to Invoice.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7218929/Duplicate.Receipts.for.Manually.adding.CC.to.Invoice.docx)

**Comment by hamiltonmark** [comment]
Hello Mark,

Please provide the following file(s):

1. AR Receipt Analyzer: For R12, please run the Receivables Receipt Analyzer for the following receipt numbers:

9070298
9070299
9070300

Take note that analyzers are *different* from diagnostics. We need you to upload the analyzer because it contains a more comprehensive list of checks that can help us resolve your issue(s) faster.

Ensure you provide at least version 200.27, for details review Note 2089720.1 : EBS Receivables Receipt Analyzer.
Run with the following parameters:

User Name: Enter the User name currently logged in
Responsibility Name: Enter the Responsibility you are using
Receipt#: Enter the Receipt# with the issue
Include GL Tables: Y
Include Apps Check: N

Review the output generated by the analyzer because it may identify errors/warnings and recommendations on how you can fix them.

NOTE: Save output as 'Webpage, HTML only' and upload to SR, if you need additional assistance from Support.

Thank you

Uploaded....

[Receivables_Receipt_Analyzers_240921.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7228227/Receivables_Receipt_Analyzers_240921.zip)

**Comment by hamiltonmark** [comment]
I updated the SR with the following...

![image](https://user-images.githubusercontent.com/85197361/134961804-96e59430-d5b4-4a42-ba5a-9498480fe108.png)

**Comment by hamiltonmark** [comment]
SR Updated with ...

![image](https://user-images.githubusercontent.com/85197361/134981840-72bf7a9a-01c3-4f4d-9fba-f6a2d9bef568.png)

**Comment by hamiltonmark** [comment]
Since setups were incorrect and needed updated with the proper folder - the receipts were left in limbo.
Did the following sql's to reset the 3 receipts so the iPay Process would select them and send them to Paymentech.

-- ACTUAL FIX SCRIPTS USED 

-- 1.  SUMMARY  -- THESE ARE THE VALUES TO SET THEM TO
--   SET STATUS = 100,
--       BATCHID = NULL,
--       MBATCHID = NULL,
--       OBJECT_VERSION_NUMBER = 999
select S.ROWID, S.STATUS, S.BATCHID, S.MBATCHID, S.OBJECT_VERSION_NUMBER
from IBY_TRXN_SUMMARIES_ALL S
WHERE  STATUS = 111
AND BATCHID =  '2442_1'  

-- 2.  BATCH  -- THESE ARE THE VALUES TO SET THEM TO
--   SET BATCHSTATUS = 114,
--       OBJECT_VERSION_NUMBER = 999
select B.ROWID, B.BATCHSTATUS, B.OBJECT_VERSION_NUMBER, b.batchid
from IBY_BATCHES_ALL B
WHERE 1=1 --B.BATCHSTATUS = 11
AND B.BATCHID =  '2442_1'  

-- RESUBMIT  - CREATE BATCH SETTLEMENTS FOR 2442_1

Once Create Settlement Batches were re-submitted - file was sent to Paymentech.
Fetch Settlement Batches were run 30 mins later and pulled into back into EBS.

Two of the 3 receipts were cleared.
One of the receipts did not clear because it had a maturity date in October 2021.
Found the invoice had a payment term = Net 30 (this is an error).  Any invoice with a credit card
needs a payment term = Immediate.  This is why the maturity date was 30 days in the future.

Once receipt's maturity date was fixed and Clear Autoreceipts was run - all was well.

This was all caused because - iPay setup path still had 12.1.3 paths so Create Settlement tried to create
file in wrong folder.

**Comment by hamiltonmark** [comment]
Vinay
Latest update from Millice...
This ticket can be closed.
Thanks
Mark

![image](https://user-images.githubusercontent.com/85197361/135100610-f0aaf35b-966c-45a2-b80d-aea5667d360c.png)

**Comment by vinaytalasila** [comment]
Mark,

Thank you for your update. I am closing this ticket now.

Thanks
Vinay
