### ISSUE TITLE
PRD Cancel a PO Req gives error No control actions found for this document

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#119]
**Describe the bug**

**Instance Name**
Instance:  PPQS1I AND DPQS2I

**Responsibility Name**
Responsibility:  

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
See doc for navigation and screenshots.
Same issue in INT and PRD.


[Trying to Cancel PO Req gives error No control actions found for this document.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7219631/Trying.to.Cancel.PO.Req.gives.error.No.control.actions.found.for.this.document.docx)

**Comment by hamiltonmark** [comment]
SR 3-27133746991 : Cancel a PO Req gives error No control actions found for this document
While entering SR - SR suggested this doc...



[Navigating to Tools Control from Requisition Summary Results in No control actions found for this document Doc ID 330455_1.pdf](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7220096/Navigating.to.Tools.Control.from.Requisition.Summary.Results.in.No.control.actions.found.for.this.document.Doc.ID.330455_1.pdf)
nt

**Comment by vinaytalasila** [comment]
Mark,

I have reviewed the document and I see that there are some 'delete' related steps. So, can we have a **Teams meeting now** and do that action steps in that session. If that works then either you (if you have access) or end users needs to do the same steps in the Production instance.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Please send me the Teams Mtg... thanks

**Comment by vinaytalasila** [comment]
Mark, I have sent the Teams Mtg invite.

**Comment by hamiltonmark** [comment]
SR Analyst is saying ... Since PO Req is in status = IN PROCESS
then PO REQ must be
1.  Rejected first
2.  then Cancelled

I will communicated this to Brenda Pennington and have her try it for REQ 43521

--------------------UPDATE ACTION PLAN DETAILS BELOW---------------------
Owner
------------------------------------------------------
Mark


ACTION PLAN
-------------------------------------------------------

The Requisition is in the status of In Process .
You are not allowed to cancel a Requisition that is in the Approval process

Lee

**Comment by hamiltonmark** [comment]
According to the SR Analyst and Vinay's knowledge bank… (and this may be a new step in the process since the upgrade)…

TO Cancel a PO Req that is “IN PROCESS”:

1.	Brenda can “REJECT” the PO Req
2.	Wait 10 mins for the Workflow Background to Run
3.	Then it can be Cancelled.

I spoke to Brenda P on the phone and she did this in PRD and
It was successfully Cancelled.

**Comment by hamiltonmark** [comment]
This ticket can be closed.

**Comment by vinaytalasila** [comment]
Mark - Thank you for your update.

Thanks
Vinay
