### ISSUE TITLE
Web ADI Upload Issues

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#120]
Having issues uploading from existing spreadsheet into Web ADI. The spreadsheet works the first day it is created but when that same spreadsheet is used the next day, unable to select List of Values and error occurs.  New spreadsheet works fine but an existing spreadsheet will only upload onc
![ADI Error](https://user-images.githubusercontent.com/85238444/134556045-bd2aa47f-287b-4fbf-95d8-0b5fef477b3c.JPG)
e.

**Comment by vinaytalasila** [comment]
Linda,

Could you please provide the navigation to that WebADI function so that I will try to check from my end in INT 12.2.10 instance. If you have already checked that in INT 12.2.10 instance and it works there then please upload that file to this ticket.

Thanks
Vinay

**Comment by lindamrigo** [comment]
Vinay
Grace was in excel in version 2016 & 2013.  Attached is the ADI spreadsheet

Grace opens the spreadsheet
Then she hits the Upload button on the upper left
The error occurs.

Thanks
Linda

**Comment by lindamrigo** [comment]
Grace is in excel in version 2016 & 2013.  Attached is the ADI spreadsheet

Grace opens the spreadsheet
Then she hits the Upload button on the upper left
The error occurs.

Thanks
Linda

**Comment by vinaytalasila** [comment]
Linda,

Could not find ADI spreadsheet in your comments. Could you please check and upload it again.

May I also know the Navigation (Responsibility and function name). 

As I cannot this issue from my end in non-production instances, can I have a Teams session with Grace.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Linda,

Ref: https://github.com/Fujitsu-America/Fujitsu-Repository/issues/50

Below comments are from the above mentioned ticket..

**Art from the SBS ATS department has resolved the issue. All documentation for IE settings has said Trusted Sites, but Art added everything to the Local Intranet settings and Debbie is now working. IE settings needed to be done for local intranet option**

Could you please check whether the above setups are missing for Grace.

Thanks
Vinay

**Comment by lindamrigo** [comment]
This isn't the same issue.  Grace is able to use Web ADI on Monday. On Tuesday, the same spreadsheet that successfully uploaded on Monday, no longer works following an update of the data on the spreadsheet.  The spreadsheet no longer works at all and Debbie G. has to create a new spreadsheet for Grace. This was not a problem in INT.

**Comment by lindamrigo** [comment]
[General Ledger - Journals 2016 09232021.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7236421/General.Ledger.-.Journals.2016.09232021.zip)

**Comment by vinaytalasila** [comment]
Update...

- Recommended steps...1) Login to Oracle Applications 2) Update some info in the spreadsheet 3) Upload (at this point if Grace still faces the same error then needs to check which responsibility she uses and have a Teams meeting with us).
- Linda will check with Grace today.  

Thanks
Vinay

**Comment by lindamrigo** [comment]
Below is Grace's response:
Hi Linda,

As we discussed.  I do not want to create a new form each time I need to use the ADI.

I want to be able to use the form I created originally and just refresh that data, as I currently do.

I am going to create a new form today and try it as I now have the Oracle responsibility to see if that makes a difference.
However I have always used forms in the past that others created and I just reused them on a monthly basis.

I will let you know how that goes after I generate a new form today.

Thanks,
Grace

**Comment by vinaytalasila** [comment]
Linda,

Thank you for posting Grace's response. So, I believe that we can expect her reply in a day or two.

Thanks
Vinay

**Comment by lindamrigo** [comment]
Grace had an error the first time she went to do the upload today but I asked if she try again and the 2nd time it worked.  I am keeping this open through the rest of week as to give Grace time to test tomorrow and Thursday

**Comment by lindamrigo** [comment]
I just found out today that Randy Agler has also been having issues with ADI when he never had any issues when testing
[Agler ADI Issues.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7252165/Agler.ADI.Issues.docx)
.

**Comment by lindamrigo** [comment]
It has been corrected by making sure that the user is logged into EBS prior to starting the ADI upload results in a successful ADI upload
