### ISSUE TITLE
PRD AR Aging buckets are not correct after upgrade ##SR 3-27146589141 : AR Aging buckets are not correct after upgrade

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#121]
**Describe the bug**
When the Aging is run...the buckets are not the same as what we had before.  In fact, Nichole said she validated it in the non-prod test but I just had her retry it in INT and it's the same as production.

**Instance Name**
Instance: PPQS1I

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**
Aging buckets should be the same as what we had.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TinaGriffin** [comment]
[After 12-2-10 Upgrade Aging Buckets are not the same as they used to be.xlsx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7220403/After.12-2-10.Upgrade.Aging.Buckets.are.not.the.same.as.they.used.to.be.xlsx)

**Comment by hamiltonmark** [comment]
Tina
I will open an SR with the following info...

[Aging buckets are not correct.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7225824/Aging.buckets.are.not.correct.docx)

**Comment by hamiltonmark** [comment]
SR Created

SR 3-27146589141 : AR Aging buckets are not correct after upgrade

**Comment by hamiltonmark** [comment]
Before and After Collections Bucket Setup in INT.
Changes have been made in INT.
End User is testing.
Waiting for response.

[Collections Aging Bucket Before and After in INT.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7227044/Collections.Aging.Bucket.Before.and.After.in.INT.docx)

**Comment by hamiltonmark** [comment]
INT Testing Results...

![image](https://user-images.githubusercontent.com/85197361/134709737-67ed3509-b8a0-4e9d-b2da-78e4311fd25a.png)

**Comment by hamiltonmark** [comment]
End User - Nichole - has changed the Collections Aging Bucket Setup in Prod.
All seems to be working as expected.

OK to close this ticket.

**Comment by vinaytalasila** [comment]
Mark,

Thank you for your update. I am 'Closing' this ticket now.

Thanks
Vinay
