### ISSUE TITLE
PRD Create Accounting Error 95937 non accountable events

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#122]
**Describe the bug**

**Instance Name**
Instance:  PPQS1I

**Responsibility Name**
Responsibility:   PBS US General Ledger User

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
Vinay
Our Accountant, Liz Fulton, ran her weekly job for Create Accounting.

[Sep21 US Week 4 Part C Receivables Summary.pdf](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7227695/Sep21.US.Week.4.Part.C.Receivables.Summary.pdf)

Report had an error message:

![image](https://user-images.githubusercontent.com/85197361/134721108-3ba786a3-73cd-4b8b-b1f8-878f5d2cff5c.png)

Liz has seen this in the past but wanted to make us aware in case it prevents her from closing period next week.

Here is a MOS Hit for the error:

[Create Accounting Error 95937 non accountable events Doc ID 1315042_1.pdf](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7227704/Create.Accounting.Error.95937.non.accountable.events.Doc.ID.1315042_1.pdf)

I am just entering this ticket to keep us prepared.

**Comment by vinaytalasila** [comment]
Mark,

Could you please request Liz Fulton to run the 'Subledger Period Close Exception' Report now in the AR. That report displays all accounting events and journal entries that fail period close validation. If that report looks good then there is no issue.
 
Thanks
Vinay

**Comment by hamiltonmark** [comment]
Vinay
Yes - sent off an email asking her to run it.
Waiting on her response.
Thanks
Mark

**Comment by hamiltonmark** [comment]
Vinay
Liz thanks you for the information and responds...
"Ok thanks I will keep that it mind.  I just ran it but there is now data from today’s activities."

Here is the report....

[Subledger_Period_Close_Excepti_240921.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7228132/Subledger_Period_Close_Excepti_240921.docx)

**Comment by vinaytalasila** [comment]
Mark,

I see that those transactions are not posted in GL yet. Could you please check whether any journal is created in GL for 'Receivables' Source with 'Unposted' status. If that exists then we are good or else it might have stuck somewhere in XLA.

![image](https://user-images.githubusercontent.com/84878630/134733640-b68e1408-b773-4e00-a2d7-402422c5d911.png)

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Asked Liz when they will Post again... here response....

No sorry we won’t post for another week.

**Comment by vinaytalasila** [comment]
'Update...

Mark will check with Liz whether any journal 'Source' as Receivables and 'Status' as Unposted exists in the Journal search. If it exists then we can 'Close' this issue. 

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Sent an email to her this morning 10:39am
Waiting for a response...

![image](https://user-images.githubusercontent.com/85197361/134952621-0346a66f-a79e-4011-903a-b86b418b29d9.png)

**Comment by hamiltonmark** [comment]
Spoke to Liz
She believes - all is well with this issue and
this ticket can be closed.

She really won't know if there is an issue until Sunday 10/2/2021
when she closes SEP21 AR Period and opens OCT21.

**Comment by vinaytalasila** [comment]
Mark,

Thank you for your update. I am closing this ticket now.

Thanks
Vinay
