### ISSUE TITLE
Ability for End User to View Other Concurrent Jobs than their own

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#124]
An end user now has the ability to view other people's concurrent jobs other than their own. The attached document goes through the steps.  FQ8809 should not be able to view SysAdmin jobs on hold. The user should only see his own concurrent requests and no one else's
[View Other jobs.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7238388/View.Other.jobs.docx)
.

**Comment by vinaytalasila** [comment]
**Linda,**

This used to work correctly in 12.1.3 release?

**@ashoksnapfj :** Could you please look into this? 

Responsibility name in the 'View Other jobs.docx' is not clear. Please check this issue for 'FQ8809' user in the 'PBS Automotive Customer Support' responsibility.

Thanks
Vinay

**Comment by lindamrigo** [comment]
An end user should not be able to see any concurrent job other than their own. So for FQ8809 to see Sys Admin jobs is not correct. This is what the screen shot was showing

**Comment by vinaytalasila** [comment]
Update...

As per today's status meeting, Linda will check this from her end and if works as expected ('Remove Hold', 'Cancel Request', 'View Log', 'View Output' and 'View Details -> Update' actions should not work from her user related to other users (example like SYSADMIN) ) then we will close this issue.

Thanks
Vinay

**Comment by lindamrigo** [comment]
Closing this as end user does not have ability to change the job
