### ISSUE TITLE
Add Back Save button to Update Customer Page

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#125]
Responsibility: Sales User
Go to Sales Dashboard>Search 87847 customer.
The Update Customer page no longer has the Save button. The Save button personalization for the Sales User responsibility needs to be removed as a Sales User requires the Save ability.
![Save button](https://user-images.githubusercontent.com/85238444/134968066-98e48372-f1c2-48db-a36d-5c0abd8f8311.png)
![Sales User Missing Save Button](https://user-images.githubusercontent.com/85238444/134968074-d9d741dc-6a0d-4654-ac7b-c8a3feb2f074.JPG)
Please make changes in INT first for testing purposes.

**Comment by vinaytalasila** [comment]
@AkshayK247: Could you please look into this?

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Linda,

Akshay made the changes in the INT instance. Could you please logout of your current INT session and log back in to test.

Thanks
Vinay

**Comment by lindamrigo** [comment]
I have asked the end user to confirm the Save button in INT.

**Comment by lindamrigo** [comment]
The end user has tested the Save button. Please make the change in production

**Comment by vinaytalasila** [comment]
Update...

- Akshay will upload the migration document for Linda's review.
- After that gets approved by Linda then Akshay will guide Somu to move that personalization to from INT to Production instance.

Thanks
Vinay

**Comment by AkshayK247** [comment]
Hi @lindamrigo 

Please review the attached migration document.

[Show Save Button for Update Customer on Sales Dashboard.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7245140/Show.Save.Button.for.Update.Customer.on.Sales.Dashboard.docx)



Regards,
Akshay

**Comment by lindamrigo** [comment]
This looks good, please proceed with the change

**Comment by vinaytalasila** [comment]
**@AkshayK247:** Please work with Somu regarding the migration of that personalization into Production instance.

Thanks
Vinay

**Comment by lindamrigo** [comment]
Has the change been migrated to production?

**Comment by SomuSundaramM** [comment]
Hi Linda,

We have just made the changes in production, Please request user to logout and re-login to verify the changes.
Thanks,
som

**Comment by lindamrigo** [comment]
I had the end-user test and the Save button is there
