### ISSUE TITLE
Searches not working for Sales & Territory Manager ***SR 3-26108359301***

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#13]
No customers returned for  all Sales and Territory Manager searches

**Comment by SherryXLiu** [comment]
[R12-2 ISSUES STG_SL.xlsx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6586080/R12-2.ISSUES.STG_SL.xlsx)
@Haqueraz @suhas-deshpande

**Comment by SherryXLiu** [comment]
Please review my issue list and give me feedback

**Comment by SherryXLiu** [comment]
@Haqueraz Do you still plan to meet at 11am to review the issue list?

**Comment by Haqueraz** [comment]
We are able to search in sales manager and others responsibilities as per the above excel sheet except the responsibility 'Territory Management' .
Please refer the attached doc to see the search data. 
[sales manager search.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6594708/sales.manager.search.docx)

**Comment by SherryXLiu** [comment]
Issue 11. TAC Customer search is OK

**Comment by SherryXLiu** [comment]
Issue 11. TCA Customer search is OK

**Comment by SherryXLiu** [comment]
Issue 10, is not change yet. PBS US Customer Inquiry should not include Canadian Customer
![image](https://user-images.githubusercontent.com/85246030/120820066-35605e00-c522-11eb-9c49-3d7e525f3e6e.png)

**Comment by SherryXLiu** [comment]
Issue 8; Sales Manager > Shortcut>Customer is now OK

**Comment by SherryXLiu** [comment]
Issue 10: PBS User Customer Inquiry is OK. Canadian Customer details is blacked

**Comment by SherryXLiu** [comment]
Issue 7: Sales Manager>Short cut>Contact is OK

**Comment by SherryXLiu** [comment]
Issue 5 Sales Manager> Lead>Recent Opportunity link is OK

**Comment by SherryXLiu** [comment]
All issues in the attached list are fixed, except customer Link error in Lead and Opportunity which you said the solution is waiting for DBA

**Comment by SherryXLiu** [comment]
And The Issues in TM modules are waiting for SR




<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:///C:\Users\lius\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel="File-List" href="file:///C:\Users\lius\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>





1 | TM | Territory   Management&gt;Territory Administration&gt;   Dashboard&nbsp;&nbsp;&gt;&nbsp;Sales Team Search&nbsp;&nbsp;&gt; | Error | 5/28/2021
-- | -- | -- | -- | --
2 | TM | Territory   Management&gt;Territory Administration&gt;   Dashboard&nbsp;&nbsp;&gt;&nbsp;Sales Team Search&nbsp;&nbsp;&gt; | No Records | 5/28/2021
3 | TM | Territory   Management &gt; Search | Error | 5/28/2021

**Comment by vinaytalasila** [comment]
Sherry,

Thank you for your testing. 

We will keep you posted when we get an update from Oracle's SR regarding # 1, 2 and 3.

Thanks
Vinay Talasila

**Comment by SherryXLiu** [comment]
Since the main problems are fixed, you may change this ticket type as Medium. Thanks

**Comment by suhas-deshpande** [comment]
Hi Sherry - We are now able to search from below navigation in STG after adding missing roles. 

1. Territory Management>Territory Administration> Dashboard  > Sales Team Search  >
2. Territory Management > Search

Attaching the screenshot for your reference. Please test and let us know if you are able to search.

![Capture](https://user-images.githubusercontent.com/85028593/121496729-44378c80-c9ca-11eb-8b4e-d1f170024df1.JPG)

**Comment by SherryXLiu** [comment]
It is now OK in INT
