### ISSUE TITLE
http://172.22.144.141:8181/ords/ & http://ssbsashebsap3.oci.snapbs.com:8181/ords not working

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#14]
http://172.22.144.141:8181/ords/ & http://ssbsashebsap3.oci.snapbs.com:8181/ords not working

receiving error 
Unable to connect

Firefox can’t establish a connection to the server at ssbsashebsap3.oci.snapbs.com:8181.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

and 
Unable to connect

Firefox can’t establish a connection to the server at 172.22.144.141:8181.

**Comment by amitjori** [comment]
Hi Linda,

Apex tomcat services were down , I have re-started the services. Can you please now and confirm?

Regards,
Amit

**Comment by amitjori** [comment]
Hi Linda,

Apex tomcat services were down , I have re-started the services. Can you please now and confirm?

Regards,
Amit

**Comment by lindamrigo** [comment]
HI Amit
It is now working.  Why were the services down?

Thanks
Linda

**Comment by lindamrigo** [comment]
Services are up and working
