### ISSUE TITLE
12.2.10 STG Issue with IB *** SR 3-26258040451 ***

### ISSUE THREAD

**Issue by vinaytalasila** [Fujitsu-America/Fujitsu-Repository#16]
**Describe the bug**
Attached are the screenshots for the Install Base Search not showing (above the warning).  This is happening in 12.1.3 INT, 12.1.3 PreProd, 12.2.10 STG but not happening in 12.1.3 Prod.

PBS US View Only Contracts and Install Base Responsibility
(it is working fine in the seeded Install Base responsibility called “Oracle Installed Base User”
[Document3.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6586805/Document3.docx)

**Instance Name**
Instance: STG 12.2.10

**Responsibility Name**
Responsibility: PBS US View Only Contracts and Install Base 

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TinaGriffin** [comment]
To access the Installed Base, you must have "Oracle Installed Base User" responsibility along with the PBS responsibility.  Also, you'll need crm html permissions.  The navigation for that is responsibility: CRM HTML Administration / Setup / Users / Registration / User Maintenance.  Enter your Oracle Username and select Go.  When the result returns, click on your highlighted username.  Select the Roles Tab.  Select "CSI_NORMAL_USER" from the Available Roles over to the Assigned Roles.  You will now have permissions to the Installed Base forms.

**Comment by Haqueraz** [comment]
Thank you for sharing the details.

**Comment by Haqueraz** [comment]
Hi Tina, 
Here is my analysis regrding the Quick Find search is not appearing in Custom responsibility but it is working fine in the seeded Install Base responsibility called “Oracle Installed Base User”. 

I checked custom responsibility has been created in 'contract core' application under 'oracle application form' but the standard responsibility has been created in  Install Base application under web service application. 

Quick find search does not supporting to contract core application based responsibility. 
[IB-quick Find.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6659220/IB-quick.Find.docx)

I have create new responsibilities in different application and it has working fine for 'Install base' application.
 
Thanks 
Razaul

**Comment by TinaGriffin** [comment]
So how would we get the View Only Contracts in with this responsibility once we change it to 'Install base' application?  Is there any option here or are we going to have to split into two responsibilities ...one for Contracts and one for Install Base?

**Comment by Haqueraz** [comment]
Hi Tina,
I don't think there is any option because of Install base is based on web application and contracts is based on Oracle Application. 

Thanks 
Razaul

**Comment by TinaGriffin** [comment]
It was in 12.1.3 also though.

**Comment by TinaGriffin** [comment]
Something curious about this issue.  In the screenshots I showed you before, 12.1.3 Prod was working and had the Quick Find.  I just got word from one of our end users that it is not there in production and I just rechecked and it is not there.  I will attach a new screenshot of 12.1.3 prod and you can compare it to the screenshot I posted earlier in Prod showing it was there.
[Uploading Issue 16 12.1.3 Prod no longer has the Quick Find.docx…]()

**Comment by Haqueraz** [comment]
Hi Tina, 
It is still uploading..
Can you send it to me in email . I will upload it here.

Thanks 
Razaul

**Comment by ashoksnapfj** [comment]
Update from Oracle
-------------------------------
When creating the responsibility, the application tied to the responsibility must be Install Base or the quick find option will not be available.
refer Quick Find Not Visible -- When Login To Custom Responsibility ( Doc ID 1301329.1 )
-------------------------------

**Comment by TinaGriffin** [comment]
We will be creating separate responsibilities to break out the Contracts and Install Base. This can be closed.

**Comment by Haqueraz** [comment]
Thanks you for the confirmation.
