### ISSUE TITLE
Default System Timeouts In Use

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#17]
The default system timeouts are currently set and need to be corrected to:
ICX:Session Timeout is set to 240
JTF_INACTIVE_SESSION_TIMEOUT is set to 720000

**Comment by amitjori** [comment]
Hi Linda,

Session time out parameters are changed both in 12.2.10 INT and STG. Please confirm if we are good to close this issue.

**Comment by lindamrigo** [comment]
Hi Amit
I am getting

***@***.***D75846.5FAC2070]

Will log issue

**Comment by lindamrigo** [comment]
Session timeouts have been corrected
