### ISSUE TITLE
Canadian contract form issue - DEVELOPER ERROR: Cannot find menu item: special11 ***SR 3-26116952241***

### ISSUE THREAD

**Issue by vinaytalasila** [Fujitsu-America/Fujitsu-Repository#18]
**Describe the bug**
From: Griffin, Tina <Tina.Griffin@snapon.com> 
Sent: Wednesday, May 26, 2021 11:05 PM
To: Jori, Amit <Amit.Jori@fujitsu.com>; Muthunarayanan, Somasundaram <Somasundaram.Muthunarayanan@fujitsu.com>; Malvankar, Priyesh <priyesh.malvankar@fujitsu.com>; Arsid, Hanmant <Hanmant.Arsid@fujitsu.com>
Cc: Hamilton, Mark W <Mark.W.Hamilton@snapon.com>; Liu, Sherry X <Sherry.X.Liu@snapon.com>; Rigo, Linda M <Linda.M.Rigo@snapon.com>; Chauhan, Harish <harish.chauhan@fujitsu.com>
Subject: Found first issue 12.2.10 STG

I was just opening some forms in STG.  I opened a Canadian contract because I just so happened to be working with the same contract number in production today, so I was already familiar with the contents of the contract.  As soon as it opened it I got this error. I haven’t seen this error before.

![image](https://user-images.githubusercontent.com/85238919/120777255-9d0fac80-c514-11eb-979d-3a4731b7bbd4.png)
 

**Instance Name**
Instance: STG 12.2.10

**Comment by suhas-deshpande** [comment]
Issue is fixed in INT, by adding Form personalization for this responsibility.

**Comment by amitjori** [comment]
Hi Team,

Patch #32975482 has been applied in STG instance as suggested in SR "SR 3-26116952241 : Issue with Service contract form - OKSAUDET".

![image](https://user-images.githubusercontent.com/85238919/123581846-3bb5c300-d7cc-11eb-9122-c578540301ea.png)

Regards,
Amit

**Comment by suhas-deshpande** [comment]
@amitjori - I have tested this in STG and working as expected.

**Comment by Haqueraz** [comment]
Hi Tina, 

This issue has been fixed after applied the patch in STG Instance. Please check once and provide us your feedback.

Thanks 
Razaul

**Comment by amitjori** [comment]
Hi Team,
As discussed in yesterday's daily call patch #32975482 has been applied in INT instance as suggested in SR "SR 3-26116952241 : Issue with Service contract form - OKSAUDET".

![image](https://user-images.githubusercontent.com/85238919/123740502-155d5980-d898-11eb-84fd-2e7fb31fefd3.png)

Regards,
Amit

**Comment by TinaGriffin** [comment]
I've retested this in STG and INT and it is resolved now.  This can be closed.

**Comment by Haqueraz** [comment]
Thank you for update!

@amitjori please add this patch in your upgrade documents.
