### ISSUE TITLE
12.2.10 Upgrade Error - ADV COLLECTIONS INVOICE DELIVERY FAILED

### ISSUE THREAD

**Issue by vinaytalasila** [Fujitsu-America/Fujitsu-Repository#20]
**Describe the bug**
From: Hamilton, Mark W <Mark.W.Hamilton@snapon.com> 
Sent: Thursday, May 27, 2021 6:27 PM
To: Jori, Amit <Amit.Jori@fujitsu.com>; Muthunarayanan, Somasundaram <Somasundaram.Muthunarayanan@fujitsu.com>
Cc: SBS IS Oracle Apps Developers <SBSISOracleAppsDevelopers@snapon.com>
Subject: 12.2.10 Upgrade Error - ADV COLLECITONS INVOICE DELIVERY FAILED
 
Attempted to deliver invoice via SMTP.
See attached log.
 
IEXXmlDelivery [May-27-2021 08:42:40]: submitting request...
DEBUG: setDebug: JavaMail version 1.5.4
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: useEhlo true, useAuth false
DEBUG SMTP: trying to connect to host "172.22.144.141", port 25, isSSL false
IEXXmlDelivery [May-27-2021 08:42:40]: Failed to complete the delivery to mark.hamilton@snapon.com

**Instance Name**
Instance: STG 12.2.10

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vinaytalasila** [comment]
From: Jori, Amit <Amit.Jori@fujitsu.com> 
Sent: Thursday, May 27, 2021 7:39 PM
To: Hamilton, Mark W <Mark.W.Hamilton@snapon.com>; Muthunarayanan, Somasundaram <Somasundaram.Muthunarayanan@fujitsu.com>; G09D-FAI_IGDC_Cloud_BAU_WM <G09D-FAI_IGDC_Cloud_BAU_WM@fujitsu.com>
Cc: SBS IS Oracle Apps Developers <SBSISOracleAppsDevelopers@snapon.com>; Arsid, Hanmant <Hanmant.Arsid@fujitsu.com>; Malvankar, Priyesh <priyesh.malvankar@fujitsu.com>
Subject: RE: 12.2.10 Upgrade Error - ADV COLLECITONS INVOICE DELIVERY FAILED
 
Looping Unix Team,
 
Hello Unix Team,
 
Can you please check the below issue
 
[root@ssbsashebsap3 ~]# telnet localhost 25
Trying ::1...
telnet: connect to address ::1: Connection refused
 
[root@ssbsashebsap3 ~]#  systemctl status sendmail
● sendmail.service - Sendmail Mail Transport Agent
   Loaded: loaded (/usr/lib/systemd/system/sendmail.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2021-05-27 10:06:59 EDT; 2s ago
  Process: 11153 ExecStart=/usr/sbin/sendmail -bd $SENDMAIL_OPTS $SENDMAIL_OPTARG (code=exited, status=0/SUCCESS)
  Process: 11139 ExecStartPre=/etc/mail/make aliases (code=exited, status=0/SUCCESS)
  Process: 11136 ExecStartPre=/etc/mail/make (code=exited, status=0/SUCCESS)
Main PID: 11156 (sendmail)
    Tasks: 1
   Memory: 2.1M
   CGroup: /system.slice/sendmail.service
           └─11156 sendmail: accepting connections
 
May 27 10:06:54 ssbsashebsap3 systemd[1]: Starting Sendmail Mail Transport Agent...
May 27 10:06:54 ssbsashebsap3 sendmail[11146]: alias database /etc/aliases rebuilt by root
May 27 10:06:54 ssbsashebsap3 sendmail[11146]: /etc/aliases: 77 aliases, longest 10 bytes, 778 bytes total
May 27 10:06:54 ssbsashebsap3 sendmail[11156]: starting daemon (8.14.7): SMTP+queueing@01:00:00
May 27 10:06:54 ssbsashebsap3 sendmail[11156]: NOQUEUE: SYSERR(root): opendaemonsocket: daemon MTA: cannot bind: Address already in use
May 27 10:06:54 ssbsashebsap3 sendmail[11156]: daemon MTA: problem creating SMTP socket
May 27 10:06:54 ssbsashebsap3 systemd[1]: Can't open PID file /run/sendmail.pid (yet?) after start: No such file or directory
May 27 10:06:59 ssbsashebsap3 systemd[1]: Started Sendmail Mail Transport Agent.
 
Regards,
Amit

From: Surve, Mazhar <Mazhar.Surve@fujitsu.com> 
Sent: Thursday, May 27, 2021 8:56 PM
To: Jori, Amit <Amit.Jori@fujitsu.com>; Hamilton, Mark W <Mark.W.Hamilton@snapon.com>; Muthunarayanan, Somasundaram <Somasundaram.Muthunarayanan@fujitsu.com>; G09D-FAI_IGDC_Cloud_BAU_WM <G09D-FAI_IGDC_Cloud_BAU_WM@fujitsu.com>
Cc: SBS IS Oracle Apps Developers <SBSISOracleAppsDevelopers@snapon.com>; Arsid, Hanmant <Hanmant.Arsid@fujitsu.com>; Malvankar, Priyesh <priyesh.malvankar@fujitsu.com>
Subject: RE: 12.2.10 Upgrade Error - ADV COLLECITONS INVOICE DELIVERY FAILED
 
Hi Amit,
 
As per the below mail logs the mails were delivered to Mark also I tested a mail to my account which also got delivered,
--------------------------------------------xxxxxxxxxxxxxxxxxxxxxxxxxxx--------------------------------------------
May 27 09:38:11 ssbsashebsap3 sendmail[29937]: 14RDcAUW029937: from=<aptpqs2i@ssbsashebsap3.oci.snapbs.com>, size=9164, class=0, nrcpts=1, msgid=<20210527133810.GA29934@ssbsashebsap3.snaponvcn01ash.oraclevcn.com>, proto=ESMTP, daemon=MTA, relay=localhost [127.0.0.1]
May 27 09:38:11 ssbsashebsap3 sendmail[29936]: 14RDcAdf029936: to=mark.hamilton@snapon.com, ctladdr=aptpqs2i (101/54322), delay=00:00:01, xdelay=00:00:01, mailer=relay, pri=38991, relay=[127.0.0.1] [127.0.0.1], dsn=2.0.0, stat=Sent (14RDcAUW029937 Message accepted for delivery)
May 27 09:38:14 ssbsashebsap3 sendmail[29939]: 14RDcAUW029937: to=<mark.hamilton@snapon.com>, ctladdr=<aptpqs2i@ssbsashebsap3.oci.snapbs.com> (101/54322), delay=00:00:03, xdelay=00:00:03, mailer=esmtp, pri=129164, relay=mxa-004aa801.gslb.pphosted.com. [148.163.144.23], dsn=2.0.0, stat=Sent (38sp9678uf-1 Message accepted for delivery)
[root@ssbsashebsap3 ~]#
--------------------------------------------xxxxxxxxxxxxxxxxxxxxxxxxxxx--------------------------------------------
Regards,
Mazhar Surve

From: Jori, Amit <Amit.Jori@fujitsu.com> 
Sent: Thursday, May 27, 2021 9:04 PM
To: Surve, Mazhar <Mazhar.Surve@fujitsu.com>; Hamilton, Mark W <Mark.W.Hamilton@snapon.com>; Muthunarayanan, Somasundaram <Somasundaram.Muthunarayanan@fujitsu.com>; G09D-FAI_IGDC_Cloud_BAU_WM <G09D-FAI_IGDC_Cloud_BAU_WM@fujitsu.com>
Cc: SBS IS Oracle Apps Developers <SBSISOracleAppsDevelopers@snapon.com>; Arsid, Hanmant <Hanmant.Arsid@fujitsu.com>; Malvankar, Priyesh <priyesh.malvankar@fujitsu.com>
Subject: RE: 12.2.10 Upgrade Error - ADV COLLECITONS INVOICE DELIVERY FAILED
 
Hello Mazhar,
 
Mark is trying to send the email from a concurrent program which is using SMTP service, I still see the connection refused error .
[root@ssbsashebsap3 ~]# telnet localhost 25
Trying ::1...
telnet: connect to address ::1: Connection refused
 
From existing INT instance.
[root@sbsashiebsap4 opt]# hostname -i
172.22.144.142
[root@sbsashiebsap4 opt]# telnet localhost 25
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220 sbsashiebsap4.oci.snapbs.com ESMTP Postfix
 
[root@sbsashiebsap4 opt]# service postfix status
master (pid  13671) is running...
 
Regards,
Amit

From: Mazhar.Surve@fujitsu.com <Mazhar.Surve@fujitsu.com> 
Sent: Thursday, May 27, 2021 12:12 PM
To: Amit.Jori@fujitsu.com; Hamilton, Mark W <Mark.W.Hamilton@snapon.com>; Somasundaram.Muthunarayanan@fujitsu.com; G09D-FAI_IGDC_Cloud_BAU_WM@fujitsu.com
Cc: SBS IS Oracle Apps Developers <SBSISOracleAppsDevelopers@snapon.com>; Hanmant.Arsid@fujitsu.com; priyesh.malvankar@fujitsu.com
Subject: RE: 12.2.10 Upgrade Error - ADV COLLECITONS INVOICE DELIVERY FAILED
 
CAUTION: This email originated from outside of Snap-on. Do not click on links or open attachments unless you have validated the sender, even if it is a known contact. Contact the sender by phone to validate the contents. 
Hi Amit,
Postfix is configured as per old server configuration & send-mail has been stopped,
Also telnet to port 25 is working please validate now & let us know if issue persist,

[root@ssbsashebsap3 etc]# telnet localhost 25
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220 ssbsashebsap3.oci.snapbs.com ESMTP Postfix
Regards,
Mazhar Surve

From: Hamilton, Mark W <Mark.W.Hamilton@snapon.com> 
Sent: Thursday, May 27, 2021 12:17 PM
To: Mazhar.Surve@fujitsu.com; Amit.Jori@fujitsu.com; Somasundaram.Muthunarayanan@fujitsu.com; G09D-FAI_IGDC_Cloud_BAU_WM@fujitsu.com
Cc: SBS IS Oracle Apps Developers <SBSISOracleAppsDevelopers@snapon.com>; Hanmant.Arsid@fujitsu.com; priyesh.malvankar@fujitsu.com
Subject: RE: 12.2.10 Upgrade Error - ADV COLLECITONS INVOICE DELIVERY FAILED
 
Hi Mazhar
Re-tested… no delivery…
 
IEXXmlDelivery [May-27-2021 12:14:11]: submitting request...
DEBUG: setDebug: JavaMail version 1.5.4
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: useEhlo true, useAuth false
DEBUG SMTP: trying to connect to host "172.22.144.141", port 25, isSSL false
IEXXmlDelivery [May-27-2021 12:14:11]: Failed to complete the delivery to mark.hamilton@snapon.com
IEXXmlDelivery [May-27-2021 12:14:11]: sqlexp:java.lang.NullPointerException
IEXXmlDelivery [May-27-2021 12:14:11]: sqlexp:java.lang.NullPointerException
        at oracle.apps.xdo.delivery.DeliveryUtil.log(Unknown Source)
        at oracle.apps.xdo.delivery.smtp.SMTPDeliveryRequestHandler.submitRequest(Unknown Source)
        at oracle.apps.xdo.delivery.AbstractDeliveryRequest.submit(Unknown Source)
        at oracle.apps.iex.xml.IEXXmlDelivery.delivery(IEXXmlDelivery.java:2568)
        at oracle.apps.iex.xml.IEXXmlDelivery.runProgram(IEXXmlDelivery.java:606)
        at oracle.apps.fnd.cp.request.Run.main(Run.java:159)

From: Hamilton, Mark W <Mark.W.Hamilton@snapon.com> 
Sent: 28 May 2021 00:10
To: Surve, Mazhar <Mazhar.Surve@fujitsu.com>; Jori, Amit <Amit.Jori@fujitsu.com>; Muthunarayanan, Somasundaram <Somasundaram.Muthunarayanan@fujitsu.com>; G09D-FAI_IGDC_Cloud_BAU_WM <G09D-FAI_IGDC_Cloud_BAU_WM@fujitsu.com>
Cc: SBS IS Oracle Apps Developers <SBSISOracleAppsDevelopers@snapon.com>; Arsid, Hanmant <Hanmant.Arsid@fujitsu.com>; Malvankar, Priyesh <priyesh.malvankar@fujitsu.com>; Talasila, Vinay <Vinay.Talasila@fujitsu.com>
Subject: RE: 12.2.10 Upgrade Error - ADV COLLECITONS INVOICE DELIVERY FAILED
 
After a Team’s Mtg with Vinay – we tested this again …
Using Firefox – it failed again – no delivery.
Using Chrome – the Adv Collections Invoice was delivered via email – Successfully.
Using Edge – the Adv Collections Invoice was delivered via email – Successfully.

From: Sneha.Mapari@fujitsu.com <Sneha.Mapari@fujitsu.com> 
Sent: Thursday, May 27, 2021 3:24 PM
To: Hamilton, Mark W <Mark.W.Hamilton@snapon.com>; Amit.Jori@fujitsu.com; Somasundaram.Muthunarayanan@fujitsu.com
Cc: SBS IS Oracle Apps Developers <SBSISOracleAppsDevelopers@snapon.com>; Mazhar.Surve@fujitsu.com; Hanmant.Arsid@fujitsu.com; priyesh.malvankar@fujitsu.com; Vinay.Talasila@fujitsu.com; G09D-FAI_IGDC_Cloud_BAU_WM@fujitsu.com
Subject: RE: 12.2.10 Upgrade Error - ADV COLLECITONS INVOICE DELIVERY FAILED
 
CAUTION: This email originated from outside of Snap-on. Do not click on links or open attachments unless you have validated the sender, even if it is a known contact. Contact the sender by phone to validate the contents. 
Hi Mark/Amit,
We have done required changes on mail configuration. We have checked and tested by sending test mail form our end we are successfully receiving test mails. Could you please check from your end and update.
 
Regards,
Sneha Mapari
Unix, Managed Infrastructure Services (MIS)

From: Hamilton, Mark W <Mark.W.Hamilton@snapon.com> 
Sent: Thursday, May 27, 2021 3:40 PM
To: Sneha.Mapari@fujitsu.com; Amit.Jori@fujitsu.com; Somasundaram.Muthunarayanan@fujitsu.com
Cc: SBS IS Oracle Apps Developers <SBSISOracleAppsDevelopers@snapon.com>; Mazhar.Surve@fujitsu.com; Hanmant.Arsid@fujitsu.com; priyesh.malvankar@fujitsu.com; Vinay.Talasila@fujitsu.com; G09D-FAI_IGDC_Cloud_BAU_WM@fujitsu.com
Subject: RE: 12.2.10 Upgrade Error - ADV COLLECITONS INVOICE DELIVERY FAILED
 
Tested in Firefox.
Job completed but when click on View Output or View Log – blank displays.

![image](https://user-images.githubusercontent.com/84878630/120539478-3de35800-c3ad-11eb-9b30-847a3a9139d0.png)

From: Hamilton, Mark W <Mark.W.Hamilton@snapon.com> 
Sent: Tuesday, June 1, 2021 7:08 AM
To: Jori, Amit <Amit.Jori@fujitsu.com>; Surve, Mazhar <Mazhar.Surve@fujitsu.com>; Mapari, Sneha <Sneha.Mapari@fujitsu.com>; Muthunarayanan, Somasundaram <Somasundaram.Muthunarayanan@fujitsu.com>
Cc: SBS IS Oracle Apps Developers <SBSISOracleAppsDevelopers@snapon.com>; Arsid, Hanmant <Hanmant.Arsid@fujitsu.com>; Malvankar, Priyesh <priyesh.malvankar@fujitsu.com>; Talasila, Vinay <Vinay.Talasila@fujitsu.com>; G09D-FAI_IGDC_Cloud_BAU_WM <G09D-FAI_IGDC_Cloud_BAU_WM@fujitsu.com>
Subject: RE: 12.2.10 Upgrade Error - ADV COLLECITONS INVOICE DELIVERY FAILED

Amit
Tested with Firefox, Chrome, and Edge – All 3 FAILED Delivery….

![image](https://user-images.githubusercontent.com/84878630/120539718-7b47e580-c3ad-11eb-99d9-ccae8a4226b7.png)

Tested with Firefox… UNSuccessful… Email was not delivered.
IEXXmlDelivery [Jun-01-2021 07:56:45]: submitting request...
DEBUG: setDebug: JavaMail version 1.5.4
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: useEhlo true, useAuth false
DEBUG SMTP: trying to connect to host "172.22.144.141", port 25, isSSL false
IEXXmlDelivery [Jun-01-2021 07:56:45]: Failed to complete the delivery to mark.hamilton@snapon.com
IEXXmlDelivery [Jun-01-2021 07:56:45]: sqlexp:java.lang.NullPointerException
IEXXmlDelivery [Jun-01-2021 07:56:45]: sqlexp:java.lang.NullPointerException
        at oracle.apps.xdo.delivery.DeliveryUtil.log(Unknown Source)
        at oracle.apps.xdo.delivery.smtp.SMTPDeliveryRequestHandler.submitRequest(Unknown Source)
        at oracle.apps.xdo.delivery.AbstractDeliveryRequest.submit(Unknown Source)
        at oracle.apps.iex.xml.IEXXmlDelivery.delivery(IEXXmlDelivery.java:2568)
        at oracle.apps.iex.xml.IEXXmlDelivery.runProgram(IEXXmlDelivery.java:606)
        at oracle.apps.fnd.cp.request.Run.main(Run.java:159)

Tested with Edge …… UNSuccessful… Email was not delivered.
IEXXmlDelivery [Jun-01-2021 08:02:46]: submitting request...
DEBUG: setDebug: JavaMail version 1.5.4
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: useEhlo true, useAuth false
DEBUG SMTP: trying to connect to host "172.22.144.141", port 25, isSSL false
IEXXmlDelivery [Jun-01-2021 08:02:46]: Failed to complete the delivery to mark.hamilton@snapon.com
IEXXmlDelivery [Jun-01-2021 08:02:46]: sqlexp:java.lang.NullPointerException
IEXXmlDelivery [Jun-01-2021 08:02:46]: sqlexp:java.lang.NullPointerException
        at oracle.apps.xdo.delivery.DeliveryUtil.log(Unknown Source)
        at oracle.apps.xdo.delivery.smtp.SMTPDeliveryRequestHandler.submitRequest(Unknown Source)
        at oracle.apps.xdo.delivery.AbstractDeliveryRequest.submit(Unknown Source)
        at oracle.apps.iex.xml.IEXXmlDelivery.delivery(IEXXmlDelivery.java:2568)
        at oracle.apps.iex.xml.IEXXmlDelivery.runProgram(IEXXmlDelivery.java:606)
        at oracle.apps.fnd.cp.request.Run.main(Run.java:159)

Tested with Chrome… UNSuccessful… Email was not delivered.

IEXXmlDelivery [Jun-01-2021 08:06:16]: submitting request...
DEBUG: setDebug: JavaMail version 1.5.4
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: useEhlo true, useAuth false
DEBUG SMTP: trying to connect to host "172.22.144.141", port 25, isSSL false
IEXXmlDelivery [Jun-01-2021 08:06:16]: Failed to complete the delivery to mark.hamilton@snapon.com
IEXXmlDelivery [Jun-01-2021 08:06:16]: sqlexp:java.lang.NullPointerException
IEXXmlDelivery [Jun-01-2021 08:06:16]: sqlexp:java.lang.NullPointerException
        at oracle.apps.xdo.delivery.DeliveryUtil.log(Unknown Source)
        at oracle.apps.xdo.delivery.smtp.SMTPDeliveryRequestHandler.submitRequest(Unknown Source)
        at oracle.apps.xdo.delivery.AbstractDeliveryRequest.submit(Unknown Source)
        at oracle.apps.iex.xml.IEXXmlDelivery.delivery(IEXXmlDelivery.java:2568)
        at oracle.apps.iex.xml.IEXXmlDelivery.runProgram(IEXXmlDelivery.java:606)
        at oracle.apps.fnd.cp.request.Run.main(Run.java:159)

Thanks
Mark

**Comment by amitjori** [comment]
Hello Mark,

Can you please test this issue one more time and confirm?

Regards,
Amit

**Comment by hamiltonmark** [comment]
Using Firefox – Failed
IEXXmlDelivery [Jun-04-2021 08:57:21]: submitting request...
DEBUG: setDebug: JavaMail version 1.5.4
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: useEhlo true, useAuth false
DEBUG SMTP: trying to connect to host "172.22.144.141", port 25, isSSL false
IEXXmlDelivery [Jun-04-2021 08:57:21]: Failed to complete the delivery to mark.hamilton@snapon.com
IEXXmlDelivery [Jun-04-2021 08:57:21]: sqlexp:java.lang.NullPointerException
IEXXmlDelivery [Jun-04-2021 08:57:21]: sqlexp:java.lang.NullPointerException
	at oracle.apps.xdo.delivery.DeliveryUtil.log(Unknown Source)
	at oracle.apps.xdo.delivery.smtp.SMTPDeliveryRequestHandler.submitRequest(Unknown Source)
	at oracle.apps.xdo.delivery.AbstractDeliveryRequest.submit(Unknown Source)
	at oracle.apps.iex.xml.IEXXmlDelivery.delivery(IEXXmlDelivery.java:2568)
	at oracle.apps.iex.xml.IEXXmlDelivery.runProgram(IEXXmlDelivery.java:606)
	at oracle.apps.fnd.cp.request.Run.main(Run.java:159)


Using Chrome – Failed
IEXXmlDelivery [Jun-04-2021 09:00:52]: submitting request...
DEBUG: setDebug: JavaMail version 1.5.4
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: useEhlo true, useAuth false
DEBUG SMTP: trying to connect to host "172.22.144.141", port 25, isSSL false
IEXXmlDelivery [Jun-04-2021 09:00:53]: Failed to complete the delivery to mark.hamilton@snapon.com
IEXXmlDelivery [Jun-04-2021 09:00:53]: sqlexp:java.lang.NullPointerException
IEXXmlDelivery [Jun-04-2021 09:00:53]: sqlexp:java.lang.NullPointerException
	at oracle.apps.xdo.delivery.DeliveryUtil.log(Unknown Source)
	at oracle.apps.xdo.delivery.smtp.SMTPDeliveryRequestHandler.submitRequest(Unknown Source)
	at oracle.apps.xdo.delivery.AbstractDeliveryRequest.submit(Unknown Source)
	at oracle.apps.iex.xml.IEXXmlDelivery.delivery(IEXXmlDelivery.java:2568)
	at oracle.apps.iex.xml.IEXXmlDelivery.runProgram(IEXXmlDelivery.java:606)
	at oracle.apps.fnd.cp.request.Run.main(Run.java:159)

Using Edge – Failed
IEXXmlDelivery [Jun-04-2021 09:02:52]: submitting request...
DEBUG: setDebug: JavaMail version 1.5.4
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: useEhlo true, useAuth false
DEBUG SMTP: trying to connect to host "172.22.144.141", port 25, isSSL false
IEXXmlDelivery [Jun-04-2021 09:02:52]: Failed to complete the delivery to mark.hamilton@snapon.com
IEXXmlDelivery [Jun-04-2021 09:02:52]: sqlexp:java.lang.NullPointerException
IEXXmlDelivery [Jun-04-2021 09:02:52]: sqlexp:java.lang.NullPointerException
	at oracle.apps.xdo.delivery.DeliveryUtil.log(Unknown Source)
	at oracle.apps.xdo.delivery.smtp.SMTPDeliveryRequestHandler.submitRequest(Unknown Source)
	at oracle.apps.xdo.delivery.AbstractDeliveryRequest.submit(Unknown Source)
	at oracle.apps.iex.xml.IEXXmlDelivery.delivery(IEXXmlDelivery.java:2568)
	at oracle.apps.iex.xml.IEXXmlDelivery.runProgram(IEXXmlDelivery.java:606)
	at oracle.apps.fnd.cp.request.Run.main(Run.java:159)

**Comment by hamiltonmark** [comment]
Amit – Good News!

Adv Collections Invoice Delivery now working successfully using:
1.  Firefox
2.  Chrome
3.  Edge

Can you please post the fix in the ticket?

Thanks
Mark

![image](https://user-images.githubusercontent.com/85197361/121052265-35fa2e00-c788-11eb-81be-76445f3cae1e.png)

**Comment by hamiltonmark** [comment]
Per email from Amit...
simple fix ,we had to change few parameters in file /etc/postfix/main.cf (postfix file configuration).

This ticket can be closed.

**Comment by amitjori** [comment]
changed inet_interfaces parameters in file /etc/postfix/main.cf (postfix file configuration) to all , also uncommented it as it was hashed out

**Comment by hamiltonmark** [comment]
Reopening issue for INT 12.2.10.
Both end user - dotson2 and hamiltonm - getting same error.

eMail:  mark.hamilton@snapon.com


IEXXmlDelivery [Jul-15-2021 11:31:21]: submitting request...
DEBUG: setDebug: JavaMail version 1.5.4
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: useEhlo true, useAuth false
DEBUG SMTP: trying to connect to host "172.22.144.170", port 25, isSSL false
IEXXmlDelivery [Jul-15-2021 11:31:21]: Failed to complete the delivery to mark.hamilton@snapon.com
IEXXmlDelivery [Jul-15-2021 11:31:21]: sqlexp:java.lang.NullPointerException
IEXXmlDelivery [Jul-15-2021 11:31:21]: sqlexp:java.lang.NullPointerException
        at oracle.apps.xdo.delivery.DeliveryUtil.log(Unknown Source)
        at oracle.apps.xdo.delivery.smtp.SMTPDeliveryRequestHandler.submitRequest(Unknown Source)
        at oracle.apps.xdo.delivery.AbstractDeliveryRequest.submit(Unknown Source)
        at oracle.apps.iex.xml.IEXXmlDelivery.delivery(IEXXmlDelivery.java:2568)
        at oracle.apps.iex.xml.IEXXmlDelivery.runProgram(IEXXmlDelivery.java:606)
        at oracle.apps.fnd.cp.request.Run.main(Run.java:159)

IEXXmlDelivery [Jul-15-2021 11:31:21]: Inside catch e : Setting failFlag to true
IEXXmlDelivery [Jul-15-2021 11:31:21]: updateStatus: sTempStatus=OTHER PROCESSING FAILURE
IEXXmlDelivery [Jul-15-2021 11:31:21]:Failure Reason: Failed to submit delivery request. Check the corresponding profile values and config file
IEXXmlDelivery [Jul-15-2021 11:31:21]: updateStatus: invoiceCopyExists =false
IEXXmlDelivery [Jul-15-2021 11:31:21]: updateStatus: updating staus column TempStatus=OTHER PROCESSING FAILURE
IEXXmlDelivery [Jul-15-2021 11:31:21]: Setting failFlag to true
IEXXmlDelivery [Jul-15-2021 11:31:21]: Before calling writeOutputPDF 
IEXXmlDelivery [Jul-15-2021 11:31:21]:writeOutputPDF: Begin 
IEXXmlDelivery [Jul-15-2021 11:31:21]:writeOutputPDF: vector size 1
IEXXmlDelivery [Jul-15-2021 11:31:21]:blDomain2 size 4387
IEXXmlDelivery [Jul-15-2021 11:31:21]:writeOutputPDF: array lenght 1
IEXXmlDelivery [Jul-15-2021 11:31:21]: Output file name /dpqs2i/applcsf/out/o35435880.out
IEXXmlDelivery [Jul-15-2021 11:31:21]:writeOutputPDF: End 
IEXXmlDelivery [Jul-15-2021 11:31:21]:after calling writeOutputPDF 
CP main completed runProgram for oracle.apps.iex.xml.IEXXmlDelivery

**Comment by vinaytalasila** [comment]
**@amitjori:** Could you please check whether inet_interfaces parameters in file /etc/postfix/main.cf (postfix file configuration) is to all , also whether it is uncommented if it was hashed out in INT 12.2.10?

Thanks
Vinay

**Comment by amitjori** [comment]
Hello Mark,

Postfix services were down, I have now started postfix services can you please re-try and confirm?

[root@isbsashebsap4 ~]# systemctl status postfix
● postfix.service - Postfix Mail Transport Agent
   Loaded: loaded (/usr/lib/systemd/system/postfix.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2021-07-16 01:27:33 EDT; 16s ago

Regards,
Amit

**Comment by hamiltonmark** [comment]
Thanks Amit
This is working now.
Ticket can be closed.

250 2.0.0 Ok: queued as 8782EC001375
DEBUG SMTP: message successfully delivered to mail server
QUIT
221 2.0.0 Bye
IEXXmlDelivery [Jul-16-2021 08:45:08]: submitted request successfully...
IEXXmlDelivery [Jul-16-2021 08:45:08]: return status :0
IEXXmlDelivery [Jul-16-2021 08:45:08]: return Status msg :Message has been successfully sent to all addresses.
IEXXmlDelivery [Jul-16-2021 08:45:08]: end sending email
IEXXmlDelivery [Jul-16-2021 08:45:08]: IN sendSignalToWorkFlow 
IEXXmlDelivery [Jul-16-2021 08:45:08]:In sendSignalToWorkFlow method Query to fetch Object_type and status  :  select object_type,status  from iex_xml_request_histories  where xml_request_id = :1 
IEXXmlDelivery [Jul-16-2021 08:45:08]: IN sendSignalToWorkFlow l_object_type : IEX_INVOICES
IEXXmlDelivery [Jul-16-2021 08:45:08]: updateStatus: sTempStatus=SUCCESSFUL
IEXXmlDelivery [Jul-16-2021 08:45:08]:Failure Reason is set to null 
IEXXmlDelivery [Jul-16-2021 08:45:08]: updateStatus: invoiceCopyExists =false
IEXXmlDelivery [Jul-16-2021 08:45:08]: updateStatus: updating staus column TempStatus=SUCCESSFUL
IEXXmlDelivery [Jul-16-2021 08:45:08]: delivery done
IEXXmlDelivery [Jul-16-2021 08:45:08]: Before calling writeOutputPDF 
IEXXmlDelivery [Jul-16-2021 08:45:08]:writeOutputPDF: Begin 
IEXXmlDelivery [Jul-16-2021 08:45:08]:writeOutputPDF: vector size 1
IEXXmlDelivery [Jul-16-2021 08:45:08]:blDomain2 size 4389
IEXXmlDelivery [Jul-16-2021 08:45:08]:writeOutputPDF: array lenght 1
IEXXmlDelivery [Jul-16-2021 08:45:08]: Output file name /dpqs2i/applcsf/out/o35437196.out
IEXXmlDelivery [Jul-16-2021 08:45:08]:writeOutputPDF: End 
IEXXmlDelivery [Jul-16-2021 08:45:08]:after calling writeOutputPDF 
CP main completed runProgram for oracle.apps.iex.xml.IEXXmlDelivery
