### ISSUE TITLE
12.2.10 Upgrade - SBS CPQ File Extract Interface Price List - is failing - cannot find table qp_list_headers_all_b

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#24]
**Describe the bug**
SBS CPQ File Extract Interface Price List - is failing

**Instance Name**
Instance: tpqs2i

**Responsibility Name**
Responsibility:  PBS TROUBLESHOOTER

**Navigation**
Navigation:  Submit Job - SBS CPQ File Extract Interface Price List

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
select *
from  qp_list_headers_all_b

Returns - no table found... but...

select *
from  apps.qp_list_headers_all_b

Returns successfully.

PACKAGE PBS.sbs_cpq_prclst_pkg is in error because of this issue.

**Comment by vinaytalasila** [comment]
Mark,

We will look into this and keep you posted.

Thanks
Vinay Talasila

**Comment by suhas-deshpande** [comment]
Hi Mark,

This has been fixed in STG. Kindly check and let us know if any issues.

Thanks,
Suhas.

**Comment by hamiltonmark** [comment]
Thank you Suhas.
SBS CPQ File Extract Interface Price List working successfully.
Below is the log ....


+---------------------------------------------------------------------------+
Business Online: Version : 12.2

Copyright (c) 1998, 2013, Oracle and/or its affiliates. All rights reserved.

SBS_CPQ_PRICELST_INF_CONC_SH: SBS CPQ File Extract Interface Price List
+---------------------------------------------------------------------------+

Current system time is 04-JUN-2021 12:34:43

+---------------------------------------------------------------------------+

1. OOD: PINGING SBS SERVER to check if host is alive. 
1. RESULT: PING SBS INTERNAL - SUCCESSFUL. 
2. OOD: EXEC CONCSUB JOB TO GENERATE CPQ EXTRACT FILE.
Param1 APPS/apps123
Param2 1320
Param3 HAMILTONM
Param4 35389601
Param5 AUTO DIRECT US ALL-INCLUSIVE
Param6
Param7
Param5 AUTO DIRECT US ALL-INCLUSIVE
parm5_pricelist1 AUTO DIRECT US ALL-INCLUSIVE
parm5_pricelist2 AUTO DIRECT US ALL-INCLUSIVE
SOURCE1:   SBS_US_PriceList.csv
DESTIN1:   SBS_US_PriceList.csv
2. RESULT: CPQ EXTRACT (1) DATA AND (2) XML FILEs GENERATED.
3. OOD: Copy file /tpqs2i/applcsf/tmp/SBS_US_PriceList.csv TO oci-ssh-dev.snaponbusinesssolutions.com:cpq_pricelst_intf/outbound/SBS_US_PriceList.csv
3. RESULT: CPQ EXTRACT DATA FILE GENERATED - /tpqs2i/applcsf/tmp/SBS_US_PriceList.csv 
4a. OOD: Copy file /tpqs2i/applcsf/tmp/upload_list.xml TO oci-ssh-dev.snaponbusinesssolutions.com:cpq_pricelst_intf/outbound/upload_list.xml
4a. RESULT: CPQ EXTRACT XML FILE GENERATED - /tpqs2i/applcsf/tmp/upload_list.xml 
4b. OOD: Copy file /tpqs2i/applcsf/tmp/data_table_deploy.xml TO oci-ssh-dev.snaponbusinesssolutions.com:cpq_pricelst_intf/outbound/data_table_deploy.xml
4b. RESULT: CPQ EXTRACT XML FILE GENERATED - /tpqs2i/applcsf/tmp/data_table_deploy.xml 
4c. OOD: Copy file /tpqs2i/applcsf/tmp/data_table_delete.xml TO oci-ssh-dev.snaponbusinesssolutions.com:cpq_pricelst_intf/outbound/data_table_delete.xml
4c. RESULT: CPQ EXTRACT XML FILE GENERATED - /tpqs2i/applcsf/tmp/data_table_delete.xml 
5. RESULT: CPQ EXTRACT DATA AND XML FILEs copied to oci-ssh-dev.snaponbusinesssolutions.com -- SUCCESSFUL.
6. OOD: Execute Remote Script on SBS INTERNAL DB SERVER.
 
-rwxrwxrwx. 1 sbsintf sbsintf 317496 Jun  4 12:35 /home/sbsintf/cpq_pricelst_intf/outbound/SBS_US_PriceList.csv
-rwxrwxrwx. 1 sbsintf sbsintf 312 Jun  4 12:35 /home/sbsintf/cpq_pricelst_intf/outbound/upload_list.xml
-rwxrwxrwx. 1 sbsintf sbsintf 183 Jun  4 12:35 /home/sbsintf/cpq_pricelst_intf/outbound/data_table_deploy.xml
-rwxrwxrwx. 1 sbsintf sbsintf 187 Jun  4 12:35 /home/sbsintf/cpq_pricelst_intf/outbound/data_table_delete.xml
 
7. REMOTE: Prep File (chmod, zip and cp) /home/sbsintf/cpq_pricelst_intf/outbound/SBS_US_PriceList.zip upload_list.xml data_table_deploy.xml
  adding: SBS_US_PriceList.csv (deflated 93%)
  adding: data_table_deploy.xml (deflated 31%)
  adding: data_table_delete.xml (deflated 31%)
total 356
-rwxrwxrwx. 1 sbsintf sbsintf    321 Jun  4 12:35 data_table_delete.zip
-rwxrwxrwx. 1 sbsintf sbsintf    319 Jun  4 12:35 data_table_deploy.zip
-rwxrwxrwx. 1 sbsintf sbsintf  22494 Jun  4 12:35 SBS_US_PriceList.zip
-rwxrwxrwx. 1 sbsintf sbsintf    187 Jun  4 12:35 data_table_delete.xml
-rwxrwxrwx. 1 sbsintf sbsintf    183 Jun  4 12:35 data_table_deploy.xml
-rwxrwxrwx. 1 sbsintf sbsintf    312 Jun  4 12:35 upload_list.xml
-rwxrwxrwx. 1 sbsintf sbsintf 317496 Jun  4 12:35 SBS_US_PriceList.csv
7. RESULT: Prep File (chmod, zip and cp) /home/sbsintf/cpq_pricelst_intf/outbound/SBS_US_PriceList.csv - /home/sbsintf/cpq_pricelst_intf/outbound/SBS_US_PriceList.zip - SUCCESSFUL.
 
### TEST ### TEST ### TEST SERVER ###
### TEST ### TEST ### TEST SERVER ###
### TEST ### TEST ### TEST SERVER ###
### TEST ### TEST ### TEST SERVER ###
 
sftp_user:    sbsitest1
sftp_host:    sftp2.bigmachines.com
sftp_folder:  /home/sbsitest1/upload_zip/automated/
 
8. REMOTE: Copying file /home/sbsintf/cpq_pricelst_intf/outbound/SBS_US_PriceList.zip upload_list.xml data_table_deploy.zip data_table_delete.zip TO sbsitest1@sftp2.bigmachines.com
 
Connecting to sftp2.bigmachines.com...
sftp> version
SFTP protocol version 3
sftp> cd /home/sbsitest1/upload_zip/automated/
sftp> pwd
Remote working directory: /upload_zip/automated
sftp> ls -ltr
-rwxr-xr-x    1 1431     10002       21918 Jun  4 12:00 SBS_US_PriceList.zip
sftp> lcd /home/sbsintf/cpq_pricelst_intf/outbound
sftp> lpwd
Local working directory: /home/sbsintf/cpq_pricelst_intf/outbound
sftp> lls
data_table_delete.xml
data_table_delete.zip
data_table_deploy.xml
data_table_deploy.zip
SBS_US_PriceList.csv
SBS_US_PriceList.zip
upload_list.xml
sftp> put SBS_US_PriceList.zip
Uploading SBS_US_PriceList.zip to /upload_zip/automated/SBS_US_PriceList.zip
sftp> put upload_list.xml
Uploading upload_list.xml to /upload_zip/automated/upload_list.xml
sftp> put data_table_deploy.zip
Uploading data_table_deploy.zip to /upload_zip/automated/data_table_deploy.zip
sftp> put data_table_delete.zip
Uploading data_table_delete.zip to /upload_zip/automated/data_table_delete.zip
sftp> pwd
Remote working directory: /upload_zip/automated
sftp> ls -ltr
-rwxr-xr-x    1 1431     10002         321 Jun  4 16:36 data_table_delete.zip
-rwxr-xr-x    1 1431     10002       22494 Jun  4 16:36 SBS_US_PriceList.zip
-rwxr-xr-x    1 1431     10002         319 Jun  4 16:36 data_table_deploy.zip
-rwxr-xr-x    1 1431     10002         312 Jun  4 16:36 upload_list.xml
sftp> quit
8. RESULT: TEST Copying file /home/sbsintf/cpq_pricelst_intf/outbound/SBS_US_PriceList.zip upload_list.xml data_table_deploy.zip data_table_delete.zip TO sbsitest1@sftp2.bigmachines.com - SUCCESSFUL
9. REMOTE: Archiving /home/sbsintf/cpq_pricelst_intf/outbound/SBS_US_PriceList.csv TO /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/SBS_US_PriceList_20210604PM123554.csv
 
### TEST ### ARCHIVING ###
### TEST ### ARCHIVING ###
### TEST ### ARCHIVING ###
### TEST ### ARCHIVING ###
 
/home/sbsintf/cpq_pricelst_intf/outbound
 
SBS_US_PriceList_20210604PM123554.csv
SBS_US_PriceList_20210604PM123554.zip
upload_list_20210604PM123551.xml
data_table_deploy_20210604PM123551.xml
data_table_deploy_20210604PM123551.zip
data_table_delete_20210604PM123551.xml
data_table_delete_20210604PM123551.zip
 
9a1. REMOTE: Archiving /home/sbsintf/cpq_pricelst_intf/outbound/SBS_US_PriceList.csv TO /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/SBS_US_PriceList_20210604PM123554.csv
9a2. REMOTE: Archiving /home/sbsintf/cpq_pricelst_intf/outbound/SBS_US_PriceList.zip TO /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/SBS_US_PriceList_20210604PM123554.zip
9a3. REMOTE: Archiving /home/sbsintf/cpq_pricelst_intf/outbound/upload_list.xml TO /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/upload_list_20210604PM123551.xml
9a4. REMOTE: Archiving /home/sbsintf/cpq_pricelst_intf/outbound/data_table_deploy.xml TO /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_deploy_20210604PM123551.xml
9a5. REMOTE: Archiving /home/sbsintf/cpq_pricelst_intf/outbound/data_table_deploy.zip TO /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_deploy_20210604PM123551.zip
9a6. REMOTE: Archiving /home/sbsintf/cpq_pricelst_intf/outbound/data_table_delete.xml TO /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_delete_20210604PM123551.xml
9a7. REMOTE: Archiving /home/sbsintf/cpq_pricelst_intf/outbound/data_table_delete.zip TO /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_delete_20210604PM123551.zip
 
/home/sbsintf/cpq_pricelst_intf/outbound
 
### TEST ### HOUSEKEEPING ###
### TEST ### HOUSEKEEPING ###
### TEST ### HOUSEKEEPING ###
### TEST ### HOUSEKEEPING ###
 
9b. REMOTE: Cleanup Files - Remove /home/sbsintf/cpq_pricelst_intf/outbound/SBS_US_PriceList.csv  upload_list.xml data_table_deploy.xml data_table_deploy.zip SBS_US_PriceList.zip
9c. REMOTE: Cleanup +14 Days Old Archive Files - Remove /oodxfer/cpq_pricelst_intf/outbound/archive/SBS_*_PriceList_*
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer  22494 Jun  4 12:36 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/SBS_US_PriceList_20210604PM123554.zip
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 317496 Jun  4 12:36 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/SBS_US_PriceList_20210604PM123554.csv
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer  21918 Jun  4 08:00 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/SBS_US_PriceList_20210604AM080026.zip
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 312178 Jun  4 08:00 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/SBS_US_PriceList_20210604AM080026.csv
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer  21918 Jun  4 07:54 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/SBS_US_PriceList_20210604AM075429.zip
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 312178 Jun  4 07:54 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/SBS_US_PriceList_20210604AM075429.csv
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer  18856 May 20 08:31 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/SBS_CN_PriceList_20210520AM083127.zip
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 259749 May 20 08:31 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/SBS_CN_PriceList_20210520AM083127.csv
9d. REMOTE: Cleanup +14 Days Old Archive Files - Remove /oodxfer/cpq_pricelst_intf/outbound/archive/upload_list* 
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 312 Jun  4 12:36 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/upload_list_20210604PM123551.xml
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 127 Jun  4 08:00 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/upload_list_20210604AM080023.xml
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 127 Jun  4 07:54 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/upload_list_20210604AM075425.xml
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 312 May 20 08:31 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/upload_list_20210520AM083124.xml
9e. REMOTE: Cleanup +14 Days Old Archive Files - Remove /oodxfer/cpq_pricelst_intf/outbound/archive/data_table_deploy* 
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 319 Jun  4 12:36 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_deploy_20210604PM123551.zip
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 183 Jun  4 12:36 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_deploy_20210604PM123551.xml
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 323 Jun  4 08:00 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_deploy_20210604AM080023.zip
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 182 Jun  4 08:00 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_deploy_20210604AM080023.xml
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 323 Jun  4 07:54 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_deploy_20210604AM075425.zip
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 182 Jun  4 07:54 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_deploy_20210604AM075425.xml
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 320 May 20 08:31 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_deploy_20210520AM083124.zip
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 183 May 20 08:31 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_deploy_20210520AM083124.xml
9f. REMOTE: Cleanup +14 Days Old Archive Files - Remove /oodxfer/cpq_pricelst_intf/outbound/archive/data_table_delete* 
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 321 Jun  4 12:36 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_delete_20210604PM123551.zip
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 187 Jun  4 12:36 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_delete_20210604PM123551.xml
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 324 Jun  4 08:00 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_delete_20210604AM080023.zip
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 186 Jun  4 08:00 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_delete_20210604AM080023.xml
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 324 Jun  4 07:54 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_delete_20210604AM075425.zip
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 186 Jun  4 07:54 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_delete_20210604AM075425.xml
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 321 May 20 08:31 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_delete_20210520AM083124.zip
-rwxrwxr-x. 1 sbsintf ent_ood_dev_xfer 187 May 20 08:31 /oodxfer/cpq_pricelst_intf/outbound/archive/TPQS2I/data_table_delete_20210520AM083124.xml
10. REMOTE: Remote Archiving and Housecleaning - Completed.
11. REMOTE: Remote Job Completed.
12. REMOTE: Returning to calling Shell Script on OOD Server.
Null message body; hope that's ok
Null message body; hope that's ok
13. RESULT: Remote Script Complete.  Returned from Calling Script.
::::::::::::::
/tmp/SBS_CPQ_PRICELST_INF_CONC_SH.prog.29212
::::::::::::::
Submitted request 35389602 for CONCURRENT PBS SBS_CPQ_LOAD_PRCLST ORG_ID=83 "AUTO DIRECT US ALL-INCLUSIVE" 

Normal completion
14. OOD: Performing Housekeeping - Copy /tmp/SBS_CPQ_PRICELST_INF_CONC_SH.prog.29212 Log to /oodxfer/cpq_pricelst_intf/logs/20210604PM123545.TPQS2I.
14. RESULT: /tmp/SBS_CPQ_PRICELST_INF_CONC_SH.prog.29212 Copied to oci-ssh-dev.snaponbusinesssolutions.com - /oodxfer/cpq_pricelst_intf/logs/20210604PM123545.TPQS2I - SUCCESSFUL.
15. OOD: Performing Housekeeping - Remove Temporary Log File - /tmp/SBS_CPQ_PRICELST_INF_CONC_SH.prog.29212 
15. OOD: Returning to Main Controlling Script



+---------------------------------------------------------------------------+
No completion options were requested.

Output file size: 



Output is not being printed because:
The print option has been disabled for this report.

+---------------------------------------------------------------------------+
Concurrent request completed successfully
Current system time is 04-JUN-2021 12:36:12

+---------------------------------------------------------------------------+

**Comment by hamiltonmark** [comment]
SBS CPQ File Extract Interface Price List working successfully.
This ticket can be closed.

**Comment by vinaytalasila** [comment]
Mark, Thank you for your confirmation.
