### ISSUE TITLE
Sales User Search Error

### ISSUE THREAD

**Issue by SherryXLiu** [Fujitsu-America/Fujitsu-Repository#25]
**Describe the bug**
Sales User > Search > Error

![image](https://user-images.githubusercontent.com/85246030/120803048-21603080-c511-11eb-8230-867107352719.png)

**Instance Name**
Instance: TPQS21

**Responsibility Name**
Responsibility:
![image](https://user-images.githubusercontent.com/85246030/120803048-21603080-c511-11eb-8230-867107352719.png)
**Navigation**
Navigation:
above
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vinaytalasila** [comment]
Sherry,

We will look into this and keep you posted.

Thanks
Vinay Talasila

**Comment by suhas-deshpande** [comment]
Hi Sherry,

Can you please check now? Please logout and login again into applications.

Thanks,
Suhas

**Comment by vinaytalasila** [comment]
Resource Name was changed and now it is working.
