### ISSUE TITLE
STG Service Request / Task / Task Template is not opening.

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#26]
**Describe the bug**
When creating a Service Request, you can click on the Task tab and create tasks using already pre-filled out templates for tasks you enter repetitively.  This task template button is not opening for me in Firefox.  I did notice that the field on the task tab, Corporate Time Zone now looks like a required field.  I don't believe it was in 12.1.3 and/or we had a default to default it in.

**Instance Name**
Instance: TPQS2I

**Responsibility Name**
Responsibility: PBS Automotive Customer Support

**Navigation**
Navigation: PBS Automotive Customer Support / Service Requests / Find Service Requests 

**To Reproduce**
Search for Request Number 2350802.   Click on the Tasks Tab.  Click Use Template button at the bottom of the page.

**Expected behavior**
Task Template Screen pop should open and allow you to select a task template that will prepopulate the task fields.

**Screenshots**
Screenshots attached.
[STG Issue Task Template showing 12-1-3 DPQS2I working and 12-2-10 TPQS2I not working.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6598706/STG.Issue.Task.Template.showing.12-1-3.DPQS2I.working.and.12-2-10.TPQS2I.not.working.docx)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vinaytalasila** [comment]
Tina,

We will look into this and keep you posted.

Thanks
Vinay Talasila

**Comment by vinaytalasila** [comment]
[Chrome.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6601064/Chrome.docx)

Tina, 

In the Chrome browser, I have reproduced this issue in STG 12.2.10 and I am able to click on 'Use Template' and I got the pop-up successfully. Attached 'Chrome.docx' for the screenshot. 

I am facing frmservlet issue using Firefox so I am unable to test it in that browser.

I am thinking that the issue might have resolved after bouncing STG today morning. So, could you please retest this issue one more time in the Firefox and let me know the results. If you are still facing the same issue then I will continue working in Firefox browser on Monday. 

Thanks
Vinay Talasila

**Comment by TinaGriffin** [comment]
Hi Vinay, I normally use Firefox for Oracle.  I just retested...it doesn't open in Firefox.

**Comment by vinaytalasila** [comment]
Tina,

Thank you for your quick test. We will work on this on Monday using Firefox browser and keep you posted.

Thanks
Vinay Talasila

**Comment by ashoksnapfj** [comment]
Hi Tina,

I have reproduced this issue in STG 12.2.10 and I am able to click on 'Use Template' and I got the pop-up successfully using Firefox. Please check once.

Thanks
Ashok.T

**Comment by ashoksnapfj** [comment]
Hi Tina,

After entering the mandatory fields in Tasks tab, it is popup the template window as attached the file (2350802_STG.docx).

Thanks ,
Ashok.T

**Comment by ashoksnapfj** [comment]
[2350802_STG.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6609291/2350802_STG.docx)

**Comment by ashoksnapfj** [comment]
Hi Tina,

This has been fixed in STG and INT. Kindly check and let us know if any issues.

Thanks,
Ashok.

**Comment by ashoksnapfj** [comment]
[TASK_ISSUE_FIXED.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6663206/TASK_ISSUE_FIXED.docx)

**Comment by TinaGriffin** [comment]
I have retested this in INT and it its working.  This can be closed.
