### ISSUE TITLE
Unable to create or update an employee manually ***SR 3-26011488991***

### ISSUE THREAD

**Issue by vinaytalasila** [Fujitsu-America/Fujitsu-Repository#27]
**Describe the bug**
Unable to create or update an employee manually.

**Instance Name**
Instance: STG 12.2.10 and INT 12.2.10

**Responsibility Name**
Responsibility: PBS US Purchasing Super User

**Navigation**
Navigation: Setup->Personnel->Employees

**Expected behavior**
Users should able to create or update an employee

**Screenshots**
[Employee creation issue.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6600886/Employee.creation.issue.docx)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by vinaytalasila** [comment]
Mark,

This issue has been fixed in INT 12.2.10. Please find attached 'Employee creation issue.docx' file for the details and the test results. Could you please test this issue in STG 12.2.10 and confirm the results so that I can close this issue.

Thanks
Vinay Talasila

**Comment by hamiltonmark** [comment]
Vinay
In 12.2 STG - Tested:
1.  Creating New Employee - Successful
2. Maintain Existing Employee - Successful

See screenshots below.
Thanks
Mark

[Screenshots Entering and Maintain Employees in HR Foundation.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6600958/Screenshots.Entering.and.Maintain.Employees.in.HR.Foundation.docx)

**Comment by hamiltonmark** [comment]
Vinay
This ticket can be closed.
Thanks
Mark

**Comment by vinaytalasila** [comment]
Mark, Thank you for testing this so quickly. I am closing this ticket now.
