### ISSUE TITLE
Sales Dashboard is not loading

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#29]
Sales Dashboard is a standard HTML form
as
![Sales Dashboard Error](https://user-images.githubusercontent.com/85238444/121031370-46a2a800-c778-11eb-8dc5-9ba0bdd22b92.JPG)
 Sales User
sales user>customers>simple search>enter 00926>Go>Click on Guaranty Chevrolet>
Should be
![Sales Dashboard in INT 12 1 3](https://user-images.githubusercontent.com/85238444/121031407-4efae300-c778-11eb-81ca-7ff9c4c51d31.JPG)

**Comment by vinaytalasila** [comment]
Linda,

We will look into this and keep you posted.

@Haqueraz @suhas-deshpande : Could you please check whether you are also getting the same issue in STG 12.2.10 instance. If yes, then we will work with Amit (and DBA team).

Thanks
Vinay Talasila

**Comment by suhas-deshpande** [comment]
@amitjori - We are having same error in STG also. Could you please check this as well? Let me know when can we discuss this on call.

**Comment by Haqueraz** [comment]
I verified this issue and it is working as expected. 
I am able to get the new page  clicking on Top right button. 
[Pagescreen.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6624444/Pagescreen.docx)

**Comment by lindamrigo** [comment]
What is the navigation you are using?  I am still getting the error.

**Comment by lindamrigo** [comment]
Also, can we load a new standard form of this without the buttons?

**Comment by Haqueraz** [comment]
Resp : Sales User
sales user>customers>simple search>enter 00926>Go>Click on Guaranty Chevrolet>
Yes. I am able to load the standard form also.

**Comment by lindamrigo** [comment]
Sales Dashboard form without the buttons is the form I am referring to as your screenshot has both the personalization button and the hard-coded button.

**Comment by Haqueraz** [comment]
I choose the action list and click on GO button. It is also working. 
Please find the last screen.
[Sales User-Pagescreen.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6625365/Sales.User-Pagescreen.docx)

**Comment by lindamrigo** [comment]
This is working in Stage
