### ISSUE TITLE
STG Configurator Concurrent Program error

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#30]
**Describe the bug**
The first step to use when working with the Oracle Configurator is to run the concurrent program to load new BOM items into the configurator.  This program is erroring with $SRS$ error.

**Instance Name**
Instance: TPQSTI

**Responsibility Name**
Responsibility: Oracle Configurator Administrator

**Navigation**
Navigation: Oracle Configurator Administrator / Concurrent Programs / Schedule

**To Reproduce**
1. Program Name "Refresh a Single Configuration Model"
2. Errors right away without displaying any of the option parameters available to select.3
3. . See error

**Expected behavior**
Program should allow you to either validate or modify the options and submit the program.

**Screenshots**
[STG Issue Configurator - Refresh a Single Configuration Model concurrent program error.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6609746/STG.Issue.Configurator.-.Refresh.a.Single.Configuration.Model.concurrent.program.error.docx)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vinaytalasila** [comment]
Tina,

We will look into this and keep you posted.

Thanks
Vinay Talasila

**Comment by TinaGriffin** [comment]
Did you all fix this?  I was just testing something else in the Configurator and thought I'd try this again while I was in there and it worked and the program completed successfully without error.

**Comment by vinaytalasila** [comment]
Tina,

I did not work on this yet from my end. DBA team might have worked on some other issue and this might have fixed. 

As this is working now can we close this issue?

Thanks
Vinay Talasila

**Comment by TinaGriffin** [comment]
Yes, but can you check first to see if anyone changed anything that might have addressed it, otherwise, if it happens in another instance we won't know what the fix is.  Once you check with them...we can close it.

**Comment by vinaytalasila** [comment]
Tina,

There is no technical fix for this issue. DBA's has done OAF configurations and it has fixed this issue.
