### ISSUE TITLE
SOA Undeploy/Deploy Failed

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#31]
Attempted to undeploy/deploy existing deployed SOA package and it failed.
![SOA Undeploy Deploy Error](https://user-images.githubusercontent.com/85238444/121034552-17416a80-c77b-11eb-929a-55369bc30b8e.JPG)

**Comment by SomuSundaramM** [comment]
Hi Linda,

Please select all the check boxes under service operations(for eg . Return Snapshot information) while deploying, it will work.

Thanks,
Somu

**Comment by lindamrigo** [comment]
It is working
