### ISSUE TITLE
Create a new contact, Address should be not required

### ISSUE THREAD

**Issue by SherryXLiu** [Fujitsu-America/Fujitsu-Repository#32]
**Describe the bug**
When create a contact, his/she address is be not required

**Instance Name**
Instance:
TPQS2I
**Responsibility Name**
Responsibility:
Trading Community Manager (or PBS US/CA Customer Maintenance) 
**Navigation**
Navigation:
Trading Community Manager > Customer > Standard>Account Details > Communication>create contact
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/85246030/121039549-2cb89380-c77f-11eb-9862-c820c26f0505.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vinaytalasila** [comment]
Sherry,

It look like 'Address Line 1' is a mandatory field now in 12.2.10. Anyway, we will look into this and keep you posted.

@Haqueraz @suhas-deshpande: Could you please look into this.

Thanks
Vinay Talasila

**Comment by SherryXLiu** [comment]
Yes. I see “*”. But in current version ( also has “*”), it allow the address fields blank. SBS User don’t put a contact address.

**Comment by suhas-deshpande** [comment]
Hi Sherry,

Can you please check now. Address line 1 was mandatory in Address DFFF, which is now made optional.

![Capture](https://user-images.githubusercontent.com/85028593/121365360-1c8fe800-c928-11eb-83e6-2163ec628260.JPG)

Thanks,
Suhas

**Comment by SherryXLiu** [comment]
Yes. This is fixed. You may close it. thanks
