### ISSUE TITLE
STG When Manually trying to create a task in a Service Request an error occurs *** SR 3-26150947721

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#33]
**Describe the bug**
After entering or re-opening a service request, you should be able to manually add a task or use the task template.  I already have an open issue for the task template, however, I tried manually creating a task and it does not work either.  It threw an error.

**Instance Name**
Instance: TPQS2I

**Responsibility Name**
Responsibility: PBS Automotive Customer Support

**Navigation**
Navigation: PBS Automotive Customer Support / Service Request/ Find Service Requests

**To Reproduce**
1. Find Request Number 2350802
2. Click on Task Tab
3. Enter all mandatory fields.

**Expected behavior**
Should be able to enter all the mandatory fields and Save without error.
[STG 12-2-10 Issue in Service Request Task when Manually creating a Task.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6611700/STG.12-2-10.Issue.in.Service.Request.Task.when.Manually.creating.a.Task.docx)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TinaGriffin** [comment]
In comparing this to 12.1.3 INT (using SR 2332368) I also noticed that it appears some default profiles are not set in 12.2.10 that are set in 12.1.3  In particular, in 12.1.3 the Corporate Time Zone and Eastern Time Zone default in as well as the Planned Start and End Date default in.  Also in 12.1.3 Buttons at the bottom for Debrief, Skills, Access Hours and Workflow are greyed out.  I remember that we purposely greyed them our as they were unneeded for our users.  I don't recall if that was done in the menu options or how that was done.

**Comment by vinaytalasila** [comment]
@ashoksnapfj : Could you please look into this and update the ticket.

Thanks
Vinay Talasila

**Comment by vinaytalasila** [comment]
**@TinaGriffin:** I have reviewed the profile option values and other setups of that responsibility, profile options at your user level between INT 12.1.3 and STG 12.2.10. I did not see any difference. So, need to investigate more regrading the issues that you reported in this ticket.

**@ashoksnapfj :** Apart from my above comment, when I tried to pull existing request number in INT 12.1.3 and STG 12.2.10, shown in the below document I see that task details are not pulling up in STG 12.2.10 instance. So, could you please investigate regarding this from your end as well during your shift hours and update the status. If needed, please create the SR with Oracle support.

[Existing request numbers.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6619950/Existing.request.numbers.docx)

Thanks
Vinay Talasila

**Comment by vinaytalasila** [comment]
**@ashoksnapfj :** Did we get any update from Oracle Support regarding the SR SR 3-26150947721. If no, then could you please follow-up with them?

Thanks
Vinay Talasila

**Comment by ashoksnapfj** [comment]
Hi Vinay,

I sent follow-up mail and oracle team replied that they still working on this.

Thanks
Ashok.t

**Comment by ashoksnapfj** [comment]
Hi Tina,

This has been fixed in STG and INT. Kindly check and let us know if any issues.

Thanks,
Ashok.

**Comment by ashoksnapfj** [comment]
[TASK_ISSUE_FIXED_V1.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6663217/TASK_ISSUE_FIXED_V1.docx)

**Comment by TinaGriffin** [comment]
I have retested this in INT and it has been resolved.  This can be closed.
