### ISSUE TITLE
Service Contracts Submit for Approval is greyed out

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#34]
**Describe the bug**
In order to progress a Service Contract, you have to Submit it for Approval.  This Action is greyed out.

**Instance Name**
Instance: TPQS2I

**Responsibility Name**
Responsibility: PBS US Contract Administrator and PBS CAN Contract Administrator and PBS US Contracts Admin and PBS CAN Contracts Admin

**Navigation**
Navigation: PBS US Contract Administrator / Launch Contracts 

**To Reproduce**
1. Select the Flashlight (under the Edit in the Toolbar) 
2. Click in the Contract Number field and enter SVC255156 and hit Search
3. When the result returns in blue, right click on the contract and select Open
4. Click on Actions in the Tool Bar and see Submit for Approval is greyed out.

**Expected behavior**
Submit for Approval should be available to select...you can activate the Contract without it.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[STG 12-2-10 Issue in Service Contracts where Submit for Approval is greyed out.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6619343/STG.12-2-10.Issue.in.Service.Contracts.where.Submit.for.Approval.is.greyed.out.docx)

**Comment by TinaGriffin** [comment]
I found this document that seems to be the fix for our issue.  
 What to do When the 'Submit For Approval' Button is Disabled in Service Contracts (Doc ID 2241849.1)

Also, the reason why I think this is the fix...is that I tested this in the seeded Responsibility "Service Contracts Manager" and the Submit for Approval is available there.  It is only not available in our custom responsibilities.

**Comment by vinaytalasila** [comment]
Tina,

I have reviewed the Doc ID 2241849.1 and the existing menu, submenu details related to the 'PBS US Contract Administrator', 'PBS CAN Contract Administrator', 'PBS US Contracts Admin' and 'PBS CAN Contracts Admin' responsibilities.

I added OKS_CONTRACTS_ADMIN_R12 submenu to the PBS_CONTRACTS_MAIN_MENU ('PBS US Contract Administrator', 'PBS CAN Contract Administrator' responsibilities has this menu) and PBS_CONTRACTS_ADMIN_MM ('PBS US Contracts Admin' and 'PBS CAN Contracts Admin' responsibilities has this menu) custom menu's. Now I can see the 'Submit for Approval' in the 'Actions' menu in all the 4 responsibilities in STG 12.2.10. Attached screenshot below from two of the responsibilities.

![image](https://user-images.githubusercontent.com/84878630/121271047-74771200-c888-11eb-96d5-d18b950aa9d7.png)
![image](https://user-images.githubusercontent.com/84878630/121272421-90c87e00-c88b-11eb-804f-d714b941beb6.png)

Could you please test now from your end in STG 12.2.10 and if it works then I will do the same setup in INT 12.2.10 instance.

Thanks
Vinay Talasila

**Comment by TinaGriffin** [comment]
I've retested this and it is working now.  This ticket can be closed.

**Comment by vinaytalasila** [comment]
Tina,

Thank you for testing this. 

I will move the setups to INT 12.2.10 instance and make a note of this setups in our repository. Then I will close this ticket.

Thanks
Vinay Talasila

**Comment by vinaytalasila** [comment]
Just an update.....I added OKS_CONTRACTS_ADMIN_R12 submenu to the PBS_CONTRACTS_MAIN_MENU ('PBS US Contract Administrator', 'PBS CAN Contract Administrator' responsibilities has this menu) and PBS_CONTRACTS_ADMIN_MM ('PBS US Contracts Admin' and 'PBS CAN Contracts Admin' responsibilities has this menu) custom menu's in INT 12.2.10 instance. I am closing this issue now.

Thanks
Vinay Talasila
