### ISSUE TITLE
INT 12_2_10 REQUEST SET ERROR SBS Workflow BG Process OEOL 1st OEOH 2nd

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#35]
**Describe the bug**

**Instance Name**
Instance:  DPQS2I

**Responsibility Name**
Responsibility:   Applications Administrator

**Navigation**
Navigation:  Submit Request Set

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
[INT 12_2_10 REQUEST SET ERROR SBS Workflow BG Process OEOL 1st OEOH 2nd.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6624830/INT.12_2_10.REQUEST.SET.ERROR.SBS.Workflow.BG.Process.OEOL.1st.OEOH.2nd.docx)

**Comment by vinaytalasila** [comment]
Mark,

Did this worked well in STG 12.2.10 instance? 

We will look into this and keep you posted. 

Thanks
Vinay Talasila

**Comment by hamiltonmark** [comment]
Vinay
This request set did NOT have an issue in STG.
As you can see below in STG – it is accessible and runs successfully.
It seems to have a Language (NLS) issue in INT.

![image](https://user-images.githubusercontent.com/85197361/121393369-4512e480-c91e-11eb-9f25-87c6998a2d32.png)

**Comment by vinaytalasila** [comment]
**@amitjori @SomuSundaramM** : Could you please review Mark's comments in this ticket and check whether you applied any language related setups or patches in STG 12.2.10 but did not apply them in INT 12.2.10?

Thanks
Vinay Talasila

**Comment by amitjori** [comment]
Hi Mark,

We are checking this issue will keep you updated.

Regards,
Amit

**Comment by SomuSundaramM** [comment]
Hi Mark,

Please check the program once and let us know if the issue still exists.

Thanks,
Somu

**Comment by hamiltonmark** [comment]
Thanks Somu.

Request Set - SBS Workflow BG Process OEOL 1st OEOH 2nd - ran successfully in INT.

![image](https://user-images.githubusercontent.com/85197361/121520517-fec29180-c9c0-11eb-9513-1d73ebf82402.png)

**Comment by hamiltonmark** [comment]
Request Set - SBS Workflow BG Process OEOL 1st OEOH 2nd - has been scheduled to run every 10 mins in INT.

This ticket can be closed.

**Comment by vinaytalasila** [comment]
**@SomuSundaramM :** Could you please let us know what was the fix that you applied to resolve the issue?

Thanks
Vinay Talasila

**Comment by SomuSundaramM** [comment]
We have corrected the NLS environment variable and bounced the DB fixed the issue

Thanks,
Somu

**Comment by vinaytalasila** [comment]
Thank you for your update Somu.
