### ISSUE TITLE
INT 12.2.10 REQUEST SET ERROR PBS Advanced Collections Assign Collector Populate UWQ Process

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#36]
**Describe the bug**

**Instance Name**
Instance:  dpqs2i

**Responsibility Name**
Responsibility:  SBS Collections Administrator

**Navigation**
Navigation:  Submit Request Set > PBS Advanced Collections Assign Collector Populate UWQ Process

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
[INT 12_2_10 REQUEST SET ERROR PBS Advanced Collections Assign Collector Populate UWQ Process.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6625872/INT.12_2_10.REQUEST.SET.ERROR.PBS.Advanced.Collections.Assign.Collector.Populate.UWQ.Process.docx)

**Comment by hamiltonmark** [comment]
Looks like similar issue with Language.
This Request Set ran successfully in STG.
Issue only exists in INT.

**Comment by vinaytalasila** [comment]
**@amitjori @SomuSundaramM** : Could you please review Mark's comments in this ticket and check whether you applied any language related setups or patches in STG 12.2.10 but did not apply them in INT 12.2.10?

Thanks
Vinay Talasila

**Comment by amitjori** [comment]
Hi Mark,

We are checking this issue will keep you updated.

Regards,
Amit

**Comment by SomuSundaramM** [comment]
Hi Mark,

Please check the program once and let us know if the issue still exists.

Thanks,
Somu

**Comment by hamiltonmark** [comment]
Thanks Somu

Submitted Request Set - PBS Advanced Collections Assign Collector Populate UWQ Process (Report Set) - in INT.
Job ran successfully.
Job has been scheduled to run in INT each morning at 6am.

![image](https://user-images.githubusercontent.com/85197361/121524023-ddfc3b00-c9c4-11eb-8ebb-a3fb5d79ce14.png)

**Comment by hamiltonmark** [comment]
This ticket can be closed.

**Comment by vinaytalasila** [comment]
**@SomuSundaramM :** Could you please let us know what was the fix that you applied to resolve the issue?

Thanks
Vinay Talasila

**Comment by SomuSundaramM** [comment]
We have corrected the NLS environment variable and bounced the DB fixed the issue

Thanks,
Somu

**Comment by vinaytalasila** [comment]
Thank you for your update Somu.
