### ISSUE TITLE
INT 12.2.10 CPQ DEV to EBS INT Test Connection Failed SR 3-26158238911

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#37]
**Describe the bug**
The test connection is not working in INT.  I believe CPQ will need to whitelist the url.

**Instance Name**
Instance: DPQS2I

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**
Test Connection should return results.
[INT 12.2.10 Test Connection from CPQ DEV to EBS INT failed.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6626392/INT.12.2.10.Test.Connection.from.CPQ.DEV.to.EBS.INT.failed.docx)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TinaGriffin** [comment]
I have opened Sev 1 CPQ SR 3-26158238911 to see if they need to whitelist the new INT url.

**Comment by vinaytalasila** [comment]
**@amitjori @SomuSundaramM** : Could you please look into this?

Thanks
Vinay Talasila

**Comment by TinaGriffin** [comment]
CPQ SR 3-26158238911....they whitelisted the url to resolve the issue.  This can be closed.
