### ISSUE TITLE
Sales Manager > Customer in INT customer name get error

### ISSUE THREAD

**Issue by SherryXLiu** [Fujitsu-America/Fujitsu-Repository#38]
**Describe the bug**
Sales Manager > Customer in INT , There is customer name link , when click the link get an error

**Instance Name**
Instance:
dpqs2i
**Responsibility Name**
Responsibility:
Sales Manager  
**Navigation**
Navigation:
Sales Manager > Customer
**To Reproduce**

**Expected behavior**
![image](https://user-images.githubusercontent.com/85246030/121421667-6682c900-c93c-11eb-8e0e-9f7814449763.png)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vinaytalasila** [comment]
Sherry,

We will look into this and keep you posted.

**@suhas-deshpande** : Could you please check what technical / functional setups are missing related to this issue in INT 12.2.10 vs STG 12.2.10 and apply them in INT 12.2.10. If there are any configurations that need to be done by DBA team then please add Amit and Somu to this ticket.

Thanks
Vinay Talasila

**Comment by suhas-deshpande** [comment]
Hi Sherry,

I am able to open update customers page after clicking on customer name link in INT instance. Please see below screenshot. Kindly test again and if you are still getting same error, please provide the screenshot.

Thanks,
Suhas

![image](https://user-images.githubusercontent.com/85028593/121509237-f58fef80-c9d5-11eb-8bcc-bc7d9f3ad2a9.png)

**Comment by SherryXLiu** [comment]
@suhas-deshpande : It seems ok. I can open the page too with the link. But this morning I saw the error once again like below location, but I cannot consistently reproduce it. I will try it again later. Thanks 
![image](https://user-images.githubusercontent.com/85246030/121524216-156ae780-c9c5-11eb-92a1-b89d59f28c68.png)

**Comment by suhas-deshpande** [comment]
@SherryXLiu :- Sure Sherry. Please let us know if you face any issues.

**Comment by SherryXLiu** [comment]
It seems ok
