### ISSUE TITLE
INT 12.2.10 Opening Concurrent Program Page from Configurator Errors

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#41]
**Describe the bug**
I was trying to retest the issue in TPQS2I that I got trying to run the configurator program but then it worked in TPQS2I and in DPQS2I the page won't open.

**Instance Name**
Instance: DPQS2I

**Responsibility Name**
Responsibility: Oracle Configurator Administrator

**Navigation**
Navigation: Oracle Configurator Administrator / Concurrent Programs / Schedule

**To Reproduce**
1. Go to Oracle Configurator Administrator / Concurrent Programs / Schedule
2
[INT 12.2.10 Schedule Concurrent Program for Configurator.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6626738/INT.12.2.10.Schedule.Concurrent.Program.for.Configurator.docx)
. See error

**Expected behavior**
Page should open.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vinaytalasila** [comment]
Tina,

We will look into this and keep you posted.

**@ashoksnapfj :** #30 is the related ticket number. Could you please check what setup missing in INT 12.2.10 regarding this issue. If needed, please add Amit and Somu to this ticket.

Thanks
Vinay Talasila

**Comment by ashoksnapfj** [comment]
Hi Tina,

This is working in INT instance. Please check once and provide us your feedback.
Attached tested screen shot also.
[INT.12.2.10.Schedule.Concurrent.Program.for.Configurator_Working.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6630758/INT.12.2.10.Schedule.Concurrent.Program.for.Configurator_Working.docx)


Thanks,
Ashok.T

**Comment by TinaGriffin** [comment]
This issue is resolved and can be closed.  I'm certain it was the NLS fix that resolved this one.

**Comment by vinaytalasila** [comment]
Thank you for your update Tina.
