### ISSUE TITLE
Please turn off updating customer or contact information function in Sales Modules

### ISSUE THREAD

**Issue by SherryXLiu** [Fujitsu-America/Fujitsu-Repository#42]
**Describe the bug**
Please turn off updating customer or contact information function in Sales Modules
**Instance Name**
Instance:
DPQS2I
**Responsibility Name**
Responsibility: all the Sales Responsibilities
![image](https://user-images.githubusercontent.com/85246030/121541418-46ebaf00-c9d5-11eb-9120-0e0d990a653b.png)

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/85246030/121541272-26bbf000-c9d5-11eb-8dc1-6b0925c93ed6.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SherryXLiu** [comment]
Attached screenshot is only one example. Please check all customer links in Sales module

**Comment by Haqueraz** [comment]
Hi Sherry, 

I have Turn-off the update and remove icon from the business relationships table rows for below responsibilities in STG instance. 
Please test and confirm then I will do the same in INT . 

Responsibilities  :
 Sales Manager 
 Sales User 

[ref-document.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6633297/ref-document.docx)

Thanks
Razaul

**Comment by SherryXLiu** [comment]
Checked STG. There are duplicated Sales Manager responsibility, the marked one is Error out
![image](https://user-images.githubusercontent.com/85246030/121579879-2550ee80-c9fa-11eb-8799-de9c17a3ef52.png)

**Comment by SherryXLiu** [comment]
The second one Sales Manager is OK. Can you also make these fields display only?

![image](https://user-images.githubusercontent.com/85246030/121580339-a01a0980-c9fa-11eb-93a3-96e69aa31190.png)

**Comment by SherryXLiu** [comment]
Please disable "Create Customer" 
![image](https://user-images.githubusercontent.com/85246030/121580589-e66f6880-c9fa-11eb-9a98-02a2d6d1f276.png)

**Comment by SherryXLiu** [comment]
in page Opportunity > Customer link go to update page
![image](https://user-images.githubusercontent.com/85246030/121582210-bcb74100-c9fc-11eb-93ad-ca876f5f0788.png)

**Comment by Haqueraz** [comment]
Hi Sheery, 
Thanks for the quick response. 

Yes. There are duplicate sales Manager Responsibility. 
I am getting the same error message in both instance STG 12.2.10 and 12.1.3 in the same application responsibility. 
Are you able to open the same in 12.1.3.
![image](https://user-images.githubusercontent.com/84917836/121587531-8973b280-c9fa-11eb-8d62-6b8ced54bcc4.png)

you have requested for others display filed. We will discuss more on daily status call. 

Thanks 
Razaul

**Comment by SherryXLiu** [comment]
For Customer short cut, if you could turn off 'Save" button, we may ok
![image](https://user-images.githubusercontent.com/85246030/121697274-e3c45000-ca9a-11eb-8740-6f5c01f2c5d4.png)

**Comment by SherryXLiu** [comment]
For other short cut than Customer.( e.g. Lead, Opportunity....) if you could disable the link under customer name, it might work for us

**Comment by Haqueraz** [comment]
Hi Sherry, 

I made the changes in Customer short cut to turn-off the 'save' button. 
For others short cut ( e.g. Lead, Opportunity....) .we can't  disable the link under the customer but this is redirecting to the same page were turned-off the save button. 

Thanks 
Razaul

**Comment by SherryXLiu** [comment]
I checked The Customer short cut. It may work, I will let users to test it next week

For Other short cut, if you cannot disable the URL or show a message other than error message. Then I have no idea, maybe you have to tab by tab to eliminate edit or save button

**Comment by SherryXLiu** [comment]
Or the link go to Inquiry Page (below) instead of Update Page could work too
![image](https://user-images.githubusercontent.com/85246030/121732725-922ebc00-cac0-11eb-9dc0-1229f388e08e.png)

**Comment by Haqueraz** [comment]
Hi Sherry, 

We made the below changes in customer pages now it looks exactly same at 12.1.3 page. 
Please verify all the shot cut and let us know if you have any queries. 

-> Hide the 'save' button on the Top right.
-> changed the context  value to 'Read only' 
-> Hide the update/remove Icon from all tabs. 

Thanks 
Razaul

**Comment by SherryXLiu** [comment]
@Haqueraz
Sales Manager> Customer
Yes It is much closer, But please look at 
![image](https://user-images.githubusercontent.com/85246030/121941023-c56d8700-cd1c-11eb-81dc-c7829e258988.png)
![image](https://user-images.githubusercontent.com/85246030/121941154-eb932700-cd1c-11eb-9428-3cb8081a74ab.png)
![image](https://user-images.githubusercontent.com/85246030/121941242-05cd0500-cd1d-11eb-8807-1d976135da63.png)
![image](https://user-images.githubusercontent.com/85246030/121941334-2301d380-cd1d-11eb-86f6-59a8d28c1ae2.png)
![image](https://user-images.githubusercontent.com/85246030/121941427-4298fc00-cd1d-11eb-8d1a-b3fe2e91f428.png)
![image](https://user-images.githubusercontent.com/85246030/121941479-56446280-cd1d-11eb-8334-4938c519d80a.png)

**Comment by SherryXLiu** [comment]
Suggestion:
For  Page **Sales Manager > Customer** 
Go to Customer Ver only page like 
![image](https://user-images.githubusercontent.com/85246030/121942864-f51d8e80-cd1e-11eb-8a3e-6e2dd9acad4f.png)

**Comment by Haqueraz** [comment]
Thank you for quick testing. 
We will fix these one and let you know for another round testing.

**Comment by Haqueraz** [comment]
This has been fixed now. Please test once again and let us know if you have any queries.

**Comment by SherryXLiu** [comment]
Haqueraz,
The listed locations you have done looks ok, but I can still find others, rather than list them I would wait for you to see if there is other way. As we have discussed in today's meeting, Please contact Oracle to see if there is a way to link  Sales modules to Customer view only pages.
Thanks

**Comment by Haqueraz** [comment]
Hi Sherry, 
We are working on that way ,I will keep you updated.

Thanks 
Razaul

**Comment by SherryXLiu** [comment]
Linda will check if Navigation Responsibility has been changed during upgrade
![image](https://user-images.githubusercontent.com/85246030/122230240-742dd680-ce87-11eb-8ade-5ad52890799c.png)

**Comment by SherryXLiu** [comment]
Linda has checked the Sales Manager and Sales User menu, it has been changed. It seems we don't have other options on Menu.
Linda will report the issue on the navigation options

**Comment by Haqueraz** [comment]
Can you please share the screenshot with us so we can look further into this.

**Comment by SherryXLiu** [comment]
I have sent some screenshot through email

![image](https://user-images.githubusercontent.com/85246030/122568021-4f686900-d017-11eb-824e-a334e8d2437b.png)
![image](https://user-images.githubusercontent.com/85246030/122568087-66a75680-d017-11eb-9d45-c913ca8f9c31.png)

**Comment by SherryXLiu** [comment]
![image](https://user-images.githubusercontent.com/85246030/122568318-a0785d00-d017-11eb-9cf2-8684a21f6a09.png)

**Comment by SherryXLiu** [comment]
12.1.3
![image](https://user-images.githubusercontent.com/85246030/122568419-b84fe100-d017-11eb-9dcb-e2a72638e4d0.png)

**Comment by SherryXLiu** [comment]
![image](https://user-images.githubusercontent.com/85246030/122568632-f3eaab00-d017-11eb-8c1f-baceb12ffb3d.png)

**Comment by SherryXLiu** [comment]
![image](https://user-images.githubusercontent.com/85246030/122568897-3a400a00-d018-11eb-8b97-41bc20ef35fe.png)

**Comment by SherryXLiu** [comment]
![image](https://user-images.githubusercontent.com/85246030/122569054-5a6fc900-d018-11eb-8c5f-99e58589db30.png)

**Comment by SherryXLiu** [comment]
Just add a note here, in case we may go with the personalization.
Still see "Create Customer"
Sales Manager> Opportunity >Create Opportunity >Select Customer

![image](https://user-images.githubusercontent.com/85246030/123279647-0a8c7880-d4d6-11eb-8ba4-f975bb5eb0e1.png)

![image](https://user-images.githubusercontent.com/85246030/123279593-fcd6f300-d4d5-11eb-924a-1077c446ca19.png)

![image](https://user-images.githubusercontent.com/85246030/123279338-bed9cf00-d4d5-11eb-932e-d3492ca1043a.png)

**Comment by AkshayK247** [comment]
Hi Sherry,

Please review the attached document for possible solutions.
we will discuss the same on Monday.
and all the personalization has done in STAGE Instance.


[Possible Solutions.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6717163/Possible.Solutions.docx)

Thanks,
Akshay

**Comment by SherryXLiu** [comment]
Thanks it looks very good. 
After verifying Sales Representatives' responsibility, I see they are using "Sales User" which 12.2.10 has same functions as 12.1.3 version.
In order not interrupting Upgrade, we like to cancel this plan for now and hold this solution for future to use.  If users request something else, I will let you know, 
Thanks
