### ISSUE TITLE
INT Duplicating HTML Quotes throws Error

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#43]
**Describe the bug**
When trying to duplicate a quote it will not allow it, it throws a relationship error.

**Instance Name**
Instance: DPQS2I

**Responsibility Name**
Responsibility: PBS US Contract Administrator

**Navigation**
Navigation: HTML Quote Administration / Quotes / Dashboard
[INT 12.2.10 Duplicate HTML Quote Error.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6633390/INT.12.2.10.Duplicate.HTML.Quote.Error.docx)

**To Reproduce**
1. Go to Quote Number 198150
2 .hit the Duplicate icon
3. See error

**Expected behavior**
Quote should duplicate successfully.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Haqueraz** [comment]
Hi Tinna,

We will look into this and keep you posted.

This issue comes for all quote# or it comes on particular Quote #198150? 

@suhas-deshpande : Could you please check this issue.

Thanks 
Razaul

**Comment by TinaGriffin** [comment]
I tried multiple quotes.  In addition, there are two ways to duplicate a quote...the way I listed and also, to open the quote and in the drop down on the far right top select Duplicate Quote.  I tried both methods and both threw the same error.  (This is working in TPQS2I 12.2.10)

**Comment by suhas-deshpande** [comment]
Hi Tina,  I was able to create duplicate quote in INT by selecting  Drop down from top right corner. PFA the quote number 198151 (for same customer) and 198152 (for different customer).

![image](https://user-images.githubusercontent.com/85028593/121659899-47964b00-ca92-11eb-8a9e-d95e98be3d64.png)
![image](https://user-images.githubusercontent.com/85028593/121661018-4d406080-ca93-11eb-8e80-5316004d187d.png)

**Comment by suhas-deshpande** [comment]
@TinaGriffin  - Are you changing any default values on the page when you try to submit ?

Thanks,
Suhas

**Comment by TinaGriffin** [comment]
No I'm not changing any defaults.

**Comment by Haqueraz** [comment]
Hi Tinna,

I am also  able to create duplicate quote in STG by selecting both option :
1.Drop down icon from top right corner 
2.Clicking the Duplicate Icon. 

For some cases I got the same error you reported but this is happening if existing quote have data issue in quote line. 

Thanks 
Razaul

**Comment by TinaGriffin** [comment]
Are you checking on the Copy lines?  You should be able to copy the header and the lines.  If I just copy the header it works, but selecting the lines it errors.

**Comment by Haqueraz** [comment]
Yes Tina . I am checking the line including all check list.  
![image](https://user-images.githubusercontent.com/84917836/121726571-568bf600-cab0-11eb-9312-0ed1feed9dd3.png)
![image](https://user-images.githubusercontent.com/84917836/121726583-5f7cc780-cab0-11eb-95b4-eeedf6a51d06.png)

**Comment by TinaGriffin** [comment]
Maybe we can have a conference call then so I can show you what I get.

**Comment by TinaGriffin** [comment]
I was able to confirm your findings that it would only let you duplicate the quote header and lines if there are no unconfigured (red x) icons on the lines.  In fact, I was able to replicate the same in 12.1.3 INT.  You can close this issue now.

**Comment by Haqueraz** [comment]
Thank you for update.
