### ISSUE TITLE
INT 12.2.10 Administrator Workflow - Status Monitor - Returns no data

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#44]
**Describe the bug**

**Instance Name**
Instance:  DPQS2I

**Responsibility Name**
Responsibility:      Workflow Administrator Web (New)

**Navigation**
Navigation:    Administrator Workflow > Status Monitor

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
In INT 12.2.10 - no matter what parameter is entered - it returns no rows.
Below Parameters Entered...  OEOH ... should return some data.

![image](https://user-images.githubusercontent.com/85197361/121578984-4533e280-c9f9-11eb-8d34-0e75e9ebc5ae.png)

**Comment by hamiltonmark** [comment]
Tested the same for issue in STG 12.2.10 - no rows display there as well.
Unsure if there is an issue or possibly Workflow Data is too old and has been purged.

DPQS2I Instance is not yet available to us via TOAD.  Waiting on SBS Tech to add to LDAP/OID.

**Comment by hamiltonmark** [comment]
TPQS2I 12.2.10 - The following query returns no rows.
Commented the end_date is null line - same results.

SELECT item_type,
         item_key,
         TO_CHAR (begin_date, 'DD-MON-RR HH24:MI:SS') begin_date,
         TO_CHAR (end_date, 'DD-MON-RR HH24:MI:SS') end_date,
         root_activity activity
    FROM apps.wf_items
   WHERE item_type = '&item_type' AND end_date IS NULL
ORDER BY TO_DATE (begin_date, 'DD-MON-YYYY hh24:mi:ss') DESC

**Comment by Haqueraz** [comment]
Hi Mark,

We will look into this and share the updates.

Thanks 
Razaul

**Comment by SomuSundaramM** [comment]
Hi Mark,

We've changed the permission to view the workflow as same as existing 12.1.3 instance, Please check and confirm are you able to see now

![image](https://user-images.githubusercontent.com/85238833/121661036-516c7e00-ca93-11eb-9dbb-2a40c758f594.png)

Thanks,
Somu

**Comment by hamiltonmark** [comment]
Thanks Somu
I am able to successfully query Workflow Records now in both INT and STG 12.2.10.

![image](https://user-images.githubusercontent.com/85197361/121668304-2c6b1180-ca79-11eb-9460-6ecdfd3056a7.png)

**Comment by hamiltonmark** [comment]
This ticket can be closed.

**Comment by SomuSundaramM** [comment]
Thank you Mark for the confirmation

**Comment by hamiltonmark** [comment]
Can you please re-open this issue?
Not able to query Workflow Data in Status Monitor in INT 12.2.10.
Thanks
Mark

**Comment by SomuSundaramM** [comment]
Hi Mark,

I've changed the settings again, it seems auto-config reverted the change which was corrected earlier. We will make a note of it in post autoconfig steps. Please check now and confirm its working or not.

Thanks,
Somu

**Comment by hamiltonmark** [comment]
Thanks Somu
I suspected Autoconfig.  It's reverted changes in the pass.

I've tested WF Status Monitor and it's back in business.
Thanks again.

**Comment by hamiltonmark** [comment]
Ok to close this ticket.
