### ISSUE TITLE
Get Error when try to open responsibility Sales User >Sales Search

### ISSUE THREAD

**Issue by SherryXLiu** [Fujitsu-America/Fujitsu-Repository#45]
**Describe the bug**

**Instance Name**
Instance:

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/85246030/121581745-37339100-c9fc-11eb-8943-ba99f7cd805e.png)

![image](https://user-images.githubusercontent.com/85246030/121581536-ed4aab00-c9fb-11eb-9f99-62aa5c6cc25a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SherryXLiu** [comment]
Yes. I can open it
![image](https://user-images.githubusercontent.com/85246030/121590156-fb052e00-ca05-11eb-847c-783c794599f7.png)

**Comment by Haqueraz** [comment]
Hi Amit, 

Can you please verify the highlighted Path in 12.2.10 Instance.  
![image](https://user-images.githubusercontent.com/84917836/121596954-ba0d1980-ca05-11eb-96d7-ac9ebe23e441.png)


![image](https://user-images.githubusercontent.com/84917836/121597457-5b946b00-ca06-11eb-87c7-1720e8c6aa4f.png)

Thanks 
Razaul

**Comment by amitjori** [comment]
Hi Razaul,

In STG instance I can see the below path under $JAVA_TOP

[aptpqs2i@ssbsashebsap3 webui]$ pwd
/tpqs2i/12.2/STG/fs2/EBSapps/comn/java/classes/oracle/apps/pbs/salesSearch/webui
[aptpqs2i@ssbsashebsap3 webui]$ ls -ltr
total 8
-rwxr-xr-x 1 aptpqs2i dba 7551 Feb  7  2015 SBSSalesSearchPG.xml

Thanks,
Amit

**Comment by Haqueraz** [comment]
Amit
when I am changing the function path then able to open that page. 

  OA.jsp?page=/oracle/apps/pbs/salesSearch/webui/SBSSalesSearchPG  -- not working   -- This is the Original Path 
  OA.jsp?page=/oracle/apps/pbs/snapshot/webui/PBSSalesSnapshotPG  -- working. 

Thanks 
Razaul

**Comment by SomuSundaramM** [comment]
Hi Sherry,

We have fixed the issue in STG, Please test the sales user page in STG instance and let us know the result.

![image](https://user-images.githubusercontent.com/85238833/122070992-e948cf80-cde5-11eb-95f9-bddc348adb97.png)

Thanks,
Somu

**Comment by SherryXLiu** [comment]
Somu,

Sales Search is ok now, but Sales dashboard become Not
![image](https://user-images.githubusercontent.com/85246030/122073488-754aff00-cdc6-11eb-994d-b61c5f83b0a7.png)

**Comment by Haqueraz** [comment]
Hi Sherry ,

Please check now to open the sales Dashboard. 

Thanks 
Razaul

**Comment by SherryXLiu** [comment]
Yes. It is OK. Thanks
