### ISSUE TITLE
INT PBS US View Only Contracts and Installed Base Menu Exclusions are missing

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#46]
**Describe the bug**
As I was testing this responsibility in INT 12.2.10 I noticed it had a lot more functionality than what I remembered.  So I compared the responsibilities in PRD 12.1.3 and INT 12.2.10 and noticed all but one of the menu exclusions are missing.

**Instance Name**
Instance: DPQS2I

**Responsibility Name**
Responsibility: PBS US View Only Contracts and Installed Base

**Navigation**
Navigation: PBS US View Only Contracts and Installed Base

**To Reproduce**
1. See many more functions are available than are supposed to be

**Expected behavior**
Menu exclusions should be the same as 12.1.3 for this responsibility.

**Screenshots**
[INT 12.2.10 PBS US View Only Contracts and Install Base Most Menu Exclusions are missing.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6640527/INT.12.2.10.PBS.US.View.Only.Contracts.and.Install.Base.Most.Menu.Exclusions.are.missing.docx)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vinaytalasila** [comment]
Tina,

We will look into this and keep you posted.

Thanks
Vinay Talasila

**Comment by ashoksnapfj** [comment]
Hi Tina,

This is fixed now. Please check now provide us know your feedback.

Thanks
Ashok.T

**Comment by TinaGriffin** [comment]
This is resolved in INT and can be closed.

**Comment by Haqueraz** [comment]
Thank you !
