### ISSUE TITLE
Attached is the APEX cert since it won't go through email.

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#47]
**Describe the bug**
No bug....email apparently getting blocked so using github to upload the APEX cert
[isbsashebsap4.oci.snapbs.com.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6649405/isbsashebsap4.oci.snapbs.com.zip)
.

**Instance Name**
Instance:

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Haqueraz** [comment]
Thank you for sharing the information. @amitjori will look into this.

**Comment by TinaGriffin** [comment]
I didn't want to open a new issue...so re-opening this one to attach the STG APEX cert zip file.

**Comment by TinaGriffin** [comment]
[ssbsashebsap3.oci.snapbs.com.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7128930/ssbsashebsap3.oci.snapbs.com.zip)

**Comment by vinaytalasila** [comment]
@amitjori and @SomuSundaramM: Could you please look into this?

Thanks
Vinay

**Comment by amitjori** [comment]
Hello Tina,

I was able to download the certificate for apex STG instance.

Regards,
Amit

**Comment by vinaytalasila** [comment]
Can we close this ticket now or any more steps are pending in Production Dry-run or STG 12.2.10 instances?

Thanks
Vinay

**Comment by TinaGriffin** [comment]
It can be closed after Amit is finished with the STG outage for the cert.  But I'll be re-opening this same ticket when we get the PROD Apex cert.

**Comment by amitjori** [comment]
Hello Tina,

Apex cert has been imported in STG 12.2.10 instance and this ticket can be closed, you may re-open it when you get the PROD certificate.

Regards,
Amit

**Comment by TinaGriffin** [comment]
I have received the 12.2.10 APEX PROD cert.  I'm attaching the zip file.
[psbsashebsap1.oci.snapbs.com.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7138487/psbsashebsap1.oci.snapbs.com.zip)

**Comment by vinaytalasila** [comment]
**@amitjori and @SomuSundaramM:** Could you please **acknowledge** that you downloaded psbsashebsap1.oci.snapbs.com.zip file related to 12.2.10 APEX PROD cert so that we can **close** this issue.

Thanks
Vinay

**Comment by amitjori** [comment]
Hello Tina,

I was able to download the certs.

Regards,
Amit

**Comment by vinaytalasila** [comment]
Amit,

Thank you for your update. I am closing this issue now.

Thanks
Vinay
