### ISSUE TITLE
INT 12.2.10 Check SMTP o365 Server - Job runs successfully - Log shows email was sent - but no email received

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#48]
**Describe the bug**

**Instance Name**
Instance:    DPQS2I

**Responsibility Name**
Responsibility:   SBS Collection Analyst

**Navigation**
Navigation:  Invoice Transaction Details > Send Copy

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
![image](https://user-images.githubusercontent.com/85197361/121937880-272bf200-cd19-11eb-8080-649e9078d3d1.png)

**Comment by hamiltonmark** [comment]
Log shows successful.
Checked Spam and Quarantine - emails in question not found there... so assuming they are not being blocked.
Logic next step to check SMTP Server Queue.

**Comment by hamiltonmark** [comment]
DEBUG SMTP: message successfully delivered to mail server
QUIT
221 2.0.0 Bye
IEXXmlDelivery [Jun-14-2021 13:54:54]: submitted request successfully...
IEXXmlDelivery [Jun-14-2021 13:54:54]: return status :0
IEXXmlDelivery [Jun-14-2021 13:54:54]: return Status msg :Message has been successfully sent to all addresses.
IEXXmlDelivery [Jun-14-2021 13:54:54]: end sending email
IEXXmlDelivery [Jun-14-2021 13:54:54]: IN sendSignalToWorkFlow 
IEXXmlDelivery [Jun-14-2021 13:54:54]:In sendSignalToWorkFlow method Query to fetch Object_type and status  :  select object_type,status  from iex_xml_request_histories  where xml_request_id = :1 
IEXXmlDelivery [Jun-14-2021 13:54:54]: IN sendSignalToWorkFlow l_object_type : IEX_INVOICES
IEXXmlDelivery [Jun-14-2021 13:54:54]: updateStatus: sTempStatus=SUCCESSFUL
IEXXmlDelivery [Jun-14-2021 13:54:54]:Failure Reason is set to null 
IEXXmlDelivery [Jun-14-2021 13:54:54]: updateStatus: invoiceCopyExists =false
IEXXmlDelivery [Jun-14-2021 13:54:54]: updateStatus: updating staus column TempStatus=SUCCESSFUL
IEXXmlDelivery [Jun-14-2021 13:54:54]: delivery done
IEXXmlDelivery [Jun-14-2021 13:54:54]: Before calling writeOutputPDF 
IEXXmlDelivery [Jun-14-2021 13:54:54]:writeOutputPDF: Begin 
IEXXmlDelivery [Jun-14-2021 13:54:54]:writeOutputPDF: vector size 1
IEXXmlDelivery [Jun-14-2021 13:54:54]:blDomain2 size 5095
IEXXmlDelivery [Jun-14-2021 13:54:54]:writeOutputPDF: array lenght 1
IEXXmlDelivery [Jun-14-2021 13:54:54]: Output file name /dpqs2i/applcsf/out/o35396244.pdf
IEXXmlDelivery [Jun-14-2021 13:54:54]:writeOutputPDF: End 
IEXXmlDelivery [Jun-14-2021 13:54:54]:after calling writeOutputPDF 
CP main completed runProgram for oracle.apps.iex.xml.IEXXmlDelivery

**Comment by hamiltonmark** [comment]
In addition - today (6/14/2021) begins Test Cycle 1 for End Users.
Many end users will be trying to use Login Assistance to reset their passwords.
This is not working as well.
Please check the SMTP Server.
Thanks

**Comment by hamiltonmark** [comment]
Login Assistance is now working.

Received the email

![image](https://user-images.githubusercontent.com/85197361/121939322-e7fea080-cd1a-11eb-8bf5-5d78f005885a.png)

**Comment by hamiltonmark** [comment]
Thanks Amit
SMTP Email now successfully delivering after WF Mailer Bounce.

![image](https://user-images.githubusercontent.com/85197361/122059662-dcfb4d00-cdba-11eb-945f-5db4da597df3.png)

**Comment by hamiltonmark** [comment]
This ticket can be closed.

**Comment by amitjori** [comment]
changed smtp_sasl_password_maps = static:wftpqs2i@ebsworkflow.onmicrosoft.com:Sbsnonpr0d2 from to smtp_sasl_password_maps = static:wfdpqs2i@ebsworkflow.onmicrosoft.com:Sbsnonpr0d2 in /etc/postfix/main.cf. 

Bounced postfix services and workflow services which resolved the issue

Regards,
Amit
