### ISSUE TITLE
INT Journals, Import Int’l trial balance Not Importing

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#49]
PBS INR General Ledger Senior User
1.	Reports
2.	Request
3.	Standard
4.	Request Set
5.	See screenprint 
![GL Import Error](https://user-images.githubusercontent.com/85238444/122234994-506c8f80-ce8b-11eb-9c07-c801f661946f.jpg)

**Comment by Haqueraz** [comment]
Hi Linda,
Thank you for sharing the information. @amitjori will look into this.

Thanks 
Razaul

**Comment by lindamrigo** [comment]
Uploaded log
[Int'l Import LOG INR PROD PBS_GL_International_Interface.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6664056/Int.l.Import.LOG.INR.PROD.PBS_GL_International_Interface.txt)

**Comment by amitjori** [comment]
Hi Linda,

Can you please confirm when this program was run? as log file shows below date, just wanted to confirm as log file shows below date. Is this is the date when this program was run in INT?

Current system time is 02-JUN-2021 07:52:34

Thanks,
Amit

**Comment by lindamrigo** [comment]
Hi Amit
The successful run was from 12.1.3 Production.

Linda

**Comment by lindamrigo** [comment]
Attached is the error log from 12.2.10
[GL Import 12.2.10 error log.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6670988/GL.Import.12.2.10.error.log.txt)

**Comment by amitjori** [comment]
Hello Razaul/Team,

Can you please check this issue from your side?

Regards,
Amit

**Comment by ashoksnapfj** [comment]
Hi Linda,

We are working on this. We will update once we are done.

Thanks
Ashok.T

**Comment by ashoksnapfj** [comment]
Hi Linda,
[PBS GL International Interface Process Set 49.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6677295/PBS.GL.International.Interface.Process.Set.49.docx)

This is resolved in INT. Please check and let us know.

Thanks
Ashok.T

**Comment by Haqueraz** [comment]
Hi Linda, 
Its looks like files has not imported correctly. I am looking some character in last of each line.

Can you please delete these file try to re-import in correct format.
FIle Path : /dpqs2i/12.2/INT/fs2/EBSapps/appl/xbol/12.0.0/inbound

![image](https://user-images.githubusercontent.com/84917836/122610356-1646ed80-d045-11eb-84f7-4010eb46b0df.png)

Thanks 
Razaul

**Comment by lindamrigo** [comment]
I believe that Debbie does not do anything to the file/format. But I have asked the question.

**Comment by lindamrigo** [comment]
I have attach
[SBS_INTL_GL_08_INR.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6686498/SBS_INTL_GL_08_INR.zip)
![GL INR import text](https://user-images.githubusercontent.com/85238444/122760226-e415d580-d268-11eb-945d-b75eb4972d40.JPG)
ed the excel file from Debbie.  It does not have the ^M

**Comment by lindamrigo** [comment]
Debbie says this is working now
