### ISSUE TITLE
INT ADI Upload Error - SR 3-26225604361

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#50]
This is run from Excel external from Oracle. 
For general ledger – Maintenance – ADI Upload:

1.	Created ADI worksheet
2.	Added data to upload
3.	When I “uploaded” the “Processing Upload” froze

![ADI Import](https://user-images.githubusercontent.com/85238444/122235485-bc4ef800-ce8b-11eb-863b-2c663a091467.png)
![ADI Error](https://user-images.githubusercontent.com/85238444/122235496-bf49e880-ce8b-11eb-963f-efce36441e65.jpg)

**Comment by amitjori** [comment]
Hello Linda,

Can you please confirm which browser end user is using ? If it is internet explorer can you please ask the user to review below note id.

WEBADI Cannot Upload Excel Spreadsheet - Upload Function Just Hangs (Doc ID 2309215.1)

Regards,
Amit

**Comment by lindamrigo** [comment]
Debbie was using Edge.  I asked her to try chrome or firefox.

**Comment by lindamrigo** [comment]
From Debbie G.
I will usually have to login to Oracle from the ADI worksheet so that it will upload. It doesn’t request this. I logged in to Oracle from Firefox and chrome just in case and the result is the same.

**Comment by lindamrigo** [comment]
Debbie's reponse
"I do not open a browser at all so I don’t know what it is using. I only open Excel to perform this operation. "

**Comment by lindamrigo** [comment]
Debbie is using MS Excel 2016

**Comment by lindamrigo** [comment]
From Debbie
'I recreated the form ADI form from Oracle using Firefox. I am getting the same result. '

**Comment by amitjori** [comment]
Hi Linda,

Can you please ask Debbie to check this issue now and confirm?

Regards,
Amit

**Comment by lindamrigo** [comment]
Same issue - no change

**Comment by amitjori** [comment]
Hi Linda,

We have applied th patch suggested by Oracle in STG 12.2.10 instance, can you please ask user to rest and confirm?

SQL> select name from v$database;

NAME
---------
TPQS2I

SQL> select BUG_NUMBER,CREATION_DATE from ad_bugs where BUG_NUMBER='32018285';

BUG_NUMBER                     CREATION_DATE
------------------------------ ---------------
32018285                       23-JUN-21



Regards,
Amit

**Comment by lindamrigo** [comment]
Hi Amit
Debbie is out of the office until tomorrow.

Thanks
Linda

**Comment by lindamrigo** [comment]
Debbie just tried and it is not working.

**Comment by lindamrigo** [comment]
Should Debbie be in TPQS2I and not DPQS2I for this?

**Comment by amitjori** [comment]
Hi Linda,

Please ask her to test in TPQS2I.

Regards,
Amit

**Comment by lindamrigo** [comment]
Debbie says this is not working in Stage either.

**Comment by amitjori** [comment]
Hi Linda,

Oracle has suggested the below action plan. I will complete step 1 and 2 and then we can ask end user to reproduce the issue so we can capture and upload logs to SR.

 If issue persists, please repeat the test above and capture a BNE log as follows (FYI...you will need to make sure Desktop Integration Manager - Create Integrator (WDF_CREATE_INTEGRATOR) menu function
exist in any of the responsibilities assigned to the selected Oracle username to have an access to BneAdminServlet page.

====================================================================================
1. In responsibility System Administrator set the following System Profile Options:
BNE Server Log Filename : BneLogger.log (make sure the file does not already exist, if it does delete it)
BNE Server Log Level : TRACE
BNE Server Log Path : free to choose, eg. in the IAS_TOP/Apache/Jserv/logs (use the full path)

2. restart the Apache Server

3. login -> Oracle Web ADI -> Create Document

4. follow the Steps to reproduce the problem.

5. The logfile generated can be found at the location specified in (1) at the path BNE Server Log Path with the name given in profile BNE Server Log Filename

6. Afterwards, set the BNE Server Log Level to INFORMATION to avoid excessive growth of the log file. See Note 294739.1
Regards,
Amit

**Comment by lindamrigo** [comment]
HI Amit
This sounds like a plan. Let me know when I can have Debbie retest.

Thanks
Linda

**Comment by lindamrigo** [comment]
Randy and Debbie have the same version of ADI
![Debbie Excel](https://user-images.githubusercontent.com/85238444/124615892-a3f74b00-de43-11eb-8f69-96e88ab26a80.jpg)
![Randy Excel](https://user-images.githubusercontent.com/85238444/124615903-a5c10e80-de43-11eb-8eee-150ea2cc3f23.jpg)

**Comment by lindamrigo** [comment]
Debbie's screenshot is the first screenshot.
Randy's screenshot is the second (small one).

**Comment by vinaytalasila** [comment]
Just an update...Linda has scheduled a meeting tomorrow (7/9/2021) between 10:30 AM EDT to 11:30 AM EDT with Randy, Debbie, Amit and me. 

Amit and I will review the excel and browser setting between Randy and Debbie during that session and provide the solution for this issue.

Thanks
Vinay Talasila

**Comment by vinaytalasila** [comment]
Just an update...Today Christel, Sherry and I had a web meeting. In Edge browser, added INT 12.2.10 instance URL in the Settings-> Cookies and site permissions -> Site Permissions -> Pop-Ups and redirects in both Christel and Sherry's PC's. 

Christel is having Excel Professional Plus 2016 and Sherry is having Excel Professional Plus 2013. Compared the excel setups between the two versions. Sherry was able to upload (but the data has a validation error) but Christel is still having the issue. I will investigate whether any other setups needs to be done with reference to Excel Professional Plus 2016. I will keep keep you posted.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
**@amitjori:** Is it possible to install Office Professional 2016 **demo version** in the Snap-On jump server. I found a document **Microsoft Office Integration with Oracle E-Business Suite 11i and R12 (Doc ID 1077728.1)** which I would like to try first from our end before requesting SBS end users for a web meeting.

**@lindamrigo:** Could you please **cancel** tomorrow's meeting with Debbie and Randy. If you are using Office Professional Plus 2016 then I would like to try few options in your PC tomorrow at 11:00 AM EDT. 

Thanks
Vinay

**Comment by lindamrigo** [comment]
I just had Debbie try it on my pc, and it worked correctly.  
My version is Excel 2016 Professional
![LRigo Excel](https://user-images.githubusercontent.com/85238444/125644380-414ac9ed-b871-4b9e-90d9-91779e3f23bc.JPG)

**Comment by lindamrigo** [comment]
I have created a new SR - SR 3-26458376761 : WEB ADI using Excel 2016 Professional 32 bit not working in 12.2.10 as Debbie's IE settings are correct and her excel settings match documentation

**Comment by amitjori** [comment]
Hello Linda,

Oracle is still asking for the logs which are not getting generated, analyst has asked to set the profile "BNE Debug Log Directory"(Created new directory this time to see if it helps) one more time and try to re-produce the issue to get the logs generated.

I have setup the profile values in INT 12.2.10 instance for user MCGEE can you please ask Christel to reproduce the issue again?

Regards,
Amit

**Comment by lindamrigo** [comment]
HI Amit
Can you set it up for Debbie G?  She really needs to have this work.

Thanks
Linda

**Comment by amitjori** [comment]
Hello Linda,

I have setup the profile values for user EVANSD, you may please ask her to reproduce the issue.

Regards,
Amit

**Comment by lindamrigo** [comment]
Art from the SBS ATS department has resolved the issue.  All documentation for IE settings has said Trusted Sites, but Art added everything to the Local Intranet settings and Debbie is now working.

I will downgrade this back to medium as to make sure Christel's pc also works

**Comment by lindamrigo** [comment]
This can be closed. IE settings needed to be done for local intranet option
