### ISSUE TITLE
USE API TO ADD A OEM RELATIONSHIP

### ISSUE THREAD

**Issue by SherryXLiu** [Fujitsu-America/Fujitsu-Repository#51]
**Describe the bug**
Use Oracle API to create a relationship, same program and same data is work in 12.1.3 instance DPQS2I, and failed in 12.2.10 instance DPQS2I

 HZ_RELATIONSHIP_V2PUB.CREATE_RELATIONSHIP ('T',
                                                   P_RELATIONSHIP_REC,
                                                   X_RELATIONSHIP_ID,
                                                   X_PARTY_ID,
                                                   X_PARTY_NUMBER,
                                                   X_RETURN_STATUS,
                                                   X_MSG_COUNT,
                                                   X_MSG_DATA,
                                                   'Y');

**Instance Name**
Instance:

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
test program

DECLARE
    V_DLRCODE               VARCHAR2 (10);
    V_OEM_PARTY             HZ_PARTIES.PARTY_ID%TYPE := 611778; --  CUSTOMER #187387 – PARTY #811713
    V_BU_PARTY_ID           HZ_PARTIES.PARTY_ID%TYPE := 1030621; --  GENERAL MOTORS OPEL AUTOMOBILE (DIST)  -  241787
    V_3D_PARTY_ID           HZ_PARTIES.PARTY_ID%TYPE := 85193; --  THE BILL TO CUSTOMER NUMBER - 67058
    V_CAT                   VARCHAR2 (30) := 'AUTOMOTIVE CUSTOMER INTERNAT';
    V_TAXCODE               VARCHAR2 (20) := 'INTL';
    V_PROFILE               VARCHAR2 (50) := 'AUTOMOTIVE GM INTERNATIONAL'; --'AUTOMOTIVE-DOMESTIC';
    V_CLASS                 VARCHAR2 (30) := 'DEALER';
    V_SLSCHNL               VARCHAR2 (30) := 'NATIONAL ACCOUNT';

    V_SOURCE                VARCHAR2 (20) := '';
    PBS_CREATED_BY_MODULE   VARCHAR2 (15) := 'HZ_CPUI';
    P_CREATED_BY_MODULE     VARCHAR2 (15) := 'HZ_CPUI';
    P_ORGID                 INTEGER := 83;
    -------------------------------------------------------------
    V_PHONE_CNTRY           VARCHAR2 (5);
    V_AREA                  VARCHAR2 (5) := '';
    V_PHONE                 VARCHAR2 (20);
    V_PHONE_EXT             VARCHAR2 (30) := '';
    V_FIRST_NAME            VARCHAR2 (100);
    V_LAST_NAME             VARCHAR2 (100);
    V_EMAIL                 VARCHAR2 (300);

    V_REL_PARTY_ID          HZ_RELATIONSHIPS.RELATIONSHIP_ID%TYPE;
    V_PERSON_NUMBER         HZ_PARTIES.PARTY_NUMBER%TYPE;
    V_PERSON_ID             HZ_PARTIES.PARTY_ID%TYPE;

    V_COUNTY                HZ_PARTIES.COUNTY%TYPE;
    V_NAME                  HZ_PARTIES.PARTY_NAME%TYPE;
    V_CITY                  HZ_PARTIES.CITY%TYPE;
    V_STATE                 HZ_PARTIES.STATE%TYPE;
    V_PROVINCE              HZ_PARTIES.PROVINCE%TYPE;
    V_COUNTRY               HZ_PARTIES.COUNTRY%TYPE;
    V_ZIPCODE               HZ_PARTIES.POSTAL_CODE%TYPE;
    V_ADDR1                 HZ_PARTIES.ADDRESS1%TYPE;
    V_ADDR2                 HZ_PARTIES.ADDRESS2%TYPE;
    V_ADDR3                 HZ_PARTIES.ADDRESS3%TYPE := '';
    V_PARTY_NUM             HZ_PARTIES.PARTY_NUMBER%TYPE;
    V_PARTY_ID              HZ_PARTIES.PARTY_ID%TYPE;
    V_CUST_ACCOUNT_ID       HZ_CUST_ACCOUNTS.CUST_ACCOUNT_ID%TYPE;
    V_LOCATION_ID           HZ_LOCATIONS.LOCATION_ID%TYPE;
    V_PARTY_SITE_ID         HZ_PARTY_SITES.PARTY_SITE_ID%TYPE;
    V_CUST_ACCT_SITE_ID     HZ_CUST_ACCT_SITES_ALL.CUST_ACCT_SITE_ID%TYPE;
    V_SEATS                 NUMBER := 0;
    P_USER_ID               INTEGER := 5967;
    P_RESPONSIBILITY_ID     INTEGER;
    P_APPLICATION_ID        INTEGER := '';

    ----------------------------------------------------------------
    -- STEP 3
    ----------------------------------------------------------------
    PROCEDURE SHOW_ERROR_MESSAGE (INFOR              VARCHAR2,
                                  X_RETURN_STATUS    VARCHAR2,
                                  X_MSG_COUNT        NUMBER,
                                  X_MSG_DATA         VARCHAR2)
    AS
    BEGIN
        DBMS_OUTPUT.PUT_LINE (INFOR);
        DBMS_OUTPUT.PUT_LINE ('X_RETURN_STATUS: ' || X_RETURN_STATUS);
        DBMS_OUTPUT.PUT_LINE ('X_MSG_COUNT: ' || X_MSG_COUNT);
        DBMS_OUTPUT.PUT_LINE ('X_MSG_DATA: ' || X_MSG_DATA);

        IF X_MSG_COUNT > 1
        THEN
            FOR I IN 1 .. X_MSG_COUNT
            LOOP
                DBMS_OUTPUT.PUT_LINE (
                       I
                    || '.'
                    || SUBSTR (FND_MSG_PUB.GET (P_ENCODED => FND_API.G_FALSE),
                               1,
                               255));
            END LOOP;
        END IF;
    END SHOW_ERROR_MESSAGE;

    ------------------------------
    -- 3. CREATE CUSTOMER AND PARTY
    --------------------------------
    PROCEDURE CREATE_RELATIONSHIPS (P_SUBJ_ID              NUMBER,
                                    P_SUBJ_TYPE            VARCHAR2,
                                    P_SUBJ_TAB_NAME        VARCHAR2,
                                    P_OBJ_ID               NUMBER,
                                    P_OBJ_TYPE             VARCHAR2,
                                    P_OBJ_TAB_NAME         VARCHAR2,
                                    P_RELATIONSHIP_TYPE    VARCHAR2,
                                    P_RELATIONSHIP_CODE    VARCHAR2,
                                    P_BAC                  VARCHAR2)
    -- LINK TO HZ_PARTY_SITES
    -- OUTPUT HZ_PARTY_SITE_USES
    -- ONE SITE COULD BE MULTI USES
    -- PRIMARY USE SITE CANNOT BE INACTIVE
    AS
        P_RELATIONSHIP_REC   HZ_RELATIONSHIP_V2PUB.RELATIONSHIP_REC_TYPE;
        X_RELATIONSHIP_ID    NUMBER;
        X_PARTY_ID           NUMBER;
        X_PARTY_NUMBER       VARCHAR2 (2000);
        X_RETURN_STATUS      VARCHAR2 (2000);
        X_MSG_COUNT          NUMBER;
        X_MSG_DATA           VARCHAR2 (2000);
    BEGIN
        P_RELATIONSHIP_REC.SUBJECT_ID := P_SUBJ_ID;
        P_RELATIONSHIP_REC.SUBJECT_TYPE := P_SUBJ_TYPE;
        P_RELATIONSHIP_REC.SUBJECT_TABLE_NAME := P_SUBJ_TAB_NAME;
        P_RELATIONSHIP_REC.OBJECT_ID := P_OBJ_ID;
        P_RELATIONSHIP_REC.OBJECT_TYPE := P_OBJ_TYPE;
        P_RELATIONSHIP_REC.OBJECT_TABLE_NAME := P_OBJ_TAB_NAME;
        P_RELATIONSHIP_REC.RELATIONSHIP_TYPE := P_RELATIONSHIP_TYPE;
        P_RELATIONSHIP_REC.RELATIONSHIP_CODE := P_RELATIONSHIP_CODE;
        P_RELATIONSHIP_REC.ATTRIBUTE1 := P_BAC;
        P_RELATIONSHIP_REC.ATTRIBUTE2 := P_BAC;      -- LPAD (P_BAC, 11, '0');
        P_RELATIONSHIP_REC.COMMENTS := P_BAC;               --SUBSTR(P_BAC,6);

        P_RELATIONSHIP_REC.CREATED_BY_MODULE := PBS_CREATED_BY_MODULE;

        HZ_RELATIONSHIP_V2PUB.CREATE_RELATIONSHIP ('T',
                                                   P_RELATIONSHIP_REC,
                                                   X_RELATIONSHIP_ID,
                                                   X_PARTY_ID,
                                                   X_PARTY_NUMBER,
                                                   X_RETURN_STATUS,
                                                   X_MSG_COUNT,
                                                   X_MSG_DATA,
                                                   'Y');

        INSERT INTO PBS.SBS_API_ERRORS (CUST_ID,
                                        STATUS,
                                        MSG,
                                        ID_TYPE,
                                        CREATION_DATE,
                                        INFORMATION)
                 VALUES (
                            P_SUBJ_ID,
                            X_RETURN_STATUS,
                               X_MSG_DATA
                            || ' '
                            || P_SUBJ_ID
                            || ' '
                            || P_OBJ_ID
                            || ' '
                            || P_OBJ_TYPE,
                            'X_RELATIONSHIP_ID',
                            SYSDATE,
                            'CREATE_RELATIONSHIPS');

        SHOW_ERROR_MESSAGE (
               'CREATE PARTY RELATIONSHIP: RELATIONSHIP ID='
            || X_RELATIONSHIP_ID
            || ';'
            || 'RELATIONSHIP_TYPE ='
            || P_RELATIONSHIP_TYPE,
            X_RETURN_STATUS,
            X_MSG_COUNT,
            X_MSG_DATA);
    END CREATE_RELATIONSHIPS;
BEGIN
    DBMS_APPLICATION_INFO.SET_CLIENT_INFO ('83');
    MO_GLOBAL.INIT ('AR');
    FND_GLOBAL.APPS_INITIALIZE (5967,                           ---- PBSOPS_AR
                                     50368, --- PBS US Customer Master Maintenance
                                           222);
    MO_GLOBAL.SET_POLICY_CONTEXT ('S', 83);
    FND_GLOBAL.SET_NLS_CONTEXT ('AMERICAN');

    CREATE_RELATIONSHIPS (1041264, --V_OEM_PARTY,                              -- OEM
                          'ORGANIZATION',                      -- SUBJECT TYPE
                          'HZ_PARTIES',                       -- SUBJECT TABLE
                          1041264, --V_PARTY_ID,                         -- OBJECT ID
                          'ORGANIZATION',                       -- OBJECT TYPE
                          'HZ_PARTIES',                        -- OBJECT TABLE
                          'OEM',                          -- RELATIONSHIP TYPE
                          'OEM_TO',            --P_RELATIONSHIP_CODE VARCHAR2,
                          V_DLRCODE);
END;

**Comment by Haqueraz** [comment]
Hi Sherry , 
We will verify the code and API and let you know.

Thanks 
Razaul

**Comment by Haqueraz** [comment]
Hi Sherry, 

I am not able to see  party id in INT(12.1.3) .Can you please execute the same scripts in INT- 12.1.3 instance.

Code looks good and I have executed the same ( in INT -12.2.10 upgrade) code and its looks like something wrong values passing in parameters. 

getting below errors message while executing the code: 

Please specify a party of type Person as either the subject or object type for the contact relationship record. 611778 1041264 ORGANIZATION

FYR: http://sjosyam.blogspot.com/2015/08/hz-api-for-party-party-site-location.html

Thanks 
Razaul

**Comment by SherryXLiu** [comment]
In 12.1.3, DPQS2I with same data and same code, I have created party_id=1038337 and below relationships,
![image](https://user-images.githubusercontent.com/85246030/122457973-44f99100-cf7d-11eb-93af-10cffe2bb04b.png)

But in 12.2.10 DPQS2I, I got the party_id=1041264, but none of relationships

**Comment by Haqueraz** [comment]
Hi Sherry , 
Below scripts created the Relationship in INT: 

------------------------------&&&&&&&&&&&&&&&&
DECLARE
V_DLRCODE VARCHAR2 (10);
V_OEM_PARTY HZ_PARTIES.PARTY_ID%TYPE := 611778; -- CUSTOMER #187387 – PARTY #811713
V_BU_PARTY_ID HZ_PARTIES.PARTY_ID%TYPE := 1030621; -- GENERAL MOTORS OPEL AUTOMOBILE (DIST) - 241787
V_3D_PARTY_ID HZ_PARTIES.PARTY_ID%TYPE := 85193; -- THE BILL TO CUSTOMER NUMBER - 67058
V_CAT VARCHAR2 (30) := 'AUTOMOTIVE CUSTOMER INTERNAT';
V_TAXCODE VARCHAR2 (20) := 'INTL';
V_PROFILE VARCHAR2 (50) := 'AUTOMOTIVE GM INTERNATIONAL'; --'AUTOMOTIVE-DOMESTIC';
V_CLASS VARCHAR2 (30) := 'DEALER';
V_SLSCHNL VARCHAR2 (30) := 'NATIONAL ACCOUNT';
V_SOURCE                VARCHAR2 (20) := '';
PBS_CREATED_BY_MODULE   VARCHAR2 (15) := 'HZ_CPUI';
P_CREATED_BY_MODULE     VARCHAR2 (15) := 'HZ_CPUI';
P_ORGID                 INTEGER := 83;
-------------------------------------------------------------
V_PHONE_CNTRY           VARCHAR2 (5);
V_AREA                  VARCHAR2 (5) := '';
V_PHONE                 VARCHAR2 (20);
V_PHONE_EXT             VARCHAR2 (30) := '';
V_FIRST_NAME            VARCHAR2 (100);
V_LAST_NAME             VARCHAR2 (100);
V_EMAIL                 VARCHAR2 (300);

V_REL_PARTY_ID          HZ_RELATIONSHIPS.RELATIONSHIP_ID%TYPE;
V_PERSON_NUMBER         HZ_PARTIES.PARTY_NUMBER%TYPE;
V_PERSON_ID             HZ_PARTIES.PARTY_ID%TYPE;



V_COUNTY                HZ_PARTIES.COUNTY%TYPE;
V_NAME                  HZ_PARTIES.PARTY_NAME%TYPE;
V_CITY                  HZ_PARTIES.CITY%TYPE;
V_STATE                 HZ_PARTIES.STATE%TYPE;
V_PROVINCE              HZ_PARTIES.PROVINCE%TYPE;
V_COUNTRY               HZ_PARTIES.COUNTRY%TYPE;
V_ZIPCODE               HZ_PARTIES.POSTAL_CODE%TYPE;
V_ADDR1                 HZ_PARTIES.ADDRESS1%TYPE;
V_ADDR2                 HZ_PARTIES.ADDRESS2%TYPE;
V_ADDR3                 HZ_PARTIES.ADDRESS3%TYPE := '';
V_PARTY_NUM             HZ_PARTIES.PARTY_NUMBER%TYPE;
V_PARTY_ID              HZ_PARTIES.PARTY_ID%TYPE;
V_CUST_ACCOUNT_ID       HZ_CUST_ACCOUNTS.CUST_ACCOUNT_ID%TYPE;
V_LOCATION_ID           HZ_LOCATIONS.LOCATION_ID%TYPE;
V_PARTY_SITE_ID         HZ_PARTY_SITES.PARTY_SITE_ID%TYPE;
V_CUST_ACCT_SITE_ID     HZ_CUST_ACCT_SITES_ALL.CUST_ACCT_SITE_ID%TYPE;
V_SEATS                 NUMBER := 0;
P_USER_ID               INTEGER := 5967;
P_RESPONSIBILITY_ID     INTEGER;
P_APPLICATION_ID        INTEGER := '';

----------------------------------------------------------------
-- STEP 3
----------------------------------------------------------------
PROCEDURE SHOW_ERROR_MESSAGE (INFOR              VARCHAR2,
                              X_RETURN_STATUS    VARCHAR2,
                              X_MSG_COUNT        NUMBER,
                              X_MSG_DATA         VARCHAR2)
AS
BEGIN
    DBMS_OUTPUT.PUT_LINE (INFOR);
    DBMS_OUTPUT.PUT_LINE ('X_RETURN_STATUS: ' || X_RETURN_STATUS);
    DBMS_OUTPUT.PUT_LINE ('X_MSG_COUNT: ' || X_MSG_COUNT);
    DBMS_OUTPUT.PUT_LINE ('X_MSG_DATA: ' || X_MSG_DATA);

    IF X_MSG_COUNT > 1
    THEN
        FOR I IN 1 .. X_MSG_COUNT
        LOOP
            DBMS_OUTPUT.PUT_LINE (
                   I
                || '.'
                || SUBSTR (FND_MSG_PUB.GET (P_ENCODED => FND_API.G_FALSE),
                           1,
                           255));
        END LOOP;
    END IF;
END SHOW_ERROR_MESSAGE;

------------------------------
-- 3. CREATE CUSTOMER AND PARTY
--------------------------------
PROCEDURE CREATE_RELATIONSHIPS (P_SUBJ_ID              NUMBER,
                                P_SUBJ_TYPE            VARCHAR2,
                                P_SUBJ_TAB_NAME        VARCHAR2,
                                P_OBJ_ID               NUMBER,
                                P_OBJ_TYPE             VARCHAR2,
                                P_OBJ_TAB_NAME         VARCHAR2,
                                P_RELATIONSHIP_TYPE    VARCHAR2,
                                P_RELATIONSHIP_CODE    VARCHAR2,
                                P_BAC                  VARCHAR2)
-- LINK TO HZ_PARTY_SITES
-- OUTPUT HZ_PARTY_SITE_USES
-- ONE SITE COULD BE MULTI USES
-- PRIMARY USE SITE CANNOT BE INACTIVE  --1797 -- everest -- DL --   
AS
    P_RELATIONSHIP_REC   HZ_RELATIONSHIP_V2PUB.RELATIONSHIP_REC_TYPE;
    X_RELATIONSHIP_ID    NUMBER;
    X_PARTY_ID           NUMBER;
    X_PARTY_NUMBER       VARCHAR2 (2000);
    X_RETURN_STATUS      VARCHAR2 (2000);
    X_MSG_COUNT          NUMBER;
    X_MSG_DATA           VARCHAR2 (2000);
BEGIN
 DBMS_OUTPUT.PUT_LINE ('Inside procedure CREATE_RELATIONSHIPS...');
    P_RELATIONSHIP_REC.SUBJECT_ID         := P_SUBJ_ID;
    P_RELATIONSHIP_REC.SUBJECT_TYPE       := P_SUBJ_TYPE;
    P_RELATIONSHIP_REC.SUBJECT_TABLE_NAME := P_SUBJ_TAB_NAME;
    P_RELATIONSHIP_REC.OBJECT_ID          := P_OBJ_ID;
    P_RELATIONSHIP_REC.OBJECT_TYPE        := P_OBJ_TYPE;
    P_RELATIONSHIP_REC.OBJECT_TABLE_NAME  := P_OBJ_TAB_NAME;
    P_RELATIONSHIP_REC.RELATIONSHIP_TYPE  := P_RELATIONSHIP_TYPE;
    P_RELATIONSHIP_REC.RELATIONSHIP_CODE  := P_RELATIONSHIP_CODE;
    P_RELATIONSHIP_REC.ATTRIBUTE1         := P_BAC;
    P_RELATIONSHIP_REC.ATTRIBUTE2         := P_BAC;      -- LPAD (P_BAC, 11, '0');
    P_RELATIONSHIP_REC.COMMENTS           := P_BAC;               --SUBSTR(P_BAC,6);
    P_RELATIONSHIP_REC.CREATED_BY_MODULE  := PBS_CREATED_BY_MODULE;

    HZ_RELATIONSHIP_V2PUB.CREATE_RELATIONSHIP ('T',
                                               P_RELATIONSHIP_REC,
                                               X_RELATIONSHIP_ID,
                                               X_PARTY_ID,
                                               X_PARTY_NUMBER,
                                               X_RETURN_STATUS,
                                               X_MSG_COUNT,
                                               X_MSG_DATA,
                                               Null
                                               );
                                               
 --                                              create_relationship (
 --   p_init_msg_list              IN     VARCHAR2:= FND_API.G_FALSE,
 --   p_relationship_rec           IN     RELATIONSHIP_REC_TYPE,
  --  x_relationship_id            OUT    NOCOPY NUMBER,
  --  x_party_id                   OUT    NOCOPY NUMBER,
  --  x_party_number               OUT    NOCOPY VARCHAR2,
  --  x_return_status              OUT    NOCOPY VARCHAR2,
  --  x_msg_count                  OUT    NOCOPY NUMBER,
   -- x_msg_data                   OUT    NOCOPY VARCHAR2,
   -- p_create_org_contact         IN     VARCHAR2
  
  DBMS_OUTPUT.PUT_LINE ('X_RELATIONSHIP_ID'||X_RELATIONSHIP_ID);
  DBMS_OUTPUT.PUT_LINE ('X_MSG_DATA'||X_MSG_DATA);
  
  /*
    INSERT INTO PBS.SBS_API_ERRORS (CUST_ID,
                                    STATUS,
                                    MSG,
                                    ID_TYPE,
                                    CREATION_DATE,
                                    INFORMATION)
             VALUES (
                        P_SUBJ_ID,
                        X_RETURN_STATUS,
                           X_MSG_DATA
                        || ' '
                        || P_SUBJ_ID
                        || ' '
                        || P_OBJ_ID
                        || ' '
                        || P_OBJ_TYPE,
                        'X_RELATIONSHIP_ID',
                        SYSDATE,
                        'CREATE_RELATIONSHIPS');
*/

    SHOW_ERROR_MESSAGE (
           'CREATE PARTY RELATIONSHIP: RELATIONSHIP ID='
        || X_RELATIONSHIP_ID
        || ';'
        || 'RELATIONSHIP_TYPE ='
        || P_RELATIONSHIP_TYPE,
        X_RETURN_STATUS,
        X_MSG_COUNT,
        X_MSG_DATA);
END CREATE_RELATIONSHIPS;

BEGIN
 DBMS_OUTPUT.PUT_LINE ('Start...');
DBMS_APPLICATION_INFO.SET_CLIENT_INFO ('83');
MO_GLOBAL.INIT ('AR');
FND_GLOBAL.APPS_INITIALIZE (10709,--10709, --5967, ---- PBSOPS_AR
                            50368, --- PBS US Customer Master Maintenance  -- PBS US Customer Master Maintenance
                            222
                            );
MO_GLOBAL.SET_POLICY_CONTEXT ('S', 83);
FND_GLOBAL.SET_NLS_CONTEXT ('AMERICAN');
 DBMS_OUTPUT.PUT_LINE ('Calling procedure CREATE_RELATIONSHIPS...');
CREATE_RELATIONSHIPS (1116, --V_OEM_PARTY,                              -- OEM
                      'ORGANIZATION',                      -- SUBJECT TYPE
                      'HZ_PARTIES',                       -- SUBJECT TABLE
                      77009, --V_PARTY_ID,                         -- OBJECT ID
                      'ORGANIZATION',                       -- OBJECT TYPE
                      'HZ_PARTIES',                        -- OBJECT TABLE
                      'COMPETITOR',                          -- RELATIONSHIP TYPE
                      'COMPETITOR_OF',            --P_RELATIONSHIP_CODE VARCHAR2,
                      V_DLRCODE);
END;
----------------------&&&&&&&&&&&&&&&&&&&&&&&&
Start...
Calling procedure CREATE_RELATIONSHIPS...
Inside procedure CREATE_RELATIONSHIPS...
X_RELATIONSHIP_ID4782895
X_MSG_DATA
CREATE PARTY RELATIONSHIP: RELATIONSHIP ID=4782895;RELATIONSHIP_TYPE =COMPETITOR
X_RETURN_STATUS: S
X_MSG_COUNT: 0
X_MSG_DATA:

**Comment by SherryXLiu** [comment]
I'll look at it

**Comment by SherryXLiu** [comment]
use NULL to replace 'Y' is OK. Thanks
