### ISSUE TITLE
INT 12.2.10 Missing Create Contact button under Customer Standard button in Advanced Collections ***SR 3-26260732121***

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#52]
**Describe the bug**

**Instance Name**
Instance:

**Responsibility Name**
Responsibility:    SBS Collections Agent

**Navigation**
Navigation:    Search > (Enter Account Number 00926) > Search > Click OK > Click on Accounts Tab > Customer Standard Button > Create Contact

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
See Screenshot Word Doc for details...

[Screenshots Customer Contact in Adv Collections.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6664489/Screenshots.Customer.Contact.in.Adv.Collections.docx)

**Comment by hamiltonmark** [comment]
Here is the 2015 Screenshots of Personalizations created to accomplish this.

[PERSONALIZATION SCREENSHOTS ADV COLLECTIONS ADDING CONTACTS EMAILS 28OCT2015.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6664531/PERSONALIZATION.SCREENSHOTS.ADV.COLLECTIONS.ADDING.CONTACTS.EMAILS.28OCT2015.docx)

**Comment by Haqueraz** [comment]
Thank you Mark for sharing the documents. 
@AkshayK247 will work on this.

Thanks 
Razaul

**Comment by AkshayK247** [comment]
We have upload the file on the SR and following up with Oracle.

Regards,
Akshay

**Comment by ashoksnapfj** [comment]
================ below oracle update==================
Thank you for the update. Since this button is missing only post upgrade to 12.2.10, I will have to validate the upgrade logs to begin with.

I am reviewing the upgrade logs and shall update the SR.
================ below oracle update==================

**Comment by AkshayK247** [comment]
=================Update from Oracle=================
	
Hi Team,

Can you check if function "IEX: Read/Write mode of Customer Standard Form" is attached to the responsibility from which you are querying?

1) Navigate to System administrator -> Security-> Responsibility -> Define

2) Query your responsibility and note down the Menu name.

3) Navigate to System administrator ->Application->Menu

4) Query for the Menu noted in step 2.

5) Under this check if function "IEX: Read/Write mode of Customer Standard Form" is attached and let us know.

Thanks,
Divya

	
-- Search --

Note: This is INTERNAL ONLY research. No action should be taken by the customer on this information. This is research only, and may NOT be applicable to your specific situation.

Keywords: Customer Standard Form read only

Product : Oracle Advanced Collections

Results: Doc ID 2187811.1 - Why is Customer Button on Account Tab Read Only After the application of patch 22534844:R12.IEX.B?

-Above note says that issue happens in 12.2.6 upgraded environment, customer is also in same version

-Note says menu "IEX_RW_CUSTOMER_STANDARD" has to be attached to any responsibility from which the form is opened.

-Need to check if the menu is attached to User's responsibility or not

=================Update from Oracle=================

**Comment by AkshayK247** [comment]
Hi Team,

As suggested by Oracle I have attached the function 'IEX: Read/Write mode of Customer Standard Form" to the responsibility "SBS Collection Agent" and it is working as expected. Now Create Contact button and save, apply buttons are visible on the Customer Page.

I have done this changes on both INT and STAGE. Kindly verify the same.

Please review the attached document for details.
[Enable Create Contact Button.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6746970/Enable.Create.Contact.Button.docx)

Regards,
Akshay

**Comment by hamiltonmark** [comment]
Akshay
In INT - when I initially go in to test this ....

![image](https://user-images.githubusercontent.com/85197361/124121228-a5d79d80-da42-11eb-91e0-d7dc4d77dfaa.png)

I get the following error.... and it kicks me out to the Menus ...

![image](https://user-images.githubusercontent.com/85197361/124121184-948e9100-da42-11eb-950b-5526dde8fe0f.png)

**Comment by hamiltonmark** [comment]
WHen I try to use Search....

![image](https://user-images.githubusercontent.com/85197361/124121515-fb13af00-da42-11eb-8f28-eb3c433e7be4.png)

I get the following...

![image](https://user-images.githubusercontent.com/85197361/124121477-ed5e2980-da42-11eb-82eb-baffc23e557a.png)

**Comment by AkshayK247** [comment]
Hi Mark,

Please try now.

**Comment by hamiltonmark** [comment]
Akshay
INT Testing - Looks Good!
I will ask end users to test.
Thanks for your work on this...
Mark

![image](https://user-images.githubusercontent.com/85197361/124125218-5b0c5480-da47-11eb-96d2-1066278a9142.png)

Contact TEST TEST added below.

![image](https://user-images.githubusercontent.com/85197361/124125299-737c6f00-da47-11eb-8e5d-772419d77e88.png)

**Comment by hamiltonmark** [comment]
Thanks for all your work on this.
This ticket can be closed.
Mark

**Comment by Haqueraz** [comment]
Thank you Mark for confirmation.
