### ISSUE TITLE
INT 12.2.10 Are ENV Variables Set on isbsashebsap4 - particularly $XBOL_TOP

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#53]
**Describe the bug**
Using Putty - Logging as sudo su apdpqs2i
[apdpqs2i@isbsashebsap4 ~]$ whoami
apdpqs2i
[apdpqs2i@isbsashebsap4 ~]$ hostname
isbsashebsap4
[apdpqs2i@isbsashebsap4 ~]$ echo $XBOL_TOP

 [apdpqs2i@isbsashebsap4 ~]$ pwd
/home/apdpqs2i
[apdpqs2i@isbsashebsap4 ~]$ cd $XBOL_TOP
[apdpqs2i@isbsashebsap4 ~]$ pwd
/home/apdpqs2i
[apdpqs2i@isbsashebsap4 ~]$

**Instance Name**
Instance:

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by amitjori** [comment]
Hello Mark,

I have set the environment file in .bashrc profile. Can you please try now and confirm?

[ajori@isbsashebsap4 ~]$ sudo su apdpqs2i
[sudo] password for ajori:

  E-Business Suite Environment Information
  ----------------------------------------
  RUN File System           : /dpqs2i/12.2/INT/fs2/EBSapps/appl
  PATCH File System         : /dpqs2i/12.2/INT/fs1/EBSapps/appl
  Non-Editioned File System : /dpqs2i/12.2/INT/fs_ne


  DB Host: isbsashebsdb4.oci.snapbs.com  Service/SID: DPQS2I


  Sourcing the RUN File System ...

[apdpqs2i@isbsashebsap4 ajori]$ whoami
apdpqs2i
[apdpqs2i@isbsashebsap4 ajori]$ hostname
isbsashebsap4
[apdpqs2i@isbsashebsap4 ajori]$ echo $XBOL_TOP
/dpqs2i/12.2/INT/fs2/EBSapps/appl/xbol/12.0.0
[apdpqs2i@isbsashebsap4 ajori]$ cd $XBOL_TOP
[apdpqs2i@isbsashebsap4 12.0.0]$ pwd
/dpqs2i/12.2/INT/fs2/EBSapps/appl/xbol/12.0.0
[apdpqs2i@isbsashebsap4 12.0.0]$

**Comment by hamiltonmark** [comment]
Thanks Amit
I can now see ENV Variables in INT 12.2.10.

[apdpqs2i@isbsashebsap4 12.0.0]$ hostname
isbsashebsap4
[apdpqs2i@isbsashebsap4 12.0.0]$ whoami
apdpqs2i
[apdpqs2i@isbsashebsap4 12.0.0]$ cd $XBOL_TOP
[apdpqs2i@isbsashebsap4 12.0.0]$ pwd
/dpqs2i/12.2/INT/fs2/EBSapps/appl/xbol/12.0.0
[apdpqs2i@isbsashebsap4 12.0.0]$

**Comment by hamiltonmark** [comment]
This ticket can closed

**Comment by amitjori** [comment]
Hello Mark,

This issue is resolved after setting environment variable in .bashrc profile hence closing the ticket.

Regards,
Amit
