### ISSUE TITLE
Batch loading Sales Lead process (Import Sales Leads ) do not work

### ISSUE THREAD

**Issue by SherryXLiu** [Fujitsu-America/Fujitsu-Repository#54]
**Describe the bug**

**Instance Name**
Instance:

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SherryXLiu** [comment]
Responsibility: Oracle Sales Administration
Process name Import Sales Leads
No results, no error
![image](https://user-images.githubusercontent.com/85246030/122287539-0b625080-cebf-11eb-9db6-ddacc66cdce3.png)

**Comment by Haqueraz** [comment]
Hi Sherry,

Could you please mention the Instance name? 
Is there is data for this parameter. Completed Normal without output result means data does not exists for this parameter values.

Thanks 
Razaul

**Comment by Haqueraz** [comment]
Hi Sherry , 

I have submitted the import program and it has successfully processed. 

Please verify the processed records and let us know if any queries. 
![image](https://user-images.githubusercontent.com/84917836/122305389-6a7a9200-cecc-11eb-8c19-ed8d8a73871d.png)

Calling LeadImport-PRE Event
Total batch size: 1
Spawned child# 1 request_id: 35399422
Calling LeadImport-POST Event

Thanks 
Razaul

**Comment by SherryXLiu** [comment]
It worked. I run in wrong instance
