### ISSUE TITLE
Java look and feel is not consistent

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#55]
The java look and feel between dpqs2i and tpqs2i is not set the same
![dpqs2i java look](https://user-images.githubusercontent.com/85238444/122389491-f9c08d80-cf3e-11eb-84ea-f0a4af42f536.JPG)
![tpqs2i java look](https://user-images.githubusercontent.com/85238444/122389495-fc22e780-cf3e-11eb-8f21-a9da917b38e4.JPG)

**Comment by amitjori** [comment]
Hi Linda,

Can you please this now and confirm if Java look and feel looks good in INT 12.2.10 instance?

Regards,
Amit

**Comment by lindamrigo** [comment]
This is now consistent with tpqs2i
