### ISSUE TITLE
INT Sales User

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#56]
There is a difference in the Sales User menu between 12.1.3 and 12.2.10. In 12.1.3, I can get into the menu and full functionality, in 12.2.10, I get an error. Both screenshots are attached.

![sales user dpqs2i 12 1 3](https://user-images.githubusercontent.com/85238444/122452286-1a0c3e80-cf77-11eb-8261-879929ba15d2.JPG)
![sales user dpqs2i 12 2 10](https://user-images.githubusercontent.com/85238444/122452292-1bd60200-cf77-11eb-8a9b-10485a8e4205.JPG)

**Comment by Haqueraz** [comment]
Hi sherry, 

Could you please help to Linda to get access this page. 

Thanks 
Razaul

**Comment by lindamrigo** [comment]
This is working.
