### ISSUE TITLE
INT 12.2.10 PO Requisition flowing directly to PO and not Autocreate - WF PO CREATE DOCUMENTS - Custom Value Overridden with Default Value

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#60]
**Describe the bug**
PO Requisition flowing directly to PO and not Autocreate - Possible Personalization Missing

**Instance Name**
Instance:  dpqs2i

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
Can you please verify attached Personalizations are present in INT for end user - PENNINGTONB?

[PERSONALIZATION SCREENSHOTS AUTOCREATE PO DEFAULTS.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6679369/PERSONALIZATION.SCREENSHOTS.AUTOCREATE.PO.DEFAULTS.docx)

**Comment by Haqueraz** [comment]
Thank you  for sharing the documents . 
We will verify the personalization and let you know if any help needed.

**Comment by ashoksnapfj** [comment]
Hi Mark,

I verified any forms Personalizations are present in function "PO_POXBWVRP (PO Auto Create fomr
[60#_PERSO_PO_AUTO_CREATE.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6686438/60._PERSO_PO_AUTO_CREATE.docx)
)"  but there are no personalization.

Thanks
Ashok.T

**Comment by hamiltonmark** [comment]
Ashok
We had this issue in the past during the OMCS to OCI Project in 2019.  I will look for any doc that I have on fixing it.
I realized the doc I sent you was from the 11i Project.  We fixed this issue with Personalizations.  If I remember correctly - during the OCI Project it was fixed with Profile Setup but I will confirm.

Thanks
Mark

**Comment by hamiltonmark** [comment]
Ashok
Please see screenshots for the fix.
Thanks
Mark

**Comment by hamiltonmark** [comment]
[SCREENSHOTS OF WF BUILDER PO CREATE DOCUMENTS JUN2021.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6686953/SCREENSHOTS.OF.WF.BUILDER.PO.CREATE.DOCUMENTS.JUN2021.docx)

**Comment by Haqueraz** [comment]
Hi Mark, 

I have modified the workflow "PO Creation Documents"  to change default value from Y to N.

Please verify the changes in INT-12.2.10  and let me know if any queries. 

Thanks 
Razaul

**Comment by hamiltonmark** [comment]
Thanks Razaul
I've asked end user to test.  Will let you know when I hear results.
Thanks
Mark

**Comment by hamiltonmark** [comment]
End User - Brenda Pennington - has tested this Workflow change.
The PO Requisition flowed to Autocreate successfully as expected.
This now allowed her to approve it and then it flowed to a Purchase Order.

**Comment by hamiltonmark** [comment]
Thank you all.
Ok to close this ticket.

**Comment by Haqueraz** [comment]
Thank you Mark!
