### ISSUE TITLE
INT 12.2.10 Entering Invoice Amount using AP Invoice Workbench - Amt defaulting to format 9999,(comma)99 

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#61]
**Describe the bug**
Entering Invoice Amount using AP Invoice Workbench - Amt defaulting to format 9999,(comma)99 

**Instance Name**
Instance:  dpqs2i

**Responsibility Name**
Responsibility:  PBS US Payables User

**Navigation**
Navigation:  Invoice Workbench

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
Using AP Invoice Workbench - End User is trying to enter an invoice under batch name TESTBATCH06182101.

She was trying to enter dollar amount of $99.01.  Receives the following error message.  It appears there is a COMMA instead of a period in-between the dollars and cents.
If entering 99 without any cents it is fine or if I enter the value as 99,01.

![image](https://user-images.githubusercontent.com/85197361/122619053-91b49900-d05d-11eb-850f-01ac6a109653.png)

**Comment by Haqueraz** [comment]
Hi Mark ,
We will look into this and get back to you.

Thanks 
Razaul

**Comment by ashoksnapfj** [comment]
Hi Mark,

Could you please test now and let us know your feedback, as i am able to create invoices with amount separator as "." .
[61#_INT_12.2_10_Invoice_Amount_format_issue.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6686295/61._INT_12.2_10_Invoice_Amount_format_issue.docx)


Thanks
Ashok.T

**Comment by hamiltonmark** [comment]
Thanks Ashok
End User - Grace - has reported....

Good Morning,
The formatting issue is fixed.  As I just tested this in INT 12.2.10.
Thank you for the quick turnaround.  Now I will proceed with the rest of my testing.
Thanks,
Grace

**Comment by hamiltonmark** [comment]
This ticket can be closed.
