### ISSUE TITLE
INT Unable to drilldown from GL into AR

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#62]
Per Liz FultonUnable to drill down into AR from the GL.  In production, it usually gives me a message that I have to relog into Oracle, which I do from the message prompt, and then it goes thru the Java thing, and then pulls up the transaction in AR. So maybe related to all that……it just sits there 
![GL to AR](https://user-images.githubusercontent.com/85238444/122749829-ca21c600-d25b-11eb-922a-a0ab10a2e1da.jpg)

**Comment by Haqueraz** [comment]
Could you please provide the navigation details and message screenshot.

**Comment by lindamrigo** [comment]
PBS US General Ledger Senior User 1, Account Inquiry, Accounting period of Apr-21, GL account 01.11.111.41001.1001.0000.00.

**Comment by ashoksnapfj** [comment]
Hi Linda,

I am able to see drilldown in INT instance. Please check from your browser setting or anyorther issue.
attached file also for your reference.

Thanks
Ashok.T
[62_ INT_drilldown_GL_AR.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6694007/62_.INT_drilldown_GL_AR.docx)

**Comment by lindamrigo** [comment]
Liz was able to drill down once her pop ups were allowed
