### ISSUE TITLE
INT SOA Web Service SBS_CPQ_SNAPSHOT_PKG WADL erroring

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#63]
**Describe the bug**
The Web Service shows deployed, however, the WADL shows an error.

**Instance Name**
Instance: DPQS2I

**Responsibility Name**
Responsibility: 

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**
WADL should return Snapshot web service call correctly.
[Uploading INT 12.2.10 SOA Snapshot WADL failing.docx…]()

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TinaGriffin** [comment]
We might want to wait and see if the bounce for the Quote Web Service fixes this issue as well.

**Comment by Haqueraz** [comment]
Hi Tina, 
I am not able to open the attached docs file. 
Could you please re-attached the same docs.
Thanks 
Razaul

**Comment by TinaGriffin** [comment]
I think it's because it's a word doc.  I have never been able to upload word docs to github.

**Comment by TinaGriffin** [comment]
[Uploading INT 12.2.10 SOA Snapshot WADL failing.docx…]()

**Comment by TinaGriffin** [comment]
[Uploading INT 12.2.10 SOA Snapshot WADL failing.xlsx…]()

**Comment by TinaGriffin** [comment]
I tried to send it in Excel too...maybe it's my wifi I'm not sure.  They all just still saying "Uploading".  I'll send it via email and see if you can copy it into the ticket.

**Comment by Haqueraz** [comment]
[INT 12.2.10 SOA Snapshot WADL failing.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6687580/INT.12.2.10.SOA.Snapshot.WADL.failing.docx)

**Comment by Haqueraz** [comment]
Thank you Tina.
I have uploaded  the email attached docs ..

**Comment by SomuSundaramM** [comment]
Hi Tina,

We just undeployed and redeployed the package, its working now both in INT and STG instance. Please check and confirm from your side.
![image](https://user-images.githubusercontent.com/85238833/122971776-f4b86f80-d37e-11eb-86e5-cb9fd172ba50.png)

![image](https://user-images.githubusercontent.com/85238833/122971904-174a8880-d37f-11eb-9671-a87cf059f364.png)


Thanks,
Somu

**Comment by TinaGriffin** [comment]
Great!  I was going to try that myself but didn't want to interfere with anything you were working on.  I'll let you know after I test it.

**Comment by TinaGriffin** [comment]
I've retested in INT and STG and it is working now.  This can be closed.

**Comment by Haqueraz** [comment]
Thank you for testing this.
