### ISSUE TITLE
Territory Export Error SR 3-26313785411

### ISSUE THREAD

**Issue by SherryXLiu** [Fujitsu-America/Fujitsu-Repository#64]
**Describe the bug**

**Instance Name**
Instance: INT

**Responsibility Name**
Responsibility:
![image](https://user-images.githubusercontent.com/85246030/123145587-fd667f80-d42a-11eb-8a53-719447415093.png)

**Navigation**
Navigation:
[Territory export Error.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6703981/Territory.export.Error.docx)

**To Reproduce**
see attached file
**Expected behavior**
see attached file
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SherryXLiu** [comment]
Here is 12.1.3 result
![image](https://user-images.githubusercontent.com/85246030/123146392-cd6bac00-d42b-11eb-915f-58337cf6d3ed.png)

**Comment by Haqueraz** [comment]
Hi Sherry, 
It is showing different menu in my user. 
![image](https://user-images.githubusercontent.com/84917836/123155138-57684480-d42d-11eb-9783-3516b610749c.png)
  

Thanks 
Razaul

**Comment by SherryXLiu** [comment]
Please use Christel McGee account

**Comment by Haqueraz** [comment]
I have reset the password in INT: 
User Name : MCGEE
Password : Fujitsu@123456

**Comment by Haqueraz** [comment]
@amitjori Please check this issue. 

Its looks like Popup blockers.

**Comment by Haqueraz** [comment]
Hi @amitjori  
As discussed ,please look this issue on priority. If you wish then we can open the SR for this issue.  
In my primary investigation. "About this page" showing the below message 

A popup window blocker has been detected in your browser. Popup blockers interfere with the operation of this application. 

***************************************************************
<!DOCTYPE HTML><html dir="ltr" lang="en-US-ORACLE9I"><head>
<title>About Page: Error</title>
<meta name="generator" content="Oracle UIX"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<link rel="stylesheet" charset="UTF-8" type="text/css" href="/OA_HTML/cabo/styles/cache/alta-desktopEXTN-custom-12_2_10_0_0-en-1619159624000.css">
<script>var _UixWindowOpenError='A popup window blocker has been detected in your browser. Popup blockers interfere with the operation of this application. 
        Please disable your popup blocker or allow popups from this site.'
</script>
<script src="/OA_HTML/cabo/jsLibs/Common12_2_10_0_0.js"></script>

*************************************************************

**Comment by amitjori** [comment]
Hi Team,

SR has been opened for this issue - SR 3-26313785411 : Territory Export issue in 12.2.10

Regards,
Amit

**Comment by SherryXLiu** [comment]
The Export is passed, but after change and upload it back, the process is  stopped
![image](https://user-images.githubusercontent.com/85246030/124166502-e8b06a00-da70-11eb-9f65-7860f4f3bbab.png)

**Comment by SherryXLiu** [comment]
This information may help.
I have look at it with user, and it seems ADI issue, before Upload, it should show this and we did not see it in 12.2.10
![image](https://user-images.githubusercontent.com/85246030/124185864-83b53e00-da89-11eb-980e-1ff0bd720e11.png)

**Comment by amitjori** [comment]
Hi Team,

The above error is releated to ADI. Export issue was solved by setting the below profile options.

1. System Administrator Responsibility > Profile > System.
2. Query profile option BNE: Enable Simplified Create Document
3. Set profile BNE: Enable Simplified Create Document = No at Site level.
5. Clear the cache from Functional Administrator
4. Retest the issue.
5. 
We are checking further on ADI issue.

Regards,
Amit

**Comment by SherryXLiu** [comment]
@amitjori Do you prefer to close this and open a new issue for load the file back function? I am ok to create a new issue.

**Comment by SherryXLiu** [comment]
I have submit  issue # 82. So this issue can be closed Thanks
