### ISSUE TITLE
INT 12.2.10 CANNOT ADJUST CASH RECEIPT APPLIED TO WRONG INVOICE NUMBER *** SR 3-26328804901 ***

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#65]
**Describe the bug**

**Instance Name**
Instance:   dpqs2i

**Responsibility Name**
Responsibility:   PBS CAD Receivables Cash Application

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
Please see Screenshot Document describing the issue:  INT 12.2.10 CANNOT ADJUST CASH RECEIPT APPLIED TO WRONG INVOICE NUMBER.docx
[INT 12.2.10 CANNOT ADJUST CASH RECEIPT APPLIED TO WRONG INVOICE NUMBER.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6709469/INT.12.2.10.CANNOT.ADJUST.CASH.RECEIPT.APPLIED.TO.WRONG.INVOICE.NUMBER.docx)

**Comment by hamiltonmark** [comment]
Found this hit on Google Search saying...

Previously in 12.1.3, user can change customer on a receipt without running create accounting on the receipt.
However, after the upgrade to 12.2.8 once a receipt has been allocated to a specific account/invoice and users try to reallocate, they get the below error :  "Please account the receipt before updating Customer details."

https://support.oracle.com/knowledge/Oracle%20E-Business%20Suite/2721888_1.html

**Comment by hamiltonmark** [comment]
Receipt form error: Please account the receipt before updating Customer details (Doc ID 2721888.1)

Document is saying...

Solution

This is expected functionality. Changing customer on receipt without running create accounting was creating data corruption in SLA for few instances.   Hence, functionality has been changed to make accounting mandatory before changing customer on receipt.

Looks like running - Create Accounting - is the fix.  Please let me know if I should ask her to run it.
Thanks
Mark

**Comment by Haqueraz** [comment]
Thank you Mark for Investigation. 
Could you please go through this Doc ID 2054953.1

Yes ,As per oracle Note -create Accounting should be run before changing the customer.

**Comment by hamiltonmark** [comment]
Thanks Razaul
Yes - per Doc ID 2054953.1 ... Can you please confirm the file versions to see if/what patch is needed?

Confirm the file versions listed above, by navigating to the directory where the file is and using:
strings -a $AU_TOP/resource/ARXRWRCT.plx |grep '$Header'

Thanks
Mark


Solution
1. Bug Summary

    Description
    If the user has "Applied" a receipt and the Customer Name and Number field in the User Interface will be non updatable.

    Workaround
    None

    Resolution
    Customer details of a applied receipt can be updated if the corresponding applied documents for a receipt are posted. User will get message  AR_APP_ACCT_MANDATORY, that means that Create Accounting should be run before changing the customer.

2. Fixed Files

R12.AR.A:
ARXRWRCT.pld 120.150.12000000.267

R12.AR.B:
ARXRWRCT.pld 120.170.12010000.244

R12.AR.C:
ARXRWRCT.pld 120.320.12020000.77
PROACTIVE TIP:
Applying higher versions of the files listed above can help you avoid known issues. Use Note 1584999.1 to help identify other patches containing higher versions of these files.
3. Recommended Patches

R12.AR.A: No released patch available.
R12.AR.B: Patch 21620611:R12.AR.B
R12.AR.C: Patch 21620611:R12.AR.C

NOTE:
This fix may already be part of the latest Recommended Patch Collection (RPC). You are advised to apply the RPC instead of standalone patches to ensure your instance has all the critical fixes identified by development.

Please review Note 1433375.2, this note is periodically updated to contain the latest information on the most recently released RPC.

**Comment by Haqueraz** [comment]
File version in 12.210 
![image](https://user-images.githubusercontent.com/84917836/123308400-39601a00-d4e9-11eb-8028-6130a671f837.png)

**Comment by amitjori** [comment]
Hi Mark,

Patch mentioned in the above note id is already applied in INT 12.2.10 instance.

![image](https://user-images.githubusercontent.com/85238919/123676219-2cb62b80-d833-11eb-92a0-17f71219e236.png)

Regards,
Amit

**Comment by hamiltonmark** [comment]
Thanks Amit
If we are patched up and issue was not resolved - possibly we will need end user to run - Create Accounting - to work around.
I will ask her to run - Create Accounting to see if this fixes the issue.
Thanks
Mark

**Comment by hamiltonmark** [comment]
End user - Millice - has run Create Accounting as a Temporary Workaround.
Below is her response...

![image](https://user-images.githubusercontent.com/85197361/123862783-c8f53680-d8f6-11eb-8d46-09c31a6dbdc8.png)

I responded with - We are still pursuing a permanent fix.

**Comment by Haqueraz** [comment]
We are going to open the SR for permanent solution.

**Comment by hamiltonmark** [comment]
FYI - After Millice tested a JPMorgan Lockbox Import which imported more lockbox cash receipts.  She reports the following...

"As I am working in the USD batch I just imported, I am having to create accounting as the workaround for some of the transactions as expected.  For some of the transactions like the screenshot below, I get stuck in a loop.  The system keeps asking me to Create accounting, which I already did.  The only way for me to get out of the form is to File>Close Form. When I navigate back to the transaction, I still receive Error message to create accounting."

I assured her we are still pursuing a permanent fix.

![image](https://user-images.githubusercontent.com/85197361/124022347-afb5be00-d9ba-11eb-9767-0bcb06bc802b.png)

**Comment by suhas-deshpande** [comment]
Oracle has asked for the files which I have uploaded to SR. Waiting for their reply.

**Comment by suhas-deshpande** [comment]
Latest update from Oracle -
-------------------------------------------------------------------------------------------------------------------------------------------------   An automated process has reviewed the Receipt Analyzer uploaded, ARRCTANLZ_Analyzer_DPQS2I_2021-07-01_05_40.html.   It identified 1 error/s and 3 warning/s.     You are advised to review all the Errors and Warnings identified in the analyzer output.     If any specific items are listed below, please review and evaluate if  they are relevant to your issue, then perform the recommendations.  If you need assistance, please provide an update to engage Oracle Support.

**Comment by suhas-deshpande** [comment]
@hamiltonmark  - Hi Mark, Below is the update from Oracle. As per Oracle, this is expected functionality. I have asked them further if we can run this for problematic receipts once or it has to be run individually for each record.

-------------------------------------------------------------------------
  | Hello Suhas,As per noteReceipt form error: Please account the receipt before updating Customer details ( Doc ID 2721888.1 )This is expected functionality. Changing customer on receipt without running create accounting was creating data corruption in SLA for few instances.Hence, functionality has been changed to make accounting mandatory before changing customer on receipt.Best regards,Chris

**Comment by hamiltonmark** [comment]
Suhas - I will paste the following concerns into the SR...

Here are the scenarios for Daily Cash Receipts.
Each day we run 3 Lockbox Interface Jobs:
1.	JPMorgan Lockbox USD
2.	JPMorgan Lockbox CAD
3.	JPMorgan Lockbox Manual Credit Cards

These transactions total around 2500 transactions per day.
On average 10% (approx. 250) of these bank transactions cannot be applied to the correct invoice because:

1.	Bank keyed wrong or no invoice number.
2.	Bank keyed wrong or no customer number.
3.	Bank sent a cash receipt to Snap-on Business Solutions where it should have gone to one of our 33 other divisions so receipt needs to be transferred to Misc Receipt.

To remedy each of these 250 bad transactions – either a Reversal or Unidentified Transaction is required; or in the case of the wrong division – a Miscellaneous Receipt is required.  These are the day to day required tasks to get the cash receipts applied to the correct invoice.

Are you saying the Cash Person needs to run – Create Accounting for each of these 250 transactions each day?

In addition – in the case where there is No Invoice and No Customer Number on the Receipt – the screen gets stuck in a Loop saying to run Create Accounting but there is no way to exit except to Click on File > Close Form.  Upon re-entering into Receipt the same Loop happens.

This all seems like a bug to me and not very practical.
Please let us know.

**Comment by suhas-deshpande** [comment]
Hi All below  is the update from Oracle - 

*****************************************************************
Hello Suhas,

Thank you for the update.

Yes, you have to run Create Accounting for all problematic receipts
You can submit the create accounting for transaction from the submit request option to complete accounting for all transactions at once.

If you have any questions, please call Support or update the Service Request. Thanks very much!

Kind Regards,
Chris

**Comment by hamiltonmark** [comment]
Hello Suhas -

Thank you for the update.


You asked for
the navigation for the PBS US Receivables Cash Application User to run Create accounting. This doesn't look like a seeded AR Responsibility. We can't help on navigation with custom responsibility.

Please note you need to run Create accounting from AR responsibility.
For Cash receipt, you can submit the Create accounting for AR responsibility

View >> Requests >> Submit a new request >>
Select Name = Create Accounting >>

In the parameters
select Process Category = Standard Receipts

select other mandatory parameters as needed and Click ok.
Submit the request.

Best regards,
Chris

**Comment by hamiltonmark** [comment]
Updated SR with these questions...

Thanks Chris    
I just got out of a mtg with our Finance Group... Got a few questions...     

1.  If we give the Cash Person the Create Accounting Job to run - they  will have the options to Transfer to GL and/or Post to GL.  Currently  only our Controller can do that.  Do we have to customize Create  Accounting by copying it and hiding the parameters?  or do you have any  other suggestions?    

2.  Cash Person would only need to choose either - Standard Receipts or Miscellaneous Receipts - correct?  Again - another custom drop down?  or any other suggestions? |  


![image](https://user-images.githubusercontent.com/85197361/124629501-816b2f00-de4f-11eb-8384-969e30efd1eb.png)

**Comment by hamiltonmark** [comment]
Oracle Support is saying in SR 3-26328804901 : Cannot adjust Cash Receipt applied to wrong invoice number
that Cash Person needs to run Create Accounting when having errors applying cash.  We do not want Cash Person to be able to run – Create Accounting – because it allows to (1) Transfer to GL and (2) Post to GL.  SBS Corporate Controller should be the only one able to do this.

CUSTOMIZATION Required:  Attachment below shows Conc Job – Create Accounting – was copied to – SBS Create Accounting for Standard Receipts - and Parameters were modified.

Cash Person, Millice and I will be testing this.  I will post the results.


[Screenshots SBS Create Accounting Std Receipts.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6777377/Screenshots.SBS.Create.Accounting.Std.Receipts.docx)

**Comment by hamiltonmark** [comment]
We tested with SR Analyst suggestion but still did not work.
See the uploaded screenshots in the Word Doc.

[Still issue after Create Accounting.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6779684/Still.issue.after.Create.Accounting.docx)


We ran creating accounting for Standard Receipts.
Attempted to bring up an invoice on a receipt.

No matter which receipt we choose… gives same error…
Cannot do anything except click on X to exit Form

**Comment by hamiltonmark** [comment]
Zip file container - Receivables Receipt Analyster for 2 Receipts requested in SR...

[Receivables_Receipt_Analyzer_for_SR.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6785313/Receivables_Receipt_Analyzer_for_SR.zip)

**Comment by hamiltonmark** [comment]
Zip file container - Receivables Receipt Analyster for 2 Receipts requested in SR...

[Receivables_Receipt_Analyzer_for_SR.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6785341/Receivables_Receipt_Analyzer_for_SR.zip)

**Comment by hamiltonmark** [comment]
SR Analyst is asking for a Zoom Session.  I have emailed the following....

Hi Chris
End User - Millice - can demonstrate any time today from 10:30am to 3:30pm EDT.
She is available.
Can you please send Zoom Mtg email to:
millice.kreighbaum@snapon.com
Mark.hamilton@snapon.com
suhas.deshpande@in.fujitsu.com

Suhas - not sure if you are available. If you can join - please do.

Thanks
Mark

**Comment by suhas-deshpande** [comment]
Hi Mark - Sure. I can join in if meeting is scheduled before 12 pm EDT.

**Comment by hamiltonmark** [comment]
Zoom Meeting to Demonstrate issue with End User - Millice - and SR Analyst - Roberto

Thanks for the update. 
We can have the OWC - Tue 7/13/2021 at 11:00 AM EST time. 

You need to connect to this url : 
--------------------------------------------- 
Oracle Zoom Conference Details: 

Invitation from: Roberto Alonzo 

Topic: Roberto Alonzo's Personal Meeting Room 

Single click URL to join Zoom: https://oracle.zoom.us/j/5942479503?pwd=bkdhR2lxVjJSRlhBcDBVbGVQdGZndz09

Meeting ID: 594 247 9503 


One tap mobile 
+13017158592,,5942479503# US (Washington DC) 
+13126266799,,5942479503# US (Chicago) 

Dial by your location 
+1 301 715 8592 US (Washington DC) 
+1 312 626 6799 US (Chicago) 
+1 646 558 8656 US (New York) 
+1 253 215 8782 US (Tacoma) 
+1 346 248 7799 US (Houston) 
+1 669 900 6833 US (San Jose) 
Meeting ID: 594 247 9503 
Password: 126982 
Find your local number: https://oracle.zoom.us/u/axlhCuyyr 

Join by SIP 
5942479503@zoomcrc.com 

Join by H.323 
162.255.37.11 (US West) 
162.255.36.11 (US East) 
115.114.131.7 (India Mumbai) 
115.114.115.7 (India Hyderabad) 

Meeting ID: 594 247 9503 
Password: 126982 


Regards, 
Roberto 
Oracle Customer Services

**Comment by hamiltonmark** [comment]
Vinay
Below is the Action Plan from the SR.
Millice and I executed all the steps EXCEPT step 5 where it is asking for TKPROF Logs.

Here are the jobs run.
Conc Request 35432761 is the one where all the logs were created.

Can you please retrieve the TKPROF and Trace Files?

I'm unsure where they would be located.  Google searches tell me they may be on the DB Server (?).
Thanks
Mark

![image](https://user-images.githubusercontent.com/85197361/125498931-a8365220-a7aa-4919-88b1-ed273b991199.png)


[Action Plan from SR3-26328804901.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6810852/Action.Plan.from.SR3-26328804901.txt)

**Comment by vinaytalasila** [comment]
Mark,

Yes, it should be in DB Server. We will retrieve the TKPROF files and upload to this issue. 

Thanks
Vinay

**Comment by amitjori** [comment]
Hello Mark,

Trace files uploaded to the SR.

Regards,
Amit

**Comment by hamiltonmark** [comment]
Vinay
SR Analyst requested the following ACTION PLAN in INT 12.2.10.
Can you please have your team execute the following?
Thanks
Mark

-------------------- ACTION PLAN DETAILS BELOW---------------------

Hello Mark,

After reviewing in details the information in file: Diagnostics__Apps_Check_130721.txt and our knowledge base
The following patch complements the versions that you already have according to your application diagnosis,
avoiding some bugs already registered.

ACTION PLAN
-------------------------------------------------------
1. Ensure that you have taken a backup of your system before applying the recommended patch.
2. Apply the Patch 32799754:R12.AR.C in a test environment.
3. Confirm the file versions listed below, by navigating to the directory where the file is and using:
strings -a |grep '$Header'
arcabp.h 120.12.12020000.6
arm.h 120.1.12020000.4
raaddx.lpc 120.12.12020000.2
raavdx.lpc 120.8.12020000.3
arzarc.lpc 120.7.12020000.2
arzarm.lpc 120.18.12020000.2
arzcar.opc 120.34.12020000.2
arzcrm.lpc 120.10.12020000.2
arzira.lpc 120.25.12020000.2
arcabp.opc 120.10.12020000.4
arcach.lpc 120.6.12020000.5
arcatc.lpc 120.17.12020000.15
arccar.lpc 120.21.12020000.7
arccbp.lpc 120.20.12020000.7
arcgbt.lpc 120.10.12020000.6
arcgcr.lpc 120.18.12020000.9
arcgdf.lpc 120.6.12020000.5
arcgin.lpc 120.20.12020000.14
arcgrl.lpc 120.7.12020000.7
arcmis.lpc 120.56.12020000.18
arcout.lpc 120.11.12020000.5
arcpau.lpc 120.44.12020000.9
arcpbt.lpc 120.10.12020000.7
arcptck.lpc 120.17.12020000.6
arcrul.lpc 120.8.12020000.6
arctab.lpc 120.31.12020000.16
arctest.lpc 120.5.12020000.6
ardisc.lpc 120.8.12020000.5
arfccf.lpc 120.13.12020000.4
arfcfc.lpc 120.2.12020000.2
arfpsc.lpc 120.8.12020000.2
arfxpl.opc 120.5.12020000.3
arfxut.lpc 120.3.12020000.3
arlplb.opc 120.29.12020000.11
arlvcb.lpc 120.42.12020000.32
armadj.lpc 120.4.12020000.5
armapp.lpc 120.3.12020000.3
armcb.lpc 120.3.12020000.4
armck.lc 120.3.12020000.3
armps.lpc 120.17.12020000.9
armub.lpc 120.3.12020000.3
arreci.lpc 120.23.12020000.14
-------------------------------------------------------

Regards,
Roberto
Oracle Customer Services

**Comment by arsidhan** [comment]
1. Didn't find the files which will be updated by this Patch on our file system. That mean it may be introducing new files. 
2.  Patch 32799754:R12.AR.C need a password to download. 
3.  Once we could download this patch, we can look at the patch itself or do patch analysis using "Standard wizard" to generate a report, which will give us more details on it. 
![image](https://user-images.githubusercontent.com/87445344/125962343-4d52891b-182a-4066-9854-71ef820b18c5.png)

-Hanmant

**Comment by hamiltonmark** [comment]
Thanks Hanmant
I've updated the SR with the following...

![image](https://user-images.githubusercontent.com/85197361/125963812-4b022221-d275-4541-8670-b38419192ca9.png)

**Comment by hamiltonmark** [comment]
Response from SR ...
Hello Mark -


Thanks for the update
Regarding your questions/comment:

1) Can you please unprotect it or provide the pw so we can download it?
Answer: This password is valid for 21 days: ZLqIbQbq

2) Are they in $AR_TOP? App Server?
Answer: Yes, you are right.


Regards,
Roberto
Oracle Customer Services

**Comment by arsidhan** [comment]
Hi Mark, 
We also need password to download NLS patches  [ ESA ,FRC ]. Password provided can only download generic patch, which is downloaded. 
-Hanmant  

-Hanmant

**Comment by arsidhan** [comment]
For now i have downloaded the patch under /oci-backup/stage/SR_PATCHES/SR3-26328804901. 
I will download remaining to patches once we have the password. 
-Hanmant

**Comment by hamiltonmark** [comment]
I have requested the pw for NLS... waiting on their response.

In the meantime - SR Analyst is saying files are located - $AR_TOP/src/cash/

I am not finding it... Possibly you have access? 
If not - I will update SR.  Please let me know.

[apdpqs2i@isbsashebsap4 12.0.0]$ cd $AR_TOP
[apdpqs2i@isbsashebsap4 12.0.0]$ pwd
/dpqs2i/12.2/INT/fs1/EBSapps/appl/ar/12.0.0
[apdpqs2i@isbsashebsap4 12.0.0]$ ls -ltr
total 28
drwxr-xr-x 2 apdpqs2i dba 6 Nov 24 2012 out
drwxr-xr-x 2 apdpqs2i dba 6 Nov 24 2012 log
drwxr-xr-x 5 apdpqs2i dba 47 Nov 24 2012 admin
drwxr-xr-x 3 apdpqs2i dba 17 Nov 24 2012 patch
drwxr-xr-x 2 apdpqs2i dba 4096 Nov 24 2012 media
drwxr-xr-x 3 apdpqs2i dba 20 Nov 24 2012 xml
drwxr-xr-x 3 apdpqs2i dba 16 Nov 24 2012 help
drwxr-xr-x 2 apdpqs2i dba 4096 Apr 21 12:47 sql
drwxr-xr-x 2 apdpqs2i dba 4096 Apr 21 13:03 lib
drwxr-xr-x 5 apdpqs2i dba 38 Apr 22 06:32 forms
drwxr-xr-x 2 apdpqs2i dba 4096 May 19 13:57 bin
drwxr-xr-x 5 apdpqs2i dba 4096 Jul 5 07:04 html
drwxr-xr-x 21 apdpqs2i dba 4096 Jul 5 07:04 mds
drwxr-xr-x 5 apdpqs2i dba 38 Jul 5 07:04 reports
drwxr-xr-x 2 apdpqs2i dba 4096 Jul 5 09:36 mesg
[apdpqs2i@isbsashebsap4 12.0.0]$

**Comment by hamiltonmark** [comment]
US  This password is valid for 21 days: ZLqIbQbq
ESA This password is valid for 21 days: atcUKoaf
FRC This password is valid for 21 days: ZTgXPYSr 

In addition - SR Analyst is saying it is a permissions issue...
where I do not have access to $AR_TOP/src/cash/

Sorry I was trying to help grep the $Headers.

**Comment by hamiltonmark** [comment]
Below is xlsx containing 656 Bug Fixes included in Patch 32799754:R12.AR.C.
In column B - I've added functions that will need to be re-tested after patch is applied in INT 12.2.10.
In addition - I've shared and explained this document with Nichole Dotson (AR Manager).

Here is the particular bug fix that closely describes our current issue:
13625713 - REW:RCA FOR 13390196:WHEN UNAPPLYING UPGRADED RECEIPTS ACCOUNTING NOT GENERATED.


[Patch 32799754.xlsx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6841937/Patch.32799754.xlsx)

**Comment by arsidhan** [comment]
Downloaded Lang patches under /oci-backup/stage/SR_PATCHES/SR3-26328804901
-Hanmant

**Comment by amitjori** [comment]
Hello Mark/Team,

Patch has been applied in INT 12.2.10 instance.

![image](https://user-images.githubusercontent.com/85238919/126282199-23aa3fc9-62ca-484c-8570-37d3b08744c2.png)

Regards,
Amit

**Comment by hamiltonmark** [comment]
Thanks Amit.
I've asked Millice to test.
Will let you know the results.

**Comment by hamiltonmark** [comment]
I've updated SR with the following...

Testing Results after Patch:

32799754:R12.AR.C was installed in our new INT 12.2.10 instance last night.

End User tested the following:

Receipt #104288.
Tried to apply to customer #116381.
No invoices listed. Backed out. Tried to remove customer information.
Was prompted to create accounting.
Created accounting and verified.
Unable to remove customer information and choose another customer.
Prompted again to create accounting.

Unsuccessful - Receipt not updated and the only way to exit is to close the form.

**Comment by hamiltonmark** [comment]
Ran - Receivables Receipt Analyzer - for Receipt #104288 and uploaded to SR.


[Receivables_Receipt_Analyzer_200721.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6848374/Receivables_Receipt_Analyzer_200721.zip)

**Comment by hamiltonmark** [comment]
Latest update from SR Analyst...  7/22/2021 9:45am ET

Hello Mark -

We are working on your issue discussing internally your case.
As soon as we have a new action plan we let you know.

Regards,
Roberto
Oracle Customer Services

**Comment by hamiltonmark** [comment]
SR Analyst is asking for the following.  I will work with Millice on this...

-------------------- ACTION PLAN DETAILS BELOW---------------------

Hello Mark -

We were working on your issue.
We cannot reproduce your issue in our environments.

Please do the following to diagnose further.


ACTION PLAN
-------------------------------------------------------
Having this steps from you:
Receipt #104288.
- Tried to apply to customer #116381.
No invoices listed. Backed out. Tried to remove customer information.
Was prompted to create accounting.
- Created accounting and verified.
Unable to remove customer information and choose another customer.
Prompted again to create accounting.

1) Please reproduce the issue and provide us a receipt analyzer just after the create accounting have been executed for first time (Step 2)
-------------------------------------------------------

Regards,
Roberto
Oracle Customer Services

**Comment by hamiltonmark** [comment]
Millice and I replicated the issue.  I ran Receipt Analyzer.
We replicated it for 2 different Receipts.  Zip file contains Receipt Analyzer for each test.

[INT CAD Receipts ADJS Create Acctg Std Receipts.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6870269/INT.CAD.Receipts.ADJS.Create.Acctg.Std.Receipts.zip)

**Comment by hamiltonmark** [comment]
New 12.2.10 procedure for correcting Unapplied Cash Receipts fixes issue we were having.
My update to SR asking to verify new process...

Roberto
Thanks ... yes - that worked.

I guess we did not realize when you requested to Run Create Accounting - that meant to Post to GL.
The associates that apply run Lockboxes and apply cash do not have permission to Create Accounting and Post to GL.
They must request an Accountant to perform this.

So just to make sure of the new process in 12.2.10... Can you please verify the below?

1. Cash Person runs Lockbox
2. Queries batch of receipts for all Unapplied
3. For each Unapplied Receipt - they would remove the customer number from each receipt and Save and close form.
4. Then request Accounting Dept to run Create Accounting and Post to GL.
5. Cash Person can then go into each Unapplied Receipt, research for correct customer/invoice and apply receipt to correct one.

**Comment by hamiltonmark** [comment]
Confirmation from SR Analyst below.
We will continue to test in INT.

Hello Mark -
Thanks for the update, it is appreciated.
I am glad the issue worked with our directions.
Regarding your question:
Q: So just to make sure of the new process in 12.2.10... Can you please verify the below?
1. Cash Person runs Lockbox
2. Queries batch of receipts for all Unapplied
3. For each Unapplied Receipt - they would remove the customer number from each receipt and Save and close form.
4. Then request Accounting Dept to run Create Accounting and Post to GL.
5. Cash Person can then go into each Unapplied Receipt, research for correct customer/invoice and apply receipt to correct one.

Answer: The steps are right.

Regards,
Roberto

**Comment by hamiltonmark** [comment]
Millice (Cash) and Liz (GL) are doing a one more round of testing to finalize Create Accounting Steps.

5.	Liz will run a weekly scheduled Transfer to GL that will create a journal entry (for those that Millice created accounting for)
6.	Liz will run her normally weekly scheduled – Submit Accounting which includes Revenue Recognition/Create Accounting/Transfer to GL) (for all records not yet processed)
7.	Mike E can then Post both journal entries each week.

Option B
or if we don’t want two journal entries each week, Liz can test running revenue recognition, then running create accounting (without transferring) that will grab all records not yet processed).  Then after that finishes Liz would run transfer to GL and see if it picks up the multiple batches and creates only one JE for Mike to post.

**Comment by hamiltonmark** [comment]
Millice (Cash Person) has approved Steps 1-4.

Liz (Accountant) approved the steps 5-7 below.  No option B that is too many steps for me to submit so she will stay with two submissions and two journal entries each week for each ledger:

1.	After Millice runs a Lockbox – some cash transactions will be unapplied or unidentified.
2.	Upon her correcting the Unapplied/Unidentified – some may pop a message saying to “Create Accounting”.
3.	Millice will run – “Create Final Accounting”
a.	This will create the accounting but not a transfer nor a post to gl (which is the goal)
4.	Millice can proceed with correcting the batch
5.	Liz will run a weekly scheduled Transfer to GL that will create a journal entry (for those that Millice created accounting for)
6.	Liz will run her normally weekly scheduled – Submit Accounting which includes Revenue Recognition/Create Accounting/Transfer to GL) (for all records not yet processed)
7.	Mike E can then Post both journal entries each week.

Option B
or if we don’t want two journal entries each week, I can test running revenue recognition, then running create accounting (without transferring) that will grab all records not yet processed).  Then after that finishes I would run transfer to GL and see if it picks up the multiple batches and creates only one JE for Mike to post.

**Comment by hamiltonmark** [comment]
This ticket can be closed.

**Comment by vinaytalasila** [comment]
Thank you for your update Mark.

**@suhas-deshpande**: Please close the SR now.

Thanks
Vinay
