### ISSUE TITLE
Customer name field is too small

### ISSUE THREAD

**Issue by SherryXLiu** [Fujitsu-America/Fujitsu-Repository#66]
**Describe the bug**

**Instance Name**
Instance:
INT

**Responsibility Name**
Responsibility:
Sales Manager > Opportunity
**Navigation**
Navigation:

**To Reproduce**
![image](https://user-images.githubusercontent.com/85246030/123274115-38bb8980-d4d1-11eb-97be-d991085f938b.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Haqueraz** [comment]
Hi Sherry, 

I have increase the customer name field size in both instance INT/STG. 

![image](https://user-images.githubusercontent.com/84917836/123293304-7de3b980-d4d9-11eb-9298-f8360f616060.png)

Thanks 
Razaul

**Comment by SherryXLiu** [comment]
It looks good to me. I would keep it for users to see if it is ok for them. And I will close it later. Thanks

**Comment by Haqueraz** [comment]
Hi Sherry, 

Please let us know if you get any update from user. 

Thanks 
Razaul

**Comment by SherryXLiu** [comment]
I will meet user tomorrow afternoon, I will update it then. 
Thanks

**Comment by SherryXLiu** [comment]
This can be closed. Thanks for fixing it
