### ISSUE TITLE
Could export file be excel format

### ISSUE THREAD

**Issue by SherryXLiu** [Fujitsu-America/Fujitsu-Repository#67]
**Describe the bug**

**Instance Name**
Instance:
INT, STG

**Responsibility Name**
Responsibility:
Sales Manager > Opportunity
**Navigation**
Navigation:

**To Reproduce**
![image](https://user-images.githubusercontent.com/85246030/123278224-c482e500-d4d4-11eb-8392-09b094b48aa8.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Haqueraz** [comment]
@amitjori look into it.

**Comment by Haqueraz** [comment]
Hi Sherry , 
Please follow the attached documents steps then you will be able to export the files in Excel Formats . 

[Oracle file export in Excel format.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6710932/Oracle.file.export.in.Excel.format.docx)

**Comment by SherryXLiu** [comment]
That's will work. Thanks
