### ISSUE TITLE
Increase Display row number ***SR 3-26319190531***

### ISSUE THREAD

**Issue by SherryXLiu** [Fujitsu-America/Fujitsu-Repository#68]
**Describe the bug**
Currently in Production 12.1.3 can display 750, but in 12.2.10 only allow 100. It is critical to display at least 750.
**Instance Name**
Instance: INT, STG

**Responsibility Name**
Responsibility:
Sales Manager > Opportunity > Create personalize search
**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/85246030/123282535-98696300-d4d8-11eb-91dd-1ef4f35d363f.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

  **Additional context**

**Comment by SherryXLiu** [comment]
12.1.3
![image](https://user-images.githubusercontent.com/85246030/123438821-16903d00-d59f-11eb-836b-d42370e36f28.png)

**Comment by Haqueraz** [comment]
Hi Sherry,

As discussed in daily status Call. Oracle has changed the functionality in 12.2.10 upgrade and it has removed the dropdown list from row count filed and it has provided the text field to enter values between range 1 to 100.

Thanks 
Razaul

**Comment by SherryXLiu** [comment]
Is possible to create SR?

**Comment by Haqueraz** [comment]
we have open the SR for this issue . will keep you updated.

**Comment by Haqueraz** [comment]
Oracle Support comments :

"Row Count" is not a personalizable field due to performance implications of allowing users to display more than 100 records in a single search.
Hence, this is an expected functionality.
Indeed, the following tip shown below the field is hardcoded: "Enter a value between 1 and 100".

**Comment by SherryXLiu** [comment]
In fact it is not Simple Search, it is Personalize view

**Comment by Haqueraz** [comment]
Yes.

**Comment by vinaytalasila** [comment]
Just an update.....Yesterday we uploaded log files to Oracle support for their review. Oracle says that their internal DEV team is working on this. We will follow-up with Oracle support on this tomorrow.

**Comment by vinaytalasila** [comment]
@AkshayK247 : Could you please follow up with Oracle support regarding the SR.

Thanks
Vinay Talasila

**Comment by vinaytalasila** [comment]
Just an update...Till we get an update from Oracle support DEV team, Razaul and Akshay are also investigating this issue internally. When we receive a major updates, we will update this ticket.

Thanks
Vinay Talasila

**Comment by vinaytalasila** [comment]
**@SherryXLiu :** As per today's status meeting update, I am closing this issue and will work on the other two issues (#87 and #77)
