### ISSUE TITLE
INT 12.2.10 AP Payment Clearing not allowing to select more than one invoice to clear****SR 3-26314696811

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#69]
**Describe the bug**

**Instance Name**
Instance:   DPQS2I

**Responsibility Name**
Responsibility:   

**Navigation**
Navigation:   Payments > Entry > Payments >

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
Please see this Screenshots Doc of exact issue.

[INT AP Payment Clearing not showing more than one invoice.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6711260/INT.AP.Payment.Clearing.not.showing.more.than.one.invoice.docx)

**Comment by Haqueraz** [comment]
Hi Mark , 
I replicated the same issue in 12.1.3.
After enter the 1st invoice you will be able to click the "Invoice overview" button. 
When you click on second row then you have to clean the all the records.
 
![image](https://user-images.githubusercontent.com/84917836/123315036-e12d1600-d4f0-11eb-9bfd-d9b483ab28cc.png)

**Comment by hamiltonmark** [comment]
Payment Processor should be allowed to enter a payment for more than one invoice for a vendor.
Once the payment is entered then end user can select a supplier's invoice to be paid - this is working.
But form does not allow end user to enter another supplier's invoice to be paid under the same payment.
List of invoice numbers does not display a second time for the remaining invoices.

![image](https://user-images.githubusercontent.com/85197361/123634241-31a1bd80-d7e8-11eb-9f36-cfcffc1cdc2f.png)

Initially you can see the bottom 2 invoices to select.  These are the test invoices.
But once one is selected... the other cannot be displayed to select on a second line.

![image](https://user-images.githubusercontent.com/85197361/123634832-ed62ed00-d7e8-11eb-8b24-6fbd0f0781e2.png)

**Comment by hamiltonmark** [comment]
It has been reported to me - This issue is now happening in both 12.2.10 and 12.1.3 (Prod and non-Prods).
Is it possible that recent CPU Patch caused this issue?

**Comment by Haqueraz** [comment]
@amitjori @SomuSundaramM Is there is any way to know this issue started after CPU patch applied in production. 

Is this patch applied in 12.2.10?

**Comment by amitjori** [comment]
Hello Team,

JAN2021 PSU has not been applied in INT12.2.10 instance.

SR has been raised for this issue - SR 3-26314696811 : AP Payment Clearing not allowing to select more than one invoice to clear

Regards,
Amit

**Comment by hamiltonmark** [comment]
SR 3-26314696811 : AP Payment Clearing not allowing to select more than one invoice to clear

Oracle Support is saying the following…

Dear Customer, 

Acknowledging your update. 

Possibly, the supplier invoices are enabled for Pay Alone. Thus, the application is not allowing you to choose the next invoice for payment by the same check. 
This is intended behavior. 

Please verify the reported issue for two invoices which are not enabled for Pay Alone setup (AP_Invoices_All.exclusive_payment_flag). 

Let us know the outcome. 
Regards 
Shyam

It is confirmed these two invoices are set to Pay Alone.
I’ve requested AP to re-test.

![image](https://user-images.githubusercontent.com/85197361/124016435-a6752300-d9b3-11eb-9734-f69ad5767efa.png)

![image](https://user-images.githubusercontent.com/85197361/124016463-ac6b0400-d9b3-11eb-848b-b92896f63170.png)

**Comment by hamiltonmark** [comment]
I've sent the following email onto AP End Users....

Mark P
Unfortunately – CPU patches have been applied to all non-prod and prod instances…
So I do not believe we’ll ever get to the bottom of this.

I’ve written a script showing Suppliers and Supplier Sites where Pay Alone is checked on
And gave the results.  I’ve run it in diff instances.  Script is returning about 50 Suppliers where Pay Alone is ON.

My guess is – CPU Patching may have “fixed” an issue (we were unaware of) where previously Pay Alone on an Invoice
(defaulted from the Supplier) was being ignored but now works after CPU.  Just speculating...

**My suggestion though is ….  Review the List of 50+ Suppliers and in Oracle Supplier Maintenance - check off the Suppliers and Sites that should not be Pay Alone
As to prevent this from happening again.**

Let me know after any cleanup and I can run the script again to show list.

Any ???’s – please lemeno.
Thanks
Mark H

**Comment by hamiltonmark** [comment]
This ticket can be closed.
Thanks
Mark

**Comment by Haqueraz** [comment]
Thank you Mark for confirmation.
