### ISSUE TITLE
INT 12.2.10 AP Positive Pay File is failing – rdf output going to .txt instead of .out

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#70]
**Describe the bug**

**Instance Name**
Instance:

**Responsibility Name**
Responsibility:  PBS US Payment Processor

**Navigation**
Navigation:  Submit Job - PBS Positive Pay Process (US Bank)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
LOG ERROR:

+---------------------------------------------------------------------------+
Business Online: Version : 12.2

Copyright (c) 1998, 2013, Oracle and/or its affiliates. All rights reserved.

PBS_AP_POSPAY_USB_CONC_SH: PBS Positive Pay Process (US Bank)
+---------------------------------------------------------------------------+

Current system time is 24-JUN-2021 15:05:24

+---------------------------------------------------------------------------+

1. OOD: PINGING SBS SERVER to check if host is alive. 
1. RESULT: PINGING SBS SERVER -- SUCCESSFUL. 
2. OOD: CONCSUB JOB GENERATING USB POSITIVE PAY REPORT.
*******************************************
ERROR: USB AP POSITIVE PAY Report File COPY to PBS DB SERVER (RFPRD1) - FAILED(4). 
*******************************************
/dpqs2i/12.2/INT/fs2/EBSapps/appl/xbol/12.0.0/bin/PBS_AP_POSPAY_USB_CONC_SH
Program exited with status 4

**Comment by hamiltonmark** [comment]
1.	Shell Script - $XBOL_TOP/bin/PBS_AP_POSPAY_USB_CONC_SH.prog  - is calling rdf in CONCSUB
CONCSUB $1 SQLAP "PBS US Payment Processor" $3 WAIT=Y CONCURRENT PBS PBS_AP_POSPAY_USB > $TEMPFILE

2.	Report rdf exists…
[apdpqs2i@isbsashebsap4 US]$ hostname
isbsashebsap4
[apdpqs2i@isbsashebsap4 US]$ pwd
/dpqs2i/12.2/INT/fs2/EBSapps/appl/xbol/12.0.0/reports/US
[apdpqs2i@isbsashebsap4 US]$ ls -ltr PBS_AP_POSPAY_USB.rdf
-rwxr-xr-x 1 apdpqs2i dba 217088 Sep 30  2014 PBS_AP_POSPAY_USB.rdf

 

3.	Report is creating output successfully by Shell Script submitting CONCSUB:
CONCSUB $1 SQLAP "PBS US Payment Processor" $3 WAIT=Y CONCURRENT PBS PBS_AP_POSPAY_USB > $TEMPFILE
Below is the output….

[apdpqs2i@isbsashebsap4 out]$ hostname
isbsashebsap4
[apdpqs2i@isbsashebsap4 out]$ pwd
/dpqs2i/applcsf/out
[apdpqs2i@isbsashebsap4 out]$ cd $APPLCSF/$APPLOUT
[apdpqs2i@isbsashebsap4 out]$ pwd
/dpqs2i/applcsf/out
[apdpqs2i@isbsashebsap4 out]$ more o35410391.txt
01182380188066000036754700000162793806242021 AKAMAI TECHNOLOGIES INC
01182380188066000036754800000005680006242021 ARLINGTON INDUSTRIES
01182380188066000036754900001290040006242021 AVNET INC
01182380188066000036755000000008499906242021 B + H FOTO & ELECTRONICS CORP
01182380188066000036755100000004675006242021 BEST COMMERCIAL ENERGY SERVICES INC
01182380188066000036755200000001648306242021 BETTENBAKER CHEVROLET BUICK GMC
01182380188066000036755300003986869406242021 CDK GLOBAL LLC
01182380188066000036755400000004660006242021 COAST TO COAST COMPUTER PRODUCTS
01182380188066000036755500000038171906242021 DATA MEMORY MARKETING INC
01182380188066000036755600000392441906242021 FUJITSU AMERICA INC
01182380188066000036755700000001860006242021 G & L SUPPLY COMPANY
01182380188066000036755800000017381806242021 GABRIEL JORDAN CHEVROLET CADILLAC
01182380188066000036755900000046029006242021 IRON MOUNTAIN INFORMATION MANAGEMENT
01182380188066000036756000000005860606242021 KASPER BUICK GMC INC
01182380188066000036756100000000769906242021 MARCHESE FORD
01182380188066000036756200000006611506242021 MCAFEE LLC
01182380188066000036756300000017720506242021 MICRO CLEAN SERVICES INC
01182380188066000036756400000133480206242021 MIRACLE CLEAN SERVICES
01182380188066000036756500000012740006242021 PLUMBING TECH LLC
01182380188066000036756600000015200006242021 PUROCLEAN OF WESTERN RESERVE
01182380188066000036756700000011500006242021 R B STOUT INC
01182380188066000036756800000004500006242021 RADLEY AUTOMOTIVE GROUP
01182380188066000036756900000160000006242021 REALFLEX APPLICATIONS LLC
01182380188066000036757000000034800906242021 RICOH USA INC
01182380188066000036757100000044796106242021 SHI INTERNATIONAL CORP
01182380188066000036757200000012000006242021 SUBARU OF AMERICA INC
021823801880660000000026000064207307
[apdpqs2i@isbsashebsap4 out]$


4.	Now it tries to get the REQUEST ID from the $TEMPFILE
    
    returnedvalue=$?
    if [ $returnedvalue -eq 0 ] ; then
         REQID=`grep request $TEMPFILE | awk '{ print $3 }'`
         Srcfile="o$REQID.out"  ## This is the output file from Conc Requests

       if [ -f $Srcdir/$Srcfile ] ; then
          echo "3. RESULT: POSITIVE PAY REPORT FILE GENERATED."
          echo "4. OOD: Copying file $Srcdir/$Srcfile "
          echo "4. OOD: TO $Srchost:$destdir/$destfile"
          scp -pqr $Srcdir/$Srcfile  $destuser@$Srchost:$destdir/$destfile


5.	Here is content of $TEMPFILE
[apdpqs2i@isbsashebsap4 tmp]$ more PBS_AP_POSPAY_USB_CONC_SH.prog.23211
Submitted request 35410391 for CONCURRENT PBS PBS_AP_POSPAY_USB

Normal completion

6.	Seems to be failing on this command.  I see the print $3 value below…. Is it the awk command?  Is it available for use?

[apdpqs2i@isbsashebsap4 tmp]$ `grep request PBS_AP_POSPAY_USB_CONC_SH.prog.23211 | awk '{ print $3 }'`
bash: 35410391: command not found...
[apdpqs2i@isbsashebsap4 tmp]$

**Comment by amitjori** [comment]
Hello Mark,

As per oracle doc id 2435024.1 we have changed the APPCPNAM parameter from REQID to REQID.OUT in $CONTEXT_FILE.

Can you please re-test this issue and let us know if this helps?

Regards,
Amit

**Comment by hamiltonmark** [comment]
Positive Pay Process is now working successfully.
See attached docx containing Log and Email.
Thank you for your help on this.

[RE Positive Pay Process failed - Please re-test in INT 12.2.10.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6734228/RE.Positive.Pay.Process.failed.-.Please.re-test.in.INT.12.2.10.docx)

**Comment by hamiltonmark** [comment]
Ok to close ticket.

**Comment by Haqueraz** [comment]
Thank you !
