### ISSUE TITLE
INT 12.2.10 AP Suppliers Report - shows 121,000 Pages of All Suppliers (Active/Inactive) no matter the Params # SR 3-26322628731

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#71]
**Describe the bug**

**Instance Name**
Instance:  dpqs2i

**Responsibility Name**
Responsibility:  PBS US Payables Manager

**Navigation**
Navigation:  Submit Report - Suppliers Report

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
Params:
![image](https://user-images.githubusercontent.com/85197361/123333751-24e34800-d510-11eb-80d8-95554b9a70d7.png)

**Comment by Haqueraz** [comment]
Hi Mark, 

Its look like you ran this report with default parameter values.

Can you run the same report with additional parameter values like supplier type, Supplier Name and date etc.. 

I ran for supplier type 'Company' but didn't get the records. 
I ran for others parament supplier type 'Employee' and Site pay group 'Employee'. - No data found. 

We will look for others scenario.

Thanks 
Razaul

**Comment by hamiltonmark** [comment]
I've run it with these params - Active Suppliers, where last updated from and to a date.
The report is 130 pages long.
It shows user created and last updated on 21-JUN-2021.
This cannot be correct.

![image](https://user-images.githubusercontent.com/85197361/123342989-d7baa280-d51e-11eb-993a-bb86c9a88ecb.png)


[Suppliers_Report_240621.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6712515/Suppliers_Report_240621.txt)


![image](https://user-images.githubusercontent.com/85197361/123342811-7397de80-d51e-11eb-9b7f-464d14824c25.png)

**Comment by hamiltonmark** [comment]
We are finding this end user is doing something that kicks off this job.
She is not submitting it so assuming it is being kicked off by some trigger.
Possibly these are updating the Supplier's Last Update Date?

DQM Serial Sync Index Program (DQM Serial Sync Index Program)

![image](https://user-images.githubusercontent.com/85197361/123345078-439f0a00-d523-11eb-80b0-89268493b8e4.png)

**Comment by hamiltonmark** [comment]
MOS Hit shows...

Why is the DQM Serial Sync Index Program Submitted Automatically? (Doc ID 577388.1)

Why does the "DQM Serial Sync Index Program" get submitted under my user id automatically?

Solution

Setting Data Quality Management (DQM) to Automatic causes this concurrent program DQM Serial Synchronization Index to run automatically in the back ground every time there is a party data create/maintain.

The Automatic setting is the appropriate choice when using the DQM application functionality.

To review the DQM setup, please reference the Oracle Customer Data Librarian Implementation Guide.

The settings for DQM synchronization method are controlled in the responsibility Customers Online Data Librarian or Customers Online Data Librarian Superuser.
Choose the Administration tab > Choose the DQM tab > from the menu in the left side box choose Diagnostics  > Choose Synchronization method > The three radio buttons under DQM Synchronization Method are Automatic, Batch and Disable.

**Comment by Haqueraz** [comment]
Hi Mark ,
Please see our findings below :

We observed that, each time we run the report, same supplier site 56444P is displayed under all suppliers. Supplier – “TINAS TESTING” and  supplier site – “56444P” was created by RADUJKOVICL on 21st Jun for testing.
But somehow, this site is getting displayed under each supplier. 

We are still investigating more and keep you updated.

**Comment by suhas-deshpande** [comment]
@hamiltonmark - 

Hi Mark, I tried running this report for particular supplier and it returns the correct data. I also tried few other combinations and data was returned as expected. Only when we run this report for date range, it is having issues. At the same time, this report is running fine in STG instance. While I am still looking into this issue further, I also suspect there might be some issue related to supplier setup. Can we please verify the setup once again or may be try disabling this supplier and create new one. Meanwhile, I continue to debug further.

**Comment by hamiltonmark** [comment]
Suhas
I submitted the report to list simply - Active Suppliers.  
See attached report showing just the first 10 pages.
The supplier - 3I Infotech shows as the supplier for the first 2000+pages along with Sites from all different other suppliers.
This supplier only has 2 active sites but it shows on 2000+ pages.

Can you verify we have the latest report version?

This report seems to have some issues.

Thanks
Mark

[Suppliers Report 10 pages all the same Supplier.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6735668/Suppliers.Report.10.pages.all.the.same.Supplier.txt)

**Comment by hamiltonmark** [comment]
Suhas
I submitted the report to list - Active Suppliers created or changed in JUN 2021.
Report shows 183 pages.   Way too many.  I was expecting less than 5 suppliers added or changed.
I saved report to a pdf... see below.

[Supplier Report Active Created or Updated in Jun 2021.pdf](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6736299/Supplier.Report.Active.Created.or.Updated.in.Jun.2021.pdf)

**Comment by suhas-deshpande** [comment]
@hamiltonmark  - Hi Mark, From Oracle support, I found that sometimes this report has issues when run for date range parameters. I have raised SR 3-26322628731 and provided them the requested information. Will update you as I hear back from them.

**Comment by suhas-deshpande** [comment]
Oracle support shows that report has some issue when system is upgraded. I have raised SR 3-26322628731 and provided them required details. Will update once I hear back from Oracle.

Thanks,
Suhas

**Comment by ashoksnapfj** [comment]
============== update from oracle --------------------
Regarding your comments given below , I want to clarify one thing -

12.1.x - Patch 30624396:R12.AP.B : TOP ACCOUNT: SUPPLIERS REPORT IS DISPLAYING EVERY SITE FOR EACH SUPPLIER
12.2.x - Patch 30624396:R12.AP.C : TOP ACCOUNT: SUPPLIERS REPORT IS DISPLAYING EVERY SITE FOR EACH SUPPLIER


--- Report is not displaying every site for each supplier for the date range. We have created one test supplier and supplier site for testing and when report is run for the date range, it displays the newly created site under all suppliers (Not only the newly created supplier). Report does not display the correct supplier sites for other suppliers and only displays this newly created site, which is wrong. However, when report is run for any other older supplier ( by giving supplier name as parameter), report returns the correct supplier sites under that supplier and does not report the newly created problematic supplier.

Please let me know if the action plan can still be executed in this scenario. 
============== update from oracle --------------------

**Comment by hamiltonmark** [comment]
Per request in morning mtg ...  Reminder: STG Testing

1.  In STG 12.2.10 - added a new Supplier
Supplier Name: TEST TEST TEST SUPPLIER
Supplier Num: 56444

Ran Supplier Reports twice with diff params.

2.  Here is report with selecting 56444 only.
Results: Looks as expected.

[STG Suppliers_Report_300621 with New Supplier TEST TEST TEST SUPPLIER.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6741918/STG.Suppliers_Report_300621.with.New.Supplier.TEST.TEST.TEST.SUPPLIER.txt)

3.  Here is report with selecting CREATION DATE of 30-JUN-2021
Results:  256 pages of diff suppliers.  Expected just the one supplier created today.

[STGSUP~2.TXT](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6741936/STGSUP.2.TXT)

**Comment by Haqueraz** [comment]
Thank you mark for replicate the issue in Stage. 
This is a bug in report. will update the SR accordingly.

**Comment by suhas-deshpande** [comment]
@amitjori @SomuSundaramM  - Hi Both, Oracle has suggested to apply patch  "30624396:R12.AP.C" for this issue as per the SR number in subject. Can you please do the needful in INT and let me know so that I can test ?

Thanks,
Suhas

**Comment by amitjori** [comment]
Hello Team,

Can this issue be replicated in STG so we can apply the patch first in STG instance.

Else let us know if the patch can be applied directly in INT instance.

Regards,
Amit

**Comment by suhas-deshpande** [comment]
@amitjori - As discussed, you can apply patch in STG first as issue replicated in both instances.

**Comment by amitjori** [comment]
Hi Team,

Patch applied in STG instance, please test the issue now.

![image](https://user-images.githubusercontent.com/85238919/124094545-67dd7800-da48-11eb-98c9-ce3cbcc125c1.png)

Regards,
Amit

**Comment by hamiltonmark** [comment]
Amit
Suppliers Report testing in STG - Looks Good!
Can you please apply patch in INT so I can ask end users to test?
Thanks!
Mark

[STG Suppliers_Report_010721 using LASTUP DATE Results SUCCESS 01JUL2021 POST PATCH.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6748047/STG.Suppliers_Report_010721.using.LASTUP.DATE.Results.SUCCESS.01JUL2021.POST.PATCH.txt)
[STG Suppliers_Report_010721 using CREATION DATE Results ONE SUPPLIER 01JUL2021 POST .txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6748048/STG.Suppliers_Report_010721.using.CREATION.DATE.Results.ONE.SUPPLIER.01JUL2021.POST.txt)

**Comment by amitjori** [comment]
Hi Team,

Patch as been applied in INT instance.

![image](https://user-images.githubusercontent.com/85238919/124240814-a8052f00-db0a-11eb-88ad-14f605239445.png)

Regards,
Amit

**Comment by hamiltonmark** [comment]
Thank you Amit.
I've re-tested Suppliers Report in INT 12.2.10 after patch.
See successful report below.
I will ask end users to re-test.
Thanks to Suhas and Akshay too for all your work!
I will let you know.
Mark

[INT Suppliers_Report_020721 using LASTUP DATE Results SUCCESS 02JUL2021 POST PATCH.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6754442/INT.Suppliers_Report_020721.using.LASTUP.DATE.Results.SUCCESS.02JUL2021.POST.PATCH.txt)

**Comment by hamiltonmark** [comment]
This ticket can be closed
Thanks
Mark

**Comment by suhas-deshpande** [comment]
Thanks Mark for confirmation.
