### ISSUE TITLE
INT All shippable order lines have status of 'Backordered' instead of Awaiting Shipping *** SR 3-26327577311 *** 

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#74]
**Describe the bug**
Every time an order is booked.  The shippable lines go to Backordered when trying to do the Pick Release.

**Instance Name**
Instance: DPQS2I

**Responsibility Name**
Responsibility: PBS US Order Management Senior User

**Navigation**
Navigation: Orders/Returns.../Order Organizer 

**To Reproduce**
1. Search Order Number 939878
2. Click on Open
3. Click on Lines Tab
4. Scroll down to item 265-0199 and scroll right to see the status

**Expected behavior**
If there is Quantity On Hand, line status should be 'Awaiting Shipping'.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TinaGriffin** [comment]
I've found this document which seems to be a direct hit.  It provides a workaround for 12.2.9 but I don't know what the solution is for 12.2.10
SALES ORDER LINE STATUS IS SHOWN AS "BACKORDERED" INSTEAD OF "AWAITING SHIPPING" IN R12.2.9 (Doc ID 2769459.1)

**Comment by Haqueraz** [comment]
Hi Tina, 

We will look this issue and keep you updated.

Thanks 
Razaul

**Comment by Haqueraz** [comment]
Hi Tina, 
I observed that ,supply/demand form not displaying  the available quantity for this item. 
For the testing  I have created Miscellaneous receipt transaction for the same Sub inventory & locator and it has also not display in the supply/demand form.     
Then, we found the issue in subinventories status. when changed to status in 'Active'. Then it is populating on-hand on supply/demand form.

Old Subinventories Status : Active : Available for Netting and Reservations
New Subinventories Status : Active 

Can you please change the subinventories status to active then process the order...

![image](https://user-images.githubusercontent.com/84917836/123713767-bd443a00-d83a-11eb-975c-29c5c88779cc.png)
![image](https://user-images.githubusercontent.com/84917836/123714407-d994a680-d83b-11eb-92b6-38e0a8c9bcb6.png)

Let us know if you have any concern..

Thanks 
Razaul

**Comment by TinaGriffin** [comment]
I checked in INT 12.1.3 and our subinventory is set up the same "Active : Available for Netting and Reservations".  So I wouldn't think this is the issue.  I really feel like we need an SR on this one as it is holding up our testing right now.

**Comment by Haqueraz** [comment]
Ok.. We will open the SR for this issue. 

But meanwhile could you please create a new order for the same item/subinventories/locator in 12.1.3.

**Comment by TinaGriffin** [comment]
Order 936955 has been created in 12.1.3 INT.  After I booked the order, the 265-0199 changed to Awaiting Shipping Lines status as expected.

**Comment by TinaGriffin** [comment]
Do you want me to do the Pick Release or do you want to look at it first?

**Comment by Haqueraz** [comment]
I am looking .. Pick Release not needed now..

**Comment by TinaGriffin** [comment]
I've created an order in INT 12.2.10, order # 939883.  After I booked the order, the 265-0199 changed to Awaiting Shipping Lines status as expected.

**Comment by TinaGriffin** [comment]
So booking the order appears the same in both 12.1.3 and 12.2.10.  It's the picking that backorders it.

**Comment by Haqueraz** [comment]
I have created new order for this item. every thing looking  fine to me. 
This is really strain.. we are raising the SR for this issue. 

![image](https://user-images.githubusercontent.com/84917836/123868545-78310e00-d8f5-11eb-9db5-290454cfc3fe.png)

**Comment by suhas-deshpande** [comment]
I have raised SR 3-26327577311 for this issue.

**Comment by hamiltonmark** [comment]
Yes - below is confirmation that SBS has customized OEOH and OEOL Workflows.
Thanks
Mark


![H_1 OEOH](https://user-images.githubusercontent.com/85197361/123972789-2cc83f80-d989-11eb-982d-7bcbf4af8324.gif)
![L_2 OEOL](https://user-images.githubusercontent.com/85197361/123972854-3782d480-d989-11eb-8295-51a3894e122b.gif)

Here is OEOL broken out...

![L_2_1 SCHEDULE LINE](https://user-images.githubusercontent.com/85197361/123973242-9a746b80-d989-11eb-857d-35cd04639f83.gif)

![L_2_2 CREATE SUPPLY LINE](https://user-images.githubusercontent.com/85197361/123973280-a19b7980-d989-11eb-8cd4-0fcc27b1aac7.gif)

![L_2_3 SHIP LINE MANUAL](https://user-images.githubusercontent.com/85197361/123973290-a6602d80-d989-11eb-9e2b-fce6cf3b407b.gif)

![L_2_4 INSTALL BASE INTERFACE](https://user-images.githubusercontent.com/85197361/123973324-abbd7800-d989-11eb-95ea-7975dacba550.gif)

![L_2_5 INVOICE INTERFACE LINE](https://user-images.githubusercontent.com/85197361/123973363-b37d1c80-d989-11eb-9bbe-59b38da68a53.gif)

**Comment by Haqueraz** [comment]
Thank you Mark for confirmation.

**Comment by suhas-deshpande** [comment]
We have provided the required files to Oracle SR. Waiting for their reply.

**Comment by suhas-deshpande** [comment]
Hi All,

Severity of SR is raised to P1.

**Comment by suhas-deshpande** [comment]
Update -  I downloaded OEOH and OEOL workflows from production and applied in INT with the help of DBA. Retested the issue but still same error. I have not seen any update from Oracle on this SR and escalated it already over call.

**Comment by suhas-deshpande** [comment]
Oracle provided below action plan --
******************************************************************************************************************************
Hi Suhas,

Let's change our approach to this issue.
Please take the following actions to help us isolate the issue.

1) Go to the Release Sales Orders For Picking form and enter the following parameters.

Orders - All
Order Number - 939886
Autocreate Delivery - Yes
Auto Allocate - No
Auto Pick Confirm - No
Submt the pick release job

2) Query the sales order in the Shipping Transaction form.
Verify that the line status had progressed to 'Released to Warehouse'.
Please also scroll over to the right and note the Move Order Number that's generated.

3) Switch responsibility to Inventory and navigate to Move Orders->Transact Move Orders and then select the correct organization.

4) Query the Move Order number that was noted from the Shipping Transaction form.
Select the move order line that appears and then click on the Allocate button.
If there is any error, please take a screen shot and upload it to the SR.
Otherwise, if the allocation completes successfully, please re-select the line and then click on the Transact button.
If any error appears, please take a screen shot and upload it to the SR for further review.
*********************************************************************************************************************************

I executed this and got error while transacting the move order. I had call with SR Owner and explained them issue. SR owner will review the error and will engage Inventory experts as required.

**Comment by hamiltonmark** [comment]
Uploaded xlsx of existing Scheduled Conc Jobs from PPQS1I.

Tina - Please review to see if we are missing a scheduled concurrent job that would need to run to fix this issue.

xlsx is filtered on these responsibilities:

![image](https://user-images.githubusercontent.com/85197361/124288947-be69b580-db1f-11eb-8625-fc81eaada35c.png)


[PPQS1I LIST OF SCHEDULED CONC JOBS AS OF 02JUL2021.xlsx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6755168/PPQS1I.LIST.OF.SCHEDULED.CONC.JOBS.AS.OF.02JUL2021.xlsx)

**Comment by suhas-deshpande** [comment]
@TinaGriffin @hamiltonmark  - Hi Tina, Mark,

As per Oracle action plan, we ran 'Generate All Rules" program. After this, I was able to do pick release successfully. Please see screenshot below. Kindly test and let us know if this is working as expected.

![image](https://user-images.githubusercontent.com/85028593/124299749-503be780-db4d-11eb-8961-df79d2626774.png)

**Comment by TinaGriffin** [comment]
That's great news!  I'll go retest it now.

**Comment by TinaGriffin** [comment]
I have retested with a new order, Order # 939893.  This worked as expected now, the item booked with Awaiting Shipping, the Pick Release worked and changed the status to Picked.  The Ship Confirm worked and changed the status to Shipped.  I will downgrade this one to Medium just until the end user has a chance to test it and confirm the shipping process all works as she expects it and then we will close this one after that.  Thank you very much for you help in resolving this one!  This will allow us to continue testing some processes that were held up.

**Comment by TinaGriffin** [comment]
FYI...that 'Generate All Rules' program is showing in our concurrent manager jobs as On Hold in INT...so it looks like maybe it's something we normally have running in the background but due to the upgrade the jobs were put on hold.

**Comment by hamiltonmark** [comment]
Tina 
Is this the same Job below?
If so - it is scheduled in PROD to run each day at 10:30.

SCHEDULED
--
7/2/2021 10:30
1 DAYS - Apply at START of Prior Run
 7/1/2021 10:30
PBSOPS_INVENTORY
Warehouse Manager
WMSGRULE
Generate all enabled WMS rules

**Comment by TinaGriffin** [comment]
It's called Generate All Rules...run by SYSADMIN.  Request ID 35321712 in INT 12.2.10

**Comment by hamiltonmark** [comment]
ok - here it is in PROD
It shows on hold... but it is really - Pending Scheduled for 10:30 each day

![image](https://user-images.githubusercontent.com/85197361/124325987-aa3fab80-db53-11eb-9761-826d8571801d.png)

**Comment by Haqueraz** [comment]
I observed that many jobs were put on hold after clone and this is one of them.
 
I verified the same job and it were put on hold in 12.1.3 -INT on 04-Jan-2021.

**Comment by TinaGriffin** [comment]
The user testing this has confirmed that it is working now.  This can be closed.

**Comment by suhas-deshpande** [comment]
Thanks Tina for confirmation. Will have this SR closed.
