### ISSUE TITLE
INT 12.2.10 Profile Option - Concurrent: Auto-refresh View Request Timer (secs) – is currently set to Null.

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#75]
**Describe the bug**

**Instance Name**
Instance:  dpqs2i

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
Profile Option - Concurrent: Auto-refresh View Request Timer (secs) – is currently set to Null.
What is best possible setting as to not affect performance?
 
![image](https://user-images.githubusercontent.com/85197361/123837163-84f33900-d8d8-11eb-9489-f1ac8552128a.png)

When the Auto Refresh check box is selected, the form will refresh the list of requests after a specified interval measured in seconds. Use the profile option Concurrent: Auto-refresh View Request Timer (secs) to set this interval.
Important: You can view only those requests to which you have been granted access by an administrator. 

 
![image](https://user-images.githubusercontent.com/85197361/123837089-71e06900-d8d8-11eb-902a-2ffb27d1dbf7.png)


Concurrent: Auto-refresh Functionality Considerations (Doc ID 2454322.1)
Last updated on SEPTEMBER 25, 2019
Applies to: 
Oracle Application Object Library - Version 12.1.3 to 12.1.3 [Release 12.1]
Information in this document applies to any platform.
Symptoms
After changing the system profile option Concurrent: Auto-refresh View Request Timer (secs) at site level to 20 seconds, users are experiencing an issue on all product forms like invoice Workbench, Purchasing and AR forms:
-when user enters data on Form column and if they exceed the 20 seconds limit , the cursor will then highlight the entire field for no particular reason much behaving like the screen is being refreshed.
The solution that worked was to set the system profile to Concurrent: Auto-refresh View Request Timer (secs) to zero from the value of 20.

This is a good short term solution – but turning off intended functionality is not a good long term solution.
One needs to use this new functionality - auto refresh schedule that is workable for the View->Request form and NOT affect other Oracle java forms.
Why would the profile of concurrent auto refresh view request timer interfere with the incremental refreshes on the Payable invoice workbench form? Or the purchasing hierarchy maintenance form?

**Comment by Haqueraz** [comment]
Hi Mark, 
Thank you for sharing the Oracle Notes. 

I have set the Profile Option - Concurrent: Auto-refresh View Request Timer (secs)  at 5 sec in both instance INT/STG.
This is a new profile in 12.2.10 .it does not exists in 12.1.3 instance. 

It is working as expected . Please verify the and let me know if any queries. 
![image](https://user-images.githubusercontent.com/84917836/123843715-d2bb7180-d8d7-11eb-815b-97fa6d0f3f50.png)

Thanks 
Razaul

**Comment by hamiltonmark** [comment]
Thanks Razaul

I am curious to see of it has an effect on performance.  The doc I referenced is from 2019 and it states -
"The solution that worked was to set the system profile to Concurrent: Auto-refresh View Request Timer (secs) to zero from the value of 20."

Unless there has been fixes - if it does have adverse effect - we may need to set it to zero.
We will monitor.

**Comment by Haqueraz** [comment]
Sure Mark, Will monitor the performance issue. 

This profile option only workable for the View->Request form and NOT affect other Oracle java forms.

**Comment by hamiltonmark** [comment]
Thanks Razaul
This ticket can be closed.

**Comment by Haqueraz** [comment]
Ok . Thank you !
