### ISSUE TITLE
INT Remove Sales Snapshot button from Update Customer Form

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#76]
Navigation
sales user>sales dashboard>customers
enter 00926 for Account click go
select guaranty chevrolet
button in upper right corner

![Sales Snapshot](https://user-images.githubusercontent.com/85238444/123976442-24bdcf00-d98c-11eb-8d92-aab378e87905.JPG)

**Comment by lindamrigo** [comment]
Remove Sales Snapshot button

**Comment by Haqueraz** [comment]
Hi Linda, 
We did all OAF personalization in STG instance and planning to import into INT  tonight. 

we will remove the 'Sales Snapshot' button also.

Thanks 
Razaul

**Comment by lindamrigo** [comment]
The button is still in the Stage instance.  User walden/2021YouthSportsNow

**Comment by Haqueraz** [comment]
Yes. will remove from stage also.

**Comment by Haqueraz** [comment]
Hi Linda,
We have removed custom button "Sales Snapshot" from both  INT/STG Instance. 
Please verify the same and let us know if you have any queries.
![image](https://user-images.githubusercontent.com/84917836/124311360-37263d00-db33-11eb-9ce1-d1a226a7e223.png)

Thanks 
Razaul

**Comment by lindamrigo** [comment]
Looks perfect. Thank you
