### ISSUE TITLE
Sales Personalize View issue ***SR 3-26319190531***

### ISSUE THREAD

**Issue by SherryXLiu** [Fujitsu-America/Fujitsu-Repository#77]
**Describe the bug**
Garnett has personalize view on Opportunity that has over 100 records. The view after upgrade (12.2.10) in INT/STG behave different. when click Opportunity link, it show error or blank page as attached

**Instance Name**
Instance: INT/STG

**Responsibility Name**
Responsibility:
PBS US Sales Support Admin
PBS CAN Sales Support Admin
**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**
[Garnett Personalized view issue.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6742064/Garnett.Personalized.view.issue.docx)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Haqueraz** [comment]
Hi Sherry, 
I am able to go on next page after clicking the opportunity link. 

![image](https://user-images.githubusercontent.com/84917836/124002024-e4b21880-d99a-11eb-9f52-88b6aa0bead5.png)
![image](https://user-images.githubusercontent.com/84917836/124002166-04e1d780-d99b-11eb-8929-9ef38855cfce.png)

Can you please asked to user to update the row count (max -100 ) in saved search personalize. 

We got the update from oracle can't go beyond 100. 
 
Thanks 
Razaul

**Comment by SherryXLiu** [comment]
We have tried and she is not able to change the display number. Can you do it?
What browser do you use?

**Comment by Haqueraz** [comment]
I am using Chrome.
Can you please share Garnett user /password then I can try to change display number.

**Comment by Haqueraz** [comment]
Also try to create the new save search and delete the existing one.

**Comment by SherryXLiu** [comment]
So you went to next page is not from her personalize view? I don't have her password. I will let her to provide her password

**Comment by Haqueraz** [comment]
I used my user and sample search opportunity name  2021%,  , can you try from your user then see ,  you also facing same issue.  
This should not be user specific.

**Comment by SherryXLiu** [comment]
I see. It is only her personal view issue

**Comment by Haqueraz** [comment]
We will check when get her user/password.

**Comment by SherryXLiu** [comment]
@Haqueraz Garnett password sent to you by email

**Comment by Haqueraz** [comment]
Hi Sherry, 

I observed that display records over 100 it show blank page when clicking  on any link or button on this page even clicking on Personalize button also .

But , when you go through the dropdown list then search for a customer for less than 100 records  then it allow to go next page.

I am looking alternate way to change  the row count.
 
![image](https://user-images.githubusercontent.com/84917836/124019667-f30a2f80-d9ae-11eb-8e56-9b7cff9ad1e7.png)

**Comment by SherryXLiu** [comment]
I don't have an objection on about go to next page from initial search 2021% list or small list. I can also create a new personal view without issue.
But users have many personalize views and they even save the history views for future using. How to make the views working after upgrade? 
I still hope Oracle can resolve it.
Meanwhile, Can you change existing views row number from 750 to 100? With this way, at least, users can go thought their testing.
Thanks

**Comment by TinaGriffin** [comment]
We had this same issue when we went to Release 12.  I was able to fix the issue then.  I'm attaching a document of screenshots I used at the time so you can see if this is an option again now.

**Comment by Haqueraz** [comment]
[SBSOBS-146 Sales Leads and Oppys view creations need to allow for more than 25 rows.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6748763/SBSOBS-146.Sales.Leads.and.Oppys.view.creations.need.to.allow.for.more.than.25.rows.docx)

**Comment by SherryXLiu** [comment]
Here is what Tina add
![image](https://user-images.githubusercontent.com/85246030/124182471-e5bf7480-da84-11eb-8349-125a4946340a.png)

**Comment by Haqueraz** [comment]
This lookup used for the Dropdown list on Row count field. Now oracle not providing the list on this field.
We asked the question from the Oracle about change the row count for existing saved search.

**Comment by SherryXLiu** [comment]
I believe you. It seems no longer an option.  but it is for issue 68. 
And this issue #77, I try to fix Personal view, do you have a way to reduce user view's row count and so user can use their view even it is only display 100?

**Comment by Haqueraz** [comment]
Oracle solution offered to keep the results under 100 rows.
------------------------------------------------------

Thank you for clarifying the issue.
My recommendation is to recreate those searches in 12.2.10.
Please add additional filters (conditions) in the new searches to keep the results under 100 rows.
For example: One search for open opportunities only, one search for specific countries, etc.
This is not only to avoid performance issues, but also to make them useful to users.

**Comment by SherryXLiu** [comment]
I got this answer for many times.
Now my question is How to make the existing views to be under 100 rows without rebuild them? The upgrade made them unusable. Can it be fixed by the upgrade?

**Comment by Haqueraz** [comment]
Oracle already responded that "Row Count" is not a personalizable field this means can not change the value. so they suggested filtering the search criteria to reduce the count.  

Now I put the same question to the oracle that you asked.

**Comment by SherryXLiu** [comment]
I saw the row count is not changeable. 
Oracle have not answered my question. If The personalize button dese not open next page, where I can do "_filtering the search criteria to reduce the count".  Can anyone show me?
Please see  user's view (acct sample  Coughenourg ).
Thanks

![image](https://user-images.githubusercontent.com/85246030/124320560-1ae1ca80-db4a-11eb-881c-98ce1632f8c0.png)

**Comment by SherryXLiu** [comment]
In fact, I am not sure this issue is related to the row number. For Canadian Mitchell1 Opportunities have less then 100 records, but none of these view can be opened
![image](https://user-images.githubusercontent.com/85246030/124323775-d9541e00-db4f-11eb-88bb-379b0a32d57a.png)

**Comment by SherryXLiu** [comment]
records count
![image](https://user-images.githubusercontent.com/85246030/124324631-4e742300-db51-11eb-97be-d8ab0fde03eb.png)

**Comment by Haqueraz** [comment]
I understand your concern. we are working with oracle they are try to replicate the issue in internal system. 
we will keep you updated.

**Comment by vinaytalasila** [comment]
@AkshayK247 : Could you please follow-up with Oracle support regarding this issue. Could you also append the SR # to this ticket issue description.

Thanks
Vinay Talasila

**Comment by vinaytalasila** [comment]
Just an update...Till we get an update from Oracle support DEV team, Razaul and Akshay are also investigating this issue internally. When we receive a major updates, we will update this ticket.

Thanks
Vinay Talasila

**Comment by vinaytalasila** [comment]
Update...Oracle Support DEV team is still working on this bug. We are looking for a workaround (create new saved search) in the 'Sales User', 'PBS US Sales Support Admin' and 'PBS CAN Sales Support Admin' responsibilities. We tried few options and it did not work so we are also requesting Oracle customer support to provide us the workaround so that we can use till we get a permanent solution.

**Comment by arsidhan** [comment]
Requested files are uploaded to SR. 

-Hanmant

**Comment by AkshayK247** [comment]
Hi Team,

Below are the points for saved search issue:

**Responsibility:** Sales Manager
Notes: 1) It is working in 12.2.10 as same as in 12.1.3
2) No saved search showing from 12.1.3.
3) As a workaround: Create new saved search then we are able to access 'Opportunities'

**Responsibilities:** Sales User, PBS US Sales Support Admin and PBS CAN Sales Support Admin
Notes: 1) Old saved search from 12.1.3 are accessible
2) Created SR regarding the performance issue - if we click on any link/personalized button it shows blank page.
3) Created new saved search then we are able to access 'Opportunities'.(Only working for users that does not have existing saved search from 12.1.3)
4) As old saved searches are having 'default' flag set So it automatically search opportunities on page and then we are not able to create a new saved search.

while Oracle working on this issue we can use Sales Manager responsibility for testing as a workaround.

Regards,
Akshay

**Comment by SherryXLiu** [comment]
@AkshayK247 You may use Pulatie account to test in STG. 
Before execute the deletion, please reset his password (and share it with me) and screen shot the view list (drop down). 
Thanks

**Comment by AkshayK247** [comment]
Hi Sherry,

For User "Pulatie" row count for all its saved search is 100. So Sales User working fine for this user.
I can access the saved search with this user. Can you please give other user.

![image](https://user-images.githubusercontent.com/85236271/128200744-75b03c9d-d5e2-4c52-a6cf-90b5d546ae32.png)

I will send user/pass in separate mail.

Regards,
Akshay

**Comment by SherryXLiu** [comment]
That is Good to know. Then you may test Coughenourg in STG. Thanks

**Comment by AkshayK247** [comment]
Hi Sherry,

I have deleted all saved searches for user "COUGHENOURG" on STAGE 12.2.10.
After that I am able to create/update new Saved search and I am able to open Opportunity and other functionalities on the page.

Can you please test the same on STAGE 12.2.10 and update.

Regards,
Akshay

**Comment by AkshayK247** [comment]
I have check all 25 user's files and 
1. I found only 6 users that have row count greater than 100 and active users.
2. Rest of the user either inactive or having row count less than or equal to 100.
3. There is one user "CALDERWOODD" that have default saved search row count is 100, but also having some Saved Search with row count 250. We should check that user and try to update the saved search manually.

![image](https://user-images.githubusercontent.com/85236271/128211936-b758495d-6601-4d3d-ac96-e29a5c6495c8.png)


Regards,
Akshay

**Comment by AkshayK247** [comment]
Hi Sherry,

I have check the user CALDERWOODD on STAGE 12.2.10 and I was able to update the saved search with row count 250.
I have attached the document for reference and I will share the password for user CALDERWOODD in separate mail.


[Update_saved_search_for_User_CALDERWOODD.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6939481/Update_saved_search_for_User_CALDERWOODD.docx)


Regards,
Akshay

**Comment by SherryXLiu** [comment]
Akshay,
I checked  user CALDERWOODD and it looks good. 
Do you think if an user default count > 100, this way may work as well, e.g. AndersonP ?

**Comment by AkshayK247** [comment]
Hi Sherry,

It will not work. 
For CALDERWOODD user it worked because default row count was <= 100.
but for other users default row count is >100 and that create performance issue on Sales Dashboard page.

**Comment by SherryXLiu** [comment]
Thanks. Can you provide the query?

**Comment by AkshayK247** [comment]
Hi Sherry,

Below are the queries:

1) list all personalizations with below script. :

set serveroutput on;

DECLARE
BEGIN
jdr_utils.listcustomizations(p_document => '/oracle/apps/asn/opportunity/webui/OpptyUwqPG');
END;

2) Customer can printDocument to see the contents of each personalization :
Below one is a sample.

set serveroutput on;
exec
jdr_utils.printdocument('/oracle/apps/asn/opportunity/webui/customizations/user/1003728/OpptyUwqPG');

3) Once we identify which one is having more than 100 rows we can delete it using below script:
****NOTE:  This query will delete the all saved search for user, So be careful to use.****
set serveroutput on;
BEGIN
jdr_utils.deletedocument('/oracle/apps/asn/opportunity/webui/customizations/user/1003728/OpptyUwqPG');
END;



Regards,
Akshay

**Comment by SherryXLiu** [comment]
Thanks. 
Please provide Sales users a document to make changes for their personalize views and fix the page loading performance issue.

**Comment by AkshayK247** [comment]
@SherryXLiu 
Can You provide the password for user COUGHENOURG for 12.1.3 or I can reset it?
So that I can provide document for the same.

**Comment by SherryXLiu** [comment]
Which instance?

**Comment by vinaytalasila** [comment]
Hi Sherry,

It is INT 12.1.3 instance.

Thanks
Vinay

**Comment by SherryXLiu** [comment]
I told her and you may reset her password in  INT 12.1.3 instance

**Comment by AkshayK247** [comment]
Hi Sherry,

Please find attached document to update Saved search on INT 12.1.3
I will share the reset password for user COUGHENOURG in separate mail.

[Update_Saved_Search_on_INT_12_1_3.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6954630/Update_Saved_Search_on_INT_12_1_3.docx)


Regards,
Akshay

**Comment by vinaytalasila** [comment]
Sherry,

Please find the attached saved search list.

[Saved_Search_details_for_User.xlsx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6955411/Saved_Search_details_for_User.xlsx)

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Sherry,

Just an update....I have called Oracle global customer support and escalated the SR to get updates from the Development team.

Thanks
Vinay

**Comment by SherryXLiu** [comment]
I have just tried and cannot go to next page
![image](https://user-images.githubusercontent.com/85246030/129945918-eb4cf1f5-754a-4732-9c5d-090a417e48c4.png)

**Comment by AkshayK247** [comment]
Hi Sherry,

It will not go to next page. It is loading the next records on the same page.

You have to scroll down to the last record and it will load next rows.
Please go through the attached document for details.

[Load_next_records_12_2_10.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7012250/Load_next_records_12_2_10.docx)


Regards,
Akshay

**Comment by vinaytalasila** [comment]
DBA Team - Garnett went in and changed all 2022, 2021, 2020 opportunity lists to 100 rows in **Prod 12.1.3** on Friday, August 20, 2021 3:31 PM. So, could you please let us know when the **new 12.2.10 instance** is ready so that they can test this in that instance and make sure that it works there.

Just an update...Today Oracle support requested information from 12.1.3 instance and Akshay replied to them. Waiting for the next updates from them.

Thanks
Vinay

**Comment by amitjori** [comment]
Hi Vinay,

We will update once the upgrade is compete on new server.

Regards,
Amit

**Comment by vinaytalasila** [comment]
Sherry,

Please find attached bug's that are raised by Oracle support for our issue. 
[Bug 33084391.pdf](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7129673/Bug.33084391.pdf)
[Bug 33300391.pdf](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7129676/Bug.33300391.pdf)

Just an update from Oracle Support: We are in constant touch with the development to prioritize the issue. The base bug raised to the Oracle Applications Framework is escalated and the development is working on the same.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Sherry,

Just an update...**Oracle Applications Framework** Development team is waiting for an information from **Oracle Sales** Development team. I did follow up with Oracle Support regarding the updates.

Thanks
Vinay

**Comment by AkshayK247** [comment]
Hi Sherry,

Today, Oracle provided one action plan to update the Row count through command line Export/Import.
I have updated the row count for users on INT 12.2.10. Please verify the same.

Please check for below users on INT 12.2.10:

![asn](https://user-images.githubusercontent.com/85236271/133419875-a75a6a04-d2de-4eb3-8b28-d9ba1901b7f1.png)


Regards,
Akshay

**Comment by vinaytalasila** [comment]
Sherry,

Could you please review Akshay's last comments and update this ticket. Can we have a Teams meeting at 11:00 AM CDT today so that we can explain you the solution that was provided by Oracle for this issue. If you are not having any further concerns then we can close this ticket as well after our meeting.

Thanks
Vinay

**Comment by SherryXLiu** [comment]
We can meet in 11am today

**Comment by vinaytalasila** [comment]
Sherry,

Thank you for your update. I have scheduled a Teams meeting at 11:00 AM EDT today to go over through the latest update by Oracle support.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Sherry,

Thank you for attending the Teams meeting today. Below are the meeting minutes.
1) Explained the solution that was provided by Oracle support to Sherry.
2) After Go-Live, from Production 12.2.10 instance DBA team will download saved searches of 6 users.
3) Akshay will upload the migration document to this ticket and he will mention step by step instructions.
4) Sherry will refer to that migration document and use that when any of the 6 users need that solution to update the default saved search value from 250 to 100.
5) Akshay will downgrade the SR to Sev-3 and keep it open till 10/01/2021.

Thanks
Vinay

**Comment by SherryXLiu** [comment]
Send email to business user leader
![image](https://user-images.githubusercontent.com/85246030/133678659-19579c17-a35b-49aa-b643-a16369cea820.png)

**Comment by SherryXLiu** [comment]
Vinay,
Please provide the execution document of the process. Thanks.

**Comment by vinaytalasila** [comment]
Sherry,

As mentioned earlier in the above comments (meeting minutes), Akshay will work on that document and he will upload to this issue tomorrow.

Thanks
Vinay

**Comment by SherryXLiu** [comment]
Thanks. No rush. It can be next week

**Comment by AkshayK247** [comment]
Hi Sherry,

Please find attached document to Update Personalized View.

[Update Personalized Views - Migration steps.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7186491/Update.Personalized.Views.-.Migration.steps.docx)


Regards,
Akshay

**Comment by vinaytalasila** [comment]
Sherry,

Could you please review the the 'Update Personalized Views - Migration steps.docx' document that was attached by Akshay yesterday and let us know if that looks good or do you have any questions?

If everything looks good then please save that document in your shared folders for future reference and can we 'Close' this ticket.

Thanks
Vinay

**Comment by SherryXLiu** [comment]
It looks good. Thanks
