### ISSUE TITLE
ERROR FRM-40010 under opportunity

### ISSUE THREAD

**Issue by SherryXLiu** [Fujitsu-America/Fujitsu-Repository#78]
**Describe the bug**
Login as BORCHARDT a few forms cannot open. please see attached file
**Instance Name**
Instance:
INT/STG
**Responsibility Name**
Responsibility:
PBS US Auto Sales Manager
**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
[Sales Manager Issue.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6742158/Sales.Manager.Issue.docx)

**Additional context**

**Comment by Haqueraz** [comment]
Hi @amitjori 
Please check why many folder is missing in  $AS_TOP including forms folder. 

![image](https://user-images.githubusercontent.com/84917836/123997425-0066f000-d996-11eb-84b3-f21f802598d8.png)

Thanks 
Razaul

**Comment by amitjori** [comment]
Hello Razaul,

I compared this with existing 12.1.3 production the directory structure is same , below is the screen shot.

![image](https://user-images.githubusercontent.com/85238919/124106081-69606d80-da53-11eb-9ddb-9b62092c36f1.png)



Regards,
Amit

**Comment by SherryXLiu** [comment]
I have checked 12.1.3 the forms have same error. He must not use it and we can let it go.
