### ISSUE TITLE
What make it different?

### ISSUE THREAD

**Issue by SherryXLiu** [Fujitsu-America/Fujitsu-Repository#79]
**Describe the bug**
Why Sales Responsibility Sales Manager under my account LIUS is complete different from BORCHARDT

**Instance Name**
Instance:
INT
**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/85246030/123991262-8f750780-d998-11eb-8a46-841db7bd34a8.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Haqueraz** [comment]
Hi Sherry, 
We have same responsibility name 'Sales Manger ' under many Application.

your user have 'Sales Manager' responsibility  which are in under 'Sales' Application and BORCHARDT have same responsibility which are in under 'Sales Foundation'.


![image](https://user-images.githubusercontent.com/84917836/123998935-951e1d80-d997-11eb-8264-22ed18ae8386.png)
![image](https://user-images.githubusercontent.com/84917836/123999028-b0892880-d997-11eb-81f7-8d6c3d44b229.png)

**Comment by SherryXLiu** [comment]
That makes sense. Thanks
