### ISSUE TITLE
INT PBS Sales Reports - SBS IB To SVC Extract - runs for over 2 hours

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#81]
INT 12.2.10 PBS Sales Reports - SBS IB To SVC Extract - runs for over 2 hours. In 12.1.3 it runs for 3 minutes
responsibility - PBS Sales Reports
single request
SBS IB To SVC Extract 
No parameters

**Comment by Haqueraz** [comment]
Program main query running from long time looks like a performance issue.
We are Tuning the query performance.

**Comment by Haqueraz** [comment]
Hi Linda, 
We have fixed the performance issue. Please check now. 
![image](https://user-images.githubusercontent.com/84917836/124195032-350aa280-da8f-11eb-8700-44d37268932b.png)

Thanks 
Razaul

**Comment by lindamrigo** [comment]
extract running under 3 minutes now
