### ISSUE TITLE
Territory Manager upload exported file back to Oracle failed

### ISSUE THREAD

**Issue by SherryXLiu** [Fujitsu-America/Fujitsu-Repository#82]
**Describe the bug**
After issue 64 resolved, we are able to download a Territory to excel, but not able to upload same file back
**Instance Name**
Instance: INT

**Responsibility Name**
Responsibility:
![image](https://user-images.githubusercontent.com/85246030/124274496-57440500-db0f-11eb-887c-2483d408a3ca.png)

**Navigation**
Navigation:
Same as issue 64

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/85246030/124274761-a5f19f00-db0f-11eb-964b-264eb156a073.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SherryXLiu** [comment]
Normally we should see below before upload the file back
![image](https://user-images.githubusercontent.com/85246030/124275045-fe28a100-db0f-11eb-8882-910b80591b54.png)

**Comment by SherryXLiu** [comment]
Christel is on vacation, she will be back on Tuesday. About Excel version, here is she told me
![image](https://user-images.githubusercontent.com/85246030/124313487-ed435400-db3e-11eb-87cd-4e6269d2b905.png)

**Comment by TinaGriffin** [comment]
I have found a similar sounding document on MOS "WebADI Create Document Process/Activity Hangs When Attempting To Create Document With: A system error has occurred (Doc ID 459536.1)"  

It says to check this internet options setting...worth a try to see how the users is set:
Internet Options / Security Setting/ Scripting / Allow Status Bar Updates via Script set to Enabled.

**Comment by SherryXLiu** [comment]
@TinaGriffin It seems only for Internet Explore, now we are in Edge

**Comment by TinaGriffin** [comment]
Just because the note is for IE, doesn't mean the Internet Options wouldn't still need to be reviewed.

**Comment by SherryXLiu** [comment]
![image](https://user-images.githubusercontent.com/85246030/124658247-880a9e00-de71-11eb-9157-845dc7fa09cb.png)

**Comment by vinaytalasila** [comment]
Just an update...Amit will check whether we can install 'Professional Plus 2016' on Snap-On's jump server so that we can test it. If we face any issues or approval's to install then we will have a working session with the users and look into the setups.

Thanks
Vinay Talasila

**Comment by vinaytalasila** [comment]
Just an update...Linda has scheduled a meeting tomorrow (7/9/2021) between 10:30 AM EDT to 11:30 AM EDT with Randy, Debbie, Amit and me.

Amit and I will review the excel and browser setting between Randy and Debbie during that session and provide the solution for this issue.

Thanks
Vinay Talasila

**Comment by SherryXLiu** [comment]
@vinaytalasilaCould I send you a zoom invitation? Christel is out this morning, I can schedule a meeting this afternoon.

**Comment by SherryXLiu** [comment]
@vinaytalasila Sent you invitation ( 1:30PM EST) . Let me know if you want change the time. Thanks

**Comment by vinaytalasila** [comment]
**@SherryXLiu:** I am available at 1:30 PM EDT today. I will join the meeting.

**Comment by vinaytalasila** [comment]
Just an update...Today Christel, Sherry and I had a web meeting. In Edge browser, added INT 12.2.10 instance URL in the Settings-> Cookies and site permissions -> Site Permissions -> Pop-Ups and redirects in both Christel and Sherry's PC's. 

Christel is having Excel Professional Plus 2016 and Sherry is having Excel Professional Plus 2013. Compared the excel setups between the two versions. Sherry was able to upload (but the data has a validation error) but Christel is still having the issue. I will investigate whether any other setups needs to be done with reference to Excel Professional Plus 2016. I will keep keep you posted.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
**@amitjori:** Is it possible to install Office Professional 2016 **demo version** in the Snap-On jump server. I found a document **Microsoft Office Integration with Oracle E-Business Suite 11i and R12 (Doc ID 1077728.1)** which I would like to try first from our end before requesting SBS end users for a web meeting.

**@lindamrigo:** Could you please **cancel** tomorrow's meeting with Debbie and Randy. If you are using Office Professional Plus 2016 then I would like to try few options in your PC tomorrow at 11:00 AM EDT. 

Thanks
Vinay

**Comment by vinaytalasila** [comment]
As per today's status meeting, I am closing this issue. 

We will continue to work through another issue #50
