### ISSUE TITLE
INT 12.2.10 - Cannot Close Period JUN21

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#83]
**Describe the bug**

**Instance Name**
Instance:   dpqs2i

**Responsibility Name**
Responsibility: PBS US General Ledger

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
Period JUN21 could not be closed even thought there are no unposted items on the Unposted items report.


![image](https://user-images.githubusercontent.com/85197361/124633662-803c0100-de53-11eb-865e-2a5d829d514b.png)

![image](https://user-images.githubusercontent.com/85197361/124633800-a6fa3780-de53-11eb-88fc-c6e49c4a8550.png)

**Comment by hamiltonmark** [comment]
Email from end user (Liz)...

Sorry I got it to close.  I transferred to GL again like the message said and it picked up more items.

**Comment by hamiltonmark** [comment]
This ticket can be closed.

**Comment by Haqueraz** [comment]
Thank you Mark for confirmation.
