### ISSUE TITLE
INT Custom Trigger used for Shipping to Third Party Vendor is Inactive 

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#84]
**Describe the bug**
We use a third party vendor to drop ship inventory for us.  Years ago a custom trigger was created that would insert into a staging table the data needed to be sent to the vendor when running the  "PBS Supplier Drop Ship Export" program is run.  I have researched this all day due to the fact that the tester had told me this is not working.  I finally found what I believe is the issue.  The trigger is not Enabled.  You can compare the trigger to 12.1.3 INT to see it's enabled there.  The name of the trigger is "PBS_WSH_DELIVERY_ASSIGN_AI".

**Instance Name**
Instance: INT

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TinaGriffin** [comment]
FYI...it is enabled in 12.2.10 STG.

**Comment by Haqueraz** [comment]
Hi Tina, 
We had disabled this trigger during the investigation of Backorder issue. 

I have enabled this trigger Now. Thank you for heads-up

Thanks 
Razaul

**Comment by TinaGriffin** [comment]
The user created a new order and tried this again using the US org this time and it still did not work.

**Comment by TinaGriffin** [comment]
I do see data in the table the trigger inserts into from the past week for user "FAI-SDESHPANDE".  So it was working it appears as of 7/1/21...not sure what date it was disabled.

**Comment by TinaGriffin** [comment]
I tested this in 12.2.10 STG and it worked there.  I started up Generate All Rules that was inactivated so it will run in the background thinking maybe that would fix it...but I retested in INT and it still doesn't work. The trigger is still not inserting the data into the table.

**Comment by Haqueraz** [comment]
Hi Tina, 

I created new order 939900 and able to see the records in  table PBS_SH_POP_THRDPRTY_SHIP_O_STG.
![image](https://user-images.githubusercontent.com/84917836/124821875-d92f9600-df34-11eb-96f6-90fc013c3bbe.png)

**Comment by TinaGriffin** [comment]
I just entered order 939899 this afternoon and it's not there

**Comment by TinaGriffin** [comment]
In STG the order that worked is 939883.

**Comment by TinaGriffin** [comment]
I see you just copied my order and it's in the table...939901.  Are you running pick release and then ship confirm?  For this process to third party we don't run ship confirm.  The record should flow to the table after pick release.  Also, when doing pick release, choose Avnet instead of APN for the rule.

**Comment by Haqueraz** [comment]
In INT triggers is working as expected . 

created a new order 939901 by copy  939899

**Comment by TinaGriffin** [comment]
I see you just copied my order and it's in the table...939901. Are you running pick release and then ship confirm? For this process to third party we don't run ship confirm. The record should flow to the table after pick release. Also, when doing pick release, choose Avnet instead of APN for the rule.

**Comment by Haqueraz** [comment]
I did below steps:
 
- Copy the Order 
- Save/Book order 
- Release sales Order  
![image](https://user-images.githubusercontent.com/84917836/124825202-eea6bf00-df38-11eb-84fd-e75e553a8a69.png).

**Comment by TinaGriffin** [comment]
Ok, that's the right steps except change the Based on Rule to Avnet.

**Comment by Haqueraz** [comment]
Worked  for Based on Rule to Avnet. 
New order : 939902 
![image](https://user-images.githubusercontent.com/84917836/124827139-5100bf00-df3b-11eb-99cc-a2f02c2a5940.png)
![image](https://user-images.githubusercontent.com/84917836/124827346-8e654c80-df3b-11eb-99d7-0571f6d88a98.png)

**Comment by TinaGriffin** [comment]
Lol...well I guess you're going to have to come and work for us to enter our orders.  It's not working for me or Debbie Roberts.  Username ROBERTS. Can you try it with my username, GRIFFINT. I'll send you my pwd.

**Comment by TinaGriffin** [comment]
can you send me your email address

**Comment by Haqueraz** [comment]
Razaul.Haque@fujitsu.com

**Comment by TinaGriffin** [comment]
I see the order in the table with my user_id.  I don't understand why her and I can't get it to work.

**Comment by vinaytalasila** [comment]
As per today's issues status meeting update, I am closing this issue.
