### ISSUE TITLE
INT 12.2.10 iPay Autocreate Remittances not being created after Autocreate Receipts **SR 3-26399695621 : IBY iPay Autocreate Receipts failing when testing

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#85]
**Describe the bug**

**Instance Name**
Instance:  dpqs2i

**Responsibility Name**
Responsibility:  PBS US Receivables Cash Application

**Navigation**
Navigation:  See Word Doc with info

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
See Word Doc for Screenshots and explanation of issue...

[INT 12.2.10 AUTOCREATE REMITTANCES NOT BEING CREATED.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6779409/INT.12.2.10.AUTOCREATE.REMITTANCES.NOT.BEING.CREATED.docx)

**Comment by vinaytalasila** [comment]
Mark,

We will look into this and keep you posted.

Thanks
Vinay Talasila

**Comment by hamiltonmark** [comment]
After opening up the batch of receipts - I noticed none of the receipts were assigned Receipt Numbers.
When Create AutoReceipts was run the parameter APPROVE was Yes... but looks like they need approved.
Wondering if the Approve Parameter is working.

![image](https://user-images.githubusercontent.com/85197361/124838201-5cacaf80-df54-11eb-9b93-8bdc4a639001.png)

**Comment by vinaytalasila** [comment]
Mark,

Looked into this. Please find attached file for the details. 
[#85-Details.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6781259/85-Details.docx)

Could you please review and and check whether the action plans works.

If action plan doesn't work then I will check whether there is any bug in the program in 12.2.10.

Thanks
Vinay Talasila

**Comment by hamiltonmark** [comment]
Vinay
Thank you for your analysis on this.
Yes - I am finding the same.
End User is running Action Plan as we speak.

In 12.1.3 - we had changed the parameters for the 2 jobs.  Please see doc below.
We will need to do the same for 12.2.10.
Thanks
Mark

[Screenshots of Param Setup Changes for Autocreate Receipts and Remitt.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6784711/Screenshots.of.Param.Setup.Changes.for.Autocreate.Receipts.and.Remitt.docx)

**Comment by hamiltonmark** [comment]
Vinay
Results were not what I expected.
Batch 3371 now only contains one receipt.
Since we did not run this as it should with the correct params... I think we should run another invoicing run for SVCs with Credit Cards... and do the process again.  ok?

![image](https://user-images.githubusercontent.com/85197361/124923706-b8b11b80-dfc8-11eb-8fc4-370354cf0b3f.png)

**Comment by vinaytalasila** [comment]
Just an update...As per today's issues status meeting update, Mark will request the end user to retest the issue with the correct set of parameter values in the program in INT 12.2.10 and update the results.

Thanks
Vinay Talasila

**Comment by hamiltonmark** [comment]
Yes – thanks Vinay
I have asked Billing Person to process a batch of Service Contracts (having credit cards) for invoicing.
This will give test invoices so we can run jobs for Autocreating Receipts and Autocreating Remittances.
Thanks
Mark

**Comment by hamiltonmark** [comment]
Having issues with creating Autoreceipts - failing on CC Authorizations.
Contacted JPMorgan Paymentech.
See below emails.

[Emails to Paymentech on Failing CC Authorizations.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6787129/Emails.to.Paymentech.on.Failing.CC.Authorizations.zip)

**Comment by hamiltonmark** [comment]
Received email from JP Morgan

It looks as though you are directly connected.  Ill add the info to the case.   In about a week or so, a TI will reach out to you directly to start the testing process with you and assist with any questions.   

________________________________________
Bill Cosban l Vice President l Senior Relationship Manager l J.P. Morgan l Wholesale Payments l Corporate Address: 8181 Communications Parkway, Plano, TX 75024 l M: 815.353.6253
william.cosban@jpmorgan.com

**Comment by hamiltonmark** [comment]
In addition to creating a ticket with JPMorgan...
Created SR 3-26399695621 : IBY iPay Autocreate Receipts failing when testing
with Oracle Support.

**Comment by hamiltonmark** [comment]
Diagnostics Apps Check uploaded to SR (Param:  Payments)

[Diagnostics__Apps_Check_090721.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6791369/Diagnostics__Apps_Check_090721.txt)

**Comment by hamiltonmark** [comment]
Doc uploaded to SR...

[Screenshots for SR Testing Credit Card Transactions Failing.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6791866/Screenshots.for.SR.Testing.Credit.Card.Transactions.Failing.docx)

**Comment by vinaytalasila** [comment]
Just an update...There was an issue to upload the 'Diagnostics__Apps_Check_090721.txt' file by Mark in the SR. I renamed the file to 'Diagnostics__Apps_Check_090721-1.txt' and uploaded the info to Oracle support review.

Thanks
Vinay Talasila

**Comment by hamiltonmark** [comment]
Latest update from SR Analyst....

One minute passes between "Reading resp" entry and the timeout error "resp status code:=504":

Mon 12-Jul-2021 08:06:44
Mon 12-Jul-2021 08:07:44

Looks like connectivity to "https://ebsdev1-temp.snaponbusinesssolutions.com:443" from Database is not possible.
Need to engage a network administrator from OMCS (Oracle Managed Cloud Services) to review.
-Pablo. 

ACTION PLAN (What, Why)
-------------------------------------------------------



Thank you for providing the requested information.

Please review my previous research.
The logs show that one minute passes between "Reading resp" entry and the timeout error "resp status code:=504" when trying
to contact your payments servlet through this hostname/port: https://ebsdev1-temp.snaponbusinesssolutions.com:443


Reading Resp: Mon 12-Jul-2021 08:06:44
Timeout error (resp status code:=504): Mon 12-Jul-2021 08:07:44


There are two options to proceed:

1. Check if increasing the "IBY network timeout" setting allows the connection. Currently, the default is 60000 (milliseconds).
Can you please reset profile option "IBY%Network%timeout" to 300000 (5 minutes) and retest?

2. Please specify instance name with the issue so we can engage a network administrator from OMCS (Oracle Managed Cloud Services)
to check whether connectivity from Database to "https://ebsdev1-temp.snaponbusinesssolutions.com:443" is allowed.

3. In order to test the connectivity in a simple way (without creating receipts) you may follow instructions from the following documentation:

313951.1 - Troubleshooting iPayment/Payments connection from Database to Engine
Section III. Testing the settings
Step 2. Testing HTTPS (SSL) connections
Scenario 3
You can execute the script from "Scenario 3" and make sure that connectivity is possible. If you are not getting code "IBY_204704" then this means
that connection is not possible and a network administrator should review.


Regards,
-Pablo.

**Comment by hamiltonmark** [comment]
This test below was working previously... but now failing in INT....


-- Login as Apps (INT) Select to Test Paymentech Connection (INT 12.2.10) 11Jun2021
select utl_http.request('https://ebsdev1-temp.snapbs.com:443/OA_HTML/ibyecapp',null, 'file:/u01/app/oracle/product/12.1.0.2/dbhome_1/appsutil/wallet', null) from dual;
-- It should return... below showing connection is fine..
--<H2>Results</H2>OapfCode: IBY_204704<BR>OapfStatus: 3<BR>OapfCause: <BR>

**Comment by amitjori** [comment]
Hello Mark,

I tested this query in INT 12.2.10 looks to be working as expected, can you share the error message you are facing?

![image](https://user-images.githubusercontent.com/85238919/125471665-3c80c73c-79ab-4be8-b6f1-78fdbbbc21b8.png)

**Comment by hamiltonmark** [comment]
Hi Amit
Sorry - I was testing in the INT 12.1.3...  below is working fine in 12.2.10.

![image](https://user-images.githubusercontent.com/85197361/125472785-4c232f63-13b4-4605-abea-74bea7759d59.png)

**Comment by hamiltonmark** [comment]
Latest email to JPMorgan Tech Support showing Oracle Support's latest findings...

Thanks Anthony

In addition to this ticket with JPMorgan – I’ve entered another ticket with Oracle Support in trying to resolve this failure to test credit card processing.
(Oracle’s SR 3-26399695621 : DPQS2I: IBY iPay Autocreate Receipts failing when testing).

Oracle Support’s latest response:
1.	Your connectivity test shows that the connection to Oracle Payments (blue square) in the graph is fine: 

select utl_http.request('https://ebsdev1-temp.snaponbusinesssolutions.com:443/OA_HTML/ibyecapp',null, 'file:/u01/app/oracle/product/12.1.0.2/dbhome_1/appsutil/wallet', null) from dual; 

This successfully returns the expected result: IBY_204704 

2.	IBY: Network Timeout is currently set to 360000 (6 minutes). We don't see any timeout error in 6 minutes. This proves that the connection to IBY is fine. 

3.	Logs show there is a timeout error exactly in one minute.  This means that this timeout error comes from Paymentech, not from Oracle Payments. In other words, based on the graph, we think that the connection to Paymentech (through Internet) is not allowed.

So – Oracle Support has completed their analysis.   Hoping to resolve this issue and complete UAT soon.
Thanks
Mark Hamilton


[RE Testing Credit Card Transactions Failing.docx  Case  PS 4836798.msg.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6811913/RE.Testing.Credit.Card.Transactions.Failing.docx.Case.PS.4836798.msg.zip)

**Comment by vinaytalasila** [comment]
Mark,

![image](https://user-images.githubusercontent.com/84878630/125849900-ae655abc-cbf0-4d37-8d0d-53c3f62805bb.png)

As per the information in the above screenshot, Oracle customer support is looking for **oacore.log** file from us. Could you please check for that file and upload to the SR.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Google Search shows oracore.log could be on Web Logics Server in 12.2.

Amit/Somu - Can you please check?


![image](https://user-images.githubusercontent.com/85197361/125869108-2f35da9f-6589-4d15-a861-9e64f47cc80b.png)

**Comment by amitjori** [comment]
oacore logfiles from INT 12.2.10 uploaded to the SR

**Comment by hamiltonmark** [comment]
Amit - Compared PPQS1I to DPQS2I 12.2.10.
Can you please change DPQS2I to match?
Thanks
Mark

![image](https://user-images.githubusercontent.com/85197361/126339543-b54823ae-abaf-432b-b187-9485f9723bb4.png)

![image](https://user-images.githubusercontent.com/85197361/126339608-dc01da9d-4f38-4058-a1c2-d8f1c4f1abe8.png)

**Comment by amitjori** [comment]
Hello Mark,

I have corrected the IBY: ECAPP URL profile value in INT 12.2.10 .

As suggested by Oracle can you please advise when can we re-start application services in INT instance? It will take around 10 - 15 minutes to restart the services.

Regards,
Amit

**Comment by hamiltonmark** [comment]
yes - Amit - please restart application services in INT.

**Comment by amitjori** [comment]
Hello Mark,

Application services re-started in INT 12.2.10.

Can you please re-test and confirm?

Regards,
Amit

**Comment by hamiltonmark** [comment]
Amit
This has fixed the issue.
End User Testing can now run successfully:
1.  Create Autoreceipts
2. Create Autoremittances

Unfortunately - it is now erroring on
3.  Create Settlement Batches when trying to call XML Publisher to format the file creation.

I have opened a new ticket for this new issue.

I will give the ok to close this current ticket once we get thru complete testing of the iPayment Process.
Thanks!

**Comment by hamiltonmark** [comment]
Adding email correspondence to Paymentech Implementor for future reference...


[RE Testing Credit Card Transactions Failing.docx  Case  PS 4836798.msg.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6856524/RE.Testing.Credit.Card.Transactions.Failing.docx.Case.PS.4836798.msg.zip)

**Comment by vinaytalasila** [comment]
As per today's status meeting, I am closing this issue.
