### ISSUE TITLE
INT 12.2.10 Create Settlement Batches Failing trying to write file

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#86]
**Describe the bug**

**Instance Name**
Instance:  dpqs2i

**Responsibility Name**
Responsibility:  PBS US Funds Processor

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
When running - Create Settlement Batches - for the Funds Capture/iPayment Process... get the following error...

![image](https://user-images.githubusercontent.com/85197361/124926988-1f840400-dfcc-11eb-8e98-79d3bb5d4115.png)

**Comment by vinaytalasila** [comment]
@ashoksnapfj : Could you please look into this?

**Comment by hamiltonmark** [comment]
Amit emailed me that he...
"...updated the profile option IBY: XML Temp Directory in INT 12.2.10 instance and bounced oacore/apache services in INT 12.2.10.  Could I please re-test?"  

Job completed successfully.  Log File below....
![image](https://user-images.githubusercontent.com/85197361/124943359-6bd64080-dfda-11eb-87b0-3a3dd20f1d7c.png)


+---------------------------------------------------------------------------+
Payments: Version : 12.2

Copyright (c) 1998, 2013, Oracle and/or its affiliates. All rights reserved.

IBY_FC_CREATE_SETTLE_BATCHES: Create Settlement Batches
+---------------------------------------------------------------------------+

Current system time is 08-JUL-2021 10:47:26

+---------------------------------------------------------------------------+

CP main executing runProgram for oracle.apps.iby.scheduler.SchedInitiator
instr_type: CREDITCARD
prog_name: IBY_FC_CREATE_SETTLE_BATCHES
retry_flag: N
batch_name: 
Task Parameter: key: P_PAYMENT_SYSTEM_ID, value: 10022
Task Parameter: key: P_FC_CC_PROFILE_ID_SENTRY, value: X
Task Parameter: key: P_INTERNAL_PAYEE_ID, value: 025771
Task Parameter: key: P_PAYMENT_CHANNEL_CODE, value: CREDIT_CARD
Task Parameter: key: P_INSTRUMENT_TYPE, value: CREDITCARD
Task Parameter: key: P_CONC_PROGRAM_NAME, value: IBY_FC_CREATE_SETTLE_BATCHES
Task Parameter: key: P_CURRENCY_CODE, value: USD
Task Parameter: key: P_PAYMENT_SYSTEM_ACCOUNT_ID, value: 1
Task Parameter: key: P_RETRY_FLAG, value: N
Task Parameter: key: P_FC_CC_PROFILE_ID, value: 2

Processing BATCH CLOSE operations ..

empty batch for profiles  : 2

Finished processing BATCH CLOSE
CP main completed runProgram for oracle.apps.iby.scheduler.SchedInitiator
+---------------------------------------------------------------------------+
Start of log messages from FND_FILE
+---------------------------------------------------------------------------+
+---------------------------------------------------------------------------+
End of log messages from FND_FILE
+---------------------------------------------------------------------------+


+---------------------------------------------------------------------------+
No completion options were requested.

Output file size: 
0
Deleting empty output file.

+---------------------------------------------------------------------------+
Concurrent request completed successfully
Current system time is 08-JUL-2021 10:47:30

+---------------------------------------------------------------------------+

**Comment by vinaytalasila** [comment]
Mark,

Thank you for your update. 

@amitjori : Could you please setup the profile option IBY: XML Temp Directory in STG 12.2.10 and Pre-prod instances as well. Then, we can close this issue.

Thanks
Vinay Talasila

**Comment by amitjori** [comment]
Hi Team,

IBY: XML Temp Directory  profile has been setup to "/tpqs2i/applcsf/tmp" and "/tpqs1i/applcsf/tmp" in STG and PRE-PROD instance respectively.

Regards,
Amit

**Comment by amitjori** [comment]
Hi Team,

IBY: XML Temp Directory profile has been setup to "/tpqs2i/applcsf/tmp" and "/tpqs1i/applcsf/tmp" in STG and PRE-PROD instance respectively.

Regards,
Amit
