### ISSUE TITLE
INT "Update" Personalize no longer work and Older views no longer to see

### ISSUE THREAD

**Issue by SherryXLiu** [Fujitsu-America/Fujitsu-Repository#87]
**Describe the bug**
First I cannot update my view
Then Older views can be found
**Instance Name**
Instance:
INT
**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SherryXLiu** [comment]
![image](https://user-images.githubusercontent.com/85246030/125136976-c86c5500-e0d9-11eb-9cb0-6a69b39b270a.png)

**Comment by vinaytalasila** [comment]
**@AkshayK247:** Could you please look into this and update your findings.

Thanks
Vinay Talasila

**Comment by AkshayK247** [comment]
Hi Sherry,


I have created one saved search on INT and STAGE and I am able to update it.
Responsibility: PBS US Auto Sales Support Admin, Sales Manager
 
![image](https://user-images.githubusercontent.com/85236271/125314286-95b69c80-e325-11eb-8d05-0720f3c4e068.png)


Can you please give me the name of responsibility from which Saved Search are not showing for Garnett?

Regards,
Akshay

**Comment by SherryXLiu** [comment]
@AkshayK247 I have a meeting with Garnett on 11AM. Maybe after 12 PM is too late for you, then we can meet tomorrow. Thanks

**Comment by AkshayK247** [comment]
Hi Sherry,

sure, we will have call tomorrow.

I have check Personalized View on STAGE for user garnett and below are my findings:
1.	From Responsibility Sales User and PBS US Auto Sales Support Admin all older Personalized Views are showing.
![image](https://user-images.githubusercontent.com/85236271/125473107-d09291a7-522c-4082-bb26-071d3a818824.png)

2.	From Responsibility Sales Manager no older Personalized View showing. It is showing only Views created from this responsibility.

![image](https://user-images.githubusercontent.com/85236271/125473207-36e16ddf-f2e9-49be-aecb-c663d0de9dfb.png)

To confirm I have created some test Views from Sales User and Sales Manager Responsibilities and the Personalized Views created from Sales Manager Responsibility are not visible from other responsibilities like Sales User and PBS US Auto Sales Support Admin.
I have also confirmed from 12.1.3 it is working the same way.

Regards,
Akshay

**Comment by SherryXLiu** [comment]
Thanks Akshay. 
I am just out of meeting. do you want we meet now? 
The issue I report is in DEV1. We just checked, it looks like now the views showed, but still with same issue:
Under responsibility PBS SU/CAN Support Admin and Sales User

- Cannot update an opportunity record (add amount, change status, etc.)
- Cannot open an Views other than default view
- Cannot Open personalize view to make any change (update)
- Cannot create a new view
- Cannot create new opportunity or export the list

Under Sales Manager:

After Simple, then save the search still get error
![image](https://user-images.githubusercontent.com/85246030/125485649-bcada558-ffe0-4de6-b220-b8e68e479746.png)

**Comment by SherryXLiu** [comment]
I have tried use Sales User responsibility to create a new views, then I can update it as you found

**Comment by SherryXLiu** [comment]
Above error (save search) has been resolved by Akshay. Thanks.
![image](https://user-images.githubusercontent.com/85246030/125644620-3837ac26-14a7-446b-9221-9917ec19c2a1.png)
