### ISSUE TITLE
INT 12.2.10 Screenshots of Service Contract Main Billing Parameters

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#88]
**Describe the bug**

**Instance Name**
Instance:  dpqs2i

**Responsibility Name**
Responsibility:   PBS US System Administrator

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
For Pre-prod and PROD - please modify these below params on the Concurrent Program Setup.

[Screenshots of Service Contract Main Billing Parameters.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6804294/Screenshots.of.Service.Contract.Main.Billing.Parameters.docx)

**Comment by vinaytalasila** [comment]
Mark,

I have updated the [Programs.xlsx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6804361/Programs.xlsx) file with the program details.

[Screenshots of Service Contract Main Billing Parameters.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6804364/Screenshots.of.Service.Contract.Main.Billing.Parameters.docx)

When DBA team releases the Pre-Prod instance to SBS team, please setup them from your end in that instance and also during Production (Go-Live).

Can I leave this issue open till you complete the setup in Pre-Prod or close it now.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Vinay
This ticket can be closed.
Thanks
Mark
