### ISSUE TITLE
INT 12.2.10 Screenshots of Param Setup Changes for Autocreate Receipts and Remitt

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#89]
**Describe the bug**

**Instance Name**
Instance:  dpqs2i

**Responsibility Name**
Responsibility:  PBS US System Administrator

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
For Pre-Prod and Prod - please execute the below Concurrent Program Changes per docx.


[Screenshots of Param Setup Changes for Autocreate Receipts and Remitt.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6804307/Screenshots.of.Param.Setup.Changes.for.Autocreate.Receipts.and.Remitt.docx)

**Comment by vinaytalasila** [comment]
Mark,

I have updated the **[Programs.xlsx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6804393/Programs.xlsx)** file with the program details.

**[Screenshots of Param Setup Changes for Autocreate Receipts and Remitt.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6804390/Screenshots.of.Param.Setup.Changes.for.Autocreate.Receipts.and.Remitt.docx)**

When DBA team releases the Pre-Prod instance to SBS team, please setup them from your end in that instance and also during Production (Go-Live).

Can I leave this issue open till you complete the setup in Pre-Prod or close it now.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Vinay
This ticket can be closed.
Thanks
Mark
