### ISSUE TITLE
12.2.10 Upgrade Issue for Global Licensing - SR 3-26091295071 : CETA-OCI-N iStore URL error

### ISSUE THREAD

**Issue by vinaytalasila** [Fujitsu-America/Fujitsu-Repository#9]
**Describe the bug**
Unable to access global Licensing page

**Responsibility Name**
N/A

**Navigation**
https://ebstest2.snaponbusinesssolutions.com/OA_HTML/ibeCZzpHome.jsp

**To Reproduce**
1. Go to  - https://ebstest2.snaponbusinesssolutions.com/OA_HTML/ibeCZzpHome.jsp
2. Click on "License Maintenance Form" from drop down
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/85238919/120776563-eb707b80-c513-11eb-9f8b-44b558abd755.png)
![image](https://user-images.githubusercontent.com/85238919/120776587-f0cdc600-c513-11eb-8c46-57cfc4a77493.png)
![image](https://user-images.githubusercontent.com/85238919/120776619-f75c3d80-c513-11eb-9e18-14da3d76803d.png)

.

**Comment by lindamrigo** [comment]
iStore setups are the same in both 12.1.3 dpqs2i and 12.2.10 tpqs2i
![tpqs2i istore profiles](https://user-images.githubusercontent.com/85238444/120663785-55c3e600-c458-11eb-92cc-afb3c7b9617e.JPG)
![dpqs2i istore setups](https://user-images.githubusercontent.com/85238444/120663793-578da980-c458-11eb-8439-fabc382c17df.JPG)

**Comment by amitjori** [comment]
From: Rigo, Linda M <Linda.M.Rigo@snapon.com> 
Sent: Thursday, May 27, 2021 6:11 PM
To: Jori, Amit <Amit.Jori@fujitsu.com>; Muthunarayanan, Somasundaram <Somasundaram.Muthunarayanan@fujitsu.com>
Cc: Griffin, Tina <Tina.Griffin@snapon.com>; Hamilton, Mark W <Mark.W.Hamilton@snapon.com>; Liu, Sherry X <Sherry.X.Liu@snapon.com>
Subject: 12.2.10 Upgrade Issue for Global Licensing

Hi Amit and Somu
When I access Global Licensing and select my site

 
![image](https://user-images.githubusercontent.com/85238919/120776133-6ab17f80-c513-11eb-9d5f-eff99c6fb542.png)

 

I get 
 
![image](https://user-images.githubusercontent.com/85238919/120776175-756c1480-c513-11eb-9d82-0aabb2ccdd29.png)

Thanks
Linda

**Comment by lindamrigo** [comment]
[Product licensing MD 050  Functional Design.pdf](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6665387/Product.licensing.MD.050.Functional.Design.pdf)
[SBS_MD50_LICENSE_RECORD_GENERATOR-8-02-07_v20.pdf](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6665388/SBS_MD50_LICENSE_RECORD_GENERATOR-8-02-07_v20.pdf)
[Global Licensing Doc.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6665389/Global.Licensing.Doc.docx)

**Comment by lindamrigo** [comment]
please check the classpath again. There are differences between 12.2.10 and 12.1.3
Classpath in DPQS2I
[apdpqs2i@sbsashiebsap4 html]$ echo ${CLASSPATH}
/dpqs2i/product/1013/appsutil/jdk/lib/dt.jar:/dpqs2i/product/1013/appsutil/jdk/lib/tools.jar:/dpqs2i/product/1013/appsutil/jdk/jre/lib/rt.jar:/dpqs2i/applmgr/common/java/lib/appsborg.zip:/dpqs2i/product/1012/forms/java:/dpqs2i/product/1012/forms/java/frmall.jar:/dpqs2i/product/1012/jlib/ewt3.jar:/dpqs2i/product/1012/j2ee/OC4J_BI_Forms/applications/formsapp/formsweb/WEB-INF/lib/frmsrv.jar:/dpqs2i/applmgr/common/java/classes
Classpath in TPQS2I
echo ${CLASSPATH}
/tpqs2i/12.2/STG/fs2/EBSapps/comn/util/jdk32/lib/dt.jar:/tpqs2i/12.2/STG/fs2/EBSapps/comn/util/jdk32/lib/tools.jar:/tpqs2i/12.2/STG/fs2/EBSapps/comn/ut      il/jdk32/jre/lib/rt.jar:/tpqs2i/12.2/STG/fs2/EBSapps/comn/shared-libs/ebs-3rdparty/WEB-INF/lib/ebs3rdpartyManifest.jar:/tpqs2i/12.2/STG/fs2/FMW_Home/Oracle_EBS-app1/shared-libs/ebs-fmw/WEB-INF/lib/ebsFMWManifest.jar:/tpqs2i/12.2/STG/fs2/FMW_Home/Oracle_EBS-app1/shared-libs/ebs-appsborg/WEB-INF/lib/ebs      AppsborgManifest.jar:/tpqs2i/12.2/STG/fs2/FMW_Home/oracle_common/modules/oracle.uix_11.1.1/uix2.jar:/tpqs2i/12.2/STG/fs2/EBSapps/comn/java/classes:/tpq      s2i/12.2/STG/fs2/EBSapps/10.1.2/forms/java:/tpqs2i/12.2/STG/fs2/EBSapps/10.1.2/forms/java/frmall.jar:/tpqs2i/12.2/STG/fs2/EBSapps/10.1.2/jlib/ewt3.jar:      /tpqs2i/12.2/STG/fs2/EBSapps/10.1.2/j2ee/OC4J_BI_Forms/applications/formsapp/formsweb/WEB-INF/lib/frmsrv.jar:/tpqs2i/12.2/STG/fs2/EBSapps/comn/shared-libs/ebs-product/WEB-INF/lib/ebsProductManifest.jar
Java/classes is missing in TPQS2I

**Comment by lindamrigo** [comment]
All jsp's are implicitly loading from the classpath as I have documented in Global Licensing Doc

**Comment by lindamrigo** [comment]
current error
![Bad Request Error](https://user-images.githubusercontent.com/85238444/122281376-31d0bd80-ceb8-11eb-8304-c5dc3696c08e.JPG)

**Comment by lindamrigo** [comment]
[ojspCompile.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6670945/ojspCompile.txt)

**Comment by lindamrigo** [comment]
/dpqs2i/applmgr/common/webapps/oacore/html
$ export PATH=$PATH:$FND_TOP/patch/115/bin
$ ojspCompile.pl --compile -s '[PBS_IBE_LMFLicMainForm.jsp]'
logfile set: /dpqs2i/inst/apps/DPQS2I_sbsashiebswb4/logs/appl/rgf/ojsp/ojspc_error.log
starting...(compiling delta)
using 10i internal ojsp ver: 10
synchronizing dependency file:
  enumerating jsps...8155
  parsing jsp...8155
  writing deplist...8155
initializing compilation:
  enumerating jsps...8155
  eliminating children...6076 (-2079)
  searching uncompiled...6041 (1 were stale)
translating and compiling:
  searching untranslated...6041
  translating jsps... 16% complete: 1000/6041 ETA: 55s^C
Quitting...Terminated.

**Comment by SomuSundaramM** [comment]
Hi Linda,

We are now able to successfully get through the below page in Global licensing, Please check from your side and let us know if thiss working as expected.

![image](https://user-images.githubusercontent.com/85238833/122741014-0eb95b80-d274-11eb-9d07-94d1801fb1a9.png)

We've made the changes in oracle_apache.conf file to comment the security.conf as cross referenced from 12.1.3(httpd.conf) Instance.

oracle_apache.conf - Commented the security2.conf
< #include ${ORACLE_INSTANCE}/config/${COMPONENT_TYPE}/${COMPONENT_NAME}/security2.conf

Thank,
Somu

**Comment by lindamrigo** [comment]
HI Somu
I get to that page too now. What was changed?  Functionality is not 100%. The Save button for a Regen is not working.

Linda

**Comment by amitjori** [comment]
Hello Linda,

We commented the below line in 12.2.10 instance in oracle_apache_conf file which is equivalent to httpd.conf file in 12.1.3

oracle_apache.conf - Commented the security2.conf
< #include ${ORACLE_INSTANCE}/config/${COMPONENT_TYPE}/${COMPONENT_NAME}/security2.conf

can you please share the screen shot of the error that you are facing now?

Regards,
Amit

**Comment by lindamrigo** [comment]
These are the jar files that are required to placed in $JAVA_TOP
![jar files](https://user-images.githubusercontent.com/85238444/122815255-3673e800-d2a3-11eb-847f-73869a10aa0b.JPG)

**Comment by lindamrigo** [comment]
Activate Licenses/Deactivate Licenses and Save button  not working

**Comment by lindamrigo** [comment]
Modified the jar file on Stage, ready for WLS bounce

**Comment by amitjori** [comment]
Hello Linda,

can you please re-test ,looks like this is working now.

After fixing the code with driver , we ran adcgnjar and bounced the services today after which this looks like working.

There are no more errors seen in oacore logs.

![image](https://user-images.githubusercontent.com/85238919/123402094-e9d82780-d596-11eb-8585-ea23ae5cd189.png)

Regards,
Amit

**Comment by TinaGriffin** [comment]
The internal url is not working https://ebstest2.snapbs.com

**Comment by TinaGriffin** [comment]
https://ebstest2.snapbs.com/OA_HTML/ibeCZzpHome.jsp

**Comment by TinaGriffin** [comment]
I've retested everything on the public tier. url (snaponbusinesssolutions) and all functionality is working there.  The private tier ...url (snapbs) it is not working.

**Comment by SomuSundaramM** [comment]
Hi Tina,

In Private tier, we missed to do oacore bounce, can we do now to reflect the changes in private tier as well.

ETA 15 mins

Thanks,
Somu

**Comment by amitjori** [comment]
Hello Linda/Tina,

Global Licensing is working on STG internal tier can you please now and confirm?

Regards,
Amit

**Comment by amitjori** [comment]
![image](https://user-images.githubusercontent.com/85238919/123439827-a941d380-d5c1-11eb-913b-660d113578d8.png)

**Comment by lindamrigo** [comment]
It is working on the private tier now

**Comment by amitjori** [comment]
Hi Linda/Team,

Global Licensing issue has been fixed in INT 12.2.10 instance , can you please check from your side and confirm if all looks good?

![image](https://user-images.githubusercontent.com/85238919/123602179-028b4c00-d7e8-11eb-8c49-3b897bc9c337.png)

![image](https://user-images.githubusercontent.com/85238919/123602418-3cf4e900-d7e8-11eb-93bd-2bdb2ef3cfd1.png)

Regards,
Amit

**Comment by lindamrigo** [comment]
Hi Amit
It is working.

Thanks
Linda

**Comment by TinaGriffin** [comment]
I have tested all the functions on both the Private url and Public url for both License Maintenance and Temporary License Maintenance and all functions are working.

**Comment by amitjori** [comment]
[Global Licensing Issue Fix document.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6781565/Global.Licensing.Issue.Fix.document.docx)

**Comment by vinaytalasila** [comment]
Just an update....As per today's issues status meeting update, I will keep this issue open till DBA team releases Pre-Prod instance to SBS team for testing and confirm the results.

**Comment by TinaGriffin** [comment]
I have tested using both the internal (using cust 00926) and external url (using cust 20188) and all of the functions in global licensing are working in Pre-Prod.

**Comment by lindamrigo** [comment]
I have also tested both using cust 87847 and all functions are working

**Comment by vinaytalasila** [comment]
Tina and Linda - Thank you for your updates.

I am closing this issue now.

Thanks
Vinay
