### ISSUE TITLE
INT Items are not flowing to the Installed Base from new orders

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#90]
**Describe the bug**
During the process of the order workflow, if an item is Installed Base Trackeable and the SFM Manager is up then that item should flow to the Install Base.  We have just entered our first test orders and I've noticed the items did not flow to the Installed Base.

**Instance Name**
Instance: DPQS2I

**Responsibility Name**
Responsibility:  SBS View Only Installed Base

**Navigation**
Navigation: Oracle Installed Base

**To Reproduce**
1. Go to Oracle Installed Base
2. In Search option, select drop down of Sales Order Number
3. Enter recent order numbers.  Here are some: 939899, 939897, 939907, 939908, 939906, 939909
4. After entering the order number, select Go

**Expected behavior**
The Installed Base data that flowed from the order should display in the results

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Normally when this has happened in the past it's always been due to the SFM Manager.  (We've had SR's opened for this in the past)  however, I've saved many of those scripts and ran them and the SFM Manager appears to be up.  I also checked to see if any background jobs needed starting.  I don't think these are related to items flowing but I went ahead and started these inactive jobs "Resubmit Interface Process", and "Resubmit Waiting Transactions" (both found under the Oracle Installed Base Admin responsibility).

**Comment by suhas-deshpande** [comment]
Hi Tina,

While looking at Oracle support documnet -  "Understand SFM Managers and How Oracle Installed Base Uses SFM Event Manager Queue Service (Doc ID 1528132.1)" I saw that Oracle has suggested below configuration -

============================================================================== 
     Although SFM Manager can run multi-threads to process transactions, when used by Oracle Installed Base, SFM Event Manager Queue Service can only use thread = 1. 

              You can find out your set up on the number of thread through

                  System Administrator  (R) > Concurrent > Manager > Define > Query up Manager = 'SFM Event Manager Queue Service' > Workshift 

                         In Parameter field you show see 'XDP_DQ_INIT_NUM_THREADS=1' 

                         If this thread is anything > 1, you will need re-set it to 1 in the manager definition form, then go Deactivate and Activate the manager
==============================================================================

However, I could not see this value setup in INT. Can we check please if this is correct?

![image](https://user-images.githubusercontent.com/85028593/125773905-a130cc93-7ce8-4a60-af53-3af646411152.png)

**Comment by suhas-deshpande** [comment]
Ok, I further checked and looks like this setup is correct.

**Comment by suhas-deshpande** [comment]
Hi Tina - Program - "Interface Install base Lines" was not running in INT. After I ran it from responsibility -"Oracle Installed Base Admin', I can now see the records in install base. Please see below screenshot for SO- 939909.

Kindly check and confirm.

![image](https://user-images.githubusercontent.com/85028593/125791328-8fa8c930-aeed-415c-b1d6-ad440e94d94b.png)

**Comment by TinaGriffin** [comment]
I have verified the test orders entered are now in the Installed Base.  (This did not show on the list of programs we had on hold)....was it on hold from the clone...or was it just not running altogether?

**Comment by suhas-deshpande** [comment]
Hi Tina, 

In Oracle EBS versions up to 12.2.4  --> SFM Event Manager Queue Service was being used. If it was up and running data would flow to install base. 

From versions 12.2.5 and above, program 'Interface Installed Base Lines' needs to be run. So we need to schedule this.

**Comment by TinaGriffin** [comment]
Ohhhh...well that is definitely good to know!  We have has several times in the past issues with the SFM Manager.

**Comment by TinaGriffin** [comment]
This can be closed.

**Comment by vinaytalasila** [comment]
Thank you for your update Tina.
