### ISSUE TITLE
INT 12.2.10 IBY CREATE SETTLEMENT BATCHES FAILING during formatting API call to XML Publisher **SR 3-26504481261 : IBY CREATE SETTLEMENT BATCHES FAILING during formatting API call to XML Publish SR 3-26620420758 : VIEW Logs on Create Settlement Batches are displaying Live Credit Card Numbers

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#92]
**Describe the bug**

**Instance Name**
Instance:  DPQS2I

**Responsibility Name**
Responsibility:  FUNDS CAPTURE PROCESS MANAGER

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
Submitted Job - Create Settlement Batches - to create final file to be sent to Paymentech for Credit Card Processing.
Job errors... see log below...

Request ID:  35440553

![image](https://user-images.githubusercontent.com/85197361/126386254-1452fe9c-7550-46f8-a2ba-f50433141039.png)


[Create_Settlement_Batches_200721.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6850823/Create_Settlement_Batches_200721.txt)

**Comment by vinaytalasila** [comment]
**@ashoksnapfj:** Could you please look into this? 

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Helpful Doc - Below document describes iPayment Process.  
We are executing STEP 6.
Second Page of xlsx shows parameters used for Step by Step for Step 6.

[SBS iPayment Process Cheat Sheet Oracle R12 ver 2.5.xlsx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6850837/SBS.iPayment.Process.Cheat.Sheet.Oracle.R12.ver.2.5.xlsx)

**Comment by hamiltonmark** [comment]
ACTION PLAN from SR:

-------------------- ACTION PLAN DETAILS BELOW---------------------

Hi Mark,

The log file shows error -

Exception occured during formatting
oracle.apps.iby.exception.PSException: Error java.lang.ClassNotFoundException when loading class oracle.apps.iby.bep.proc.paymentech.net.PTKSecureFTPPutFunction .

This is a known upgrade issue for 12.2.8 and higher releases, see: Create Settlement Batch Program Is Failing with Error after Upgrade to 12.2.8 ( Doc ID 2582049.1 )


ACTION PLAN (What, Why)
-------------------------------------------------------

To implement the solution, please execute the following steps:

1. Download and review the readme and pre-requisites for Patch 19554624:R12.IBY.C

2. Ensure that you have taken a backup of your system before applying
the recommended patch.

3. Apply the patch in a test environment.

4. Confirm the following file versions:

iby java/bep/proc/paymentech/net PTKSecureFTPPutFunction.java 120.0.12020000.3


5. Retest the issue.

6. Migrate the solution as appropriate to other environments.


Thank you,
Deborah Bourgeois, Oracle Customer Support

**Comment by vinaytalasila** [comment]
**@amitjori @SomuSundaramM @arsidhan:** Could you please review the patch that was mentioned in the above comments by Mark and apply that tonight in INT 12.2.10 instance.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
SR Analyst response...

-------------------- ACTION PLAN DETAILS BELOW---------------------


ACTION PLAN (What, Why)
-------------------------------------------------------
Please continue with the action plan to have the Patch 19554624:R12.IBY.C applied.

This patch includes the $JAVA_TOP/oracle/apps/iby//bep/proc/paymentech/net/PTKSecureFTPPutFunction.java version 120.0.12020000.3

Thank you.

**Comment by hamiltonmark** [comment]
Adding email correspondence to Paymentech Implementor for future reference...

[RE Testing Credit Card Transactions Failing.docx  Case  PS 4836798.msg.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6858381/RE.Testing.Credit.Card.Transactions.Failing.docx.Case.PS.4836798.msg.zip)

**Comment by vinaytalasila** [comment]
**@amitjori:** Could you please apply the **Patch 19554624:R12.IBY.C** tonight in INT 12.2.10 instance.

Thanks
Vinay Talasila

**Comment by amitjori** [comment]
Hello Team,

Patch has been applied in INT instance.

![image](https://user-images.githubusercontent.com/85238919/126615253-49ac8b3e-e9dd-4192-a459-ac89d1bf2b98.png)

Regards,
Amit

**Comment by amitjori** [comment]
File version after applying patch in 12.2.10 INT

/dpqs2i/12.2/INT/fs1/EBSapps/comn/java/classes/oracle/apps/iby//bep/proc/paymentech/net/PTKSecureFTPPutFunction.class:
$Header PTKSecureFTPPutFunction.java 120.0.12020000.3 2014/09/23 07:03:01 sugottum noship $

**Comment by hamiltonmark** [comment]
Thank you
I have requested end user - Millice - to test iPay end to end.
Waiting on her response.

**Comment by hamiltonmark** [comment]
I've updated the SR with the following...

We finally were able to go thru the Funds Capture/iPayment Process without error.

I've uploaded a docx showing the partial display of – Create Settlement Batches – Log.
Log Displaying Credit Card Numbers?
Is this intended functionality? 

[Create Settlement Batches Log showing CCs.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6864296/Create.Settlement.Batches.Log.showing.CCs.docx)

**Comment by hamiltonmark** [comment]
SR Response...

UPDATE
=====
Hello Team
In my research I have found an open issue for displaying credit card numbers in the logging outputs.
I can engage Payments Development team if a fix is required for your business.
Thank You,
Deborah Bourgeois, Oracle Customer Support 

My response ...

Thank you Deborah.
Yes - a fix is definitely required.
The auditors and PCI Compliance Team would definitely have issue
with anyone seeing these credit card numbers.

**Comment by hamiltonmark** [comment]
1.  Still waiting on SR Analyst to give Bug Fix so Credit Cards do not display in Conc Request Log.

2.  Waiting on Ryan Phillips to verify and validate 3 test batches transmitted to Paymentech Test Server
Transmit Date/Time
1.	22-JUL-2021 10:55:18 EDT
2.	22-JUL-2021 13:55:26 EDT
3.	27-JUL-2021 07:08:07  EDT  (Refunds)

Contact Info:   Ryan Phillips | Technical Implementations Analyst II | Chase l Merchant Services l 2118 E Elliot Rd Tempe, AZ 85284 l T: 480.514.3061 l Ryan.Phillips@chasepaymentech.com

**Comment by hamiltonmark** [comment]
Latest update from SR....  "Support is engaging Development"

**Comment by hamiltonmark** [comment]
Response from Ryan Phillips ...

Hi Mark,
I was able to take a look at those 3 files. There were 5 successful deposits and 21 successful deposits in each of the files on 7/22. I’m assuming the original authorizations came through as an online transaction. In the 7/27 file there were 4 successful refunds. Please let me know if you need anything else.
Thank You,
Ryan Phillips | Technical Implementations Analyst II | Chase l Merchant Services l 2118 E Elliot Rd Tempe, AZ 85284 l T: 480.514.3061 l Ryan.Phillips@chasepaymentech.com

Mark's response to Ryan...

Thanks Ryan
Yes – Correct – Authorizations are transacted in the “Automatic Receipts/Remittances” Jobs.

Below are the Settlement and Refund transactions created by the “Create Settlement” Jobs.
Yes – 21 Settlements (Deposits) on 7/22
Yes – 4 Credit (Refunds) on 7/27

Now that we’ve establish successful authorizations and transmissions between our “Test” environments –
Is there anything that needs done in preparation for Go Live between our “Production” environments estimated for Mid-Sept 2021?

Our new Oracle eBusiness “Production” Server will have a new IP Addr but just like our new “Test” Server – the both IP Addrs are Nat’d
So I do not foresee any issue there – Correct?

Any questions - Please let me know.
I just want to make sure all is well for Go Live.
Thanks
Mark

**Comment by hamiltonmark** [comment]
SR Analyst has created another SR for Development ...

SR 3-26620420758 : IBY Logs Displaying Credit Card Numbers

**Comment by hamiltonmark** [comment]
Latest SR Update...

UPDATE
=====

Hello Mark,

I have created a defect with Development that is being tracked in the new SR 3-26620420758 - IBY CSB Logs Displaying Credit Card Numbers

Please monitor SR 3-26620420758 for this updates on the CSB logging issue.

Advise if we can inactivate this SR whereas the original issue reported is now resolved.


Thank You,
Deborah Bourgeois, Oracle Customer Support

**Comment by hamiltonmark** [comment]
Latest update from Ryan Phillips at Paymentech...

![image](https://user-images.githubusercontent.com/85197361/128178731-b09f8b1c-aee2-4016-ae7e-7d6916403b0e.png)

**Comment by hamiltonmark** [comment]
SR Analyst latest update...
UPDATE
=====
Hello Mark,
Oracle Payments Development advises as follows -
The logging is conditional i.e. when it is enabled then the logs/extract will be displayed.

This data/extract is used to send the payment file to the payment system. They will need to see the unmasked credit card number to actually settle the transaction .

If you do not wish to show the extract, you can edit the log file before sharing.

This is as per product functionality.
Thank You,
Oracle Customer Support 



Mark Hamilton's response...

Please let me understand...

1. Credit Card Numbers are encrypted/masked and stored on the customer master.
2. The data extract is encrypted and sent over an encrypted T1 line to Paymentech for security purposes...
but...
the credit card numbers are now displayed in the log file so that anyone that views the log can now get the credit card numbers?

If I am missing something - please let me know.

If not - Auditors (both internal and external) are going to love this one.

**Comment by hamiltonmark** [comment]
SR Analyst asked for the following...

-------------------- ACTION PLAN DETAILS BELOW--------------------
Hi Mark,
Please provide below sql output :
select * from iby_sys_security_options;
Thank You,
Oracle Customer Support 

My response ....
Results of -- select * from iby_sys_security_options;

Uploaded an xlsx with 2 tabs...
one from current PROD 12.1.3
one from upgraded 12.2.10

As you know - The issue of credit cards displaying in log resides in 12.2.10
Thanks
Mark

Added a 3rd tab comparing the 2...

[iby_sys_security_options 10aug2021.xlsx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6961498/iby_sys_security_options.10aug2021.xlsx)

**Comment by hamiltonmark** [comment]
Update from SR Analyst...
-------------------- ACTION PLAN DETAILS BELOW---------------------
Hi Mark,


Development advises as follows -

As part of the extract generation Oracle Payments pulls unencrypted credit card data which is sent to the payment system for settling the transaction.

As far is logging is concerned, we sometimes ask for the extract/logs to investigate the issue at hand.
For this reason code change is not possible, instead please disable logging at site level. Only allow logging on a user level for specific products and for Module specify ap% . This way no iby log gets generated.

You can grant system admin responsibility to only specific users who will have the authority to enable the logging.

To remove the already generated logs, you can simply delete the /tmp/iby.log and /tmp/iby_af.log. These files only get generated when the logging is enabled. Thank you.


Regards,
Oracle Customer Support 

******************************************************************

Mark's response....
Please let me clarify....

When anyone navigates to > View > Requests
Then queries the job - Create Settlement Batches
When they click on - View Log
They can see all the credit card numbers in the log.

We are not talking about iby_logs or any logs where we are trying to diagnose an issue.
These are just one concurrent job - Create Settlement Batches
where all the credit cards are displaying.

Please verify we are speaking about the same.
Thanks
Mark

**Comment by TinaGriffin** [comment]
I don't think they are still understanding what you're asking.  Disabling log at site level will affect too many other programs and is not an appropriate response from Oracle.

**Comment by hamiltonmark** [comment]
Re-emphasized and resent screenshots showing CCs displaying in View Logs.

SR Analyst response:
-------------------- ACTION PLAN DETAILS BELOW---------------------

Hi Mark,

Development advises that the concurrent request logs will also be disabled when logging is disabled at site level plus at user level.
If not, then please provide screenshots from the instance where the logging has been disabled and still concurrent logs are showing the credit card details.
12.2 debug logging and section B for Create Settlement Batches: How to generate Debug Log Files for Oracle Payments Funds Capture R12.2 ( Doc ID 1635161.1 )

Thank You,
Oracle Customer Support 

**************************************************************************************
Mark's response:

Uploaded screenshots of Profile Options - %FND%Debug%
showing all values set to NO for FND: Debug Log Enabled

In addition - showing results of this sql below - showing all values set to NO at any other level for FND Debug...

SELECT VL.USER_PROFILE_OPTION_NAME, V.PROFILE_OPTION_VALUE, V.*
FROM FND_PROFILE_OPTIONS_VL VL
,FND_PROFILE_OPTION_VALUES V
WHERE UPPER(VL.USER_PROFILE_OPTION_NAME) LIKE UPPER ('FND%DEBUG%')
AND V.PROFILE_OPTION_ID(+)=VL.PROFILE_OPTION_ID
order by 1

[Screenshots FND Debug Profile Settings.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6975298/Screenshots.FND.Debug.Profile.Settings.docx)

***************************************************************************************
SR Analyst response...

![image](https://user-images.githubusercontent.com/85197361/129203085-58c2aa49-0c7b-40c1-8d6b-9eb0a39a7147.png)

**Comment by hamiltonmark** [comment]
SR Analyst has requested the following Action Plan.
I've changed the Profile Values and asked Millice to run the iPay Process.
Waiting on her response...

![image](https://user-images.githubusercontent.com/85197361/129559625-62879daa-2b53-4fac-984e-a732c1000a75.png)

**Comment by hamiltonmark** [comment]
SR has been updated with - Screenshots FND Debug Profile Settings after set to null.docx

Screenshots show FND Debug Profile Values set as requested.
In addition - Create Settlement Batches - VIEW LOG - still displaying customer credit cards.

Credit Card Numbers in this docx have been changed to fake numbers to protect customer. 

[Screenshots FND Debug Profile Settings after set to null.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6994666/Screenshots.FND.Debug.Profile.Settings.after.set.to.null.docx)

**Comment by hamiltonmark** [comment]
I've requested SR Analyst to:

![image](https://user-images.githubusercontent.com/85197361/129616629-711118c2-3396-4b99-a243-cf08744bed18.png)

**Comment by hamiltonmark** [comment]
Updated the SR with the following...
In addition - called Support - asked to Escalate to a Duty Manager.
This is the step they recommended prior to raising to a Sev 1.

![image](https://user-images.githubusercontent.com/85197361/130119259-a83540c1-6eeb-4b3f-a769-9e9fa539328e.png)

**Comment by hamiltonmark** [comment]
Lou Reents (Oracle Support Senior Manager) called and left VM.
I called him back.  He asked me for Go Live Date.  I gave him Mid Sept (Week of 9/13).
He is in contact with Development and discussing this CC issue along with the iStore issue.
Below is the SR Update prior to our conversation.

![image](https://user-images.githubusercontent.com/85197361/130134138-ae5639bf-11f2-4433-9ffd-28b46e67720f.png)

**Comment by hamiltonmark** [comment]
![image](https://user-images.githubusercontent.com/85197361/130137437-f69e0cdd-7f57-41ec-9ea1-b946ec38fc7d.png)

**Comment by vinaytalasila** [comment]
Hi Mark,

Just an update and an internal comment.....Looks like Lou Reents supports many of our SR's currently. For the SOA issue, during escalation, I told him that our Go-Live is 09/01/2021. He may be wondering that multiple Go-Live dates are coming from the same customer. 

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Thanks Vinay
Yes - he did mention that... I told him 9/1 was probably for the New Server Build Team where they need everything working for the build but the upgrade cut over date would most likely happen mid Sept.  I told him - any way you look at it - we need it all working ASAP. 

Latest SR Update as of 8/19/2021 4:45pm ET....

![image](https://user-images.githubusercontent.com/85197361/130145216-289d87b8-d435-4b86-91ef-fae46eee0db4.png)

**Comment by vinaytalasila** [comment]
Mark,

Just an update...When we had a call with Oracle support today, I mentioned Lou Reents that this is one of critical issues currently and he says that he will follow-up with the Development team. 

If you don't see an update by today evening then you may follow-up with him from your end.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
SR Analyst update....

-------------------- ACTION PLAN DETAILS BELOW---------------------
Hi Mark,

Development has created a test patch in the uploaded file p33185797_R12.IBY.C_R12_GENERIC.zip. Please apply, bounce the middle tier services, and test.

Advise if this resolves the behavior.

Thank you.
Oracle Global Customer Support 

[p33185797_R12.IBY.C_R12_GENERIC.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7039186/p33185797_R12.IBY.C_R12_GENERIC.zip)

**Comment by vinaytalasila** [comment]
Just an update...**Amit** will apply the test patch p**33185797**_R12.IBY.C_R12_GENERIC.zip in **INT 12.2.10** instance tonight. Then, Mark can test this tomorrow in that instance.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Absolutely – be glad to…

**Comment by amitjori** [comment]
Hello Mark,

Patch has been applied in INT 12.2.10 instance.

SQL> select name from v$database;

NAME
---------
DPQS2I

SQL> !hostname -f
isbsashebsap4.oci.snapbs.com

SQL>  select BUG_NUMBER,CREATION_DATE from ad_bugs where BUG_NUMBER='33185797';

BUG_NUMBER                     CREATION_DATE
------------------------------ ---------------
33185797                       25-AUG-21

Regards,
Amit

**Comment by hamiltonmark** [comment]
Thanks Amit...

Good News – Create Settlement Batches – View LOG – NOT displaying customer credit card numbers in Log after Oracle Development Test Patch applied in INT 12.2.10.  See screenshots below.

I will update SR with news and request next Action Plan.

[Create Settlement Batches after Test Patch in INT.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7046851/Create.Settlement.Batches.after.Test.Patch.in.INT.docx)

**Comment by hamiltonmark** [comment]
Latest SR Update has the official patch...

Hello,

Please go to the My Oracle Support ( http://support.oracle.com/ ) to download
the patch referenced below.

Patch: 33185797 - CREATE SETTLEMENT BATCHES LOG SHOWS CREDIT CARD NUMBERS

Password = acQrlfjw
Platform = Generic Platform
Product = Oracle Payments
Version = R12

Customers are reminded that one-off Oracle Server patches are not
subject to the same rigorous level of testing as done for Oracle
Server patch sets. Customers are encouraged to install and test this
patch in a test environment prior to full production implementation.

This password is valid for 21 days.

Thanks,

Mark

**Comment by vinaytalasila** [comment]
**@amitjori:**  Could you please review the patch that was mentioned in the above comment and apply that in **STG or Pre-Prod 12.2.10** instance tonight so that we can see whether it gets applied successfully or not.

Thanks
Vinay

**Comment by amitjori** [comment]
Hi Vinay,

Patch has been applied in STG 12.2.10 instance.

SQL> select name from v$database;

NAME
---------
TPQS2I

SQL> select bug_number,creation_date,language from ad_bugs where bug_number='33185797';

BUG_NUMBER                     CREATION_DATE   LANG
------------------------------ --------------- ----
33185797                       01-SEP-21       US

Regards,
Amit

**Comment by hamiltonmark** [comment]
Thanks Amit.

Vinay - this ticket can be closed.

**Comment by vinaytalasila** [comment]
Mark will request for language patches (ESA and FRC) to Oracle support.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Updated SR with ...

Will you be releasing other languages?
We usually apply EN, FRC, and ESA language patches.

Please let me know.
Thanks
Mark

**Comment by hamiltonmark** [comment]
Latest SR Update ...

UPDATE
=====

Hello Mark,

This patch does not require translation and is a generic patch. Please continue with your testing on the different environments and we can advise Development if any issues. Thank you.

Regards,
Deborah Bourgeois, Oracle Customer Support

**Comment by vinaytalasila** [comment]
Closing this issue.
