### ISSUE TITLE
PRD Dry Run - ssh sbsintf@oci-ssh-prd.snaponbusinesssolutions.com requiring password 

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#95]
**Describe the bug**

**Instance Name**
Instance:  ppqs1i

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
Initial login asked to save RSA/SSH Key- I answered Yes.... but still requiring a password...

login as: mhamil
mhamil@psbsashebsap1.oci.snapbs.com's password:
Last login: Thu Sep  2 15:07:47 2021 from 172.22.216.7
[mhamil@psbsashebsap1 ~]$ sudo su apppqs1i
[sudo] password for mhamil:
[apppqs1i@psbsashebsap1 mhamil]$ hostname
psbsashebsap1.oci.snapbs.com
[apppqs1i@psbsashebsap1 mhamil]$ whoami
apppqs1i
[apppqs1i@psbsashebsap1 mhamil]$ ssh sbsintf@oci-ssh-prd.snaponbusinesssolutions.com
sbsintf@oci-ssh-prd.snaponbusinesssolutions.com's password:

**Comment by vinaytalasila** [comment]
@SomuSundaramM and @arsidhan: Could you please look into this?

Thanks
Vinay

**Comment by SomuSundaramM** [comment]
Hi Tina,

This has been fixed, we missed to redeploy the services after LB setup. 

Now all the wadl url’s are pointing to ebs-temp.snapbs.com. Please check and confirm

Thanks,
Somu

**Comment by SomuSundaramM** [comment]
Hello Mark/Team,

I’ve attached the public key in email from new prod server, can you please raise a ticket with SBS team to install the keys as we did for INT 12.2.10 

Thanks,
Somu

**Comment by hamiltonmark** [comment]
Public ssh key has been installed and added to authorized keys on the SBS Side.
Successfully logged in without need of password.


[apppqs1i@psbsashebsap1 mhamil]$ ssh sbsintf@oci-ssh-prd.snaponbusinesssolutions.com
Last login: Mon Aug 30 14:52:38 2021 from 172.22.223.202
*************************************************************
*   rich-oodi-01-pv    Oracle On Demand Scripts and Optio   *
*                      Application Server                   *
*                      Production Environment               *
*************************************************************
[sbsintf@rich-oodi-01-pv ~]$

**Comment by hamiltonmark** [comment]
ok to close this ticket
