### ISSUE TITLE
PROD  Dry run 12.2.10 -Concurrent programs log/out files not opening 

### ISSUE THREAD

**Issue by SomuSundaramM** [Fujitsu-America/Fujitsu-Repository#97]
Instance: New PPQS1I during dry run testing

When opening any concurrent programs log file I get this:
An error occurred while attempting to establish an Applications File Server connection with the node FNDFS_SBSASHPEBSAP1. There may be a network configuration problem, or the TNS listener on node FNDFS_SBSASHPEBSAP1 may not be running. Please contact your system administrator.

When opening any concurrent programs output file I get the same:
An error occurred while attempting to establish an Applications File Server connection with the node FNDFS_SBSASHPEBSAP1. There may be a network configuration problem, or the TNS listener on node FNDFS_SBSASHPEBSAP1 may not be running. Please contact your system administrator.

**Comment by SomuSundaramM** [comment]
Hi Tina,

We have copied old log/out file from existing 12.1.3 instance to new 12.2.10 prod instance. 

We will be able to see the log/out files now.

Regards,
Amit

**Comment by TinaGriffin** [comment]
This is working now and can be closed.
