### ISSUE TITLE
Prod Dry run 12.210 - Wadl url's are pointing to hostname instead of LB name

### ISSUE THREAD

**Issue by SomuSundaramM** [Fujitsu-America/Fujitsu-Repository#98]
**Describe the bug**
All the wadl's url are pointing to hostname url, it should be pointing to Load balancer url
**Instance Name**
Instance:New PPQS1I

**Navigation**
Navigation: Integrated SOA gateway -> Search any custom package -> click wadl url under REST tab

**Comment by SomuSundaramM** [comment]
Hi Tina,

This has been fixed, we missed to redeploy the services after LB setup. 

Now all the wadl url’s are pointing to ebs.snapbs.com.

Thanks,
Somu

**Comment by TinaGriffin** [comment]
I've verified these are all fixed now.  This can be closed.
