### ISSUE TITLE
PROD Dry Run 12.2.10 - PBS Account Analysis Report - Post Processing Failed; in addition Log is displaying 2 different jobs

### ISSUE THREAD

**Issue by hamiltonmark** [Fujitsu-America/Fujitsu-Repository#99]
**Describe the bug**

**Instance Name**
Instance:  PPQS1I Dry Run

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamiltonmark** [comment]
In addition to job failing... Log shows an additional Job - Check Periodic Alert

Here is the log...  

+---------------------------------------------------------------------------+
Alert: Version : 12.1

Copyright (c) 1998, 2013, Oracle and/or its affiliates. All rights reserved.

ALECDC: Check Periodic Alert
+---------------------------------------------------------------------------+

Current system time is 04-SEP-2021 01:31:04

+---------------------------------------------------------------------------+

+---------------------------------------------------------------------------+
Start of log messages from FND_FILE
+---------------------------------------------------------------------------+
+---------------------------------------------------------------------------+
End of log messages from FND_FILE
+---------------------------------------------------------------------------+
Successfully resubmitted concurrent program ALECDC with request ID 35935403 to start at 04-SEP-2021 01:45:00 (ROUTINE=AFPSRS)


+---------------------------------------------------------------------------+
No completion options were requested.

Output file size: 
325


Output is not being printed because:
The print option has been disabled for this report.

+---------------------------------------------------------------------------+
Concurrent request completed successfully
Current system time is 04-SEP-2021 01:31:04

+---------------------------------------------------------------------------+
+---------------------------------------------------------------------------+
Subledger Accounting: Version : 12.2

Copyright (c) 1998, 2013, Oracle and/or its affiliates. All rights reserved.

PBS_XLAAARPT: PBS Account Analysis Report
+---------------------------------------------------------------------------+

Current system time is 07-SEP-2021 10:55:10

+---------------------------------------------------------------------------+

CP main executing runProgram for oracle.apps.xdo.oa.cp.JCP4XDODataEngine
XDO Data Engine Version No: 10.1.3.4.2
Resp: 50252
Org ID : 83
Request ID: 35935365
All Parameters: P_RESP_APPLICATION_ID=200:P_LEDGER_ID=2:P_LEDGER=PROQUEST-USD:P_COA_ID=101:P_LEGAL_ENTITY_ID=:P_LEGAL_ENTITY=:P_GL_DATE_FROM="2021/07/04 00:00:00":P_PERIOD_FROM=JUL-21:P_GL_DATE_TO="2021/07/31 00:00:00":P_PERIOD_TO=JUL-21:P_APPLICATION_ID=:P_JE_SOURCE_NAME=:P_BALANCE_TYPE_CODE=A:P_BALANCE_TYPE=Actual:P_DUMMY_BUDGET_VERSION=:P_BUDGET_VERSION_ID=:P_BUDGET_NAME=:P_DUMMY_ENCUMBRANCE_TYPE=:P_ENCUMBRANCE_TYPE_ID=:P_ENCUMBRANCE_TYPE=:P_BALANCE_SIDE_CODE=:P_BALANCE_SIDE=:P_BALANCE_AMOUNT_FROM=:P_BALANCE_AMOUNT_TO=:P_BALANCING_SEGMENT_FROM=:P_BALANCING_SEGMENT_TO=:P_ACCOUNT_SEGMENT_FROM=:P_ACCOUNT_SEGMENT_TO=:P_ACCOUNT_FLEXFIELD_FROM=00.00.000.00000.0000.0000.00:P_ACCOUNT_FLEXFIELD_TO=99.99.999.99999.9999.9999.99:P_INCLUDE_ZERO_AMOUNT_LINES=N:P_INCLUDE_ZERO_AMT_LINES=No:P_INCLUDE_USER_TRX_ID_FLAG=N:P_INCLUDE_USER_TRX_ID=No:P_INCLUDE_TAX_DETAILS_FLAG=N:P_INCLUDE_TAX_DETAILS=No:P_INCLUDE_LE_INFO_FLAG=NONE:P_INCLUDE_LEGAL_ENTITY=None:P_CUSTOM_PARAMETER_1=:P_CUSTOM_PARAMETER_2=:P_CUSTOM_PARAMETER_3=:P_CUSTOM_PARAMETER_4=:P_CUSTOM_PARAMETER_5=:DebugFlag=N:P_INCLUDE_STAT_AMOUNT_LINES=N:P_INCLUDE_STAT_AMT_LINES=No:P_INCLUDE_ACCT_WITH_NO_ACT=N:P_INC_ACCT_WITH_NO_ACT=No:ScalableFlag=N
Data Template Code: PBS_XLAAARPT
Data Template Application Short Name: XLA
Debug Flag: N
{P_ACCOUNT_SEGMENT_FROM=, P_ENCUMBRANCE_TYPE=, P_ACCOUNT_SEGMENT_TO=, P_BALANCE_AMOUNT_FROM=, P_DUMMY_ENCUMBRANCE_TYPE=, P_DUMMY_BUDGET_VERSION=, P_GL_DATE_TO=2021/07/31 00:00:00, P_COA_ID=101, P_BALANCE_TYPE_CODE=A, P_BALANCE_AMOUNT_TO=, P_RESP_APPLICATION_ID=200, P_ENCUMBRANCE_TYPE_ID=, P_JE_SOURCE_NAME=, P_BALANCE_SIDE=, P_CUSTOM_PARAMETER_5=, P_CUSTOM_PARAMETER_4=, P_CUSTOM_PARAMETER_3=, P_CUSTOM_PARAMETER_2=, P_CUSTOM_PARAMETER_1=, P_BALANCE_TYPE=Actual, P_INC_ACCT_WITH_NO_ACT=No, P_INCLUDE_USER_TRX_ID=No, P_ACCOUNT_FLEXFIELD_FROM=00.00.000.00000.0000.0000.00, P_BUDGET_NAME=, P_INCLUDE_STAT_AMT_LINES=No, P_INCLUDE_LE_INFO_FLAG=NONE, P_PERIOD_TO=JUL-21, P_LEGAL_ENTITY_ID=, P_BALANCE_SIDE_CODE=, P_INCLUDE_ACCT_WITH_NO_ACT=N, P_INCLUDE_STAT_AMOUNT_LINES=N, P_BUDGET_VERSION_ID=, P_INCLUDE_LEGAL_ENTITY=None, P_INCLUDE_TAX_DETAILS_FLAG=N, P_BALANCING_SEGMENT_FROM=, P_INCLUDE_ZERO_AMT_LINES=No, P_LEDGER_ID=2, P_PERIOD_FROM=JUL-21, P_APPLICATION_ID=, P_INCLUDE_USER_TRX_ID_FLAG=N, P_BALANCING_SEGMENT_TO=, P_LEGAL_ENTITY=, P_INCLUDE_TAX_DETAILS=No, P_LEDGER=PROQUEST-USD, P_GL_DATE_FROM=2021/07/04 00:00:00, P_INCLUDE_ZERO_AMOUNT_LINES=N, P_ACCOUNT_FLEXFIELD_TO=99.99.999.99999.9999.9999.99}
Calling XDO Data Engine...
[090721_105513005][][EXCEPTION] [DEBUG] Trying to get XDO_TOP in CP parameter list : null
[090721_105513006][][EXCEPTION] [DEBUG] Trying to get XDO_TOP in Apps Preference : null
[090721_105513007][][EXCEPTION] [DEBUG] Trying to get XDO_TOP in Apps Profile : null
[090721_105513007][][EXCEPTION] [DEBUG] Trying to get XDO_TOP in Apps Env : /ppqs1i/12.2/PROD/fs1/EBSapps/appl/xdo/12.0.0
[090721_105513007][][EXCEPTION] [DEBUG] Setting XDO_TOP to java system properties : /ppqs1i/12.2/PROD/fs1/EBSapps/appl/xdo/12.0.0
XDO Config properteies :null
CP main completed runProgram for oracle.apps.xdo.oa.cp.JCP4XDODataEngine
+---------------------------------------------------------------------------+
Start of log messages from FND_FILE
+---------------------------------------------------------------------------+
+---------------------------------------------------------------------------+
End of log messages from FND_FILE
+---------------------------------------------------------------------------+


+---------------------------------------------------------------------------+
Executing request completion options...

Output file size: 
231759481

+--------- 1) POST-PROCESSING  ---------+
Beginning post-processing of request 35935365 on node PSBSASHEBSAP1 at 07-SEP-2021 10:55:49.
-- Publishing output

 
Post-processing of request 35935365 failed at 07-SEP-2021 10:56:06 with the error message:
One or more post-processing actions failed. Consult the OPP service log for details.
 
CONC-POST-PROCESSING RESULTS

-- PUBLISH: 
oracle.apps.fnd.cp.opp.PostProcessorException: oracle.apps.fnd.cp.opp.PostProcessorException: oracle.apps.xdo.XDOException
+---------------------------------------+


Finished executing request completion options.

+---------------------------------------------------------------------------+
Concurrent request completed
Current system time is 07-SEP-2021 10:56:06

+---------------------------------------------------------------------------+

**Comment by amitjori** [comment]
Hello Mark,

Can you please re-test this and confirm?

Regards,
Amit

**Comment by hamiltonmark** [comment]
Amit
The Log is now displaying properly only one job... but...
The PBS Account Analysis Report still has error... which is not 
displaying in View Report.


+---------------------------------------------------------------------------+
Subledger Accounting: Version : 12.2

Copyright (c) 1998, 2013, Oracle and/or its affiliates. All rights reserved.

PBS_XLAAARPT: PBS Account Analysis Report
+---------------------------------------------------------------------------+

Current system time is 07-SEP-2021 11:53:26

+---------------------------------------------------------------------------+

CP main executing runProgram for oracle.apps.xdo.oa.cp.JCP4XDODataEngine
XDO Data Engine Version No: 10.1.3.4.2
Resp: 50252
Org ID : 83
Request ID: 35935379
All Parameters: P_RESP_APPLICATION_ID=200:P_LEDGER_ID=2:P_LEDGER=PROQUEST-USD:P_COA_ID=101:P_LEGAL_ENTITY_ID=:P_LEGAL_ENTITY=:P_GL_DATE_FROM="2021/07/04 00:00:00":P_PERIOD_FROM=JUL-21:P_GL_DATE_TO="2021/07/31 00:00:00":P_PERIOD_TO=JUL-21:P_APPLICATION_ID=:P_JE_SOURCE_NAME=:P_BALANCE_TYPE_CODE=A:P_BALANCE_TYPE=Actual:P_DUMMY_BUDGET_VERSION=:P_BUDGET_VERSION_ID=:P_BUDGET_NAME=:P_DUMMY_ENCUMBRANCE_TYPE=:P_ENCUMBRANCE_TYPE_ID=:P_ENCUMBRANCE_TYPE=:P_BALANCE_SIDE_CODE=:P_BALANCE_SIDE=:P_BALANCE_AMOUNT_FROM=:P_BALANCE_AMOUNT_TO=:P_BALANCING_SEGMENT_FROM=:P_BALANCING_SEGMENT_TO=:P_ACCOUNT_SEGMENT_FROM=:P_ACCOUNT_SEGMENT_TO=:P_ACCOUNT_FLEXFIELD_FROM=00.00.000.00000.0000.0000.00:P_ACCOUNT_FLEXFIELD_TO=99.99.999.99999.9999.9999.99:P_INCLUDE_ZERO_AMOUNT_LINES=N:P_INCLUDE_ZERO_AMT_LINES=No:P_INCLUDE_USER_TRX_ID_FLAG=N:P_INCLUDE_USER_TRX_ID=No:P_INCLUDE_TAX_DETAILS_FLAG=N:P_INCLUDE_TAX_DETAILS=No:P_INCLUDE_LE_INFO_FLAG=NONE:P_INCLUDE_LEGAL_ENTITY=None:P_CUSTOM_PARAMETER_1=:P_CUSTOM_PARAMETER_2=:P_CUSTOM_PARAMETER_3=:P_CUSTOM_PARAMETER_4=:P_CUSTOM_PARAMETER_5=:DebugFlag=N:P_INCLUDE_STAT_AMOUNT_LINES=N:P_INCLUDE_STAT_AMT_LINES=No:P_INCLUDE_ACCT_WITH_NO_ACT=N:P_INC_ACCT_WITH_NO_ACT=No:ScalableFlag=N
Data Template Code: PBS_XLAAARPT
Data Template Application Short Name: XLA
Debug Flag: N
{P_ACCOUNT_SEGMENT_FROM=, P_ENCUMBRANCE_TYPE=, P_ACCOUNT_SEGMENT_TO=, P_BALANCE_AMOUNT_FROM=, P_DUMMY_ENCUMBRANCE_TYPE=, P_DUMMY_BUDGET_VERSION=, P_GL_DATE_TO=2021/07/31 00:00:00, P_COA_ID=101, P_BALANCE_TYPE_CODE=A, P_BALANCE_AMOUNT_TO=, P_RESP_APPLICATION_ID=200, P_ENCUMBRANCE_TYPE_ID=, P_JE_SOURCE_NAME=, P_BALANCE_SIDE=, P_CUSTOM_PARAMETER_5=, P_CUSTOM_PARAMETER_4=, P_CUSTOM_PARAMETER_3=, P_CUSTOM_PARAMETER_2=, P_CUSTOM_PARAMETER_1=, P_BALANCE_TYPE=Actual, P_INC_ACCT_WITH_NO_ACT=No, P_INCLUDE_USER_TRX_ID=No, P_ACCOUNT_FLEXFIELD_FROM=00.00.000.00000.0000.0000.00, P_BUDGET_NAME=, P_INCLUDE_STAT_AMT_LINES=No, P_INCLUDE_LE_INFO_FLAG=NONE, P_PERIOD_TO=JUL-21, P_LEGAL_ENTITY_ID=, P_BALANCE_SIDE_CODE=, P_INCLUDE_ACCT_WITH_NO_ACT=N, P_INCLUDE_STAT_AMOUNT_LINES=N, P_BUDGET_VERSION_ID=, P_INCLUDE_LEGAL_ENTITY=None, P_INCLUDE_TAX_DETAILS_FLAG=N, P_BALANCING_SEGMENT_FROM=, P_INCLUDE_ZERO_AMT_LINES=No, P_LEDGER_ID=2, P_PERIOD_FROM=JUL-21, P_APPLICATION_ID=, P_INCLUDE_USER_TRX_ID_FLAG=N, P_BALANCING_SEGMENT_TO=, P_LEGAL_ENTITY=, P_INCLUDE_TAX_DETAILS=No, P_LEDGER=PROQUEST-USD, P_GL_DATE_FROM=2021/07/04 00:00:00, P_INCLUDE_ZERO_AMOUNT_LINES=N, P_ACCOUNT_FLEXFIELD_TO=99.99.999.99999.9999.9999.99}
Calling XDO Data Engine...
[090721_115328266][][EXCEPTION] [DEBUG] Trying to get XDO_TOP in CP parameter list : null
[090721_115328267][][EXCEPTION] [DEBUG] Trying to get XDO_TOP in Apps Preference : null
[090721_115328267][][EXCEPTION] [DEBUG] Trying to get XDO_TOP in Apps Profile : null
[090721_115328267][][EXCEPTION] [DEBUG] Trying to get XDO_TOP in Apps Env : /ppqs1i/12.2/PROD/fs1/EBSapps/appl/xdo/12.0.0
[090721_115328268][][EXCEPTION] [DEBUG] Setting XDO_TOP to java system properties : /ppqs1i/12.2/PROD/fs1/EBSapps/appl/xdo/12.0.0
XDO Config properteies :null
CP main completed runProgram for oracle.apps.xdo.oa.cp.JCP4XDODataEngine
+---------------------------------------------------------------------------+
Start of log messages from FND_FILE
+---------------------------------------------------------------------------+
+---------------------------------------------------------------------------+
End of log messages from FND_FILE
+---------------------------------------------------------------------------+


+---------------------------------------------------------------------------+
Executing request completion options...

Output file size: 
231759481

+--------- 1) POST-PROCESSING  ---------+
Beginning post-processing of request 35935379 on node PSBSASHEBSAP1 at 07-SEP-2021 11:54:18.
-- Publishing output

 
Post-processing of request 35935379 failed at 07-SEP-2021 11:54:34 with the error message:
One or more post-processing actions failed. Consult the OPP service log for details.
 
CONC-POST-PROCESSING RESULTS

-- PUBLISH: 
oracle.apps.fnd.cp.opp.PostProcessorException: oracle.apps.fnd.cp.opp.PostProcessorException: oracle.apps.xdo.XDOException
+---------------------------------------+


Finished executing request completion options.

+---------------------------------------------------------------------------+
Concurrent request completed
Current system time is 07-SEP-2021 11:54:34

+---------------------------------------------------------------------------+

**Comment by vinaytalasila** [comment]
Mark,

**What we did so far regarding this issue:**

- Attached the report template from INT 12.1.3 instance to the Production Dry run instance.
- Increased Java heap size to 2 GB.
- Increased OPP value in the profile option. 
- Bounced the Production Dry run instance.

**What are our observations so far regarding this issue:**

- Ran 'PBS Account Analysis Report' from our end in **Production Dry run** instance with different sets of parameters with three months of data.
- That report has failed to run with dates of 1st, 29th, 30th, 31st May 2021 and 1st, 2nd, 3rd and 31st Jul 2021. We are thinking that it is due to the special characters or trailing spaces in the report data. So, **could you please run the same report in Production 12.1.3 instance for the dates mentioned above and check whether it completes the report without any 'Warning'. If that completes successfully in that instance, please attach the report outputs to this issue so that we can check why it is failing in Production Dry run 12.2.10 instance**.
- 'PBS Account Analysis Report' ran successfully for the whole month of Jun 2021 period dates.

Thanks
Vinay

**Comment by hamiltonmark** [comment]
Vinay
Per our AP Manager, Mark Pastor - the dates referenced in the previous thread are days where there were No Transactions... so there would be no output.

The good news - in PRD Dry Run - The PBS Account Analysis Report was run Successfully using different parameters.
One I ran with the same params for when it was failing.  The other I ran for just company=01.
Both were successful.

![image](https://user-images.githubusercontent.com/85197361/132554703-e71baed2-cccf-4148-bb72-60bec7798c64.png)

**Comment by hamiltonmark** [comment]
[PBS_Account_Analysis_Report_080921.pdf](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7130704/PBS_Account_Analysis_Report_080921.pdf)

**Comment by hamiltonmark** [comment]
[PBS_Account_Analysis_Report_080921(1).pdf](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7130709/PBS_Account_Analysis_Report_080921.1.pdf)

**Comment by hamiltonmark** [comment]
Can you please do the same for PROD?


    Attached the report template from INT 12.1.3 instance to the Production Dry run instance.
    Increased Java heap size to 2 GB.
    Increased OPP value in the profile option.
    Bounced the Production instance.

**Comment by vinaytalasila** [comment]
Sure Mark. We made a note of these steps. 

Can we close this issue now?

Thanks
Vinay

**Comment by hamiltonmark** [comment]
yes 
thanks
ok to close
